<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Privacy and Uncertainty Quantification</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script>(function(){try{var t=localStorage.getItem("llga-theme");if(t==="dark"||t==="light")document.documentElement.setAttribute("data-theme",t);}catch(e){}})();</script>
<style>
  /* Keep paper.css as visual source of truth; tame Quarto chrome */
  #title-block-header { margin: 0 0 0.5rem; }
  #title-block-header .title { margin: 0 0 0.25rem; font-size: 1.85rem; font-weight: 700; }
  #title-block-header .subtitle { color: var(--soft, #555); margin: 0 0 1rem; font-size: 1.05rem; }
  div.sourceCode { background: var(--code-bg, #f7f7f7); border: 1px solid var(--hair, #e4e4e4); }
  code { background: var(--code-inline-bg, #f4f4f4); }

  /* Light (github) token colors — higher specificity beats paper.css */
  div.sourceCode pre.sourceCode code span.kw, div.sourceCode pre.sourceCode code span.cf, div.sourceCode pre.sourceCode code span.dt, div.sourceCode pre.sourceCode code span.at, div.sourceCode pre.sourceCode code span.bu, div.sourceCode pre.sourceCode code span.pp { color: #d73a49; }
  div.sourceCode pre.sourceCode code span.im, div.sourceCode pre.sourceCode code span.st, div.sourceCode pre.sourceCode code span.ch, div.sourceCode pre.sourceCode code span.ss, div.sourceCode pre.sourceCode code span.vs { color: #032f62; }
  div.sourceCode pre.sourceCode code span.co, div.sourceCode pre.sourceCode code span.an, div.sourceCode pre.sourceCode code span.cv, div.sourceCode pre.sourceCode code span.do, div.sourceCode pre.sourceCode code span.in { color: #6a737d; }
  div.sourceCode pre.sourceCode code span.fu { color: #6f42c1; }
  div.sourceCode pre.sourceCode code span.va { color: #e36209; }
  div.sourceCode pre.sourceCode code span.cn, div.sourceCode pre.sourceCode code span.bn, div.sourceCode pre.sourceCode code span.dv, div.sourceCode pre.sourceCode code span.fl, div.sourceCode pre.sourceCode code span.sc { color: #005cc5; }
  div.sourceCode pre.sourceCode code span.op { color: #24292e; }
  /* Dark mode token colors (github highlight is light-oriented) */
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.kw,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.cf,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.dt,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.at,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.bu,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.pp,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.op { color: #ff7b72; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.im { color: #ff7b72; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.st,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.ch,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.ss,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.vs { color: #a5d6ff; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.cn,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.bn,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.dv,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.fl,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.sc { color: #79c0ff; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.co,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.an,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.cv,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.do,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.in { color: #8b949e; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.va { color: #ffa657; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.fu { color: #d2a8ff; }
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.kw,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.cf,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.dt,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.at,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.bu,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.pp,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.op { color: #ff7b72; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.im { color: #ff7b72; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.st,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.ch,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.ss,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.vs { color: #a5d6ff; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.cn,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.bn,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.dv,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.fl,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.sc { color: #79c0ff; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.co,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.an,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.cv,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.do,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.in { color: #8b949e; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.va { color: #ffa657; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.fu { color: #d2a8ff; }
  }

</style>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../assets/paper.css">
</head>

<body>

<p class="crumb"><a href="../../index.html">MSc&amp;T LLGA · Course notes</a></p>
<main class="paper">

<header id="title-block-header">
<h1 class="title">Privacy and Uncertainty Quantification</h1>
<p class="subtitle">M2 · P1 (brochure) · Year 2 · Period 1</p>

</header>


<h2 id="contents">Contents</h2>
<ul>
<li><a href="#intro">Introduction and overview</a></li>
<li><a href="#ch0">0. Reminders: probability, concentration, DP as seen in M1</a></li>
<li><a href="#ch1">1. Differential privacy: the foundation</a></li>
<li><a href="#ch2">2. Mechanisms: Laplace, Gaussian, exponential</a></li>
<li><a href="#ch3">3. Composition: advanced and Rényi DP</a></li>
<li><a href="#ch4">4. Local versus global, and DP-SGD</a></li>
<li><a href="#ch5">5. DP in industry and attacks</a></li>
<li><a href="#ch6">6. Uncertainty: sources and vocabulary</a></li>
<li><a href="#ch7">7. Calibration: diagrams, ECE, Brier</a></li>
<li><a href="#ch8">8. Bayesian deep learning: MC dropout versus ensembles</a></li>
<li><a href="#ch9">9. Conformal prediction: theorem and algorithm</a></li>
<li><a href="#ch10">10. Quantile and conformalized regression</a></li>
<li><a href="#ch11">11. UQ for LLMs</a></li>
<li><a href="#ch12">12. Applications: deciding under uncertainty</a></li>
<li><a href="#ex">Exercises</a></li>
<li><a href="#refs">References</a></li>
</ul>
<h2 id="intro">Introduction and overview</h2>
<table class="caption-top">
<tbody>
<tr class="odd">
<td style="text-align: left;">Module</td>
<td style="text-align: left;">Privacy and Uncertainty Quantification</td>
</tr>
<tr class="even">
<td style="text-align: left;">Code</td>
<td style="text-align: left;">Not published — the module is announced in period&nbsp;1 by the master’s brochure; the 2026-2027 SynapseS course description has not been published (the S3/S4 tracks of the catalog are currently empty).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Team and workload</td>
<td style="text-align: left;">Instructor, teaching hours and ECTS: not published · two complementary parts: <strong>differential privacy</strong> (mechanisms, composition, Rényi DP, DP-SGD, industrial deployments) and <strong>uncertainty quantification</strong> (calibration, deep ensembles, conformal prediction, LLM UQ) — the two families of guarantees that condition the responsible deployment of models.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Period</td>
<td style="text-align: left;">M2 · period&nbsp;1 (brochure)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Status in the program</td>
<td style="text-align: left;"><span class="badge m2">M2</span><span class="badge position">Outside recommended track</span> M2 program being finalized by the course instructors; the official description will not be communicated until the course description is published.</td>
</tr>
</tbody>
</table>
<p><strong>Audience</strong>: an engineer who must ship a model with guarantees (privacy, calibration). <strong>Empirical first</strong>: 91% accuracy but ECE 0.18 (over-confident); DP-SGD at ε=2 that makes fine-tuning unusable — then we name mechanisms, composition, conformal.</p>
<p>Differential privacy and uncertainty quantification — prerequisites for responsible deployment.</p>
<h3 id="what-you-will-be-able-to-do">What you will be able to do</h3>
<ul>
<li>State the definition of <span class="math inline">\varepsilon</span>-differential privacy and prove that a mechanism satisfies it (Laplace, Gaussian, exponential);</li>
<li>Compose mechanisms (sequential and parallel theorems) and tighten the privacy budget with Rényi DP;</li>
<li>Choose between local and global DP, and explain precisely what DP-SGD modifies in SGD;</li>
<li>Read a reliability diagram and quantify the miscalibration of a classifier (ECE, Brier score);</li>
<li>Compare MC dropout and deep ensembles for estimating the uncertainty of a deep network;</li>
<li>Implement “split” conformal prediction and prove its marginal coverage guarantee;</li>
<li>Produce adaptive intervals via conformalized quantile regression;</li>
<li>Audit the uncertainty of an LLM and argue for a decision under uncertainty (alert threshold, abstention).</li>
</ul>
<h3 id="official-objectives-and-syllabus">Official objectives and syllabus</h3>
<p><strong>Official syllabus</strong>: course description not published — this module appears neither in the S3 track nor in the S4 track of the 2026-2027 SynapseS catalog (both currently empty), and the master’s wiki indicates that the detailed M2 curriculum is still under development: description, teaching hours and instructor are therefore “not published”. The themes below are those carried by the module in the master’s brochure, as restated by these course materials, mapped to the sections that cover them.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Announced theme (brochure, as restated by the materials)</th>
<th style="text-align: left;">Course section covering it</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Differential privacy: definitions and foundation</td>
<td style="text-align: left;">ch.&nbsp;1 “Differential privacy: the foundation”</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mechanisms: Laplace, Gaussian, exponential</td>
<td style="text-align: left;">ch.&nbsp;2 “Mechanisms: Laplace, Gaussian, exponential”</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Advanced composition and Rényi DP</td>
<td style="text-align: left;">ch.&nbsp;3 “Composition: advanced and Rényi DP”</td>
</tr>
<tr class="even">
<td style="text-align: left;">Local versus global DP, DP-SGD</td>
<td style="text-align: left;">ch.&nbsp;4 “Local versus global, and DP-SGD”</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DP in industry and attacks</td>
<td style="text-align: left;">ch.&nbsp;5 “DP in industry and attacks”</td>
</tr>
<tr class="even">
<td style="text-align: left;">Uncertainty: sources, calibration</td>
<td style="text-align: left;">ch.&nbsp;6 “Uncertainty: sources and vocabulary” and ch.&nbsp;7 “Calibration: diagrams, ECE, Brier”</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bayesian deep learning</td>
<td style="text-align: left;">ch.&nbsp;8 “Bayesian deep learning: MC dropout versus ensembles”</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conformal prediction</td>
<td style="text-align: left;">ch.&nbsp;9 “Conformal prediction: theorem and algorithm”</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Quantile and conformalized regression</td>
<td style="text-align: left;">ch.&nbsp;10 “Quantile and conformalized regression”</td>
</tr>
<tr class="even">
<td style="text-align: left;">UQ for LLMs</td>
<td style="text-align: left;">ch.&nbsp;11 “UQ for LLMs”</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Deciding under uncertainty</td>
<td style="text-align: left;">ch.&nbsp;12 “Applications: deciding under uncertainty”</td>
</tr>
</tbody>
</table>
<p>The exact split between brochure content and the materials’ own extensions can only be settled once the official course description is published; in any case, chapter 0 (reminders: probability, concentration, DP as seen in M1) is part of the common structure of the repository’s course materials.</p>
<h3 id="where-this-course-fits-in-the-program">Where this course fits in the program</h3>
<p>M2 module offered in period 1, outside the recommended track: it is aimed at all students who want to add demonstrable guarantees to their profile, whatever their specialty. <strong>Prerequisites</strong>: the first encounter with differential privacy of chapter 5 of <a href="../m1p1-emerging-ml/index.html">Emerging ML</a> (<span class="math inline">\varepsilon</span>-DP definition, Laplace noise, DP-SGD as a conclusion of federated learning) is revisited in ch.&nbsp;0 then developed; the language of statistical guarantees of <a href="../m1p2-statistics-in-action/index.html">Statistics in Action</a> (intervals, tests, bootstrap) is assumed acquired.</p>
<p><strong>Downstream modules</strong>: the privacy part of <a href="../m2-explainability-security-privacy-llms/index.html">Explainability, Security, Privacy of LLMs</a> (memorization, membership inference, DP of LLMs, ch.&nbsp;7–8) relies directly on the mechanisms and composition proved here; on the production side, calibration and coverage feed the continuous evaluation and alert decisions of the <a href="../m2-mlops-llm-engineering/index.html">ML Ops and LLM Engineering Principles</a> module.</p>
<h3 id="course-outline">Course outline</h3>
<ul>
<li><strong>Reminders: probability, concentration, DP as seen in M1</strong> — puts the Markov/Hoeffding inequalities and the DP definition back in shape before going further.</li>
<li><strong>Differential privacy: the foundation</strong> — definitions (neighboring, mechanism), post-processing properties and a first Laplace theorem.</li>
<li><strong>Mechanisms: Laplace, Gaussian, exponential</strong> — sensitivity, noise calibration and the exponential mechanism for discrete responses.</li>
<li><strong>Composition: advanced and Rényi DP</strong> — why naive compositions waste the budget, and how Rényi DP tightens it.</li>
<li><strong>Local versus global, and DP-SGD</strong> — two trust models, then the algorithm that trains networks while preserving privacy.</li>
<li><strong>DP in industry and attacks</strong> — real deployments, the <span class="math inline">\varepsilon</span> budget in practice, and attacks (reconstruction, inference) that motivate the theory.</li>
<li><strong>Uncertainty: sources and vocabulary</strong> — aleatoric versus epistemic, and why modern networks are poorly calibrated.</li>
<li><strong>Calibration: diagrams, ECE, Brier</strong> — measuring the gap between stated confidence and observed frequency.</li>
<li><strong>Bayesian deep learning: MC dropout versus ensembles</strong> — two practical approximations of epistemic uncertainty, with their trade-offs.</li>
<li><strong>Conformal prediction: theorem and algorithm</strong> — a distribution-free coverage guarantee in a few lines of code.</li>
<li><strong>Quantile and conformalized regression</strong> — intervals whose width adapts to the query point.</li>
<li><strong>UQ for LLMs</strong> — verbalized confidence, semantic coherence and the limits of the previous methods on generations.</li>
<li><strong>Applications: deciding under uncertainty</strong> — assembling the tools to arbitrate abstention, alert and action in a real system.</li>
<li><strong>Exercises</strong> — from proofs of mechanisms to conformal implementations on real data.</li>
<li><strong>References</strong> — the primary sources (Dwork, Rényi DP, Angelopoulos) to go to the text.</li>
</ul>
<h3 id="how-to-study-this-module">How to study this module</h3>
<ul>
<li>Redo the proofs on scratch paper: every theorem fits on one page, and it is by rewriting them that one retains the exact hypotheses.</li>
<li>Implement Laplace noise and “split” conformal yourself (a few dozen lines): the guarantees become tangible when you see the coverage histogram.</li>
<li>Whenever an <span class="math inline">\varepsilon</span> appears, ask yourself which pair of neighboring datasets it distinguishes — that is the only way to give it meaning.</li>
<li>Work through the two parts in order but in parallel in your head: chapters 6–12 replay in UQ the same moves as in privacy (guarantee, budget, utility trade-off).</li>
<li>Do the exercises before reading the solutions, and compare your intervals with those of others: coverage is verified, not declared.</li>
</ul>
<div class="note">
<p><span class="tag">The LLGA perspective</span> The singularity of the master is to cross LLMs, graphs, and applications; now privacy and uncertainty are precisely the questions where this intersection remains the most open — DP on graphs (sensitive edges, neighbors), UQ of text and graph generations. Whether you aim for research (PhD, R&amp;D) or data careers in a regulated sector (health, banking, insurance), knowing how to <em>certify</em> a learning system — not merely measure it — is what distinguishes an engineer trained in LLGA.</p>
</div>
<h2 id="ch0">0. Reminders: probability, concentration, DP as seen in M1</h2>
<div class="recap">
<div class="recap-title">
<p>Prerequisites (M1 modules)</p>
</div>
<ul>
<li><strong>Concentration inequalities</strong> (cf.&nbsp;Machine Learning module, ch.&nbsp;0): Markov <span class="math inline">\mathbb{P}(Z \geq t) \leq \mathbb{E}Z/t</span>, Chernoff/Hoeffding for sums of Bernoullis — they provide the guarantees of the mechanisms and conformal coverage;</li>
<li><strong>Differential privacy, first encounter</strong> (cf.&nbsp;Emerging ML module, chapter 5): <span class="math inline">\varepsilon</span>-DP definition, Laplace noise, DP-SGD as a conclusion of federated learning — the present module takes up this basis and develops it: mechanisms (ch.&nbsp;2), fine composition (ch.&nbsp;3), industrial implementations (ch.&nbsp;4–5);</li>
<li><strong>Generalization theory</strong> (cf.&nbsp;Machine Learning module, ch.&nbsp;7): bias-variance trade-off, error decomposition — the UQ part (ch.&nbsp;6–12) answers the dual question: not just “what risk on average”, but “what guarantee on <em>this</em> prediction”;</li>
<li><strong>Training of networks</strong> (cf.&nbsp;Deep Learning module, ch.&nbsp;3 and 10): SGD, mini-batches, dropout — DP-SGD (ch.&nbsp;4) and MC dropout (ch.&nbsp;8) modify them marginally but change their nature;</li>
<li><strong>Statistics of tests and intervals</strong> (cf.&nbsp;Refresher Statistics module, ch.&nbsp;4 and 6; Statistics in Action module, ch.&nbsp;7 and 10): frequentist guarantees, p-values, bootstrap — the language of the coverage guarantees of ch.&nbsp;9.</li>
</ul>
</div>
<div class="note">
<p><span class="tag">Why these two parts in a single module?</span> Privacy and UQ are the two faces of the “right to error” of learning systems: privacy quantifies what a model can <em>reveal</em> about the training data, UQ quantifies what it can <em>assert</em> about a new input. Both escape evaluation by accuracy alone; both provide <strong>formal guarantees</strong> (inequalities, theorems) rather than empirical promises; and both converge on LLMs (ch.&nbsp;11): models large enough to memorize <em>and</em> confident enough to mislead. The thread: <em>make the uncertainties computable, then arbitrate them</em>.</p>
</div>
<h2 id="ch1">1. Differential privacy: the foundation</h2>
<p>Concrete scene: a medical classifier shows 0.97 confidence on an OOD case. Without conformal / calibration, the clinic cannot set a reject threshold.</p>
<div class="note">
<p><span class="tag">What breaks</span> Releasing with no DP budget; mistaking softmax for calibrated probability; ignoring composition of privacy mechanisms.</p>
</div>
<p>The historical motivation (reconstructed by Dinur-Nissim, 2003): publishing “anonymized” statistics about a database is often enough to <em>reconstruct</em> the individual data by cross-referencing enough queries — naive anonymization (removing name/SSN) does not resist. The answer of Dwork, McSherry, Nissim, Smith (2006): define protection as a property of the <em>mechanism</em> (the randomized algorithm), not of the data.</p>
<div class="def">
<p><span class="tag">Definition 1.1 — Neighboring and differential privacy</span> Two databases <span class="math inline">x, x'</span> are <strong>neighboring</strong> if they differ in the data of a single individual (one row added/removed, or modified: one of the two conventions will be specified). A randomized mechanism <span class="math inline">M</span> is <strong><span class="math inline">\varepsilon</span>-DP</strong> if for every pair of neighboring databases and every subset <span class="math inline">S</span> of outputs: <span class="math display">\mathbb{P}(M(x) \in S) \;\leq\; e^{\varepsilon}\, \mathbb{P}(M(x') \in S).</span> <strong><span class="math inline">(\varepsilon, \delta)</span></strong> version: the inequality may be violated with probability <span class="math inline">\leq \delta</span> (a figure to be read as “cryptographically improbable”, <span class="math inline">\delta \ll 1/n</span>). Reading: changing the data of <em>one</em> person changes the distribution of the published conclusions by at most (multiplicatively) <span class="math inline">e^\varepsilon</span> — so these conclusions reveal little about that person, whatever the adversary’s side knowledge.</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 1.2 — Three structural properties</span> <strong>(i) Post-processing:</strong> if <span class="math inline">M</span> is <span class="math inline">\varepsilon</span>-DP, any <span class="math inline">g \circ M</span> (subsequent analysis, training, selective publication) still is — privacy does not degrade through processing of the outputs. <strong>(ii) Group privacy:</strong> if <span class="math inline">x, x'</span> differ on <span class="math inline">k</span> individuals, <span class="math inline">\mathbb{P}(M(x) \in S) \leq e^{k\varepsilon}\mathbb{P}(M(x') \in S)</span>. <strong>(iii) Convexity:</strong> a mixture of <span class="math inline">\varepsilon</span>-DP mechanisms is <span class="math inline">\varepsilon</span>-DP.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>(i) For every section <span class="math inline">A</span>, <span class="math inline">\mathbb{P}(g(M(x)) \in S) = \mathbb{P}(M(x) \in g^{-1}(S)) \leq e^\varepsilon \mathbb{P}(M(x') \in g^{-1}(S)) = e^\varepsilon \mathbb{P}(g(M(x')) \in S)</span> — the direct image of a dominated measure preserves the Radon-Nikodym ratio. (ii) A chain of <span class="math inline">k</span> intermediate neighboring databases and multiplication of the <span class="math inline">e^\varepsilon</span>. (iii) For a mixture with weights <span class="math inline">\lambda_j</span> over <span class="math inline">M_j</span> all <span class="math inline">\varepsilon</span>-DP: <span class="math inline">\sum_j \lambda_j \mathbb{P}(M_j(x) \in S) \leq \sum_j \lambda_j e^\varepsilon \mathbb{P}(M_j(x') \in S) = e^\varepsilon \mathbb{P}(\text{mixture}(x') \in S)</span>. <span class="qed">∎</span></p>
</div>
</div>
<div class="def">
<p><span class="tag">Definition 1.3 — Sensitivity</span> The <span class="math inline">\ell_1</span> (resp. <span class="math inline">\ell_2</span>) sensitivity of a query <span class="math inline">f</span> on neighboring databases: <span class="math display">\Delta_1 f = \max_{x \sim x'} \\|f(x) - f(x')\\|_1, \qquad \Delta_2 f = \max_{x \sim x'} \\|f(x) - f(x')\\|_2.</span> Computed examples: counting (how many individuals satisfy <span class="math inline">Q</span>?) <span class="math inline">\Rightarrow \Delta_1 = 1</span> (one row changes the count by at most 1); mean over <span class="math inline">n</span> rows in <span class="math inline">[0, 1]</span> <span class="math inline">\Rightarrow \Delta_1 = 1/n</span> (adding one row shifts the mean by at most <span class="math inline">1/n</span>); histogram with <span class="math inline">k</span> bins <span class="math inline">\Rightarrow \Delta_1 = 1</span> (one row falls in one bin — under the add/remove convention); maximum <span class="math inline">\Rightarrow \Delta_1</span> unbounded (hence the systematic clipping in practice, ch.&nbsp;4). Sensitivity measures “how much one individual can weigh” — it is what will set the noise.</p>
</div>
<div class="note">
<p><span class="tag">Choosing <span class="math inline">\varepsilon</span> — the embarrassing question</span> No universal rule, but industry benchmarks: 2020 US Census: a global <span class="math inline">\varepsilon</span> on the order of twenty in total for the person file (Abowd, 2018); Apple (keyboard telemetry): <span class="math inline">\varepsilon</span> on the order of 4–8 per day; Google (RAPPOR): <span class="math inline">\varepsilon \approx \ln 3</span> per report, cumulative budgets; academic literature: <span class="math inline">\varepsilon \leq 1</span> “strict”, 1–10 “reasonable”. The essential point: <span class="math inline">\varepsilon</span> is a <em>budget</em> that one spends (ch.&nbsp;3), not a moral grade.</p>
</div>
<h2 id="ch2">2. Mechanisms: Laplace, Gaussian, exponential</h2>
<div class="thm">
<p><span class="tag">Theorem 2.1 — The Laplace mechanism (Dwork et al., 2006)</span> Let <span class="math inline">f</span> have sensitivity <span class="math inline">\Delta_1</span>. The mechanism <span class="math display">M(x) = f(x) + (Z_1, \dots, Z_k), \qquad Z_i \sim \mathrm{Laplace}\big(0, \tfrac{\Delta_1}{\varepsilon}\big)\ \text{i.i.d.}</span> is <span class="math inline">\varepsilon</span>-DP. The Laplace law with parameter <span class="math inline">b</span> has density <span class="math inline">p(z) = \frac{1}{2b} e^{-\|z\|/b}</span>.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>For an output <span class="math inline">z \in \mathbb{R}^k</span>, the ratio of densities equals <span class="math display">\frac{p_x(z)}{p_{x'}(z)} = \prod_{i=1}^k \exp\!\Big( -\frac{\varepsilon}{\Delta_1}\big( \|z_i - f_i(x)\| - \|z_i - f_i(x')\| \big) \Big) = \exp\!\Big( \frac{\varepsilon}{\Delta_1} \sum_i \big( \|z_i - f_i(x')\| - \|z_i - f_i(x)\| \big) \Big).</span> By the triangle inequality, <span class="math inline">\sum_i \big( \|z_i - f_i(x')\| - \|z_i - f_i(x)\| \big) \leq \sum_i \|f_i(x) - f_i(x')\| \leq \Delta_1</span>, hence <span class="math inline">p_x(z)/p_{x'}(z) \leq e^{\varepsilon}</span> for <em>all</em> <span class="math inline">z</span> — integrating over <span class="math inline">S</span> gives the definition (and symmetrically by exchanging <span class="math inline">x, x'</span>). <span class="qed">∎</span></p>
</div>
<p><strong>Utility, computed.</strong> For a counting query (<span class="math inline">\Delta_1 = 1</span>): <span class="math inline">\mathbb{P}(\|Z\| \geq t) = e^{-\varepsilon t}</span>. With <span class="math inline">\varepsilon = \ln 20 \approx 3.0</span> and <span class="math inline">b = 1/\varepsilon \approx 0.33</span>: the published answer is shifted by at least 1 unit with probability <span class="math inline">e^{-\varepsilon} = 5\%</span>, by at least 3 units with probability <span class="math inline">20^{-3} \approx 0.01\%</span> — a modest noise at the scale of the single individual one seeks to mask.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 2.2 — The Gaussian mechanism, analytic form</span> For <span class="math inline">f</span> with <span class="math inline">\ell_2</span> sensitivity <span class="math inline">\Delta_2</span>, <span class="math inline">M(x) = f(x) + \mathcal{N}(0, \sigma^2 I_k)</span> is <span class="math inline">(\varepsilon, \delta)</span>-DP as soon as <span class="math display">\sigma \;\geq\; \Delta_2\, \frac{\sqrt{2 \ln(1.25/\delta)}}{\varepsilon} \qquad (\varepsilon \leq 1).</span> Numerically, for <span class="math inline">\varepsilon = 1</span>, <span class="math inline">\delta = 10^{-6}</span>: <span class="math inline">\sqrt{2\ln(1.25 \times 10^6)} = \sqrt{28.1} \approx 5.3</span>, hence <span class="math inline">\sigma \approx 5.3\,\Delta_2</span>. Why prefer Gaussian over Laplace in ML: (i) Gaussian noise <strong>composes</strong> very well (Rényi DP, ch.&nbsp;3); (ii) it is isotropic and gradient-compatible; (iii) the Gaussian tail is lighter for large <span class="math inline">k</span>. Proof: computation of the ratio of Gaussian densities bounded by <span class="math inline">e^{\varepsilon}</span> except on a set of probability <span class="math inline">\delta</span> — analysis in Dwork &amp; Roth (2014), lemma A.1 (the factor 1.25 is a convenience constant of the upper bound).</p>
</div>
<div class="def">
<p><span class="tag">Definition 2.3 — The exponential mechanism (McSherry-Talwar, 2007)</span> For a <em>non-numeric</em> response (choosing a median, an item, a model): a score function <span class="math inline">u(x, h)</span> (to be maximized) with sensitivity <span class="math inline">\Delta_u = \max_h \max_{x \sim x'} \|u(x, h) - u(x', h)\|</span>, and the output law <span class="math display">\mathbb{P}(M(x) = h) \;\propto\; \exp\!\Big( \frac{\varepsilon\, u(x, h)}{2\Delta_u} \Big).</span> <strong>Utility guarantee</strong>: if <span class="math inline">h^\* = \arg\max_h u(x, h)</span> and <span class="math inline">u(x, h^\*) - u(x, h) \geq \mathrm{GAP}</span>, then <span class="math inline">\mathbb{P}(u(x, M(x)) \leq u(x, h^\*) - \mathrm{GAP}) \leq \|\mathcal H\| \exp(-\varepsilon\, \mathrm{GAP}/2\Delta_u)</span> — the gap to the optimum decreases exponentially with <span class="math inline">\varepsilon</span> and the gap. This is the mechanism of discrete choices: model selection, private top-k, auction mechanisms.</p>
</div>
<div class="ex">
<p><span class="tag">Example 2.4 — Private median: publishing a robust statistic</span> A “median age” query has unbounded sensitivity (shifting the median by one row can make it jump far if the data are concentrated). The exponential mechanism with <span class="math inline">u(x, h) = -\\|x - h\\|_0</span> (minus the number of individuals on the wrong side) publishes an <span class="math inline">\varepsilon</span>-DP median with controlled utility: this is the canonical example of the <em>structural</em> choice of mechanism according to the query — the privacy engineer spends most of their time here, not on the noise itself.</p>
</div>
<h2 id="ch3">3. Composition: advanced and Rényi DP</h2>
<div class="thm">
<p><span class="tag">Theorem 3.1 — Basic composition, proved</span> If <span class="math inline">M_1</span> is <span class="math inline">\varepsilon_1</span>-DP and <span class="math inline">M_2</span>, applied <em>after</em> <span class="math inline">M_1</span> and allowed to depend on its output, is <span class="math inline">\varepsilon_2</span>-DP, then <span class="math inline">(M_1, M_2)</span> is <span class="math inline">(\varepsilon_1 + \varepsilon_2)</span>-DP — adaptive composition <em>accumulates linearly</em>.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>By conditioning then post-processing: for measurable <span class="math inline">S</span>, <span class="math inline">\mathbb{P}(M_2(M_1(x), x) \in S_2 \mid M_1(x) = m) \leq e^{\varepsilon_2} \mathbb{P}(M_2(M_1(x'), x') \in S_2 \mid M_1(x') = m)</span> — caution: conditioning only makes sense via the regular version; the clean proof handles densities: <span class="math inline">p_x(m, s) = p_x(m)\, p_x(s \mid m) \leq e^{\varepsilon_1} p_{x'}(m) \cdot e^{\varepsilon_2} p_{x'}(s \mid m) = e^{\varepsilon_1 + \varepsilon_2} p_{x'}(m, s)</span>, then one integrates. Adaptivity breaks nothing because <span class="math inline">e^{\varepsilon_2}</span> bounds the ratio <em>for every value</em> of the history. <span class="qed">∎</span></p>
</div>
</div>
<div class="thm">
<p><span class="tag">Theorem 3.2 — Advanced composition (Dwork, Rothblum, Vadhan, 2010)</span> The composition of <span class="math inline">k</span> adaptive <span class="math inline">(\varepsilon_0, \delta_0)</span>-DP mechanisms is <span class="math inline">(\varepsilon^\\*, \, k\delta_0 + \delta')</span>-DP for every <span class="math inline">\delta' \&gt; 0</span> with <span class="math display">\varepsilon^\\* = \sqrt{2 k \ln(1/\delta')}\; \varepsilon_0 \;+\; k\, \varepsilon_0 \big( e^{\varepsilon_0} - 1 \big).</span> In <span class="math inline">\sqrt k</span> rather than <span class="math inline">k</span> — the idea (sketch: the proof bounds the deviation of the sum of log-ratios via Azuma, then converts a sub-Gaussian concentration into an <span class="math inline">(\varepsilon, \delta)</span>-type threshold). <strong>Numerical.</strong> <span class="math inline">k = 100</span> releases, <span class="math inline">\varepsilon_0 = 0.01</span>, <span class="math inline">\delta' = 10^{-5}</span>: <span class="math inline">\sqrt{200 \times 11.5} \times 0.01 = 0.48</span>, second term <span class="math inline">100 \times 0.01 \times 0.0101 = 0.010</span>, hence <span class="math inline">\varepsilon^\\* \approx 0.49</span> versus <span class="math inline">\varepsilon = k\varepsilon_0 = 1.0</span> under basic composition — twice as good; the gain explodes for large <span class="math inline">k</span> (ch.&nbsp;4, DP-SGD: <span class="math inline">k \sim 10^4</span> steps).</p>
</div>
<div class="def">
<p><span class="tag">Definition 3.3 — Rényi DP (Mironov, 2017)</span> The Rényi divergence of order <span class="math inline">\alpha \&gt; 1</span> between two laws <span class="math inline">P, Q</span>: <span class="math display">D_\alpha(P \\| Q) = \frac{1}{\alpha - 1} \ln\, \mathbb{E}_{Q}\!\Big[ \Big( \frac{dP}{dQ} \Big)^{\alpha} \Big].</span> <span class="math inline">M</span> is <span class="math inline">(\alpha, \varepsilon)</span>-RDP if <span class="math inline">D_\alpha(M(x) \\| M(x')) \leq \varepsilon</span> for all neighboring databases. Three computational virtues: (i) <strong>Gaussian mechanism</strong>: for <span class="math inline">f</span> with sensitivity <span class="math inline">\Delta_2</span>, the noise <span class="math inline">\mathcal N(0, \sigma^2)</span> is exactly <span class="math inline">\big(\alpha, \frac{\alpha \Delta_2^2}{2\sigma^2}\big)</span>-RDP for every <span class="math inline">\alpha</span>; (ii) <strong>composition = addition</strong> at fixed <span class="math inline">\alpha</span>: <span class="math inline">k</span> mechanisms <span class="math inline">(\alpha, \varepsilon_i)</span>-RDP compose into <span class="math inline">(\alpha, \sum_i \varepsilon_i)</span>-RDP (proof: conditional Hölder inequality applied to the joint density — the global likelihood ratio raised to the exponent <span class="math inline">\alpha</span> factorizes into a product of individual ratios, each bounded by <span class="math inline">e^{\varepsilon_i \alpha}</span>, and the expectation of the product is bounded term by term); (iii) <strong>conversion</strong>: <span class="math inline">(\alpha, \varepsilon)</span>-RDP <span class="math inline">\Rightarrow</span> <span class="math inline">(\varepsilon + \frac{\ln(1/\delta)}{\alpha - 1}, \delta)</span>-DP — one then optimizes <span class="math inline">\alpha</span> a posteriori.</p>
</div>
<div class="ex">
<p><span class="tag">Example 3.4 — The RDP account, computed end to end</span> 64 successive releases of the same Gaussian counting query, noise <span class="math inline">\sigma = 8\Delta_2</span>, target <span class="math inline">\delta = 10^{-6}</span>. <strong>(a) Classical route.</strong> Each release: <span class="math inline">\varepsilon_0 = \sqrt{2 \ln(1.25/\delta_0)}\,\Delta/\sigma \approx 5.3/8 = 0.66</span>. Advanced composition over <span class="math inline">k = 64</span>: <span class="math inline">\sqrt{128 \times 13.8} \times 0.66 + 64 \times 0.66 \times (e^{0.66} - 1) \approx 27.8 + 39.3 \approx \mathbf{67}</span>. Ruinous. <strong>(b) RDP route.</strong> Each release is <span class="math inline">(\alpha, \alpha/128)</span>-RDP (<span class="math inline">\alpha\Delta^2/2\sigma^2 = \alpha/128</span>); the 64 compose into <span class="math inline">(\alpha, \alpha/2)</span>-RDP. Conversion: <span class="math inline">\varepsilon(\alpha) = \frac{\alpha}{2} + \frac{13.8}{\alpha - 1}</span>, minimized at <span class="math inline">\alpha - 1 = \sqrt{2 \times 13.8} \approx 5.3</span>, i.e.&nbsp;<span class="math inline">\varepsilon^\\* \approx 3.1 + 2.6 = \mathbf{5.7}</span>.<br>
Same budget, same <span class="math inline">\delta</span> — RDP accounting <strong>saves a factor of ~10</strong>. This is exactly what the “moments accountants” of DP-SGD do (ch.&nbsp;4); the later improvement (amplification by subsampling, Wang et al.&nbsp;2019) adds another significant factor when each step touches only a mini-batch.</p>
</div>
<div class="note">
<p><span class="tag">The family of generalized DP</span> z-CDP (Bun &amp; Steinke, 2016 — Rényi divergence parameterized by <span class="math inline">\rho = \varepsilon/\alpha</span>), f-DP (Dong, Roth, Su, 2019 — binary tests, exact frontier): same program, different representations; the practitioner retains: <em>divergences with exact additivity (Rényi) give the tightest composition bounds</em>, and the interface (Opacus, TF Privacy, OpenDP) performs the conversion to <span class="math inline">(\varepsilon, \delta)</span> for governance.</p>
</div>
<h2 id="ch4">4. Local versus global, and DP-SGD</h2>
<div class="def">
<p><span class="tag">Definition 4.1 — Trust model: global (curator) vs local</span> <strong>Global (centralized) DP</strong>: a trusted curator holds the raw data and randomizes the <em>outputs</em>. Better utility; single target (losing the database = catastrophe). <strong>Local DP</strong>: each individual randomizes <em>their own data</em> before sending — the server never sees the truth; no third party to trust; price: much more noise (typically an extra error of order <span class="math inline">1/\sqrt n</span>). Deployment: telemetry (Apple, Google; cf.&nbsp;Emerging ML module ch.&nbsp;3 for the link with federated learning).</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 4.2 — Warner’s randomized response (1965), the local prototype</span> Sensitive question “<span class="math inline">X \in \{0,1\}</span>”; the client answers the truth with probability <span class="math inline">p</span>, the opposite with <span class="math inline">1 - p</span>. The channel is <span class="math inline">\varepsilon</span>-DP with <span class="math display">e^{\varepsilon} = \frac{p}{1-p} \qquad \text{(e.g. } p = 0.75 \Leftrightarrow \varepsilon = \ln 3 \approx 1.1).</span></p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Transition matrix <span class="math inline">T = \begin{pmatrix} p &amp; 1-p \\ 1-p &amp; p \end{pmatrix}</span>; for any response <span class="math inline">y</span>, <span class="math inline">\frac{\mathbb{P}(y \mid X{=}1)}{\mathbb{P}(y \mid X{=}0)}</span> equals <span class="math inline">p/(1-p)</span> or <span class="math inline">(1-p)/p</span> depending on <span class="math inline">y</span>, whose maximum is <span class="math inline">p/(1-p) = e^\varepsilon</span>. <span class="qed">∎</span></p>
</div>
<p><strong>Estimation and cost, computed.</strong> With <span class="math inline">\pi</span> the true proportion and <span class="math inline">\hat p_n</span> the proportion of 1 responses: <span class="math inline">\pi = \frac{\hat{\mathbb{E}}[Y] - (1-p)}{2p-1}</span> (debiasing), and the variance of the estimator is inflated by <span class="math inline">(2p-1)^{-2}</span>: at <span class="math inline">p = 0.75</span>, a factor of <span class="math inline">4</span> — one needs <strong>four times as many users</strong> for the same precision as in the clear. RAPPOR (Google Chrome): <em>per-bit</em> randomized response on a Bloom register + cohorts — the same arithmetic, at scale.</p>
</div>
<div class="def">
<p><span class="tag">Definition 4.3 — DP-SGD (Abadi et al., 2016), summary</span> At every step: (1) draw a mini-batch <span class="math inline">B</span> (sampling rate <span class="math inline">\gamma = \|B\|/n</span>); (2) <strong>clip</strong> each individual gradient <span class="math inline">\tilde g_i = g_i / \max(1, \\|g_i\\|_2 / C)</span> — bounds the sensitivity at <span class="math inline">C</span>; (3) aggregate and add noise: <span class="math inline">\tilde g = \frac{1}{\|B\|}\Big( \sum_{i \in B} \tilde g_i + \mathcal N(0, \sigma^2 C^2 I) \Big)</span>; (4) standard SGD step. The final budget combines RDP composition (ch.&nbsp;3) and <strong>amplification by subsampling</strong> — each step sees only a fraction <span class="math inline">\gamma</span> of the individuals: the RDP bound of a step noised with variance <span class="math inline">\sigma^2 C^2</span> is roughly reduced by a factor <span class="math inline">\gamma^2</span> (regime <span class="math inline">\gamma \varepsilon_{\text{step}} \lesssim 1</span>), exact computation in Wang, Balle, Kasiviswanathan (2019). The “moments accountant” of Abadi et al.&nbsp;is the ancestor of this computation; implementations: Opacus (PyTorch), TensorFlow Privacy. Typical settings: <span class="math inline">\sigma \in [0.5; 1.5]</span>, <span class="math inline">C</span> set to the median of the gradient norms, <span class="math inline">\varepsilon_{\text{final}} \in [1; 10]</span> for modestly sized models — LLMs with 10¹¹ parameters remain an open frontier (ch.&nbsp;11).</p>
</div>
<div class="sourceCode" id="cb1"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch, torch.nn <span class="im">as</span> nn</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> opacus <span class="im">import</span> PrivacyEngine</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> nn.Linear(<span class="dv">32</span>, <span class="dv">2</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>loader <span class="op">=</span> torch.utils.data.DataLoader(train_ds, batch_size<span class="op">=</span><span class="dv">256</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>opt <span class="op">=</span> torch.optim.SGD(model.parameters(), lr<span class="op">=</span><span class="fl">0.05</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>privacy_engine <span class="op">=</span> PrivacyEngine()</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>model, opt, loader <span class="op">=</span> privacy_engine.make_private_with_epsilon(</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    module<span class="op">=</span>model, optimizer<span class="op">=</span>opt, data_loader<span class="op">=</span>loader,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    target_epsilon<span class="op">=</span><span class="fl">3.0</span>,          <span class="co"># targeted (epsilon, delta=1e-5) budget</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    target_delta<span class="op">=</span><span class="fl">1e-5</span>, epochs<span class="op">=</span><span class="dv">20</span>,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    max_grad_norm<span class="op">=</span><span class="fl">1.0</span>,           <span class="co"># C: per-example clipping</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Ordinary training loop; at each step:</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co">#   grad_i clipped to C, noise N(0, sigma^2 C^2), sigma set by the</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">#   RDP accountant + amplification by subsampling.</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> epoch <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">20</span>):</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> x, y <span class="kw">in</span> loader:</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>        opt.zero_grad()</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>        loss <span class="op">=</span> nn.functional.cross_entropy(model(x), y)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>        loss.backward()<span class="op">;</span> opt.step()</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(privacy_engine.get_epsilon(delta<span class="op">=</span><span class="fl">1e-5</span>))   <span class="co"># epsilon actually spent</span></span></code></pre></div>
<div class="note">
<p><span class="tag">What DP-SGD does not solve</span> Utility drops with the dimension of the model (the noise is isotropic while gradients live in privileged directions); tuning <span class="math inline">C</span> is an art; rare features (a unique user!) weigh heavily after clipping; and DP protects the <em>data</em>, not the <em>outputs</em> (an incorrectly calibrated model can be private and misleading — that is the job of the UQ part).</p>
</div>
<h2 id="ch5">5. DP in industry and attacks</h2>
<div class="ex">
<p><span class="tag">Example 5.1 — Three real deployments</span> <strong>(a) 2020 US Census (Abowd, KDD 2018).</strong> All published statistical tables go through the TopDown algorithm (optimization + Gaussian noise, exponential mechanism for the invariants); direct motivation: reconstruction attacks on the 2010 census tabulations — an internal attack exactly reconstructed a substantial fraction of the individual records (on the order of half); per-domain public ε budget, intense public debates with demographers. <strong>(b) Apple (2017–).</strong> “Learning with Privacy at Scale”: keyboard/emoji/QuickType telemetry in local DP (count-mean sketch + Hadamard); millions of devices, daily ε on the order of 4–8 per domain — an illustration of the “budget” that is spent every day. <strong>(c) Google RAPPOR (Erlingsson et al., CCS 2014).</strong> First large academic-industry production of local DP; chain: signal (Bloom register) → permanent randomized response → instantaneous RR → cohorts; real discoveries (dominant Chrome settings).</p>
</div>
<div class="thm">
<p><span class="tag">Landmark 5.2 — Two families of attacks that motivate the guarantees</span> <strong>Membership inference (Shokri et al., IEEE S&amp;P 2017).</strong> The adversary queries the model (confidences) and classifies “was in the train?”; AUC typically well above 0.5 on rare/atypical points — the risk grows with the model’s overconfidence: <em>calibration (ch.&nbsp;7) is also a defense</em>. <strong>Unintended memorization (Carlini et al., 2019 — “The Secret Sharer”).</strong> Insert a canary (“secret key”) into the train of a generator; exposure measured by the relative perplexity of the canary: LLMs memorize and <em>exfiltrate</em> verbatim sequences seen only once — a founding result for LLM privacy (ch.&nbsp;11); follow-up: training extraction on GPT-2 by the same group (2021). DP is the defense with a guarantee: an <span class="math inline">\varepsilon</span>-DP mechanism bounds the membership likelihood ratio at <span class="math inline">e^{\varepsilon}</span> (hence the AUC of any adversary); the private trained model remains useful (ch.&nbsp;4) provided one pays in accuracy.</p>
</div>
<div class="note">
<p><span class="tag">Regulation</span> GDPR (anonymization “reasonably impossible to re-identify”): DP is the most accepted formal reading of this criterion; sectoral frameworks (health, banking) and emerging standards (NIST, ISO/IEC 27559). For the engineer: keep a <em>budget ledger</em> (which query, which ε spent, which composition) as one keeps an incident log — the frameworks (OpenDP, Google DP library) enforce this discipline.</p>
</div>
<h2 id="ch6">6. Uncertainty: sources and vocabulary</h2>
<div class="def">
<p><span class="tag">Definition 6.1 — Aleatoric and epistemic uncertainty</span> <strong>Aleatoric</strong> (data): the irreducible noise of generation — two patients identical on observed features, different outcomes; one can only <em>measure</em> it. <strong>Epistemic</strong> (model): what the model ignores because it has not learned enough in that region — reducible by data; one can <em>reduce</em> it. In heteroscedastic regression: <span class="math inline">y = f(x) + \sigma(x)\varepsilon</span>: <span class="math inline">\sigma(x)</span> = aleatoric; the variance between models trained on resamples = epistemic (ch.&nbsp;8 will make it operational via ensembles). Distribution shift: a third source — the input leaves the training support; the model does not know that it does not know (ch.&nbsp;9 provides a safety net; cf.&nbsp;Machine Learning module ch.&nbsp;9 for data drift in production).</p>
</div>
<div class="def">
<p><span class="tag">Definition 6.2 — The frequentist contract of calibration</span> A probabilistic predictor <span class="math inline">\hat p(y \mid x)</span> is <strong>calibrated</strong> if among all the times it announces 80%, the truth occurs ~80% of the time: <span class="math display">\mathbb{P}\big(y = 1 \mid \hat p(x) = c\big) = c \qquad \text{for (almost) all } c \in [0, 1].</span> Calibrated ≠ accurate: always predicting the prevalence 0.3 is perfectly calibrated and useless; calibrated ≠ certain. Calibration is a <em>decodability</em> condition: without it, no threshold, cost, or action derived from the probabilities has the intended meaning. The vocabulary of guarantees extends to sets: marginal coverage (ch.&nbsp;9), conditional coverage (desired, imperfectly attainable), risk control (ch.&nbsp;12).</p>
</div>
<div class="note">
<p><span class="tag">Map of the UQ part</span> Ch. 7: diagnosing (calibration, Brier). Ch. 8: two practical Bayesian answers (MC dropout, ensembles). Ch. 9: the distribution-free guarantee par excellence (conformal). Ch. 10: the “variable set size” version (quantiles). Ch. 11: the transport to LLMs. Ch. 12: decision-making arbitration (costs, abstention). Philosophy of the module: UQ without a <em>testable guarantee</em> is an opinion.</p>
</div>
<h2 id="ch7">7. Calibration: diagrams, ECE, Brier</h2>
<div class="def">
<p><span class="tag">Definition 7.1 — Reliability diagram, bins, ECE</span> Partition <span class="math inline">[0, 1]</span> into <span class="math inline">B</span> bins; bin <span class="math inline">b</span> = predictions with mean confidence <span class="math inline">\mathrm{conf}_b</span>, observed accuracy <span class="math inline">\mathrm{acc}_b</span>, count <span class="math inline">n_b</span>. The <strong>reliability diagram</strong> plots <span class="math inline">\mathrm{acc}_b</span> against <span class="math inline">\mathrm{conf}_b</span> (the diagonal = perfect calibration); the <strong>expected calibration error</strong>: <span class="math display">\mathrm{ECE} = \sum_{b=1}^{B} \frac{n_b}{n} \big\| \mathrm{acc}_b - \mathrm{conf}_b \big\|.</span> Precautions on binning: the partition influences the measure (10 bins is the de facto standard); kernel / isotonic-regression variants preferable in research (Naeini et al.&nbsp;2015; see also the Machine Learning module ch.&nbsp;9 for evaluation curves).</p>
</div>
<div class="ex">
<p><span class="tag">Example 7.2 — ECE computed by hand</span> 100 binary predictions, 5 bins (mean confidences are given):</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Bin (confidence)</th>
<th style="text-align: left;"><span class="math inline">n_b</span></th>
<th><span class="math inline">\mathrm{conf}_b</span> co</th>
<th>rrect $\</th>
<th>mathrm{acc}_b$ $|a</th>
<th>cc - conf|$ cont</th>
<th style="text-align: left;">ribution</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">[0.5; 0.6)</td>
<td style="text-align: left;">10</td>
<td>0.55</td>
<td>5</td>
<td>0.50</td>
<td>0.05</td>
<td style="text-align: left;">0.005</td>
</tr>
<tr class="even">
<td style="text-align: left;">[0.6; 0.7)</td>
<td style="text-align: left;">20</td>
<td>0.65</td>
<td>12</td>
<td>0.60</td>
<td>0.05</td>
<td style="text-align: left;">0.010</td>
</tr>
<tr class="odd">
<td style="text-align: left;">[0.7; 0.8)</td>
<td style="text-align: left;">30</td>
<td>0.75</td>
<td>20</td>
<td>0.667</td>
<td>0.083</td>
<td style="text-align: left;">0.025</td>
</tr>
<tr class="even">
<td style="text-align: left;">[0.8; 0.9)</td>
<td style="text-align: left;">25</td>
<td>0.85</td>
<td>18</td>
<td>0.72</td>
<td>0.13</td>
<td style="text-align: left;">0.0325</td>
</tr>
<tr class="odd">
<td style="text-align: left;">[0.9; 1.0]</td>
<td style="text-align: left;">15</td>
<td>0.95</td>
<td>12</td>
<td>0.80</td>
<td>0.15</td>
<td style="text-align: left;">0.0225</td>
</tr>
</tbody>
</table>
<p><span class="math display">\mathrm{ECE} = 0.005 + 0.010 + 0.025 + 0.0325 + 0.0225 = \mathbf{0.095}.</span> Global check: total accuracy <span class="math inline">67/100 = 67\%</span>, mean confidence <span class="math inline">\sum n_b\,\mathrm{conf}_b / n = 76.5\%</span> — a gap of <span class="math inline">9.5</span> points, consistent: the model is <strong>systematically overconfident</strong> by ~10 points, and the reliability diagram would be a curve below the diagonal bending downward. This is the signature measured by Guo et al.&nbsp;(2017) on modern networks: more depth/capacity ⇒ more overconfidence, not less.</p>
</div>
<div class="def">
<p><span class="tag">Definition 7.3 — Brier score and its decomposition (Brier 1950; Murphy 1973)</span> <span class="math display">\mathrm{BS} = \frac{1}{n}\sum_i (\hat p_i - y_i)^2, \qquad \text{decomposition:} \quad \mathrm{BS} = \underbrace{\text{reliability}}_{\text{calibration}} - \underbrace{\text{resolution}}_{\text{discrimination}} + \underbrace{\text{uncertainty}}_{\text{irreducible}}.</span> The reliability term <span class="math inline">= \sum_b \frac{n_b}{n}(\mathrm{conf}_b - \mathrm{acc}_b)^2</span> (the squared, weighted ECE); resolution measures the deviation of the <span class="math inline">\mathrm{acc}_b</span> from the prevalence; uncertainty <span class="math inline">= \bar y (1 - \bar y)</span> does not depend on the model. BS rewards <em>both</em> calibration and discrimination — it is a quadratic Brier distance; not to be confused with the log-loss (cross-entropy), which infinitely punishes wrong certainties.</p>
</div>
<div class="ex">
<p><span class="tag">Example 7.4 — Brier computed, and the mirage of confidence</span> Four predictions: <span class="math inline">(0.9; y{=}1)</span>, <span class="math inline">(0.9; y{=}1)</span>, <span class="math inline">(0.9; y{=}0)</span>, <span class="math inline">(0.3; y{=}1)</span>: <span class="math display">\mathrm{BS} = \frac{0.1^2 + 0.1^2 + 0.9^2 + 0.7^2}{4} = \frac{0.01 + 0.01 + 0.81 + 0.49}{4} = 0.33.</span> The <em>constant</em> predictor equal to the prevalence <span class="math inline">3/4 = 0.75</span> achieves <span class="math inline">\mathrm{BS} = 0.75 \times 0.25 = 0.1875 \&lt; 0.33</span>: without information, it is better to state the base rate than to assert 90% — exactly the problem of overenthusiastic models.</p>
</div>
<div class="thm">
<p><span class="tag">Procedure 7.5 — Temperature scaling (Guo, Pleiss, Sun, Weinberger, 2017)</span> A single scalar <span class="math inline">T \&gt; 0</span> recalibrates the logits: <span class="math inline">\hat p_T(y \mid x) = \mathrm{softmax}(z/T)</span>; <span class="math inline">T</span> fitted by NLL on a validation set (a 1D optimization — which does not change the argmax, hence not the accuracy). <strong>Computed.</strong> Two classes, logits <span class="math inline">z = (4; 0)</span>: <span class="math inline">\mathrm{softmax}(z) = (0.982; 0.018)</span>; <span class="math inline">T = 2</span>: <span class="math inline">\mathrm{softmax}(2, 0) = (0.881; 0.119)</span>; <span class="math inline">T = 4</span>: <span class="math inline">\mathrm{softmax}(1, 0) = (0.731; 0.269)</span>. If the true frequency of class 1 in this neighborhood is ~75%, <span class="math inline">T \approx 4</span> is the right calibration — the ranking of the predictions is intact, only the confidence scale is corrected. Limits: <span class="math inline">T</span> is global, calibrated on a fixed distribution; local recalibration: isotonic, Platt per bin, or conformalized calibration (ch.&nbsp;9-10).</p>
</div>
<div class="sourceCode" id="cb2"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> ece(conf, y, bins<span class="op">=</span><span class="dv">15</span>):</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    edges <span class="op">=</span> np.linspace(<span class="dv">0</span>, <span class="dv">1</span>, bins <span class="op">+</span> <span class="dv">1</span>)<span class="op">;</span> idx <span class="op">=</span> np.digitize(conf, edges[<span class="dv">1</span>:<span class="op">-</span><span class="dv">1</span>])</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">len</span>(conf)<span class="op">;</span> total <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> b <span class="kw">in</span> <span class="bu">range</span>(bins):</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>        m <span class="op">=</span> idx <span class="op">==</span> b</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> m.<span class="bu">sum</span>() <span class="op">==</span> <span class="dv">0</span>: <span class="cf">continue</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>        total <span class="op">+=</span> (m.<span class="bu">sum</span>()<span class="op">/</span>n) <span class="op">*</span> <span class="bu">abs</span>(y[m].mean() <span class="op">-</span> conf[m].mean())</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> total</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fit_temperature(logits, y, grid<span class="op">=</span>np.linspace(<span class="fl">0.5</span>, <span class="dv">10</span>, <span class="dv">200</span>)):</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># NLL on validation, one dimension, non-parametric and sufficient for labs</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    best_T, best <span class="op">=</span> <span class="fl">1.0</span>, np.inf</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> T <span class="kw">in</span> grid:</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>        z <span class="op">=</span> logits <span class="op">/</span> T</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>        p <span class="op">=</span> np.exp(z <span class="op">-</span> z.<span class="bu">max</span>(<span class="dv">1</span>, keepdims<span class="op">=</span><span class="va">True</span>))</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>        p <span class="op">/=</span> p.<span class="bu">sum</span>(<span class="dv">1</span>, keepdims<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>        nll <span class="op">=</span> <span class="op">-</span>np.log(np.clip(p[np.arange(<span class="bu">len</span>(y)), y], <span class="fl">1e-12</span>, <span class="va">None</span>)).mean()</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> nll <span class="op">&lt;</span> best: best, best_T <span class="op">=</span> nll, T</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> best_T</span></code></pre></div>
<h2 id="ch8">8. Bayesian deep learning: MC dropout versus ensembles</h2>
<div class="def">
<p><span class="tag">Definition 8.1 — The Bayesian framework for networks</span> A prior <span class="math inline">p(w)</span> on the weights, a likelihood <span class="math inline">p(y \mid x, w)</span>; the predictive integrates epistemic uncertainty: <span class="math display">p(y \mid x, \mathcal D) = \int p(y \mid x, w)\, p(w \mid \mathcal D)\, dw.</span> The posterior <span class="math inline">p(w \mid \mathcal D)</span> is intractable; the whole field is the art of approximating it without spending one’s life on it (variational inference, Laplace, sampling; cf.&nbsp;Refresher Statistics module ch.&nbsp;8 for the Bayesian foundation).</p>
</div>
<div class="thm">
<p><span class="tag">Result 8.2 — MC dropout (Gal &amp; Ghahramani, 2016)</span> Train with dropout (Deep Learning module ch.&nbsp;3) then, at inference, keep dropout active and average <span class="math inline">T</span> forward passes: <span class="math display">\hat p(y \mid x) = \frac{1}{T} \sum_{t=1}^{T} p(y \mid x, \hat w_t), \qquad \hat w_t \sim \text{dropout masks}.</span> Gal &amp; Ghahramani show that this procedure approximates a Gaussian variational inference: dropout is a Bernoulli prior on the weights, and the dropout loss minimizes a KL bound toward the true posterior (spirit: like the substitution theorem of the bootstrap in Statistics in Action ch.&nbsp;7 — an asymptotic justification for a massive procedure). <strong>Cost:</strong> <span class="math inline">T</span> forwards per example (typically <span class="math inline">T \in [10; 100]</span>), zero retraining. <strong>The variance between passes measures the epistemic part</strong>.</p>
</div>
<div class="thm">
<p><span class="tag">Result 8.3 — Deep ensembles (Lakshminarayanan, Pritzel, Blundell, 2017)</span> Train <span class="math inline">M</span> independent networks (different initializations; option: adversarial training) and aggregate: average of the probabilities (classification), mixture of the predicted Gaussians (regression — the aggregated variance includes the dispersion of the means). Bayesian position (Wilson &amp; Izmailov, 2020): ensembles approximate the <em>posterior in function space</em> better than methods in weight space; pragmatic position: the most robust baseline of the field, at the price of <span class="math inline">M</span> trainings.</p>
</div>
<div class="ex">
<p><span class="tag">Example 8.4 — Compared on the dimensions that matter</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Criterion</th>
<th style="text-align: left;">MC dropout</th>
<th style="text-align: left;">Deep ensembles</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Training cost</td>
<td style="text-align: left;">1×</td>
<td style="text-align: left;">M× (typically 5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inference cost</td>
<td style="text-align: left;">T forwards</td>
<td style="text-align: left;">M forwards</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Epistemic out of distribution</td>
<td style="text-align: left;">correct, sometimes underestimated</td>
<td style="text-align: left;">good (diversity of minima)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Heteroscedastic aleatoric</td>
<td style="text-align: left;">if a variance head is added</td>
<td style="text-align: left;">native (mixture)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Out-of-distribution detection (OOD)</td>
<td style="text-align: left;">variance of the passes → score</td>
<td style="text-align: left;">disagreement between members → score</td>
</tr>
<tr class="even">
<td style="text-align: left;">LLM scale</td>
<td style="text-align: left;">dropout already exists (reasonable)</td>
<td style="text-align: left;">prohibitive (but cf.&nbsp;snapshots/weight averaging)</td>
</tr>
</tbody>
</table>
<p>The famous “deep ensembles work better than one would expect from a Bayesian perspective” (a position defended by Lakshminarayanan et al.) and the counterpoint “ensembles ARE approximate Bayes model averaging” (Wilson &amp; Izmailov): the disagreement is real, practice decides: <em>with a free training compute budget, ensembles; otherwise MC dropout</em>; and in all cases, evaluate the calibration (ch.&nbsp;7) — not just the RMSE.</p>
</div>
<div class="note">
<p><span class="tag">Usage warning</span> These methods give uncertainties <em>without guarantee</em>: they can be silently overconfident out of distribution. Ch. 9 brings the distribution-free corrective; the typical modern combination: ensembles for diversity + conformal for the coverage guarantee.</p>
</div>
<h2 id="ch9">9. Conformal prediction: theorem and algorithm</h2>
<p>Question: can we build prediction sets with coverage <strong>guaranteed without any distributional assumption</strong>? Answer (Vovk): yes, provided one has <em>exchangeable</em> data and accepts <em>marginal</em> coverage. This is the most useful result of the UQ part.</p>
<div class="def">
<p><span class="tag">Definition 9.1 — Non-conformity scores and exchangeability</span> Any score <span class="math inline">s(x, y)</span> (small = conforming): for classification, <span class="math inline">s = 1 - \hat p(y \mid x)</span> (softmax of the true class); for regression, <span class="math inline">s = \|y - \hat f(x)\|</span>. The data <span class="math inline">Z_1, \dots, Z_n, Z_{n+1}</span> are <strong>exchangeable</strong> if their joint law is invariant under permutation (i.i.d. ⇒ exchangeable; cf.&nbsp;Statistics in Action ch.&nbsp;11 for the de Finetti connection — exchangeability, not i.i.d., is the true foundation). Split conformal: split into <em>train</em> (the model learns) and <em>calibration</em> (the scores, never seen by the model).</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 9.2 — Exact marginal coverage (proved)</span> Let <span class="math inline">s_1, \dots, s_n</span> be the calibration scores and <span class="math inline">s_{\text{new}}</span> the score of a new pair, <strong>exchangeable</strong> at <span class="math inline">(n+1)</span> with continuous values. For <span class="math inline">\alpha \in (0, 1)</span>, set <span class="math inline">k = \lceil (n+1)(1 - \alpha) \rceil</span> and let <span class="math inline">\hat q</span> be the <span class="math inline">k</span>-th smallest calibration score. Then <span class="math display">\mathbb{P}\big( s_{\text{new}} \leq \hat q \big) \;\geq\; 1 - \alpha \qquad \text{(exactly } k/(n+1) \text{ for continuous scores).}</span></p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>By exchangeability, the rank of <span class="math inline">s_{\text{new}}</span> in the multiset <span class="math inline">\{s_1, \dots, s_n, s_{\text{new}}\}</span> is <strong>uniform over <span class="math inline">\{1, \dots, n+1\}</span></strong>. Justification: for every permutation <span class="math inline">\sigma</span> of <span class="math inline">\{1, \dots, n+1\}</span>, the law of <span class="math inline">(Z_{\sigma(1)}, \dots, Z_{\sigma(n+1)})</span> is that of <span class="math inline">(Z_1, \dots, Z_{n+1})</span>; the event “the rank of the last coordinate equals <span class="math inline">r</span>” is the image by permutation of “the rank equals <span class="math inline">r'</span>” for all <span class="math inline">r, r'</span> — same probability, and the sum of the <span class="math inline">n+1</span> probabilities equals 1: each equals <span class="math inline">1/(n+1)</span>. With continuous scores, ties are almost surely absent, and the event <span class="math inline">\{s_{\text{new}} \leq \hat q\}</span> is exactly <span class="math inline">\{\text{rank} \leq k\}</span>, of probability <span class="math inline">k/(n+1) \geq 1 - \alpha</span> by definition of <span class="math inline">k</span>. By exchanging the roles of the <span class="math inline">n+1</span> positions, no asymptotic result is used: the guarantee is <em>finite-sample</em>. With ties, taking <span class="math inline">\hat q</span> as the <span class="math inline">k</span>-th smallest value counting strictly keeps the event <span class="math inline">\{s_{\text{new}} \&lt; \hat q\} \cup \{s_{\text{new}} = \hat q\}</span> of probability <span class="math inline">\geq k/(n+1)</span> — the bound survives. <span class="qed">∎</span></p>
</div>
</div>
<div class="ex">
<p><span class="tag">Example 9.3 — Split conformal, algorithm and worked example</span> <strong>Algorithm.</strong> (1) train <span class="math inline">\hat f</span> on the train set; (2) compute the scores <span class="math inline">s_i</span> on the <span class="math inline">n</span> calibration points; (3) <span class="math inline">k = \lceil (n+1)(1-\alpha) \rceil</span>, <span class="math inline">\hat q</span> = <span class="math inline">k</span>-th smallest score; (4) predict, for a new <span class="math inline">x</span>, the set <span class="math inline">C(x) = \{y : s(x, y) \leq \hat q\}</span> — in regression: <span class="math inline">[\hat f(x) - \hat q, \hat f(x) + \hat q]</span>. <strong>Example (regression).</strong> <span class="math inline">n = 9</span>, <span class="math inline">\alpha = 0.1</span> ⇒ <span class="math inline">k = \lceil 10 \times 0.9 \rceil = 9</span>. Absolute calibration residuals: 0.02 · 0.05 · 0.08 · 0.11 · 0.14 · 0.19 · 0.25 · 0.34 · 0.51 — the 9th (largest) is <span class="math inline">\hat q = 0.51</span>; the prediction for any new <span class="math inline">x</span> is <span class="math inline">\hat f(x) \pm 0.51</span>, with <span class="math inline">\mathbb{P}(\text{cover}) \geq 90\%</span> — <em>exactly</em> <span class="math inline">9/10 = 90\%</span> if the future residuals resemble the calibration ones. <strong>Classification</strong>: same steps with <span class="math inline">s = 1 - \hat p(\text{candidate predicted class})</span>; the set <span class="math inline">C(x)</span> contains the classes with sufficient softmax; typical size 1 where the model is confident, 2-3 at the boundaries — the map of set sizes is a free ambiguity detector. <strong>Effect of <span class="math inline">n</span></strong>: the empirical <span class="math inline">(1-\alpha)</span>-quantile with finite-sample correction <span class="math inline">\lceil(n+1)(1-\alpha)\rceil</span> — the reason for the <span class="math inline">+1</span>: without it, <span class="math inline">\alpha \&gt; 1/(n+1)</span> would be impossible (e.g.&nbsp;<span class="math inline">\alpha = 0.1</span>, <span class="math inline">n = 5</span>: one needs <span class="math inline">k = \lceil 5.4 \rceil = 6 \&gt; n</span>… in that case the set is all of <span class="math inline">\mathbb R</span>: the algorithm honestly admits its ignorance).</p>
</div>
<div class="sourceCode" id="cb3"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">1</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>n_cal, alpha <span class="op">=</span> <span class="dv">3000</span>, <span class="fl">0.1</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>Xtr, Xcal, Xte <span class="op">=</span> ...           <span class="co"># exchangeable split</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>model.fit(Xtr, ytr)            <span class="co"># never the calibration set</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>s_cal <span class="op">=</span> np.<span class="bu">abs</span>(y_cal <span class="op">-</span> model.predict(X_cal))       <span class="co"># non-conformity scores</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>k <span class="op">=</span> <span class="bu">int</span>(np.ceil((n_cal <span class="op">+</span> <span class="dv">1</span>) <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> alpha)))        <span class="co"># 9 for n=9; 2701 for n=3000</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>qhat <span class="op">=</span> np.sort(s_cal)[k <span class="op">-</span> <span class="dv">1</span>]</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>lo, hi <span class="op">=</span> model.predict(X_te) <span class="op">-</span> qhat, model.predict(X_te) <span class="op">+</span> qhat</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="co"># empirical check of the coverage (exercise 6)</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>cov <span class="op">=</span> ((y_te <span class="op">&gt;=</span> lo) <span class="op">&amp;</span> (y_te <span class="op">&lt;=</span> hi)).mean()</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"qhat = </span><span class="sc">{</span>qhat<span class="sc">:.3f}</span><span class="ss">, observed coverage = </span><span class="sc">{</span>cov<span class="sc">:.3f}</span><span class="ss"> (target &gt;= </span><span class="sc">{</span><span class="dv">1</span><span class="op">-</span>alpha<span class="sc">}</span><span class="ss">)"</span>)</span></code></pre></div>
<div class="note">
<p><span class="tag">What the theorem says — and does not say</span> Coverage is <strong>marginal</strong>: on average over the draws of the calibration set <em>and</em> of new pairs. It can be uneven across groups (conditional coverage); extensions (Mondrian conformal: per-stratum coverage; weighted conformal: known covariate shift) handle structured cases. The train/calibration swap costs data; CV+/jackknife+ variants when <span class="math inline">n</span> is scarce. Internal link: the Statistics in Action module ch.&nbsp;7 applies the same “empirical quantile + finite-sample correction” logic to bootstrap intervals.</p>
</div>
<h2 id="ch10">10. Quantile and conformalized regression</h2>
<div class="def">
<p><span class="tag">Definition 10.1 — Distributional quantile, quantile regression, pinball loss (Koenker &amp; Bassett, 1978)</span> The quantile <span class="math inline">q_\tau(x)</span> of <span class="math inline">Y \mid X = x</span> satisfies <span class="math inline">\mathbb P(Y \leq q_\tau(x) \mid x) = \tau</span>. One estimates it by minimizing the <strong>pinball loss</strong>: <span class="math display">\ell_\tau(y, \hat q) = \begin{cases} \tau\,(y - \hat q) &amp; y \geq \hat q \\ (1 - \tau)\,(\hat q - y) &amp; y \&lt; \hat q \end{cases} \qquad \text{(subgradients } \in [\tau - 1, \tau]\text{)}.</span> This is a convex problem (a linear program for the linear model; gradient descent for networks); training two heads <span class="math inline">\hat q_{\text{lo}} = \hat q_{\alpha/2}</span>, <span class="math inline">\hat q_{\text{hi}} = \hat q_{1 - \alpha/2}</span> gives an <em>adaptive</em> prediction band — wide where the data are dispersed (heteroscedastic aleatoric, ch.&nbsp;6). Without an exact coverage guarantee, however: the learned quantiles are optimistic on the train set.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 10.2 — Conformalized Quantile Regression (Romano, Patterson, Candès, 2019)</span> Non-conformity score on calibration: <span class="math display">s_i = \max\big( \hat q_{\text{lo}}(x_i) - y_i,\; y_i - \hat q_{\text{hi}}(x_i) \big).</span> Taking <span class="math inline">\hat q</span> = the <span class="math inline">\lceil(n+1)(1-\alpha)\rceil</span>-th smallest score, the band <span class="math display">C(x) = \big[ \hat q_{\text{lo}}(x) - \hat q,\; \hat q_{\text{hi}}(x) + \hat q \big]</span> has coverage <span class="math inline">\geq 1 - \alpha</span> in finite samples (thm 9.2), <em>and</em> inherits the adaptivity of the learned quantiles: the bands vary with <span class="math inline">x</span>. In short: <strong>CQR = quantiles (local shape) + conformal (global guarantee)</strong> — the dominant recipe in practice.</p>
</div>
<div class="ex">
<p><span class="tag">Example 10.3 — CQR on a synthetic case, verified</span> <span class="math inline">y = 2x + \sin(2x)\, (1 + 0.5x)\,\varepsilon</span> (increasing variance). In the lab: (1) a two-head pinball network (<span class="math inline">\tau \in \{0.05, 0.95\}</span>); (2) 1000 calibration points, scores <span class="math inline">s_i</span>; (3) <span class="math inline">\hat q \approx</span> corrected empirical quantile; (4) over 100 repetitions, mean coverage 89.8% (target 90%), bands ~3× narrower than the constant-residual split conformal in calm regions — the “hourglass” plot of the bands flaring at large <span class="math inline">x</span> is the visual deliverable of the lab (exercise 7).</p>
</div>
<h2 id="ch11">11. UQ for LLMs</h2>
<p>LLMs add three difficulties to the calibration problem: the output space is combinatorial (sequences, not classes); RLHF training seems to degrade verbal calibration; and generative use (a written answer) does not naturally expose token probabilities. The M2 module “Explainability, Security, Privacy of LLMs” will complete this part (security, jailbreaks, training extraction); cf.&nbsp;also the Large Language Models module, ch.&nbsp;9.</p>
<div class="def">
<p><span class="tag">Definition 11.1 — Verbalized confidence</span> Ask the model for its confidence <em>in words</em>: “What’s the probability that your answer is correct? Answer with a number in [0, 100]” (Lin, Hilton, Evans, 2022). On pre-trained models (GPT-3 on trivia), verbalized confidence is <em>fairly well calibrated</em> — the model has absorbed the calibration of its pre-training log-loss. But: Tian et al.&nbsp;(2023, “Just Ask for Calibration”) show that aligned (RLHF) models are clearly overconfident and not very sensitive to the wording; Xiong et al.&nbsp;(2024) confirm the systematic overconfidence and the massive influence of the prompt (chain-of-thought, multiple choice), with calibration gaps depending on the format of several tens of ECE points.</p>
</div>
<div class="def">
<p><span class="tag">Definition 11.2 — Three native sources of generative uncertainty</span> <strong>(1) Token logprobs</strong>: entropy of the distribution of the next token, or sequence probability (product); biased (length, temperature); local calibration per bin (as in ch.&nbsp;7) on a labeled set. <strong>(2) Self-consistency</strong>: sample <span class="math inline">K</span> trajectories (temperature &gt; 0) and measure agreement: the frequency of the majority answer is a proxy for confidence (direct link with the ensemble diversity of ch.&nbsp;8 — prediction averaging vs variance); Kuhn, Gal, Farquhar (2023) refine this into <strong>semantic uncertainty</strong>: cluster the <em>semantically equivalent</em> responses (mutual implications predicted by an NLI) and compute the entropy over the clusters — because “Paris”, “paris”, and “the capital” are the same answer for the user; separates semantic uncertainty (is the answer determined?) from lexical uncertainty. <strong>(3) Generative conformal</strong>: apply ch.&nbsp;9 to scores (negative sequence logprob, semantic conformity): response sets with guaranteed coverage — the loop is closed with distribution-free methods.</p>
</div>
<div class="note">
<p><span class="tag">The privacy wall on the LLM side</span> LLMs memorize (ch.&nbsp;5, Secret Sharer); DP-SGD at the scale of 10¹¹ parameters still costs too much utility for general-purpose pre-training; current industrial leads: DP-SGD on the alignment phases (the most sensitive data), private RAG (the data stay server-side with per-query budgets), federated learning + DP (cf.&nbsp;Emerging ML module ch.&nbsp;3), and the systematic evaluation of extraction (canaries). An open topic — precisely the crossroads targeted by this module.</p>
</div>
<h2 id="ch12">12. Applications: deciding under uncertainty</h2>
<div class="ex">
<p><span class="tag">Example 12.1 — Medicine: calibration as a condition of care</span> A risk model announcing “30% complications” triggers a costly protocol: if the 30% announcers actually operate at 45% (underconfidence), we overtreat; at 15% (overconfidence), we undertreat — both kill. Van Calster et al.&nbsp;(2019) document the chronic miscalibration of published clinical models and call it the “Achilles heel of predictive analytics”; remedy: mandatory reliability diagrams (ch.&nbsp;7), recalibration (temperature/isotonic), and for binary decisions: thresholds derived from utility (FN cost / FP cost), not raw probabilities.</p>
</div>
<div class="def">
<p><span class="tag">Definition 12.2 — Expected-utility decision, abstention, risk control</span> With costs <span class="math inline">c_{\text{FP}}, c_{\text{FN}}</span>, the optimal classifier will predict 1 only if <span class="math inline">\hat p \geq c_{\text{FP}} / (c_{\text{FP}} + c_{\text{FN}})</span> — an exact formula <em>if</em> <span class="math inline">\hat p</span> is calibrated (ch.&nbsp;6); hence the sequence of the module: calibrate (7), aggregate the sources (8-10), then decide. <strong>Selective abstention</strong>: the model may answer “I don’t know” when the conformal set has &gt; k elements or the CQR band is wider than a business threshold (delegation to a human); the risk-coverage curve is plotted in the lab. <strong>Risk control</strong> (Angelopoulos, Bates, Candès, Jordan, Lei, 2021): choose the threshold itself on a calibration set to control an <em>expectation</em> of arbitrary risk (error rate &gt; budget; false negatives &lt; budget); it is the same empirical-quantile equation as ch.&nbsp;9, applied to a decision threshold — the final building block of the “guarantee” chain.</p>
</div>
<div class="ex">
<p><span class="tag">Example 12.3 — Industrial assembly table</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Business need</th>
<th style="text-align: left;">Required guarantee</th>
<th style="text-align: left;">Tool of the module</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Publish stats without re-identification</td>
<td style="text-align: left;">controlled ε budget</td>
<td style="text-align: left;">ch.&nbsp;1–3 (mechanisms, RDP composition)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Train on customer data</td>
<td style="text-align: left;">formal privacy of the model</td>
<td style="text-align: left;">ch.&nbsp;4 (DP-SGD + accountant)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sort alerts</td>
<td style="text-align: left;">honest confidence ordering</td>
<td style="text-align: left;">ch.&nbsp;7 (calibration, Brier)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Per-point forecast intervals</td>
<td style="text-align: left;">guaranteed 90% coverage</td>
<td style="text-align: left;">ch.&nbsp;9–10 (conformal, CQR)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Delegate hard cases to a human</td>
<td style="text-align: left;">error rate of the subset</td>
<td style="text-align: left;">ch.&nbsp;12 (selective prediction, LTT)</td>
</tr>
<tr class="even">
<td style="text-align: left;">LLM in production</td>
<td style="text-align: left;">confidence of the answers</td>
<td style="text-align: left;">ch.&nbsp;11 (semantic, generative conformal)</td>
</tr>
</tbody>
</table>
<p>Position in the master: this module is the “guarantees” foundation of M2; the Geometric Deep Learning and Advanced GNN modules reuse MC dropout/ensembles on graphs; the Large Language Models module deepens evaluation; and the security part will be covered in “Explainability, Security, Privacy of LLMs”.</p>
</div>
<h2 id="ex">Exercises</h2>
<ol type="1">
<li><strong>Laplace mechanism.</strong> (a) Re-prove thm 2.1 for <span class="math inline">k = 1</span>. (b) Counting with ε = ln 20: probability of an error ≥ 2? ≥ 5? (c) 50-bin histogram, total ε = 1; distribute the noise (composition) and compare the mean squared error with the vector Laplace mechanism in a single query.</li>
<li><strong>Composition.</strong> (a) Redo the computation 3.4 for <span class="math inline">\sigma = 12</span>, <span class="math inline">k = 256</span>, <span class="math inline">\delta = 10^{-5}</span>. (b) Inverse: what <span class="math inline">\sigma</span> for <span class="math inline">k = 10^4</span> DP-SGD steps, ε = 2, δ = 10⁻⁵, <span class="math inline">\gamma = 0.01</span> (approximation without amplification, then with the <span class="math inline">\gamma^2</span> factor)? (c) Show that RDP composition at fixed <span class="math inline">\alpha</span> is exact for Gaussians (direct computation of the Rényi divergence of a product).</li>
<li><strong>Local DP.</strong> (a) Prove the debiasing formula 4.2 and its variance factor. (b) In RAPPOR with 128 bits, 2 successive RRs: what ε per bit? (c) Sizing: precision of ±2 points on a proportion, <span class="math inline">p = 0.75</span> — how many users?</li>
<li><strong>DP-SGD.</strong> On MNIST: implement per-example clipping + noise (numpy or Opacus), plot accuracy vs ε for σ ∈ {0, 0.5, 1, 2}, comment on the frontier; ablation on <span class="math inline">C</span> (0.1 to 10); verify that without clipping the mechanism is no longer DP.</li>
<li><strong>Calibration.</strong> (a) Recompute the ECE 7.2 with 10 equal-width bins and comment on the sensitivity. (b) Implement the reliability diagram. (c) Temperature scaling on CIFAR-10 (ResNet): ECE before/after, NLL before/after, accuracy unchanged? (d) Show that the constant 0.75 beats the classifier of example 7.4 in Brier score but not in log-loss if one of the events becomes certain.</li>
<li><strong>MC dropout versus ensembles.</strong> 1D heteroscedastic regression: train (a) one network + MC dropout (<span class="math inline">T = 50</span>); (b) 5 networks (deep ensemble); compare NLL, RMSE, coverage of the ±2σ bands; (c) test both out of distribution (extrapolation); (d) compare training and inference times, and conclude in a budget-constrained situation.</li>
<li><strong>Conformal.</strong> (a) Re-prove the uniformity of the rank with ties (convention of thm 9.2). (b) Empirically verify the coverage over 1000 repetitions (n = 1000, α = 0.1): histogram of the coverages — what happens if the data are <em>not</em> exchangeable (drift)? (c) Effect of the calibration size: <span class="math inline">n \in \{20, 100, 1000\}</span>; (d) implement per-class Mondrian and measure the coverage inequality across classes.</li>
<li><strong>CQR.</strong> Reproduce example 10.3; compare the mean widths CQR vs constant split conformal; what happens if the two quantile heads cross (lo &gt; hi)? Fix it (monotonicity constraint or sorting).</li>
<li><strong>LLM UQ.</strong> (a) On 100 trivia questions: verbalized confidence vs actual frequency — plot the reliability diagram. (b) Self-consistency K = 10: correlation between agreement and correctness. (c) Group the answers semantically (by hand or NLI) and compare lexical vs semantic entropy. (d) At small scale: build a conformal set of answers and measure the coverage.</li>
<li><strong>Decision.</strong> Screening: prevalence 5%, costs <span class="math inline">c_{FP} = 1</span>, <span class="math inline">c_{FN} = 20</span>. (a) Optimal threshold on calibrated probabilities. (b) Re-derive with probabilities overconfident by 10 points — quantify the cost of miscalibration. (c) Add the abstention option with a delegation cost; plot risk-coverage.</li>
<li><strong>Project.</strong> Complete “privacy + UQ” pipeline: a sensitive dataset (e.g.&nbsp;Adult): (1) publish useful statistics under budget ε = 2 (mechanisms, composition); (2) train a private predictive model (DP-SGD); (3) calibrate and conformalize its outputs; (4) write the guarantee sheet (ε, δ, coverage, ECE) and the limitations discussion. Grading: 30% privacy, 30% UQ, 20% empirical validation, 20% sheet and honesty about the limits.</li>
</ol>
<h2 id="refs">References</h2>
<ul>
<li>C. Dwork, F. McSherry, K. Nissim, A. Smith, “Calibrating Noise to Sensitivity in Private Data Analysis”, TCC 2006 — the founding act.</li>
<li>C. Dwork, A. Roth, “The Algorithmic Foundations of Differential Privacy”, <em>Foundations and Trends in Theoretical Computer Science</em> 9, 2014 — the handbook.</li>
<li>C. Dwork, G. Rothblum, S. Vadhan, “Boosting and Differential Privacy”, FOCS 2010 — advanced composition.</li>
<li>I. Mironov, “Rényi Differential Privacy”, CSF 2017 — <a href="https://arxiv.org/abs/1702.07476">arXiv:1702.07476</a>.</li>
<li>M. Bun, T. Steinke, “Concentrated Differential Privacy: Simplifications, Extensions, and Lower Bounds”, TCC 2016.</li>
<li>Y.-X. Wang, B. Balle, S. Kasiviswanathan, “Subsampled Rényi Differential Privacy and Analytical Moments Accountant”, AISTATS 2019 — <a href="https://arxiv.org/abs/1808.00087">arXiv:1808.00087</a>.</li>
<li>M. Abadi, A. Chu, I. Goodfellow, H. B. McMahan, I. Mironov, K. Talwar, L. Zhang, “Deep Learning with Differential Privacy”, CCS 2016 — <a href="https://arxiv.org/abs/1607.00133">arXiv:1607.00133</a> (DP-SGD, moments accountant).</li>
<li>Ú. Erlingsson, V. Pihur, A. Korolova, “RAPPOR: Randomized Aggregatable Privacy-Preserving Ordinal Response”, CCS 2014 — <a href="https://arxiv.org/abs/1407.6981">arXiv:1407.6981</a>.</li>
<li>S. Warner, “Randomized Response: A Survey Technique for Eliminating Evasive Answer Bias”, <em>JASA</em> 60, 1965.</li>
<li>A. Evfimievski et al., “Limiting Privacy Breaches in Privacy Preserving Data Mining”, PODS 2003 — modern randomized response, local DP.</li>
<li>J. Abowd, “The U.S. Census Bureau Adopts Differential Privacy”, KDD 2018.</li>
<li>Apple Differential Privacy Team, “Learning with Privacy at Scale”, <em>Apple Machine Learning Journal</em> 1(8), 2017.</li>
<li>R. Shokri, M. Stronati, C. Song, V. Shmatikov, “Membership Inference Attacks Against Machine Learning Models”, IEEE S&amp;P 2017.</li>
<li>N. Carlini, C. Liu, Ú. Erlingsson, J. Kos, D. Song, “The Secret Sharer: Evaluating and Testing Unintended Memorization in Neural Networks”, USENIX Security 2019 — <a href="https://arxiv.org/abs/1802.08232">arXiv:1802.08232</a>.</li>
<li>G. Brier, “Verification of Forecasts Expressed in Terms of Probability”, <em>Monthly Weather Review</em> 78, 1950; A. Murphy, “A New Vector Partition of the Probability Score”, <em>J. Applied Meteorology</em> 10, 1973.</li>
<li>M. P. Naeini, G. F. Cooper, M. Hauskrecht, “Obtaining Well Calibrated Probabilities Using Bayesian Binning”, AAAI 2015.</li>
<li>C. Guo, G. Pleiss, Y. Sun, K. Q. Weinberger, “On Calibration of Modern Neural Networks”, ICML 2017 — <a href="https://arxiv.org/abs/1706.04599">arXiv:1706.04599</a>.</li>
<li>B. Lakshminarayanan, A. Pritzel, C. Blundell, “Simple and Scalable Predictive Uncertainty Estimation using Deep Ensembles”, NeurIPS 2017 — <a href="https://arxiv.org/abs/1612.01474">arXiv:1612.01474</a>.</li>
<li>Y. Gal, Z. Ghahramani, “Dropout as a Bayesian Approximation: Representing Model Uncertainty in Deep Learning”, ICML 2016 — <a href="https://arxiv.org/abs/1506.02142">arXiv:1506.02142</a>.</li>
<li>A. G. Wilson, P. Izmailov, “Bayesian Deep Learning and a Probabilistic Perspective of Generalization”, NeurIPS 2020 — <a href="https://arxiv.org/abs/2002.08791">arXiv:2002.08791</a>.</li>
<li>V. Vovk, A. Gammerman, G. Shafer, <em>Algorithmic Learning in a Random World</em>, Springer, 2005 (2nd ed.&nbsp;2022) — the founding book of conformal prediction.</li>
<li>J. Lei, M. G’Sell, A. Rinaldo, R. Tibshirani, L. Wasserman, “Distribution-Free Predictive Inference for Regression”, <em>JASA</em> 113, 2018 — <a href="https://arxiv.org/abs/1604.04173">arXiv:1604.04173</a>.</li>
<li>Y. Romano, E. Patterson, E. Candès, “Conformalized Quantile Regression”, NeurIPS 2019 — <a href="https://arxiv.org/abs/1905.03222">arXiv:1905.03222</a>.</li>
<li>A. N. Angelopoulos, S. Bates, “A Gentle Introduction to Conformal Prediction and Distribution-Free Uncertainty Quantification”, 2023 — <a href="https://arxiv.org/abs/2107.07511">arXiv:2107.07511</a>.</li>
<li>A. N. Angelopoulos, S. Bates, E. Candès, M. Jordan, L. Lei, “Learn then Test: Calibrating Predictive Algorithms to Achieve Risk Control”, ICML 2021 — <a href="https://arxiv.org/abs/2110.01052">arXiv:2110.01052</a>.</li>
<li>R. Koenker, G. Bassett, “Regression Quantiles”, <em>Econometrica</em> 46, 1978.</li>
<li>S. Lin, J. Hilton, O. Evans, “Teaching Models to Express Their Uncertainty in Words”, TMLR 2022 — <a href="https://arxiv.org/abs/2205.14334">arXiv:2205.14334</a>.</li>
<li>K. Tian, W. Yao, D. Yu, L. Mou, “Just Ask for Calibration: Strategies for Eliciting Calibrated Confidence Scores from Language Models Fine-Tuned with Human Feedback”, EMNLP 2023 (Findings) — <a href="https://arxiv.org/abs/2305.14975">arXiv:2305.14975</a>.</li>
<li>M. Xiong, Z. Hu, X. Lu, Y. Li, J. Fu, J. He, B. Hooi, “Can LLMs Express Their Uncertainty? An Empirical Evaluation of Confidence Elicitation in LLMs”, ICLR 2024 — <a href="https://arxiv.org/abs/2306.13063">arXiv:2306.13063</a>.</li>
<li>L. Kuhn, Y. Gal, S. Farquhar, “Semantic Uncertainty: Linguistic Invariances for Uncertainty Estimation in Natural Language Generation”, ICLR 2023 — <a href="https://arxiv.org/abs/2302.09664">arXiv:2302.09664</a>.</li>
<li>B. Van Calster, D. J. McLernon, M. van Smeden, L. Wynants, E. W. Steyerberg, on behalf of Topic Group 6 (Evaluating diagnostic tests and prediction models) of the STRATOS initiative, “Calibration: the Achilles heel of predictive analytics”, <em>BMC Medicine</em> 17:230, 2019.</li>
<li>Internal follow-ups: M1 modules “Refresher Statistics” (ch.&nbsp;8: Bayesian statistics), “Machine Learning” (ch.&nbsp;7: generalization; ch.&nbsp;9: evaluation), “Emerging ML” (ch.&nbsp;3–5: federated, Byzantine, privacy: first encounter with DP), “Statistics in Action” (ch.&nbsp;6–7: multiple testing, bootstrap — the empirical-quantile logic of conformal), M2 “Large Language Models” (ch.&nbsp;9–10); the future M2 module “Explainability, Security, Privacy of LLMs” will complete the security and privacy part for LLMs.</li>
<li>Tools: <a href="https://opacus.ai">Opacus</a> (PyTorch&nbsp;/ Meta), TensorFlow Privacy, <a href="https://opendp.org">OpenDP</a>, Google DP library; <a href="https://github.com/valeman/awesome-conformal-prediction">awesome-conformal-prediction</a> for the conformal ecosystem, MAPIE (scikit-learn-contrib).</li>
</ul>

</main>
<footer class="foot"><p><a href="../../index.html">← Master's program</a></p></footer>
<script defer="" src="../../assets/theme.js"></script>




</body></html>