<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistics in Action</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script>(function(){try{var t=localStorage.getItem("llga-theme");if(t==="dark"||t==="light")document.documentElement.setAttribute("data-theme",t);}catch(e){}})();</script>
<style>
  /* Keep paper.css as visual source of truth; tame Quarto chrome */
  #title-block-header { margin: 0 0 0.5rem; }
  #title-block-header .title { margin: 0 0 0.25rem; font-size: 1.85rem; font-weight: 700; }
  #title-block-header .subtitle { color: var(--soft, #555); margin: 0 0 1rem; font-size: 1.05rem; }
  div.sourceCode { background: var(--code-bg, #f7f7f7); border: 1px solid var(--hair, #e4e4e4); }
  code { background: var(--code-inline-bg, #f4f4f4); }

  /* Light (github) token colors — higher specificity beats paper.css */
  div.sourceCode pre.sourceCode code span.kw, div.sourceCode pre.sourceCode code span.cf, div.sourceCode pre.sourceCode code span.dt, div.sourceCode pre.sourceCode code span.at, div.sourceCode pre.sourceCode code span.bu, div.sourceCode pre.sourceCode code span.pp { color: #d73a49; }
  div.sourceCode pre.sourceCode code span.im, div.sourceCode pre.sourceCode code span.st, div.sourceCode pre.sourceCode code span.ch, div.sourceCode pre.sourceCode code span.ss, div.sourceCode pre.sourceCode code span.vs { color: #032f62; }
  div.sourceCode pre.sourceCode code span.co, div.sourceCode pre.sourceCode code span.an, div.sourceCode pre.sourceCode code span.cv, div.sourceCode pre.sourceCode code span.do, div.sourceCode pre.sourceCode code span.in { color: #6a737d; }
  div.sourceCode pre.sourceCode code span.fu { color: #6f42c1; }
  div.sourceCode pre.sourceCode code span.va { color: #e36209; }
  div.sourceCode pre.sourceCode code span.cn, div.sourceCode pre.sourceCode code span.bn, div.sourceCode pre.sourceCode code span.dv, div.sourceCode pre.sourceCode code span.fl, div.sourceCode pre.sourceCode code span.sc { color: #005cc5; }
  div.sourceCode pre.sourceCode code span.op { color: #24292e; }
  /* Dark mode token colors (github highlight is light-oriented) */
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.kw,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.cf,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.dt,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.at,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.bu,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.pp,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.op { color: #ff7b72; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.im { color: #ff7b72; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.st,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.ch,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.ss,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.vs { color: #a5d6ff; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.cn,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.bn,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.dv,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.fl,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.sc { color: #79c0ff; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.co,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.an,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.cv,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.do,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.in { color: #8b949e; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.va { color: #ffa657; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.fu { color: #d2a8ff; }
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.kw,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.cf,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.dt,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.at,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.bu,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.pp,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.op { color: #ff7b72; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.im { color: #ff7b72; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.st,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.ch,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.ss,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.vs { color: #a5d6ff; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.cn,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.bn,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.dv,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.fl,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.sc { color: #79c0ff; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.co,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.an,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.cv,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.do,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.in { color: #8b949e; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.va { color: #ffa657; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.fu { color: #d2a8ff; }
  }

</style>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../assets/paper.css">
</head>

<body>

<p class="crumb"><a href="../../index.html">MSc&amp;T LLGA · Course notes</a></p>
<main class="paper">

<header id="title-block-header">
<h1 class="title">Statistics in Action</h1>
<p class="subtitle">APM_52066_EP · Year 1 · Period 2</p>

</header>


<h2 id="contents">Contents</h2>
<ul>
<li><a href="#intro">Introduction and overview</a></li>
<li><a href="#ch0">0. Review: the statistician’s survival kit</a></li>
<li><a href="#ch1">1. The life cycle of a statistical study</a></li>
<li><a href="#ch2">2. Experimental designs: randomization, blocks, power</a></li>
<li><a href="#ch3">3. Observational versus experimental: biases</a></li>
<li><a href="#ch4">4. Causal inference: potential outcomes and DiD</a></li>
<li><a href="#ch5">5. Regression in practice: diagnostics and transformations</a></li>
<li><a href="#ch6">6. Multiple testing: Bonferroni and Benjamini-Hochberg</a></li>
<li><a href="#ch7">7. The bootstrap in practice</a></li>
<li><a href="#ch8">8. A/B testing: sequential and targeted effects</a></li>
<li><a href="#ch9">9. Case study: agricultural trials and blocks</a></li>
<li><a href="#ch10">10. Communicating: intervals, p-values, honest visualizations</a></li>
<li><a href="#ch11">11. Course research notes (Naulet, MaIAGE)</a></li>
<li><a href="#ex">Exercises</a></li>
<li><a href="#refs">References</a></li>
</ul>
<h2 id="intro">Introduction and overview</h2>
<table class="caption-top">
<tbody>
<tr class="odd">
<td style="text-align: left;">Module</td>
<td style="text-align: left;">Statistics in Action</td>
</tr>
<tr class="even">
<td style="text-align: left;">Code</td>
<td style="text-align: left;">APM_52066_EP</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Team and workload</td>
<td style="text-align: left;">Official instructor: <a href="https://znaulet.pages-forge.inrae.fr/" style="color:#fff">Zacharie Naulet</a> (École Polytechnique &amp; INRAE, MaIAGE team) · 36 h of in-person classes (18 h lectures + 18 h small-class sessions; maximum enrollment: 90) · 4.5&nbsp;ECTS (value on the MScT tracks; 5&nbsp;ECTS in the engineering cycle) · the statistician’s craft on real data: planning a trial, randomizing, computing power, hunting biases, correcting multiple tests, bootstrapping and communicating honest results — from the agricultural trial to the A/B test.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Official course description (SynapseS 2026-2027)</td>
<td style="text-align: left;">Official title: “Statistique en Action” (in-depth program, applied mathematics) · period: X-3A-P2, from 04/01/2027 to 19/03/2027 · language of the course: French (languages of the description: French, English) · official assessment: 1 or 2 group projects + 1 lab-session report + a final exam · site linked on the description: <a href="https://jchiquet.github.io/MAP566/">jchiquet.github.io/MAP566</a> · <a href="https://synapses.polytechnique.fr/catalogue/2026-2027/ue/680/APM-52066-EP-statistique-en-action">APM_52066_EP course description</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Status in the program</td>
<td style="text-align: left;"><span class="badge option">P2 option</span><span class="badge position">Outside the recommended track</span></td>
</tr>
</tbody>
</table>
<p><strong>Audience</strong>: a product / data engineer who ships A/B tests and wants an honest pipeline. <strong>Empirical first</strong>: a “significant” p-value after peeking; underpowered design → business false negative — then we name experimental design, randomization, bootstrap, multiplicity.</p>
<p>The statistician’s craft on real data: a differentiator in an AI master’s.</p>
<h3 id="what-you-will-be-able-to-do">What you will be able to do</h3>
<ul>
<li>Run the complete cycle of a statistical study, from the initial question to communicable conclusions.</li>
<li>Design an experimental plan: randomization, blocks, and a power computation suited to the objective.</li>
<li>Identify the biases of observational studies and the classic pitfalls of inference.</li>
<li>Apply the basics of causal inference: potential outcomes and difference-in-differences (DiD).</li>
<li>Practice regression for real: diagnostics, transformations, reasoned decisions.</li>
<li>Correct multiple tests (Bonferroni, Benjamini-Hochberg) according to the goal.</li>
<li>Build intervals and tests by bootstrap on arbitrary data.</li>
<li>Run a modern A/B test: sequential, targeted effects — and report the results honestly.</li>
</ul>
<h3 id="official-objectives-and-syllabus-2026-2027-catalog">Official objectives and syllabus (2026-2027 catalog)</h3>
<p>According to the <a href="https://synapses.polytechnique.fr/catalogue/2026-2027/ue/680/APM-52066-EP-statistique-en-action">APM_52066_EP — “Statistique en Action”</a> description: the official objective is to show students how statistics are used in practice to answer a precise question, by introducing a series of important model-based approaches. Students learn to select and use the appropriate strategic methodologies, on concrete examples of real datasets from different fields — medicine, genomics, ecology, among others. All analyses are carried out in R; knowledge of R programming is not required (only basic scripting). The detailed session-by-session syllabus is not published on the description (not communicated); the course unit does however appear in the 2026-2027 catalog via the “P2 – Applied Mathematics” track of the engineering cycle, without appearing in the SynapseS composition of the LLGA track S2.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Official item (SynapseS)</th>
<th style="text-align: left;">Course section</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Statistics used in practice to answer a precise question</td>
<td style="text-align: left;">ch1 — The life cycle of a statistical study, and ch3 — Observational versus experimental</td>
</tr>
<tr class="even">
<td style="text-align: left;">A series of important model-based approaches</td>
<td style="text-align: left;">ch4 — Causal inference, ch5 — Regression in practice, ch7 — The bootstrap</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Real data from medicine, genomics, ecology…</td>
<td style="text-align: left;">ch9 — Case study: agricultural trials and blocks (partial coverage: application fields and the historical line of experimental designs)</td>
</tr>
<tr class="even">
<td style="text-align: left;">All analyses carried out in R</td>
<td style="text-align: left;">not explicitly covered: these materials remain software-independent</td>
</tr>
</tbody>
</table>
<p><em>Complement to the official syllabus&nbsp;—</em> the themes structuring these materials (experimental designs and power computation, multiple testing, sequential A/B testing, honest communication of uncertainties) extend the official description, which remains general; they correspond to the historical topics of the MAP566 course associated with this course unit.</p>
<h3 id="where-this-course-fits-in-the-program">Where this course fits in the program</h3>
<p>Module of period 2 of M1 (36&nbsp;h, 4.5&nbsp;ECTS), offered as an option: the methodological “reality check” of the master’s program, taught by Zacharie Naulet (École Polytechnique &amp; INRAE, MaIAGE team). Official prerequisites: not communicated (the “Prerequisites” tab of the SynapseS description is empty); the description only specifies that no knowledge of R is required, basic scripting being sufficient.</p>
<ul>
<li><strong>Prerequisites</strong> — the background of <a href="../m1p1-refresher-statistics/index.html">Refresher in Statistics</a> (tests, intervals, estimation) and the framework of <a href="../m1p1-machine-learning/index.html">Machine Learning</a>; the review section reactivates the “survival kit” actually used afterwards.</li>
<li><strong>Downstream modules</strong> — the culture of intervals, bootstrap and uncertainty built here directly feeds <a href="../m2-privacy-uncertainty/index.html">Privacy and Uncertainty Quantification</a> (M2), which deepens the uncertainty quantification of models.</li>
</ul>
<h3 id="course-outline">Course outline</h3>
<ul>
<li><strong>Review: the statistician’s survival kit</strong> — the only results from the statistics course that are really used, every week.</li>
<li><strong>The life cycle of a statistical study</strong> — from question to report: the map of the craft.</li>
<li><strong>Experimental designs: randomization, blocks, power</strong> — deciding <em>before</em> collecting how many and how.</li>
<li><strong>Observational versus experimental: biases</strong> — why we do not always randomize, and what that costs.</li>
<li><strong>Causal inference: potential outcomes and DiD</strong> — approaching a causal effect with imperfect data.</li>
<li><strong>Regression in practice: diagnostics and transformations</strong> — using, checking and repairing a regression model.</li>
<li><strong>Multiple testing: Bonferroni and Benjamini-Hochberg</strong> — what to do when testing many hypotheses at once.</li>
<li><strong>The bootstrap in practice</strong> — intervals without closed formulas, on almost any statistic.</li>
<li><strong>A/B testing: sequential and targeted effects</strong> — the randomized trial as digital platforms practice it.</li>
<li><strong>Case study: agricultural trials and blocks</strong> — the historical origin of experimental designs, on a complete case.</li>
<li><strong>Communicating: intervals, p-values, honest visualizations</strong> — making results readable without distorting them.</li>
<li><strong>Course research notes (Naulet, MaIAGE)</strong> — a tour of the research work of Zacharie Naulet.</li>
<li><strong>Exercises</strong> and <strong>References</strong> — systematic training and sources to go further.</li>
</ul>
<h3 id="how-to-study-this-module">How to study this module</h3>
<ul>
<li>Validate the “survival kit” of the review section: it, and not an advanced chapter, determines your ease throughout the module.</li>
<li>Work through each section on a real dataset: this course’s specificity is that obstacles come from the data, not from formulas.</li>
<li>Simulate: the power of a test, the inflation of false positives under multiple testing and the coverage of the bootstrap are understood in a few lines of code.</li>
<li>Before every analysis, write the plan — hypotheses, sample size, criterion: the reflex this module seeks to instill.</li>
<li>Apply the same rigor to your machine learning models: evaluating a model is a statistical study in its own right.</li>
<li>Redo the exercises of each section before moving on to the next; the final case study brings them all together.</li>
</ul>
<div class="note">
<p><span class="tag">Note Extrapolons</span> In a master’s program oriented toward LLMs and graphs, this module brings the discipline that makes everything else credible: A/B tests and rigorous evaluation are the daily life of the product teams deploying models, and the culture of uncertainty continues in M2 in <a href="../m2-privacy-uncertainty/index.html">Privacy and Uncertainty Quantification</a>. It is also a sought-after profile in research — at the interface with applied sciences, as at INRAE — and in industrial data science wherever decisions have consequences.</p>
</div>
<h2 id="ch0">0. Review: the statistician’s survival kit</h2>
<div class="recap">
<div class="recap-title">
<p>L3 background used (cf.&nbsp;Refresher Statistics module)</p>
</div>
<ul>
<li><strong>Convergence and limit theorems</strong> (ch.&nbsp;4): law of large numbers, CLT <span class="math inline">\sqrt{n}(\bar X_n - \mu) \Rightarrow \mathcal{N}(0, \sigma^2)</span>, delta method and bootstrap — the engine of almost every approximation in this module;</li>
<li><strong>Parametric estimation</strong> (ch.&nbsp;5): bias, variance, quadratic error, maximum likelihood estimators and their asymptotic properties;</li>
<li><strong>Confidence intervals and tests</strong> (ch.&nbsp;6): level, power, p-value, type I and II errors, two-sample Student test, chi-square test;</li>
<li><strong>Linear regression</strong> (ch.&nbsp;7): ordinary least squares, Gauss-Markov, tests on the coefficients, <span class="math inline">R^2</span> — chapter 5 of this module revisits this foundation “on misbehaving data”;</li>
<li><strong>Monte Carlo simulation</strong>: generating laws, checking a method by simulation — the permanent working tool of the applied statistician (and of all the labs in this course).</li>
</ul>
</div>
<div class="def">
<p><span class="tag">Definition 0.1 — Statistical model and data</span> A statistical model for data <span class="math inline">x_1, \dots, x_n</span> is a family <span class="math inline">(P_\theta)_{\theta \in \Theta}</span> of candidate laws. In practice, the question is not “is the model true?” (it never is) but rather: <em>what question are we asking the data, and which quantity <span class="math inline">\psi(\theta)</span></em> — mean effect, difference of rates, quantile, coefficient — <em>answers that question?</em> The whole module is organized around this triptych: <strong>question → collection plan → estimation + uncertainty</strong>. The formula <span class="math inline">\bar x \pm 1.96\, s/\sqrt{n}</span> from Refresher Statistics is legitimate only if the collection plan is: this module deals with what happens before and around the formula.</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 0.2 — The bias-variance identity and what it implies</span> For every square-integrable estimator <span class="math inline">\hat\theta</span> of <span class="math inline">\theta</span>: <span class="math display">\mathbb{E}\big[(\hat\theta - \theta)^2\big] = \underbrace{\big(\mathbb{E}\hat\theta - \theta\big)^2}_{\text{bias}^2} + \underbrace{\mathrm{Var}(\hat\theta)}_{\text{variance}}.</span></p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Set <span class="math inline">\mu = \mathbb{E}\hat\theta</span> and expand <span class="math inline">\mathbb{E}[(\hat\theta-\mu) + (\mu - \theta)]^2 = \mathbb{E}(\hat\theta-\mu)^2 + 2(\mu-\theta)\underbrace{\mathbb{E}(\hat\theta - \mu)}_{=0} + (\mu-\theta)^2</span>. The cross term is zero because <span class="math inline">\mu</span> is the expectation of <span class="math inline">\hat\theta</span>. <span class="qed">∎</span></p>
</div>
<p>In practice, the bias mostly comes from the <strong>plan</strong> (selection, confounding) and the variance from the <strong>sample size</strong>: increasing <span class="math inline">n</span> never corrects a selection bias — this is the central message of chapters 2 and 3.</p>
</div>
<div class="note">
<p><span class="tag">Position in the master’s program</span> This module is the “craft” complement of Refresher Statistics: less new theory, more <em>decisions</em>. It also prepares the M2 module “Privacy and Uncertainty Quantification”, which pushes the uncertainty question as far as the calibration of predictive models; the statistics–ML bridge is provided by the Machine Learning module (ch.&nbsp;1 and 7), and the processing of textual data by the NLP module.</p>
</div>
<h2 id="ch1">1. The life cycle of a statistical study</h2>
<p>Concrete scene: an A/B stopped too early that “proves” a nonexistent lift. This chapter structures the question before the data.</p>
<div class="note">
<p><span class="tag">What breaks</span> Peeking without correction; forgotten multiple testing; confusing correlation and causation without design.</p>
</div>
<p>A real statistical study does not begin with a dataset: it begins with a <strong>question</strong>. The diagram below structures the whole module; each chapter tackles a link where studies typically fail.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Step</th>
<th style="text-align: left;">Key question</th>
<th style="text-align: left;">Where it breaks</th>
<th style="text-align: left;">Chapter</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1. Question</td>
<td style="text-align: left;">Which effect, on which population, which unit?</td>
<td style="text-align: left;">Vague question, undefined indicator</td>
<td style="text-align: left;">ch.&nbsp;1</td>
</tr>
<tr class="even">
<td style="text-align: left;">2. Plan</td>
<td style="text-align: left;">Can we randomize? Block? How many units?</td>
<td style="text-align: left;">Underpowered, no randomization</td>
<td style="text-align: left;">ch.&nbsp;2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3. Collection</td>
<td style="text-align: left;">Who enters the sample? Who leaves it?</td>
<td style="text-align: left;">Selection bias, survival bias, missing data</td>
<td style="text-align: left;">ch.&nbsp;3</td>
</tr>
<tr class="even">
<td style="text-align: left;">4. Analysis</td>
<td style="text-align: left;">Which estimator? Which diagnostics?</td>
<td style="text-align: left;">Mis-specified model, multiple tests</td>
<td style="text-align: left;">ch.&nbsp;5–6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5. Uncertainty</td>
<td style="text-align: left;">Intervals, bootstrap, robustness</td>
<td style="text-align: left;">Underestimated uncertainty</td>
<td style="text-align: left;">ch.&nbsp;7</td>
</tr>
<tr class="even">
<td style="text-align: left;">6. Communication</td>
<td style="text-align: left;">What to report, in what form?</td>
<td style="text-align: left;">Over-interpreted p-value, misleading chart</td>
<td style="text-align: left;">ch.&nbsp;10</td>
</tr>
</tbody>
</table>
<div class="def">
<p><span class="tag">Definition 1.1 — Population, sample, statistical unit, indicator</span> The <strong>population</strong> is the set of units the question concerns; the <strong>sample</strong> is the observed subset; the <strong>statistical unit</strong> is the grain at which we measure (a patient, a field, a user, a query); the <strong>indicator</strong> (or <em>outcome</em>, <em>OEC</em> for “Overall Evaluation Criterion” in online experimentation) is the quantity measured. A study is <em>externally valid</em> if the sample allows an answer for the target population; <em>internally valid</em> if the comparisons made within the sample are reliable. One can be internally valid and externally wrong (a trial on healthy volunteers).</p>
</div>
<div class="note">
<p><span class="tag">Reproducibility: HARKing and the garden of forking paths</span> Two documented pathologies: <strong>HARKing</strong> (Kerr, 1998 — hypotheses formulated <em>after</em> seeing the results, presented as <em>a priori</em>) and the “garden of forking paths” (Gelman &amp; Loken, 2013): without any fraud, the mere freedom to choose the specification <em>after the fact</em> (control variables, coding, exclusion of points, subgroups) multiplies the tests actually performed far beyond those reported. Practical answers: pre-registration of the analysis plan, reproducible scripts, reports of every look taken at the data — exactly the disciplines of ch.&nbsp;8 for A/B testing.</p>
</div>
<h2 id="ch2">2. Experimental designs: randomization, blocks, power</h2>
<div class="def">
<p><span class="tag">Definition 2.1 — Randomized experiment (Fisher, 1935)</span> <span class="math inline">n</span> experimental units receive <span class="math inline">K</span> treatments; the assignment is drawn <strong>at random</strong> among the possible allocations (with possible balance constraints). Randomization plays three roles: (i) on average, it balances <em>all</em> factors, measured or not; (ii) it grounds an <em>exact</em> test of the null effect (prop. 2.2); (iii) it legitimizes the causal inference of ch.&nbsp;4. Historical note: the “lady tasting tea” experiment (Fisher, 1935) — 8 cups, 4 “milk first”, 4 “tea first”, randomized order.</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 2.2 — Exact randomization test, computed by hand</span> Six plots with yields 3, 4, 5, 6, 7, 8 (q/ha; teaching data) receive A or B, three each. Observed: A = {6, 7, 8}, B = {3, 4, 5}, difference of means <span class="math inline">\hat d = 7 - 4 = 3</span>. Under the null hypothesis “no effect”, <span class="math inline">\hat d</span> takes each of the <span class="math inline">\binom{6}{3} = 20</span> values <span class="math inline">\bar x_A - \bar x_B</span> with probability <span class="math inline">1/20</span>. The largest possible value of <span class="math inline">\|\hat d\|</span> is 3, reached only for the splits {6,7,8} and {3,4,5} (the split {5,7,8} against {3,4,6} gives <span class="math inline">\hat d = 6.67 - 4.33 = 2.33 \&lt; 3</span>). Therefore <span class="math display">p \;=\; \mathbb{P}\big(\|\hat d\| \geq 3 \,\big\|\, H_0\big) \;=\; \frac{2}{20} \;=\; 0.10 \quad\text{(exact, without any distributional assumption).}</span></p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>The only thing used: under <span class="math inline">H_0</span>, the treatment does not influence the yield, so the observed value of <span class="math inline">\hat d</span> is piecewise constant and only the assignment is random; the assignment being uniform over the 20 balanced allocations, the p-value is the proportion of allocations at least as extreme. Enumerating the 20 splits (or a symmetry argument on A/B) gives exactly 2 splits with <span class="math inline">\|\bar x_A - \bar x_B\| = 3</span> and all others <span class="math inline">\leq 2.33</span>. <span class="qed">∎</span></p>
</div>
</div>
<div class="def">
<p><span class="tag">Definition 2.3 — Randomized complete block design (RCBD)</span> When the units are heterogeneous but can be grouped into homogeneous <strong>blocks</strong> (neighboring plots, production days, hospitals), one draws <em>independently within each block</em> a permutation of the <span class="math inline">K</span> treatments. Analysis model: <span class="math display">y_{ij} = \mu + \tau_i + \beta_j + \varepsilon_{ij}, \qquad \varepsilon_{ij} \ \text{i.i.d.},</span> with <span class="math inline">\tau_i</span> the effect of treatment <span class="math inline">i</span>, <span class="math inline">\beta_j</span> the effect of block <span class="math inline">j</span>. Blocks turn the variability <em>between</em> units into an explicit factor: ch.&nbsp;9 shows, on numerical data, a variance gain by a factor of 30 and more.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 2.4 — Sample size for a target power (two-sample Gaussian test)</span> To test <span class="math inline">H_0 : \mu_A = \mu_B</span> against <span class="math inline">\mu_B - \mu_A = \delta</span> at level <span class="math inline">\alpha</span> (two-sided) with common variance <span class="math inline">\sigma^2</span>, <span class="math inline">n</span> measurements per group and the normal approximation, the power is <span class="math display">\pi(\delta) \;=\; \Phi\!\Big( \frac{\delta}{\sigma}\sqrt{\tfrac{n}{2}} - z_{1-\alpha/2} \Big),</span> and power <span class="math inline">1 - \beta</span> is reached for <span class="math display">n \;=\; \frac{2\,(z_{1-\alpha/2} + z_{1-\beta})^2}{(\delta/\sigma)^2} \quad \text{measurements per group.}</span></p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>The test rejects when <span class="math inline">\|\hat d\| \&gt; z_{1-\alpha/2}\,\sigma\sqrt{2/n}</span> with <span class="math inline">\hat d = \bar y_B - \bar y_A \sim \mathcal{N}(\delta, 2\sigma^2/n)</span>. Under the alternative, <span class="math inline">\mathbb{P}(\hat d \&lt; -s) \approx 0</span> (with <span class="math inline">s = z_{1-\alpha/2}\sigma\sqrt{2/n}</span> and <span class="math inline">\delta \&gt; 0</span>), so <span class="math inline">\pi = \mathbb{P}(\hat d \&gt; s) = \Phi\big(\tfrac{\delta - s}{\sigma\sqrt{2/n}}\big) = \Phi\big(\tfrac{\delta}{\sigma}\sqrt{\tfrac n2} - z_{1-\alpha/2}\big)</span>. Writing <span class="math inline">\pi = 1 - \beta</span> amounts to <span class="math inline">\tfrac{\delta}{\sigma}\sqrt{\tfrac n2} - z_{1-\alpha/2} = z_{1-\beta}</span>, hence the formula by isolating <span class="math inline">n</span>. <span class="qed">∎</span></p>
</div>
</div>
<div class="ex">
<p><span class="tag">Example 2.5 — Power computed, and a sizing table</span> We want to detect <span class="math inline">\delta = 0.3\,\sigma</span> (a <em>small</em> but economically relevant effect) with <span class="math inline">\alpha = 5\,\%</span> and 80&nbsp;% power: <span class="math inline">z_{0.975} = 1.960</span>, <span class="math inline">z_{0.8} = 0.842</span>, <span class="math display">n = \frac{2\,(1.960 + 0.842)^2}{0.3^2} = \frac{2 \times 7.85}{0.09} = 174.4 \;\Rightarrow\; \boxed{175 \text{ units per group}}.</span> Complete table (values rounded up):</p>
<table class="caption-top">
<thead>
<tr class="header">
<th><span class="math inline">\delta/\sigma</span> Po</th>
<th>wer 80&nbsp;% Po</th>
<th>wer 90&nbsp;% Re</th>
<th style="text-align: left;">ading</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.2</td>
<td>393</td>
<td>526</td>
<td style="text-align: left;">very small effect: costly</td>
</tr>
<tr class="even">
<td>0.3</td>
<td>175</td>
<td>234</td>
<td style="text-align: left;">our case</td>
</tr>
<tr class="odd">
<td>0.5</td>
<td>63</td>
<td>85</td>
<td style="text-align: left;">medium effect</td>
</tr>
<tr class="even">
<td>0.8</td>
<td>25</td>
<td>33</td>
<td style="text-align: left;">large effect: a pilot suffices</td>
</tr>
</tbody>
</table>
<p>Professional moral: <strong>half the power is paid in the square root of n, doubling the precision costs ×4 the sample</strong>, and nobody “finds” an effect of 0.2σ with 30 observations. In practice one replaces <span class="math inline">\sigma^2</span> with an estimate from a pilot or the literature, and <span class="math inline">\delta</span> with the smallest <em>useful</em> effect (the minimum clinically or economically relevant difference), never with the effect one hopes for.</p>
</div>
<div class="note">
<p><span class="tag">Power a priori, never a posteriori</span> Power is a <em>design</em> tool. The “observed power” computed after the fact with <span class="math inline">\hat\delta</span> is a monotone transformation of the p-value: it brings no new information and muddles the report (Hoenig &amp; Heisey, 2001). What should be reported: the confidence interval of the effect (ch.&nbsp;10).</p>
</div>
<h2 id="ch3">3. Observational versus experimental: biases</h2>
<div class="def">
<p><span class="tag">Definition 3.1 — Observational study, confounding factor</span> A study is <strong>observational</strong> when the assignment of “treatments” (exposure, product, degree) is not controlled by the experimenter. A <strong>confounding factor</strong> <span class="math inline">Z</span> is a variable that influences both the exposure and the response; it creates a “natural” difference of means between groups even without any effect. Canonical example: ice cream sales and drownings (confounded by weather). Adjustment (standardization, regression, matching) only corrects <em>measured</em> confounders; randomization also neutralizes the unmeasured ones — that is the whole difference between ch.&nbsp;2 and the present chapter.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 3.2 — Simpson’s paradox, real data: kidney stones (Charig et al., 1986)</span> Historical comparison of two kidney stone treatments (B: minimally invasive surgery; A: open surgery), % success:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Stratum</th>
<th style="text-align: left;">Treatment A</th>
<th style="text-align: left;">Treatment B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Small stones</td>
<td style="text-align: left;"><strong>81/87 = 93&nbsp;%</strong></td>
<td style="text-align: left;">234/270 = 87&nbsp;%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Large stones</td>
<td style="text-align: left;"><strong>192/263 = 73&nbsp;%</strong></td>
<td style="text-align: left;">55/80 = 69&nbsp;%</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Overall</strong></td>
<td style="text-align: left;">273/350 = 78&nbsp;%</td>
<td style="text-align: left;"><strong>289/350 = 83&nbsp;%</strong></td>
</tr>
</tbody>
</table>
<p>A is better in <em>every</em> stratum and worse <em>in aggregate</em>: B was preferentially given to small stones (easy cases). This is a pure confounding effect by severity, mechanically reversible by standardization.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Let <span class="math inline">p_{ks}</span> be the success rate of treatment <span class="math inline">k</span> in stratum <span class="math inline">s</span> and <span class="math inline">w_s^{(k)}</span> the proportion of patients of stratum <span class="math inline">s</span> in group <span class="math inline">k</span>. The overall rate of group <span class="math inline">k</span> is <span class="math inline">\sum_s w_s^{(k)}\, p_{ks}</span>: it mixes effectiveness (<span class="math inline">p</span>) and case mix (<span class="math inline">w</span>). B can win in aggregate with <span class="math inline">p_{Bs} \leq p_{As}</span> for every <span class="math inline">s</span> as soon as <span class="math inline">w^{(B)}</span> loads the easy strata: here <span class="math inline">w^{(B)}_{\text{small}} = 270/350 = 0.77</span> versus <span class="math inline">87/350 = 0.25</span> for A. Standardizing on a common profile <span class="math inline">w</span> (e.g.&nbsp;<span class="math inline">w^{(A)}</span>) restores A’s advantage in each stratum, hence on average. <span class="qed">∎</span></p>
</div>
</div>
<div class="def">
<p><span class="tag">Definition 3.3 — Selection bias and survivorship bias</span> <strong>Selection bias</strong>: the sample is not representative of the target population (volunteers, trade shows, survey respondents). <strong>Survivorship bias</strong>: the special case where the filter is <em>survival / still being in activity</em>; the departed carry their bad results away with them.</p>
</div>
<div class="ex">
<p><span class="tag">Example 3.4 — Two worked examples</span> <strong>(a) Wald’s airplanes (1943).</strong> Returning from missions, bullet holes concentrate on the wings and fuselage, almost none on the engines. Reinforcing the hit zones would be the survivor’s error: planes hit in the engine <em>do not come back</em>. The armor goes where the survivors are <em>untouched</em>. (The episode, popularized by W. Allen, is reconstructed and discussed by Mangel &amp; Samuels, 2002.)<br>
<br>
<strong>(b) Mutual funds (teaching figures calibrated on Elton, Gruber &amp; Blake, 1996).</strong> Of 200 funds existing in 2015, 100 closed before 2025. Advertising cites the average return of the 100 survivors: 8&nbsp;%/year. The 100 vanished ones made −5&nbsp;%/year before closing. The return actually experienced by a 2015 investor: <span class="math display">\frac{100 \times 8 + 100 \times (-5)}{200} = 1.5\,\%/\text{year} \quad \text{versus} \quad 8\,\% \text{ displayed.}</span> Over 10 years, a compounded gap of 1&nbsp;%/year ≈ 10&nbsp;% of missing final wealth — enough to rank every product on the market differently.</p>
</div>
<div class="note">
<p><span class="tag">Where do you meet these biases in ML?</span> Everywhere: models trained on <em>current</em> customers (churners do not notify their departure); evaluations of a recruitment system on hires (non-hires have no observed performance — this is the crux of ch.&nbsp;4); academic benchmarks filtered by the publications that use them (failures are not submitted). Reflex: always ask <em>how the sample was constituted and who dropped out of it</em>.</p>
</div>
<h2 id="ch4">4. Causal inference: potential outcomes and DiD</h2>
<div class="def">
<p><span class="tag">Definition 4.1 — Potential outcomes, ATE (Neyman 1923; Rubin 1974)</span> For each unit <span class="math inline">i</span> and treatment <span class="math inline">w \in \{0, 1\}</span>, we posit two <em>potential</em> outcomes <span class="math inline">Y_i(0)</span> and <span class="math inline">Y_i(1)</span>; the individual effect is <span class="math inline">\tau_i = Y_i(1) - Y_i(0)</span> and the <strong>average effect</strong> <span class="math inline">\mathrm{ATE} = \mathbb{E}[\tau_i]</span>. We only ever observe one value <span class="math inline">Y_i = W_i Y_i(1) + (1 - W_i) Y_i(0)</span>: the fundamental causal problem is a <strong>missing data</strong> problem (cf.&nbsp;Refresher Statistics, ch.&nbsp;9). Two <em>a priori</em> assumptions: <em>consistency</em> (the observed value equals the potential outcome of the received treatment) and <em>no interference</em> (the treatment of unit <span class="math inline">j</span> does not affect <span class="math inline">i</span>) — together <span style="white-space:nowrap">SUTVA</span>.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 4.2 — Randomization debiases the difference of means</span> If <span class="math inline">W \perp (Y(0), Y(1))</span> (unbiased randomization), then <span class="math inline">\hat\tau = \bar Y_1 - \bar Y_0</span> is unbiased for the ATE, and <span class="math inline">\mathrm{Var}(\hat\tau) \approx \frac{s_1^2}{n_1} + \frac{s_0^2}{n_0}</span>.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span><span class="math inline">\mathbb{E}[\bar Y_1 \mid W] = \mathbb{E}[Y(1) \mid W = 1] = \mathbb{E}[Y(1)]</span> by independence, and likewise for <span class="math inline">\bar Y_0</span>, hence <span class="math inline">\mathbb{E}\hat\tau = \mathbb{E}[Y(1)] - \mathbb{E}[Y(0)] = \mathrm{ATE}</span>. The two means are over disjoint, hence independent, groups, which gives the sum of the empirical variances. <span class="qed">∎</span></p>
</div>
<p>In an observational setting, <span class="math inline">W</span> is <em>self-selected</em>: <span class="math inline">\mathbb{E}[Y(1)\mid W{=}1] - \mathbb{E}[Y(0)\mid W{=}0]</span> mixes the causal effect with selection. The whole modern machinery (adjustment, matching, instrumental variables, DiD) aims at reconstructing a randomized comparison.</p>
</div>
<div class="def">
<p><span class="tag">Definition 4.3 — Difference-in-differences, the sketch</span> Two groups (treated, control), two dates (before, after), without randomization: <span class="math display">\widehat{\mathrm{DiD}} \;=\; \big(\bar Y_{\text{after, treated}} - \bar Y_{\text{before, treated}}\big) - \big(\bar Y_{\text{after, control}} - \bar Y_{\text{before, control}}\big).</span> Central assumption: <strong>parallel trends</strong> — without treatment, the treated/control gap would have stayed constant; the control serves as a “trajectory counterfactual”. This is the most used causal identification in applied economics since Card &amp; Krueger (1994).</p>
</div>
<div class="ex">
<p><span class="tag">Example 4.4 — Minimum wage New Jersey / Pennsylvania (Card &amp; Krueger, 1994)</span> Rise of the NJ minimum wage (April 1992); neighboring Pennsylvania serves as the control. Average full-time employment (FTE) per restaurant:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">Before</th>
<th style="text-align: left;">After</th>
<th style="text-align: left;">Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>New Jersey (treated)</td>
<td style="text-align: left;">20.44</td>
<td style="text-align: left;">21.03</td>
<td style="text-align: left;">+0.59</td>
</tr>
<tr class="even">
<td>Pennsylvania (control)</td>
<td style="text-align: left;">23.33</td>
<td style="text-align: left;">21.17</td>
<td style="text-align: left;">−2.16</td>
</tr>
</tbody>
</table>
<p><span class="math display">\widehat{\mathrm{DiD}} = 0.59 - (-2.16) = +2.75 \ \text{FTE} \quad (\approx +11\,\% \text{ vs before}).</span> The regional economy was depressing both states; the naive “NJ before/after” comparison (+0.59) would underestimate the effect, and the “NJ/PA after” comparison (−1.14&nbsp;FTE) would outright flip its sign: only the double difference neutralizes the common shock. Crucial methodological point (Bertrand, Duflo &amp; Mullainathan, 2004): naive DiD standard errors are massively too small because of serial correlation — one must cluster by unit or aggregate.</p>
</div>
<div class="note">
<p><span class="tag">Further</span> Causal graphs and the back-door criterion (Pearl), instrumental variables, regression discontinuity: beyond the sketch of this module — see Imbens &amp; Rubin (2015). The link with ML (estimating effect heterogeneity with causal forests) is covered in the Machine Learning module, and the Graph ML module for the dependence structure.</p>
</div>
<h2 id="ch5">5. Regression in practice: diagnostics and transformations</h2>
<div class="recap">
<div class="recap-title">
<p>Reminders (cf.&nbsp;Refresher Statistics module, ch.&nbsp;7)</p>
</div>
<ul>
<li>OLS estimator <span class="math inline">\hat\beta = (X^\top X)^{-1} X^\top y</span>, residuals <span class="math inline">e = y - \hat y</span>, hat matrix <span class="math inline">H = X(X^\top X)^{-1}X^\top</span>, <span class="math inline">\hat y = Hy</span>;</li>
<li>Gauss-Markov: BLUE under i.i.d. zero-mean errors; Student tests if moreover Gaussian;</li>
<li>The Machine Learning module (ch.&nbsp;2) covers ridge/lasso regularization — here we stay in inferential mode: the coefficients <em>are</em> the object of interest.</li>
</ul>
</div>
<div class="prop">
<p><span class="tag">Proposition 5.1 — Leverage and Cook’s distance</span> The leverage of observation <span class="math inline">i</span> is <span class="math inline">h_{ii}</span>, the diagonal of <span class="math inline">H</span>; <span class="math inline">\sum_i h_{ii} = p</span> (number of parameters), <span class="math inline">0 \leq h_{ii} \leq 1</span>. Cook’s distance <span class="math display">D_i = \frac{e_i^2}{p\,s^2}\cdot \frac{h_{ii}}{(1 - h_{ii})^2}</span> measures the influence of <span class="math inline">i</span> on the whole set of coefficients. Leverage point: <span class="math inline">h_{ii} \&gt; 2p/n</span>; influential point: <span class="math inline">D_i \&gt; 4/n</span>.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>For the trace: <span class="math inline">H</span> is an orthogonal projector (onto im <span class="math inline">X</span>), and the trace of a projector equals its rank <span class="math inline">= \mathrm{rank}(X) = p</span>. Removing row <span class="math inline">i</span> and re-estimating gives <span class="math inline">\hat\beta - \hat\beta_{(-i)} = \frac{(X^\top X)^{-1}x_i e_i}{1 - h_{ii}}</span>; Cook’s distance standardizes this variation by the dispersion <span class="math inline">p s^2</span> of the estimators — hence the formula: the residual alone (an outlier can be well predicted!) or the leverage alone (an extreme point can be perfectly aligned) do not suffice; it is their <em>product</em> that tips the line. <span class="qed">∎</span></p>
</div>
</div>
<div class="def">
<p><span class="tag">Definition 5.2 — The four diagnostic plots</span> <strong>(1) Residuals vs fitted values</strong>: curvature ⇒ non-linearity (add quadratic terms, splines); funnel ⇒ heteroscedasticity. <strong>(2) Q-Q of residuals</strong>: heavy tails ⇒ fragile intervals/Student tests at small <span class="math inline">n</span>. <strong>(3) Scale-location</strong> (<span class="math inline">\sqrt{\|e\|}</span> vs <span class="math inline">\hat y</span>): checks the constancy of <span class="math inline">s^2</span>. <strong>(4) Residuals vs leverage (Cook)</strong>: hunts influential points. Professional reflex: these four plots <em>before</em> any interpretation, systematically.</p>
</div>
<div class="ex">
<p><span class="tag">Example 5.3 — Transformations: the log as a universal tool</span> Prices of 30 goods (<span class="math inline">y</span>, euros) against surface area (<span class="math inline">x</span>, m²). Typical symptoms: funnel-shaped residuals, the line pulled by a few very high-leverage luxury goods. <strong>Remedy</strong>: regress <span class="math inline">\log y</span> on <span class="math inline">\log x</span>: <span class="math display">\log y_i = \beta_0 + \beta_1 \log x_i + \varepsilon_i \iff y_i = e^{\beta_0}\, x_i^{\beta_1}\, e^{\varepsilon_i}.</span> <span class="math inline">\beta_1</span> becomes an <strong>elasticity</strong>: <span class="math inline">+1\,\%</span> of surface ⇒ <span class="math inline">+\beta_1\,\%</span> of price. If <span class="math inline">\hat\beta_1 = 1.08</span>, the interpretation “each extra square meter adds 8&nbsp;%” replaces the fragile linear interpretation “each square meter adds €3,120” — wrong for a studio as for a mansion. The log transformation: (i) symmetrizes distributions and stabilizes variance when the effect is multiplicative; (ii) crushes extreme leverages; (iii) makes errors <em>relative</em>, which is often the right physical/economic model. General family: Box-Cox <span class="math inline">y^{(\lambda)} = (y^\lambda - 1)/\lambda</span>, with <span class="math inline">\lambda</span> chosen by profile likelihood; special cases <span class="math inline">\lambda = 1</span> (identity), <span class="math inline">\lambda = 0</span> (log), <span class="math inline">\lambda = 1/2</span> (square root, Poisson).</p>
</div>
<div class="note">
<p><span class="tag">Heteroscedasticity: robust errors, no panic</span> Heteroscedasticity does <em>not</em> bias <span class="math inline">\hat\beta</span> (Gauss-Markov only needs homoscedasticity for efficiency, not consistency); it distorts the standard errors. Modern solution: sandwich estimators (White, HC1) — <span class="math inline">\widehat{\mathrm{Var}}(\hat\beta) = (X^\top X)^{-1} X^\top \mathrm{diag}(e_i^2) X (X^\top X)^{-1}</span> — available everywhere (<code>statsmodels</code>, <code>sandwich</code> in R). With grouped or panel data, cluster by unit (cf.&nbsp;ch.&nbsp;4, Bertrand et al.&nbsp;2004).</p>
</div>
<h2 id="ch6">6. Multiple testing: Bonferroni and Benjamini-Hochberg</h2>
<p>The modern statistician tests thousands of hypotheses at once (genomics, multi-metric A/B testing, subgroup analyses). Testing <span class="math inline">m</span> true null hypotheses each at <span class="math inline">\alpha = 5\,\%</span> produces on average <span class="math inline">\alpha m</span> false positives — with <span class="math inline">m = 1000</span>: 50 “discoveries” in pure noise. One must choose what to control.</p>
<div class="def">
<p><span class="tag">Definition 6.1 — FWER and FDR</span> Among <span class="math inline">R</span> rejected hypotheses of which <span class="math inline">V</span> are false (false positives): <span class="math display">\mathrm{FWER} = \mathbb{P}(V \geq 1) \qquad \text{(at least one error)}</span> <span class="math display">\mathrm{FDR} = \mathbb{E}\!\left[ \frac{V}{R \vee 1} \right] \qquad \text{(expected proportion of errors).}</span> Controlling the FWER is required when a single false discovery is costly (pivotal clinical trial); controlling the FDR is enough for exploration (differential expression, product optimization) — we accept some noise among the discoveries.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 6.2 — Bonferroni controls the FWER</span> Rejecting the <span class="math inline">p_i \leq \alpha/m</span> gives <span class="math inline">\mathrm{FWER} \leq \alpha</span>.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Union bound (Boole): if an error is made, at least one p-value under a true null has crossed its threshold, so <span class="math display">\mathrm{FWER} \leq \mathbb{P}\Big( \bigcup_{i \in I_0} \{p_i \leq \alpha/m\} \Big) \leq \sum_{i \in I_0} \frac{\alpha}{m} \leq \frac{m_0\,\alpha}{m} \leq \alpha,</span> where <span class="math inline">m_0 \leq m</span> is the number of true nulls. No independence is required. <span class="qed">∎</span></p>
</div>
<p>Price to pay: as <span class="math inline">m</span> grows, the threshold <span class="math inline">\alpha/m</span> becomes untenable (<span class="math inline">m = 10^4</span> ⇒ <span class="math inline">5 \times 10^{-6}</span>) and power collapses; the Šidák variant (<span class="math inline">1 - (1-\alpha)^{1/m}</span>, exact under independence) does not change the order of magnitude.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 6.3 — Benjamini-Hochberg controls the FDR (Benjamini &amp; Hochberg, 1995)</span> Let <span class="math inline">p_{(1)} \leq \dots \leq p_{(m)}</span> be the sorted p-values and <span class="math display">k^\* = \max\Big\{ k : p_{(k)} \leq \frac{k}{m}\,q \Big\}.</span> Rejecting the <span class="math inline">k^\*</span> smallest p-values (none if the set is empty) controls <span class="math inline">\mathrm{FDR} \leq \frac{m_0}{m} q \leq q</span> when the p-values under true nulls are independent of each other and of the rest (extension: PRDS positive dependence, Benjamini &amp; Yekutieli 2001; otherwise, replace <span class="math inline">q</span> by <span class="math inline">q / \sum_{k=1}^m 1/k</span>).</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span><strong>Case where all nulls are true (<span class="math inline">m_0 = m</span>).</strong> Then <span class="math inline">V = R</span> whenever <span class="math inline">R \geq 1</span>, so <span class="math inline">V/(R \vee 1) = \mathbf{1}\{R \geq 1\}</span> and <span class="math inline">\mathrm{FDR} = \mathbb{P}(R \geq 1)</span>. Now <span class="math inline">R \geq 1</span> requires <span class="math inline">p_{(1)} \leq q/m</span>, and <span class="math inline">p_{(1)} = \min_i p_i</span> with i.i.d. uniform <span class="math inline">p_i</span>: <span class="math display">\mathrm{FDR} = \mathbb{P}\Big(\min_i p_i \leq \frac{q}{m}\Big) = 1 - \Big(1 - \frac{q}{m}\Big)^m \;\leq\; q.</span> <strong>General case (sketch).</strong> Decompose <span class="math inline">\mathrm{FDR} = \sum_{i \in I_0} \mathbb{E}\big[ \tfrac{1}{R} \mathbf{1}\{p_i \leq p_{(k^\*)}\}\big]</span> over the rejection rank. The two ingredients of the complete proof (Benjamini &amp; Hochberg, Thm 1): (i) for each null <span class="math inline">i</span>, the event “<span class="math inline">i</span> rejected at rank <span class="math inline">r</span>” requires <span class="math inline">p_i \leq qr/m</span> <em>and</em> at least <span class="math inline">r - 1</span> of the other p-values <span class="math inline">\leq qr/m</span>; (ii) by independence of <span class="math inline">p_i</span> from the rest, the product of probabilities yields a factor <span class="math inline">qr/m</span>, which, killed by the <span class="math inline">1/r</span> of the weighting, leaves the bound <span class="math inline">\frac{q}{m}</span> — then the telescoping summation over ranks (Abel’s transformation) bounds the total by <span class="math inline">\frac{m_0}{m} q</span>. The subtlety (and beauty) of the result: the <em>data-dependent</em> threshold <span class="math inline">q k^\*/m</span> “self-adjusts” to the number of apparent discoveries. <span class="qed">∎</span></p>
</div>
</div>
<div class="ex">
<p><span class="tag">Example 6.4 — BH computed, against Bonferroni</span> <span class="math inline">m = 10</span> p-values: 0.001 · 0.004 · 0.009 · 0.019 · 0.021 · 0.031 · 0.043 · 0.71 · 0.88 · 0.92. With <span class="math inline">q = 0.05</span>:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"><span class="math inline">k</span></th>
<th><span class="math inline">p_{(k)}</span> t</th>
<th>hreshold <span class="math inline">qk/m</span> B</th>
<th style="text-align: left;">H decision</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td>0.001</td>
<td>0.005</td>
<td style="text-align: left;">reject</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td>0.004</td>
<td>0.010</td>
<td style="text-align: left;">reject</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td>0.009</td>
<td>0.015</td>
<td style="text-align: left;">reject</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td>0.019</td>
<td>0.020</td>
<td style="text-align: left;">reject</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td><strong>0.021</strong></td>
<td><strong>0.025</strong></td>
<td style="text-align: left;"><strong>reject (k* = 5)</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td>0.031</td>
<td>0.030</td>
<td style="text-align: left;">stop</td>
</tr>
</tbody>
</table>
<p>BH rejects <span class="math inline">k^\* = 5</span> hypotheses (all p ≤ 0.021); Bonferroni at <span class="math inline">\alpha = 0.05</span> rejects only <span class="math inline">p \leq 0.005</span>: 2 hypotheses. If the first 5 nulls are false, Bonferroni leaves 3 discoveries on the table; BH in exchange claims <span class="math inline">\leq 5\,\%</span> false positives <em>in proportion</em>. In the lab, we will verify by simulation (exercise 5) that the empirical FDR of BH settles at <span class="math inline">q\, m_0/m</span>.</p>
</div>
<div class="note">
<p><span class="tag">Adaptive and genomic version</span> If many nulls are false, <span class="math inline">m_0/m</span> makes BH conservative. Adaptive procedures estimate <span class="math inline">\pi_0 = m_0/m</span> (Storey, 2002 — the large p-values are almost all true nulls) and gain power. This is the default setting of differential analyses in genomics (<code>qvalue</code>, <code>IHW</code>). Internal link: estimating <span class="math inline">\pi_0</span> and the “missing mass” is exactly a species sampling problem — a research axis of the instructor (ch.&nbsp;11).</p>
</div>
<h2 id="ch7">7. The bootstrap in practice</h2>
<div class="recap">
<div class="recap-title">
<p>Reminder (cf.&nbsp;Refresher Statistics module, ch.&nbsp;4)</p>
</div>
<p>The nonparametric bootstrap resamples <span class="math inline">B</span> times, <em>with replacement</em>, <span class="math inline">n</span> observations, recomputes the statistic on each resample, and reads the variability off the bootstrap distribution. Here we push through to intervals, edge cases and code.</p>
</div>
<div class="def">
<p><span class="tag">Definition 7.1 — The plug-in principle (Efron, 1979)</span> The empirical law <span class="math inline">\hat P_n = \frac{1}{n}\sum_i \delta_{x_i}</span> is the natural nonparametric estimator of the unknown law <span class="math inline">P</span>. The bootstrap <em>simulates</em> the inference problem by replacing <span class="math inline">P</span> with <span class="math inline">\hat P_n</span>: if <span class="math inline">T_n = t(x_1, \dots, x_n\,; P)</span> is the statistic of interest, its bootstrap version <span class="math inline">T_n^\* = t(x_1^\*, \dots, x_n^\* ; \hat P_n)</span> is computed by Monte Carlo. Ideal: the law of <span class="math inline">T_n^\* - t(\hat P_n)</span> approximates that of <span class="math inline">T_n - t(P)</span>.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 7.2 — Consistency for the mean (and beyond, sketch)</span> If <span class="math inline">x_i</span> are i.i.d., <span class="math inline">\mathbb{E}X^2 \&lt; \infty</span>, the law of <span class="math inline">\sqrt n(\bar x^\* - \bar x)</span> conditional on the data converges to the same limit <span class="math inline">\mathcal{N}(0, \sigma^2)</span> as <span class="math inline">\sqrt n(\bar x_n - \mu)</span>.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Conditional on the data, the <span class="math inline">x_i^\*</span> are i.i.d. with law <span class="math inline">\hat P_n</span>, expectation <span class="math inline">\bar x</span> and variance <span class="math inline">\hat\sigma_n^2 = \frac{1}{n}\sum (x_i - \bar x)^2</span>. The CLT applied to this sequence (for almost every draw of the data) gives <span class="math inline">\sqrt n(\bar x^\* - \bar x) \Rightarrow \mathcal{N}(0, \hat\sigma_n^2)</span>, and <span class="math inline">\hat\sigma_n^2 \to \sigma^2</span> almost surely (LLN) — the conditional Slutsky lemma concludes. The same scheme holds for <em>regular</em> functionals of <span class="math inline">P</span> (differentiable functionals — functional delta method); this is the subject of the empirical Donsker theorem and van der Vaart’s theory (ch.&nbsp;23). <span class="qed">∎</span></p>
</div>
</div>
<div class="ex">
<p><span class="tag">Example 7.3 — Three intervals for the median</span> Eight response times (ms): 118, 132, 127, 141, 122, 135, 128, 240 (one heavy point). Observed median: <span class="math inline">(128+132)/2 = 130</span>. A “hand-made” normal CI: delicate (no simple <span class="math inline">\sqrt n</span> formula for the median). Bootstrap with <span class="math inline">B = 2000</span>: draw 2000 resamples, each yields a median <span class="math inline">m_b^\*</span>; take the 2.5&nbsp;% and 97.5&nbsp;% percentiles; typical output: CI ≈ [124; 137]. The <em>basic</em> interval (reverse percentile) reverses: <span class="math inline">[2\hat m - q_{97.5}^\*,\ 2\hat m - q_{2.5}^\*]</span>, which corrects a version bias; BCa additionally readjusts for bias and skewness via jackknife. Reading rule: if percentile and basic differ strongly, the bootstrap distribution is very asymmetric — a signal in itself.</p>
</div>
<div class="sourceCode" id="cb1"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">0</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.array([<span class="dv">118</span>, <span class="dv">132</span>, <span class="dv">127</span>, <span class="dv">141</span>, <span class="dv">122</span>, <span class="dv">135</span>, <span class="dv">128</span>, <span class="dv">240</span>])</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>n, B <span class="op">=</span> <span class="bu">len</span>(x), <span class="dv">5000</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>med_star <span class="op">=</span> np.median(rng.choice(x, size<span class="op">=</span>(B, n), replace<span class="op">=</span><span class="va">True</span>), axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>mhat <span class="op">=</span> np.median(x)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. percentile: quantiles of the bootstrap law</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>lo, hi <span class="op">=</span> np.quantile(med_star, [<span class="fl">0.025</span>, <span class="fl">0.975</span>])</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. basic (reverse percentile): symmetrization around the estimate</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>lo_b, hi_b <span class="op">=</span> <span class="dv">2</span><span class="op">*</span>mhat <span class="op">-</span> hi, <span class="dv">2</span><span class="op">*</span>mhat <span class="op">-</span> lo</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"mediane = </span><span class="sc">{</span>mhat<span class="sc">}</span><span class="ss">, IC percentile [</span><span class="sc">{</span>lo<span class="sc">:.0f}</span><span class="ss">, </span><span class="sc">{</span>hi<span class="sc">:.0f}</span><span class="ss">], IC basic [</span><span class="sc">{</span>lo_b<span class="sc">:.0f}</span><span class="ss">, </span><span class="sc">{</span>hi_b<span class="sc">:.0f}</span><span class="ss">]"</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. bootstrap bias: E*[m*] - mhat</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"biais bootstrap estime : </span><span class="sc">{</span>med_star<span class="sc">.</span>mean() <span class="op">-</span> mhat<span class="sc">:+.2f}</span><span class="ss"> ms"</span>)</span></code></pre></div>
<div class="note">
<p><span class="tag">When the bootstrap fails</span> <strong>Dependent data</strong>: the i.i.d. bootstrap breaks the structure — use the block bootstrap (weather, financial series, web streams); <strong>extremes and deep quantiles</strong>: the empirical law does not have a rich enough tail; <strong>small <span class="math inline">n</span></strong> (&lt; 10): the empirical law is too coarse a scale (at most <span class="math inline">n^n</span> distinct resamples, and often far fewer distinct values of the statistic); <strong>non-regular statistics</strong> (boundaries, number of components): the bootstrap can be inconsistent. Research bridge: Naulet, Roy, Sharma &amp; Veitch use <em>weighted</em> bootstraps for the graphex tail index — the estimator of the “hidden mass” of large networks (ch.&nbsp;11).</p>
</div>
<h2 id="ch8">8. A/B testing: sequential and targeted effects</h2>
<div class="def">
<p><span class="tag">Definition 8.1 — A/B test and OEC</span> An online randomized experiment: every unit (user, query, session — <em>the randomization unit must be the analysis unit</em>) receives variant A (control) or B (treatment). The <strong>OEC</strong> (Overall Evaluation Criterion) is the single decision metric, defined <em>before</em> the experiment; secondary metrics (guardrails: latency, error rate, churn) are tested with multiple-testing correction (ch.&nbsp;6). Discipline: no OEC, no test.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 8.2 — The cost of “peeking” (looking before the end)</span> A fixed-horizon test of level <span class="math inline">\alpha</span>, examined <span class="math inline">K</span> times with stopping as soon as a p-value drops below <span class="math inline">\alpha</span>, has a false positive rate <span class="math display">\mathbb{P}(\exists k \leq K : p_k \leq \alpha) \;\geq\; \alpha \quad \text{and} \quad \leq\; 1 - (1 - \alpha)^K \ \text{(if independent).}</span> For <span class="math inline">K = 5</span> looks and <span class="math inline">\alpha = 5\,\%</span>, already <span class="math inline">1 - 0.95^5 = 22.6\,\%</span>; with daily continuous monitoring over weeks, Johari, Pekelis, Walsh and Ye (KDD 2017) measure rates reaching about <strong>three times</strong> the nominal level.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>The lower bound is clear (the first look is a level-<span class="math inline">\alpha</span> test). The upper bound: union bound over the <span class="math inline">K</span> events <span class="math inline">\{p_k \leq \alpha\}</span>, each of probability <span class="math inline">\leq \alpha</span> under <span class="math inline">H_0</span> — with equality × independence when the looks are independent tests (a rough approximation: in practice successive p-values are highly correlated, which makes the true rate smaller than the bound but far above <span class="math inline">\alpha</span>). Hence the simulation of exercise 7. <span class="qed">∎</span></p>
</div>
</div>
<div class="def">
<p><span class="tag">Definition 8.3 — Always-valid p-values and mSPRT (Johari et al., 2017)</span> A sequential p-value <span class="math inline">p_t</span> is <strong>always valid</strong> if <span class="math inline">\mathbb{P}(\exists t : p_t \leq \alpha) \leq \alpha</span> for every stopping time — one may then look as often as desired. Construction: a mixture of sequential probability ratio tests (mSPRT); the mirror Bayesian version: monitor the posterior of <span class="math inline">d = p_B - p_A</span> and its credible interval at every instant (code below), with a non-informative Beta prior; the two families correspond asymptotically (same boundaries in <span class="math inline">t</span>, cf.&nbsp;the Reinforcement Learning module ch.&nbsp;6 for bandits, the other answer to the problem).</p>
</div>
<div class="sourceCode" id="cb2"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">52</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Bayesian A/B test: Beta posteriors, decision by expected loss ----</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>conv <span class="op">=</span> np.array([<span class="dv">1274</span>, <span class="dv">1378</span>])          <span class="co"># conversions</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>n    <span class="op">=</span> np.array([<span class="dv">12000</span>, <span class="dv">12000</span>])        <span class="co"># visits</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>a, b <span class="op">=</span> <span class="fl">1.0</span>, <span class="fl">1.0</span>                        <span class="co"># Beta(1, 1) prior</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>post <span class="op">=</span> [rng.beta(conv[i] <span class="op">+</span> a, n[i] <span class="op">-</span> conv[i] <span class="op">+</span> b, size<span class="op">=</span><span class="dv">200_000</span>) <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">2</span>)]</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>d <span class="op">=</span> post[<span class="dv">1</span>] <span class="op">-</span> post[<span class="dv">0</span>]                  <span class="co"># absolute uplift drawn a posteriori</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>loss_if_B <span class="op">=</span> np.where(d <span class="op">&lt;</span> <span class="dv">0</span>, <span class="op">-</span>d, <span class="fl">0.0</span>)   <span class="co"># loss if we deploy B and A was better</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"P(B &gt; A)            : </span><span class="sc">{</span>(d <span class="op">&gt;</span> <span class="dv">0</span>)<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"gain median         : </span><span class="sc">{</span>np<span class="sc">.</span>median(d)<span class="sc">:.5f}</span><span class="ss">"</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"IC 95 % du gain     : </span><span class="sc">{</span>np<span class="sc">.</span>quantile(d, [<span class="fl">0.025</span>, <span class="fl">0.975</span>])<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"E[perte | deploi B] : </span><span class="sc">{</span>loss_if_B<span class="sc">.</span>mean()<span class="sc">:.2e}</span><span class="ss">"</span>)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Typical outputs: P(B&gt;A) = 0.984; median uplift = 0.0087;</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co"># CI = [0.0007, 0.0166]; E[loss] = 2.2e-05.</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Decision: the cost of a wrong choice of B (2 conversions out of 10^5) is negligible</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co"># compared with the expected gain (+0.87 point) -- we deploy B.</span></span></code></pre></div>
<div class="def">
<p><span class="tag">Definition 8.4 — Targeted (heterogeneous) effects and the associated errors</span> The average effect hides heterogeneity: B wins on mobile, loses on desktop. Two symmetric pitfalls: (i) <strong>subgroup spinning</strong>: 20 segments ⇒ expect a “significant gain” in one of them by pure noise (ch.&nbsp;6, Bonferroni/BH mandatory); (ii) <strong>ignored real interaction effects</strong>: the aggregated OEC can cancel out opposite effects (Simpson, ch.&nbsp;3). A sound framework: specify segments a priori, test the segment × treatment <em>interaction</em>, correct for multiple testing. On the variance side: CUPED (Deng et al., 2013) reuses the metric measured before the experiment as a covariate — a typical “free” variance reduction of 30–50&nbsp;%, statistically equivalent to the blocks of ch.&nbsp;2.</p>
</div>
<div class="note">
<p><span class="tag">Interference and validity</span> Two-sided market (Uber: more drivers ⇒ wait time drops for everyone, including the control), CDN caches, social network effects: SUTVA (ch.&nbsp;4) violated. Answers: randomize by clusters (cities, IP clusters — power loss via the design effect <span class="math inline">1 + (m-1)\rho</span>), or isolate (switchback). See Kohavi, Tang &amp; Xu (2020) for the complete catalog of production pitfalls; the Reinforcement Learning module (bandits, ch.&nbsp;6) addresses the “exploit during the experiment” alternative.</p>
</div>
<h2 id="ch9">9. Case study: agricultural trials and blocks</h2>
<p>Agricultural experimentation is the cradle of experimental design: Fisher at Rothamsted in the 1920s invented randomization, blocks and analysis of variance precisely because plots are heterogeneous — the same problem as your users or your patients. It is also the daily ground of INRAE, the instructor’s institution: multi-year multi-location variety trials, complete blocks and <em>alpha-lattices</em> (Patterson &amp; Williams, 1976) to screen hundreds of varieties.</p>
<div class="ex">
<p><span class="tag">Example 9.1 — RCBD computed end to end (teaching data)</span> 4 varieties (A–D) × 5 blocks, yields (t/ha) constructed as <span class="math inline">y_{ij} = 50 + \tau_i + \beta_j + e_{ij}</span> with variety effects <span class="math inline">(+3, +1, -2, -2)</span>, block effects <span class="math inline">(+8, +2, 0, -4, -6)</span> and residuals summing to zero row-wise and column-wise:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Variety</th>
<th style="text-align: left;">Block 1</th>
<th style="text-align: left;">Block 2</th>
<th style="text-align: left;">Block 3</th>
<th style="text-align: left;">Block 4</th>
<th style="text-align: left;">Block 5</th>
<th style="text-align: left;">Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: left;">62</td>
<td style="text-align: left;">54</td>
<td style="text-align: left;">53</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">46</td>
<td style="text-align: left;"><strong>53.0</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: left;">60</td>
<td style="text-align: left;">56</td>
<td style="text-align: left;">51</td>
<td style="text-align: left;">48</td>
<td style="text-align: left;">48</td>
<td style="text-align: left;"><strong>52.6</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: left;">56</td>
<td style="text-align: left;">54</td>
<td style="text-align: left;">47</td>
<td style="text-align: left;">44</td>
<td style="text-align: left;">42</td>
<td style="text-align: left;"><strong>48.6</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: left;">56</td>
<td style="text-align: left;">52</td>
<td style="text-align: left;">49</td>
<td style="text-align: left;">44</td>
<td style="text-align: left;">42</td>
<td style="text-align: left;"><strong>48.6</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mean</td>
<td style="text-align: left;">58.5</td>
<td style="text-align: left;">54</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">46.5</td>
<td style="text-align: left;">44.5</td>
<td style="text-align: left;">50.7</td>
</tr>
</tbody>
</table>
<p>(Values rounded; the sums below use the exact figures of the model.) <strong>Analysis of variance</strong>:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Source</th>
<th style="text-align: left;">df</th>
<th style="text-align: left;">Sum of squares</th>
<th style="text-align: left;">Mean square</th>
<th style="text-align: left;">F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Varieties</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">SS_v = 5 Σ(τ̂ᵢ)² = 90</td>
<td style="text-align: left;">30.0</td>
<td style="text-align: left;"><strong>30.0</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Blocks</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">SS_b = 4 Σ(β̂ⱼ)² = 480</td>
<td style="text-align: left;">120.0</td>
<td style="text-align: left;">120.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Residuals</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">SS_e = Σ e² = 12</td>
<td style="text-align: left;"><strong>1.0</strong></td>
<td style="text-align: left;">—</td>
</tr>
</tbody>
</table>
<p>Observed <span class="math inline">F_{3,12}</span> <span class="math inline">= 30</span> against a threshold of <span class="math inline">F_{0.95;\,3,12} = 3.49</span> — highly significant varietal differences. Pairwise comparisons: standard deviation of a difference of means <span class="math inline">\sqrt{2 \times 1.0/5} = 0.63</span>, LSD at the 5&nbsp;% level: <span class="math inline">2.179 \times 0.63 = 1.38</span> — A (53.0) &gt; B (52.6) &gt; C = D (48.6); A against B is <em>not</em> separated (0.4 &lt; 1.38). <strong>The gain from blocking:</strong> without blocks, the block variability would join the residual: <span class="math inline">(480 + 12)/16 = 30.75</span> instead of <span class="math inline">1.0</span> — the same trial under a completely randomized design would have an <span class="math inline">F</span> on the order of 1: <strong>the trial would have seen nothing</strong>. This is literally Fisher’s lesson: planning well beats modeling well after the fact.</p>
</div>
<div class="note">
<p><span class="tag">Natural continuation</span> Multi-environment trials: genotype × environment interactions, AMMI/GGE models (the PCA of the Machine Learning module ch.&nbsp;6 applied to interactions); resolvable incomplete blocks (alpha-lattices) when <span class="math inline">K \&gt;</span> block size; spatial analysis (fertility trend by rows/columns). The INRAE thread: dozens of trials, thousands of plots, one imperative — randomize, block, estimate the uncertainty, communicate honestly (ch.&nbsp;10).</p>
</div>
<h2 id="ch10">10. Communicating: intervals, p-values, honest visualizations</h2>
<div class="thm">
<p><span class="tag">Milestone 10.1 — The ASA’s six principles on the p-value (Wasserstein &amp; Lazar, 2016)</span></p>
<ol type="1">
<li>a p-value measures the incompatibility of the data with a specified statistical model;</li>
<li>it is <em>not</em> the probability that the null hypothesis is true, nor that the result is due to chance;</li>
<li>scientific conclusions and decisions should not pass only through a threshold (p &lt; 0.05);</li>
<li>full transparency: correct p-values only with the procedure and analysis reported in full;</li>
<li>a p-value, or statistical significance, measures neither the size of an effect nor its importance;</li>
<li>an isolated p-value proves nothing by itself — facts, context and replication make the proof.</li>
</ol>
<p>Collective follow-up: Amrhein, Greenland &amp; McShane (2019), “Scientists rise up against statistical significance” — more than 800 signatories: stop classifying results as “significant” / “not significant”.</p>
</div>
<div class="ex">
<p><span class="tag">Example 10.2 — Same data, two stories</span> Trial with <span class="math inline">n = 40</span> per arm, <span class="math inline">\hat d = 3.1</span> points, <span class="math inline">s = 15</span>, p = 0.041 (two-sided). <strong>Test story:</strong> “significant effect (p = 0.04)” — suggests clear evidence. <strong>Estimation story:</strong> 95&nbsp;% CI of <span class="math inline">d</span>: <span class="math inline">3.1 \pm 1.96 \times 15\sqrt{2/40} = 3.1 \pm 6.6 = [-3.5; 9.7]</span>: the data are compatible with a null effect, a negative one, or one triple the estimate. The second story is the right one: same numbers, honest information. Corollary: “p = 0.20” does <em>not</em> mean “proven that the effect is null” — the CI might be [−1; +8]: absence of evidence is not evidence of absence.</p>
</div>
<div class="def">
<p><span class="tag">Definition 10.3 — Honest visualizations: the rules of the craft</span> <strong>Axes:</strong> never silently truncated on bar charts (a 2&nbsp;% difference becomes a mountain); bars for counts start at zero, lines may be truncated if stated. <strong>Error bars:</strong> always say what they carry — SD (dispersion of the data), SE (precision of the mean) or a 95&nbsp;% CI (inference); by default, show the CI. <strong>Raw data:</strong> overlay individual points (jitter, violin) on the summaries — 8 observations do not deserve a boxplot. <strong>Dual axis:</strong> almost always a lie. <strong>Effect size + uncertainty + n</strong> in every figure/caption; never show a percentage without a count. Synthesis reference: Cumming (2014), “The new statistics”.</p>
</div>
<div class="ex">
<p><span class="tag">Example 10.3 — Arithmetic of the reproducibility crisis (Ioannidis, 2005)</span> A field tests 1000 hypotheses, 100 of which are true. Power 80&nbsp;%, <span class="math inline">\alpha = 5\,\%</span>: true positives <span class="math inline">= 80</span>, false positives <span class="math inline">= 0.05 \times 900 = 45</span>. Among the published discoveries (<span class="math inline">125</span>), the proportion of <em>real</em> discoveries is <span class="math display">\frac{80}{80 + 45} = 64\,\%.</span> Lower the power to 20&nbsp;% (underpowered studies, cf.&nbsp;ch.&nbsp;2): true positives 20, false 45 ⇒ 31&nbsp;%. Add the biases of ch.&nbsp;1 (analytical flexibility, selective publication): the PPV can plummet toward 0 — hence systematic replication, pre-registration, and the “announced n and analysis plan” standards of the industrial A/B testing world.</p>
</div>
<h2 id="ch11">11. Course research notes (Naulet, MaIAGE)</h2>
<p><strong>Zacharie Naulet</strong> is a junior professor (INRAE, MaIAGE team — Mathematics and Computer Science applied to Food and the Environment) and teaches at École Polytechnique; his PhD (Université Paris-Saclay) was on nonparametric Bayesian methods for signal and image processing. His themes — <strong>nonparametric Bayesian statistics, exchangeability, hidden state space models, applications to biological data and networks</strong> — directly feed several chapters of this module: the bootstrap (ch.&nbsp;7), multiple testing and the estimation of <span class="math inline">\pi_0</span> (ch.&nbsp;6), network models (ch.&nbsp;8–9).</p>
<div class="ex">
<p><span class="tag">Example 11.1 — Exchangeability and de Finetti: the backbone</span> De Finetti’s theorem (1931) states that an infinite sequence of <em>exchangeable</em> variables is conditionally i.i.d. with respect to a random law: this is the foundation of Bayesian inference. The quantitative question — how fast does exchangeability approach i.i.d.? — was solved by Dolera &amp; Favaro (“De Finetti’s theorem: rate of convergence in Kolmogorov distance”, Bernoulli 2020; <a href="https://arxiv.org/abs/1802.02244">arXiv:1802.02244</a>) — work by colleagues in the field, cited here as a standard, <em>and not</em> by the instructor. Z. Naulet’s work extends the de Finetti program on two fronts:</p>
<ul>
<li><strong>exchangeable relational data</strong>: V. Veitch, E. Sharma, <a href="https://arxiv.org/abs/1712.02311">Z. Naulet</a>, D. Roy, “Exchangeable modelling of relational data…” — train/test splitting and sparse Poisson factorization for graphs (a bridge with the Graph ML module); Z. Naulet, J. Rousseau, F. Caron, <a href="https://arxiv.org/abs/2107.01120">“Asymptotic Analysis of Statistical Estimators related to MultiGraphex Processes under Misspecification”</a> — what becomes of the estimators when the graphex model is wrong, a statistician-in-action question;</li>
<li><strong>species sampling</strong>: C. Balocchi, S. Favaro, <a href="https://arxiv.org/abs/2203.06076">Z. Naulet</a>, “Bayesian Nonparametric Inference for ‘Species-sampling’ Problems” (Statistical Science): how many species — genetic variants, words, users — have we <em>not</em> seen? This is the “missing mass” that also controls the adaptive FDR of ch.&nbsp;6 (with S. Favaro: <a href="https://arxiv.org/abs/2306.14998">“Optimal estimation of high-order missing masses…”</a>, IEEE Trans. IT; <a href="https://arxiv.org/abs/2104.03251">“Near-optimal estimation of the unseen under regularly varying tail populations”</a>, Bernoulli 2023).</li>
</ul>
</div>
<div class="ex">
<p><span class="tag">Example 11.2 — From the bootstrap to networks, and the bridge to privacy</span></p>
<ul>
<li><strong>Bootstrap for graphs:</strong> Z. Naulet, D. Roy, E. Sharma, V. Veitch, <a href="https://arxiv.org/abs/1712.01745">“Bootstrap estimators for the tail-index and for the count statistics of graphex processes”</a> — resampling networks to estimate uncertainty (ch.&nbsp;7, research version);</li>
<li><strong>hidden models:</strong> K. Abraham, E. Gassiat, <a href="https://arxiv.org/abs/2306.16293">Z. Naulet</a>, “Frontiers to the learning of nonparametric hidden Markov models”; E. Gassiat, I. Kaddouri, <a href="https://arxiv.org/abs/2309.12238">Z. Naulet</a>, “Clustering risk in Non-parametric Hidden Markov and I.I.D. Models”; quantum homodyne tomography with E. Barat (<a href="https://arxiv.org/abs/1610.01895">arXiv:1610.01895</a>);</li>
<li><strong>disclosure risk:</strong> F. Camerlenghi, S. Favaro, <a href="https://arxiv.org/abs/1902.05354">Z. Naulet</a>, F. Panero, “Optimal disclosure risk assessment” (Annals of Statistics, 2021): how far can data be published without re-identifying individuals? — the gateway to the M2 module “Privacy and Uncertainty Quantification”;</li>
<li><strong>nonparametric estimation:</strong> <a href="https://arxiv.org/abs/1805.05816">“Adaptive Bayesian density estimation in sup-norm”</a>; <a href="https://arxiv.org/abs/1608.06536">“Tails assumptions and posterior concentration rates for mixtures of Gaussians”</a> (with J. Rousseau); risk of the minimum-norm estimator in spike covariance (<a href="https://arxiv.org/abs/1912.13421">with Y. Mahdaviyeh</a>).</li>
</ul>
<p>Other recent work: change-point detection in preferential attachment graphs (<a href="https://arxiv.org/abs/2407.18685">with I. Kaddouri and E. Gassiat</a>), robust community detection (<a href="https://arxiv.org/abs/2506.03657">SubSearch, with L. Bianco and C. Keribin</a>).</p>
</div>
<div class="note">
<p><span class="tag">Common thread</span> This work shares a signature: <strong>guarantees</strong> (minimaxity, concentration rates, exact risk) for <strong>usable procedures</strong> on real data — exactly the ambition of this module at the M1 level, and its M2 extension (privacy, uncertainty, calibration).</p>
</div>
<h2 id="ex">Exercises</h2>
<ol type="1">
<li><strong>Randomization by hand.</strong> Data 3, 4, 5, 6, 7, 8, split 3+3. Enumerate the 20 allocations, compute all values of <span class="math inline">\hat d</span>, recover <span class="math inline">p = 0.10</span> and the exact distribution (stem-and-leaf display). Which split gives exactly <span class="math inline">\hat d = 2.33</span>?</li>
<li><strong>Power.</strong> (a) Redo the computation of 2.5 for <span class="math inline">\delta/\sigma = 0.4</span> and 85&nbsp;% power. (b) A two-sided test has <span class="math inline">\alpha = 5\,\%</span> and <span class="math inline">n = 50</span> per group: plot <span class="math inline">\pi(\delta)</span> for <span class="math inline">\delta/\sigma \in [0; 1]</span> and read off the smallest detectable effect size with 80&nbsp;% power. (c) For proportions (<span class="math inline">p_A = 0.10</span>, expected effect +1 point), adapt the formula by replacing <span class="math inline">2\sigma^2</span> with <span class="math inline">p_A(1-p_A) + p_B(1-p_B)</span> and compute <span class="math inline">n</span>.</li>
<li><strong>Simpson.</strong> Verify all the cells of table 3.2 (82.8&nbsp;%, etc.), then recompute the overall rates by standardizing on A’s profile and on B’s; comment on the sensitivity to the profile choice.</li>
<li><strong>DiD.</strong> With table 4.4: compute the naive before/after comparison, the cross-sectional after comparison, and the DiD; check that the DiD equals the interaction coefficient of the model <span class="math inline">y = \beta_0 + \beta_1 \text{NJ} + \beta_2 \text{After} + \beta_3 (\text{NJ} \times \text{After}) + e</span>. Simulate 500 restaurants with common AR(1) shocks and show that naive standard errors are 3–5× too small without clustering (Bertrand et al.&nbsp;2004).</li>
<li><strong>BH in practice.</strong> (a) Apply Bonferroni, Holm and BH to the p-values of example 6.4 for <span class="math inline">q = \alpha = 0.10</span> and <span class="math inline">q = 0.01</span>. (b) Simulation: generate <span class="math inline">m = 1000</span> p-values (<span class="math inline">m_0 = 900</span> uniform, 100 false nulls with p ~ Beta(1, 8)), repeat 500 times, estimate the empirical FWER and FDR of each procedure and verify the calibration <span class="math inline">\mathrm{FDR} \approx q\, m_0/m</span>.</li>
<li><strong>Regression.</strong> On the <code>cars</code> dataset (or an equivalent): fit <span class="math inline">d \sim s</span>, plot the 4 diagnostics, apply Box-Cox, refit; identify the point with the largest Cook’s distance, redo without it; compare the classical and HC1 standard errors (<code>statsmodels</code>).</li>
<li><strong>Peeking.</strong> Simulate 1000 A/B tests under <span class="math inline">H_0</span> (two Bernoulli <span class="math inline">p = 0.10</span>, <span class="math inline">n = 10^5</span> per arm): (a) a single look at midpoint — false positive rate; (b) daily looks for 28 days with stopping if p &lt; 0.05 — compare with the 22.6&nbsp;% of the union bound and with the bound of Johari et al.; (c) implement a Gaussian mSPRT and verify its “always” validity.</li>
<li><strong>Bayesian A/B.</strong> Take up the code of ch.&nbsp;8: (a) analyze the sensitivity to the Beta(1,1) vs Beta(10,10) prior; (b) turn the decision rule into “expected loss &lt; cost of a rollout”; (c) add the per-segment analysis (mobile/desktop) with BH correction of the interaction tests; (d) relate to the frequentist Wald CI — when do they diverge?</li>
<li><strong>RCBD.</strong> Add to the data of 9.1 a moderate block × variety (interaction) effect, redo the ANOVA, test the interaction; build the same trial under a completely randomized design (same values, assignment blind to the blocks) and show the loss of F. Write the simultaneous (Tukey) confidence interval for the 6 comparisons.</li>
<li><strong>Communication.</strong> You have <span class="math inline">\hat d = 3.1</span>, 95&nbsp;% CI = [−3.5; 9.7], p = 0.041, <span class="math inline">n = 80</span>. Write in 5 lines: (a) a misleading “press” summary; (b) an honest summary; (c) list the three graphical manipulations that would reverse the reader’s impression, and their fixes.</li>
<li><strong>Project.</strong> INRAE or open data from a blocked trial (or kaggle: agricultural crop yield): from plan to conclusions — map the potential biases, justify the plan, ANOVA + diagnostics, bootstrap of the contrasts, multiple-comparison correction, final one-page report with honest visualizations and limits. Grading: 40&nbsp;% plan, 40&nbsp;% correct analysis, 20&nbsp;% communication.</li>
</ol>
<h2 id="refs">References</h2>
<ul>
<li>R. A. Fisher, <em>The Design of Experiments</em>, Oliver &amp; Boyd, 1935 — randomization, blocks, the lady tasting tea.</li>
<li>G. E. P. Box, W. G. Hunter, J. S. Hunter, <em>Statistics for Experimenters</em>, 2nd ed., Wiley, 2005.</li>
<li>A. Dean, D. Voss, <em>Design and Analysis of Experiments</em>, Springer, 1999.</li>
<li>H. D. Patterson, E. R. Williams, “A new class of resolvable incomplete block designs”, <em>Biometrika</em> 63, 1976 — alpha-lattices.</li>
<li>J. Neyman, “On the application of probability theory to agricultural experiments (1923)”, trans. <em>Statistical Science</em> 5, 1990; D. B. Rubin, “Estimating causal effects of treatments in randomized and nonrandomized studies”, <em>J. Educational Psychology</em> 66, 1974.</li>
<li>G. Imbens, D. Rubin, <em>Causal Inference for Statistics, Social, and Biomedical Sciences</em>, Cambridge University Press, 2015.</li>
<li>D. Card, A. Krueger, “Minimum Wages and Employment”, <em>American Economic Review</em> 84, 1994.</li>
<li>M. Bertrand, E. Duflo, S. Mullainathan, “How Much Should We Trust Differences-in-Differences Estimates?”, <em>Q. J. Economics</em> 119, 2004.</li>
<li>C. R. Charig et al., “Comparison of treatment of renal calculi by open surgery, percutaneous nephrolithotomy, and extracorporeal shockwave lithotripsy”, <em>BMJ</em> 292, 1986 — the Simpson’s paradox data.</li>
<li>E. J. Elton, M. J. Gruber, C. R. Blake, “Survivorship Bias in Mutual Fund Performance”, <em>Journal of Finance</em> 51, 1996.</li>
<li>M. Mangel, S. M. Samuels, “Analyzing the Wald airplane data”, <em>Statistical Science</em> 17, 2002.</li>
<li>B. Efron, “Bootstrap Methods: Another Look at the Jackknife”, <em>Annals of Statistics</em> 7, 1979; B. Efron, R. Tibshirani, <em>An Introduction to the Bootstrap</em>, Chapman &amp; Hall, 1993; A. van der Vaart, <em>Asymptotic Statistics</em>, Cambridge University Press, 1998 (ch.&nbsp;23).</li>
<li>Y. Benjamini, Y. Hochberg, “Controlling the False Discovery Rate”, <em>J. R. Statist. Soc. B</em> 57, 1995; Y. Benjamini, D. Yekutieli, “The control of the false discovery rate in multiple testing under dependency”, <em>Annals of Statistics</em> 29, 2001; J. Storey, “A direct approach to false discovery rates”, <em>J. R. Statist. Soc. B</em> 64, 2002.</li>
<li>R. Johari, L. Pekelis, D. J. Walsh, W. Ye, “Peeking at A/B Tests: Why it matters, and what to do about it”, KDD 2017 (<a href="https://dl.acm.org/doi/10.1145/3097983.3097992">doi:10.1145/3097983.3097992</a>); long version “Always Valid Inference”, <em>Operations Research</em> 70, 2022 (<a href="https://doi.org/10.1287/opre.2021.2135">doi:10.1287/opre.2021.2135</a>).</li>
<li>A. Deng, Y. Xu, R. Kohavi, T. Walker, “Improving the Sensitivity of Online Controlled Experiments by Utilizing Pre-Experiment Period Data” (CUPED), KDD 2013.</li>
<li>R. Kohavi, A. Deng, B. Frasca, T. Walker, Y. Xu, N. Pohlmann, “Online Controlled Experiments at Large Scale”, KDD 2013; R. Kohavi, D. Tang, Y. Xu, <em>Trustworthy Online Controlled Experiments</em>, Cambridge University Press, 2020.</li>
<li>R. L. Wasserstein, N. A. Lazar, “The ASA’s Statement on p-Values”, <em>The American Statistician</em> 70, 2016.</li>
<li>V. Amrhein, S. Greenland, B. McShane, “Scientists rise up against statistical significance”, <em>Nature</em> 567, 2019.</li>
<li>J. P. A. Ioannidis, “Why Most Published Research Findings Are False”, <em>PLoS Medicine</em> 2, 2005.</li>
<li>N. L. Kerr, “HARKing: Hypothesizing After the Results are Known”, <em>Personality and Social Psychology Review</em> 2, 1998; A. Gelman, E. Loken, “The garden of forking paths”, 2013 (working paper).</li>
<li>G. Cumming, “The New Statistics: Why and How”, <em>Psychological Science</em> 25, 2014.</li>
<li>J. M. Hoenig, D. M. Heisey, “The Abuse of Power”, <em>The American Statistician</em> 55, 2001.</li>
<li><a href="https://synapses.polytechnique.fr/catalogue/2024-2025/ue/680/APM-52066-EP-statistique-en-action">APM_52066_EP “Statistics in action” datasheet</a>, SynapseS catalog of École Polytechnique.</li>
<li><strong>Research group (Z. Naulet, INRAE MaIAGE / École Polytechnique)</strong>: research page: <a href="https://znaulet.pages-forge.inrae.fr/">znaulet.pages-forge.inrae.fr</a>; C. Balocchi, S. Favaro, Z. Naulet, <a href="https://arxiv.org/abs/2203.06076">Bayesian Nonparametric Inference for “Species-sampling” Problems</a> (Statistical Science); S. Favaro, Z. Naulet, <a href="https://arxiv.org/abs/2104.03251">Near-optimal estimation of the unseen under regularly varying tail populations</a> (Bernoulli 2023); <a href="https://arxiv.org/abs/2306.14998">Optimal estimation of high-order missing masses, and the rare-type match problem</a> (IEEE Trans. IT); V. Veitch, E. Sharma, Z. Naulet, D. Roy, <a href="https://arxiv.org/abs/1712.02311">Exchangeable modelling of relational data</a>; Z. Naulet, J. Rousseau, F. Caron, <a href="https://arxiv.org/abs/2107.01120">Asymptotic Analysis of Statistical Estimators related to MultiGraphex Processes under Misspecification</a>; Z. Naulet, D. Roy, E. Sharma, V. Veitch, <a href="https://arxiv.org/abs/1712.01745">Bootstrap estimators for the tail-index and for the count statistics of graphex processes</a>; F. Camerlenghi, S. Favaro, Z. Naulet, F. Panero, <a href="https://arxiv.org/abs/1902.05354">Optimal disclosure risk assessment</a> (Annals of Statistics 2021); K. Abraham, E. Gassiat, Z. Naulet, <a href="https://arxiv.org/abs/2306.16293">Frontiers to the learning of nonparametric hidden Markov models</a>; E. Gassiat, I. Kaddouri, Z. Naulet, <a href="https://arxiv.org/abs/2309.12238">Clustering risk in Non-parametric Hidden Markov and I.I.D. Models</a>; Z. Naulet, E. Barat, <a href="https://arxiv.org/abs/1610.01895">Bayesian nonparametric estimation for Quantum Homodyne Tomography</a>; <a href="https://arxiv.org/abs/1805.05816">Adaptive Bayesian density estimation in sup-norm</a>; <a href="https://arxiv.org/abs/1608.06536">Tails assumptions and posterior concentration rates for mixtures of Gaussians</a>; Y. Mahdaviyeh, Z. Naulet, <a href="https://arxiv.org/abs/1912.13421">Risk of the Least Squares Minimum Norm Estimator under the Spike Covariance Model</a>; I. Kaddouri, Z. Naulet, E. Gassiat, <a href="https://arxiv.org/abs/2407.18685">On the impossibility of detecting a late change-point in the preferential attachment random graph model</a>; L. Bianco, C. Keribin, Z. Naulet, <a href="https://arxiv.org/abs/2506.03657">SubSearch: Robust Estimation and Outlier Detection for Stochastic Block Models</a>.</li>
<li>E. Dolera, S. Favaro, “De Finetti’s theorem: rate of convergence in Kolmogorov distance”, <em>Bernoulli</em> 26, 2020 — <a href="https://arxiv.org/abs/1802.02244">arXiv:1802.02244</a> (standard cited in ch.&nbsp;11).</li>
</ul>

</main>
<footer class="foot"><p><a href="../../index.html">← Master's program</a></p></footer>
<script defer="" src="../../assets/theme.js"></script>




</body></html>