<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Deep Learning</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script>(function(){try{var t=localStorage.getItem("llga-theme");if(t==="dark"||t==="light")document.documentElement.setAttribute("data-theme",t);}catch(e){}})();</script>
<style>
  /* Keep paper.css as visual source of truth; tame Quarto chrome */
  #title-block-header { margin: 0 0 0.5rem; }
  #title-block-header .title { margin: 0 0 0.25rem; font-size: 1.85rem; font-weight: 700; }
  #title-block-header .subtitle { color: var(--soft, #555); margin: 0 0 1rem; font-size: 1.05rem; }
  div.sourceCode { background: var(--code-bg, #f7f7f7); border: 1px solid var(--hair, #e4e4e4); }
  code { background: var(--code-inline-bg, #f4f4f4); }

  /* Light (github) token colors — higher specificity beats paper.css */
  div.sourceCode pre.sourceCode code span.kw, div.sourceCode pre.sourceCode code span.cf, div.sourceCode pre.sourceCode code span.dt, div.sourceCode pre.sourceCode code span.at, div.sourceCode pre.sourceCode code span.bu, div.sourceCode pre.sourceCode code span.pp { color: #d73a49; }
  div.sourceCode pre.sourceCode code span.im, div.sourceCode pre.sourceCode code span.st, div.sourceCode pre.sourceCode code span.ch, div.sourceCode pre.sourceCode code span.ss, div.sourceCode pre.sourceCode code span.vs { color: #032f62; }
  div.sourceCode pre.sourceCode code span.co, div.sourceCode pre.sourceCode code span.an, div.sourceCode pre.sourceCode code span.cv, div.sourceCode pre.sourceCode code span.do, div.sourceCode pre.sourceCode code span.in { color: #6a737d; }
  div.sourceCode pre.sourceCode code span.fu { color: #6f42c1; }
  div.sourceCode pre.sourceCode code span.va { color: #e36209; }
  div.sourceCode pre.sourceCode code span.cn, div.sourceCode pre.sourceCode code span.bn, div.sourceCode pre.sourceCode code span.dv, div.sourceCode pre.sourceCode code span.fl, div.sourceCode pre.sourceCode code span.sc { color: #005cc5; }
  div.sourceCode pre.sourceCode code span.op { color: #24292e; }
  /* Dark mode token colors (github highlight is light-oriented) */
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.kw,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.cf,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.dt,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.at,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.bu,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.pp,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.op { color: #ff7b72; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.im { color: #ff7b72; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.st,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.ch,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.ss,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.vs { color: #a5d6ff; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.cn,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.bn,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.dv,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.fl,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.sc { color: #79c0ff; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.co,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.an,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.cv,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.do,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.in { color: #8b949e; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.va { color: #ffa657; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.fu { color: #d2a8ff; }
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.kw,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.cf,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.dt,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.at,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.bu,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.pp,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.op { color: #ff7b72; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.im { color: #ff7b72; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.st,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.ch,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.ss,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.vs { color: #a5d6ff; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.cn,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.bn,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.dv,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.fl,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.sc { color: #79c0ff; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.co,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.an,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.cv,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.do,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.in { color: #8b949e; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.va { color: #ffa657; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.fu { color: #d2a8ff; }
  }

</style>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../assets/paper.css">
</head>

<body>

<p class="crumb"><a href="../../index.html">MSc&amp;T LLGA · Course notes</a></p>
<main class="paper">

<header id="title-block-header">
<h1 class="title">Deep Learning</h1>
<p class="subtitle">APM_52183_EP · Year 1 · Period 2</p>

</header>


<h2 id="contents">Contents</h2>
<ul>
<li><a href="#intro">Introduction and overview</a></li>
<li><a href="#ch0">0. Compact refresher: the P1 foundation</a></li>
<li><a href="#ch1">1. Counting: FLOPs, memory, scaling laws</a></li>
<li><a href="#ch2">2. Theoretical complexity of training</a></li>
<li><a href="#ch3">3. Parallelism: data, tensor, pipeline</a></li>
<li><a href="#ch4">4. Communication: all-reduce and friends</a></li>
<li><a href="#ch5">5. Memory efficiency: checkpointing, ZeRO, mixed precision</a></li>
<li><a href="#ch6">6. Efficient inference</a></li>
<li><a href="#ch7">7. Real systems: roofline, GPU, and the complete budget of a 7B LLM</a></li>
<li><a href="#ch8">8. Research of the instructor</a></li>
<li><a href="#ex">Exercises</a></li>
<li><a href="#refs">References</a></li>
</ul>
<h2 id="intro">Introduction and overview</h2>
<table class="caption-top">
<tbody>
<tr class="odd">
<td style="text-align: left;">Module</td>
<td style="text-align: left;">Deep Learning — <em>official title (SynapseS 2026-2027 catalog): “Apprentissage profond de la théorie à la pratique”</em></td>
</tr>
<tr class="even">
<td style="text-align: left;">Code</td>
<td style="text-align: left;">APM_52183_EP</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Team and volume</td>
<td style="text-align: left;">Coordinator: Alain Durmus (École Polytechnique, CMAP) · instructional engineering team: C. Battiloro, P. Bianchi, C. Bonet, B. Bonev · occurrence coordinator: B. Galerne · 36&nbsp;h in person · 4.5&nbsp;ECTS (MScT degrees; 5&nbsp;ECTS engineering curriculum and exchange programs) · the foundations and practice of deep learning, reread here through the lens of <strong>cost</strong>: counting FLOPs and bytes, parallelizing training, compressing inference — and knowing the lower bounds that say what cannot be done better.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Period</td>
<td style="text-align: left;">Fall semester — period 2 (X-3A-P2): from 04/01/2027 to 19/03/2027 · X3A MA3 slot · min./max. enrollment 1/80 (occurrence: –/85)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Language</td>
<td style="text-align: left;">French, English</td>
</tr>
<tr class="even">
<td style="text-align: left;">Assessment</td>
<td style="text-align: left;">Numerical grade out of 20 (literal conversion / American grade); project-based validation indicated for the X and exchange curricula; resit allowed (max of the two grades); course unit earned if final grade ≥ 10. Modalities specific to the LLGA track: not communicated.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Status in the program</td>
<td style="text-align: left;"><span class="badge option">P2 Option</span><span class="badge position">Outside recommended track</span> Course unit listed in the official LLGA&nbsp;1&nbsp;–&nbsp;S2 2026-2027 track.</td>
</tr>
</tbody>
</table>
<p><strong>Audience</strong>: a DL engineer who already trains and wants to quantify FLOPs / memory / comms. <strong>Empirical first</strong>: OOM on a 7B from bad sharding; ×1.2 speedup despite 8 GPUs (Amdahl) — then we name complexity, data/tensor/pipeline parallel, quantization.</p>
<p>Reread the P1 DL core through cost: bounds and real GPU behavior.</p>
<h3 id="what-you-will-be-able-to-do">What you will be able to do</h3>
<ul>
<li>Count the FLOPs and memory of a model, and connect these counts to scaling laws.</li>
<li>Explain the theoretical complexity bounds of training and what they rule out.</li>
<li>Choose a parallelism strategy — data, tensor, pipeline — and justify it quantitatively.</li>
<li>Analyze collective communications (all-reduce and friends) and their effective cost.</li>
<li>Reduce the memory footprint of a training run with checkpointing and ZeRO.</li>
<li>Make inference efficient and know at what performance price.</li>
<li>Read a roofline and predict the behavior of a real system, from GPU to 7B LLM.</li>
</ul>
<h3 id="official-objectives-and-syllabus-2026-2027-catalog">Official objectives and syllabus (2026-2027 catalog)</h3>
<p>Officially, the APM_52183_EP course unit offers an in-depth presentation of the <em>practical</em> and <em>theoretical</em> aspects of deep learning: on the one hand the mastery of Python / PyTorch implementation (implementation, debugging, visualization), on the other the analysis of foundations (automatic differentiation, universality results, non-convex optimization, equivariant models). The stated objective is twofold: give an overview of the deep learning landscape and its applications, and make students able to train by themselves a deep network of several million parameters. Official prerequisites: <em>basics in Machine Learning</em> and <em>coding in Python</em>.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Official theme (2026-2027 detailed syllabus)</th>
<th style="text-align: left;">Section of this module</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1. Introduction and presentation of the field</td>
<td style="text-align: left;">Introduction and ch.&nbsp;0 (refresher of the foundation).</td>
</tr>
<tr class="even">
<td style="text-align: left;">2. Training pipeline in PyTorch</td>
<td style="text-align: left;"><em>Not covered as such</em>: ch.&nbsp;1 deals with the cost of the pipeline (FLOPs, memory), not its PyTorch implementation.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3. Optimization for deep learning</td>
<td style="text-align: left;">Partial: ch.&nbsp;2 (complexity and optimality bounds); applied stochastic optimization is not detailed.</td>
</tr>
<tr class="even">
<td style="text-align: left;">4. Image analysis</td>
<td style="text-align: left;"><em>Missing.</em></td>
</tr>
<tr class="odd">
<td style="text-align: left;">5. Regression and classification of sequential data</td>
<td style="text-align: left;"><em>Missing.</em></td>
</tr>
<tr class="even">
<td style="text-align: left;">6. Text generation (Transformers)</td>
<td style="text-align: left;">Partial: ch.&nbsp;7 (7B LLM case study, systems side); the Transformer architecture is not built there.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7. Stability and robustness</td>
<td style="text-align: left;"><em>Missing</em> (ch.&nbsp;2 only gives the complexity perspective).</td>
</tr>
<tr class="even">
<td style="text-align: left;">8. Deep reinforcement learning</td>
<td style="text-align: left;"><em>Missing.</em></td>
</tr>
<tr class="odd">
<td style="text-align: left;">9. Generative models</td>
<td style="text-align: left;"><em>Missing.</em></td>
</tr>
</tbody>
</table>
<div class="note">
<p><span class="tag">Complement to the official syllabus</span> Chapters 1 to 7 of this module deepen a “cost and systems” angle (FLOPs and memory counting, data/tensor/pipeline parallelism, collective communications, checkpointing and ZeRO, efficient inference, roofline) that does not appear as such in the official syllabus; conversely, official themes 2, 4, 5, 7, 8 and 9 are not developed in it. These materials therefore complement the official syllabus on the systems side — they do not replace it.</p>
</div>
<h3 id="where-this-course-fits-in-the-program">Where this course fits in the program</h3>
<p>An option of period 2 of M1, outside the recommended track: this is the P2 variant of the P1 course, <a href="../m1p1-deep-learning/index.html">Deep Learning</a>, whose foundation it assumes (or an equivalent); chapter 0 offers compact reminders of it. Official prerequisites: <em>basics in Machine Learning</em> and <em>coding in Python</em> — exactly what chapter 0 brings back up to level before the cost chapters. Downstream, the module directly prepares <a href="../m2-mlops-llm-engineering/index.html">ML Ops and LLM Engineering Principles</a> (M2), where these cost accounts become deployment decisions, and <a href="../m2-advanced-topics-llms/index.html">Advanced Topics in Large Language Models</a> (M2), whose large-scale analyses build on the same scaling laws and budgets.</p>
<h3 id="course-outline">Course outline</h3>
<ul>
<li><strong>Compact refresher: the P1 foundation</strong> — the essentials of the P1 Deep Learning course, restated in cost vocabulary.</li>
<li><strong>Counting: FLOPs, memory, scaling laws</strong> — the module’s basic discipline: quantify before asserting.</li>
<li><strong>Theoretical complexity of training</strong> — the bounds that say what no trick will ever beat.</li>
<li><strong>Parallelism: data, tensor, pipeline</strong> — the three main ways of distributing a training run, and their trade-offs.</li>
<li><strong>Communication: all-reduce and friends</strong> — the collectives that connect the workers, and their share of total time.</li>
<li><strong>Memory efficiency: checkpointing, ZeRO</strong> — fitting models and states that do not fit.</li>
<li><strong>Efficient inference</strong> — cutting the cost of the trained model at the moment it serves.</li>
<li><strong>Real systems: roofline, GPU, 7B LLM</strong> — confronting theoretical accounts with hardware, on a textbook case.</li>
<li><strong>Research of the instructor</strong> — the research papers of Kevin Scaman, read with the module’s tools.</li>
<li><strong>Exercises</strong> — counts, bounds and parallelism choices to defend.</li>
<li><strong>References</strong> — the systems and theory papers underlying each chapter.</li>
</ul>
<h3 id="how-to-study-this-module">How to study this module</h3>
<ul>
<li>Work through chapter 0 seriously, even if the P1 course is fresh: the cost vocabulary is introduced there.</li>
<li>Quantify everything: for every architecture encountered elsewhere, practice estimating FLOPs and memory before looking up the answer.</li>
<li>Never separate theory from hardware: a complexity bound is read facing a roofline.</li>
<li>Recompute the systems chapter’s examples on paper, then check against GPU orders of magnitude.</li>
<li>Cross-reference with the optimization module of the same period: convergence rates ground the training analyses there.</li>
<li>Do the exercises by estimating first, computing second: the order of magnitude first is the target skill.</li>
</ul>
<div class="note">
<p><span class="tag">Independent note</span> The LLMs that structure the M2 of the master’s program are first and foremost objects of cost: counting them, parallelizing them and compressing them is the condition for deploying them. This module provides this language of budgets, common to the systems courses and the M2 LLM courses — and directly marketable in careers in large-scale ML engineering as in research on distributed learning.</p>
</div>
<h2 id="ch0">0. Compact refresher: the P1 foundation</h2>
<div class="recap">
<div class="recap-title">
<p>Reminders — the P1 Deep Learning module, in eight points (each point refers to the corresponding chapter of the Deep Learning module)</p>
</div>
<ul>
<li><strong>Neuron and network</strong> (ch.&nbsp;1): <span class="math inline">h = \sigma(Wx)</span>; depth = composition; initialization and normalization to keep the variance stable across layers.</li>
<li><strong>Backpropagation</strong> (ch.&nbsp;2): chain rule on the computation graph; the cost of a backward pass ≈ 2× that of the forward pass (remember: this is a complexity fact, not a software approximation — see ch.&nbsp;1 here).</li>
<li><strong>Optimization</strong> (ch.&nbsp;3): SGD, momentum, Adam/AdamW; warmup and decay — the analytical detail is in the Optimization for AI module, ch.&nbsp;2–5 and 10.</li>
<li><strong>CNN</strong> (ch.&nbsp;4): shared weights, receptive fields; cost dominated by the convolutions.</li>
<li><strong>Transformers</strong> (ch.&nbsp;6): multi-head attention <span class="math inline">\mathrm{softmax}(QK^\top/\sqrt{d})V</span>, 4<span class="math inline">d</span> MLP, residual connections; this is the architecture of all the case studies in this module.</li>
<li><strong>Generative models</strong> (ch.&nbsp;7): AE/VAE/GAN — their sampling cost will be revisited in ch.&nbsp;6.</li>
<li><strong>Transfer learning</strong> (ch.&nbsp;8): fine-tuning vs pre-training — the dividing line of budgets (ch.&nbsp;1 and 7 here).</li>
<li><strong>Training in practice</strong> (ch.&nbsp;10): mixed precision, distributed data parallel, monitoring — ch.&nbsp;5 here provides the theory.</li>
</ul>
</div>
<div class="note">
<p><span class="tag">The pedagogical contract of the P2 variant</span> The P1 course answers “how does it work?”; this variant answers “how much does it cost, and how far can one go?”. Three questions organize everything: (Q1) <em>count</em> — predict the FLOPs and memory of a training run <em>before</em> launching it (ch.&nbsp;1, 7); (Q2) <em>parallelize</em> — decompose the compute time over several machines, and know what theory forbids (ch.&nbsp;2–5); (Q3) <em>compress</em> — reduce the inference cost at nearly equal quality (ch.&nbsp;6). The instructor is a theorist of distributed optimization (ch.&nbsp;8): this module is the place in the master’s program where one proves <em>lower bounds</em>, not just algorithms.</p>
</div>
<h2 id="ch1">1. Counting: FLOPs, memory, scaling laws</h2>
<p>Concrete scene: a GPU budget burned because nobody counted FLOPs before the job. This chapter sets exact counting.</p>
<div class="note">
<p><span class="tag">What breaks</span> Confusing FLOP and FLOP/s; ignoring memory bandwidth; parallelizing without Amdahl’s law.</p>
</div>
<p>The module’s first skill: <strong>exact counting</strong>. An engineer who can estimate the FLOPs of a training run by hand saves GPU-days — and catches configuration errors before they explode.</p>
<div class="def">
<p><span class="tag">Definition 1.1 — Units: FLOP, FLOPs, FLOP/s</span> A <strong>FLOP</strong> (floating-point operation) = one elementary operation (+, ×); we count a multiply-add <span class="math inline">a \cdot b + c</span> as <strong>2 FLOPs</strong> (the module’s convention, aligned with the systems literature); <strong>FLOP/s</strong> = throughput. An A100 GPU: ≈ 19.5 TFLOP/s fp32, 312 TFLOP/s tensor-core bf16; an H100: ≈ 1000 TFLOP/s bf16 (sparse modes excluded). The <strong>MFU</strong> (model FLOPs utilization) = achieved FLOP/s ÷ peak FLOP/s: 35–50% is a good LLM training run; the rest is lost to memory, communication and subtasks (ch.&nbsp;7).</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 1.2 — Cost of a linear layer and a transformer (proved)</span> (i) A matrix-matrix product <span class="math inline">A \in \mathbb{R}^{m \times n}</span> by <span class="math inline">B \in \mathbb{R}^{n \times p}</span> costs <span class="math inline">2mnp</span> FLOPs. (ii) A linear layer <span class="math inline">d_\mathrm{in} \to d_\mathrm{out}</span> applied to <span class="math inline">n</span> tokens costs <span class="math inline">2\,n\,d_\mathrm{in}d_\mathrm{out}</span> FLOPs and has <span class="math inline">d_\mathrm{in}d_\mathrm{out}</span> parameters — that is, <strong>2 FLOPs per parameter and per token</strong>. (iii) Transformer block of width <span class="math inline">d</span>, over a sequence of <span class="math inline">n</span> tokens: QKVO <span class="math inline">4 \times 2d^2 = 8d^2</span>, scores <span class="math inline">QK^\top</span> and product with <span class="math inline">V</span>: <span class="math inline">2 \times 2n^2 d</span>, MLP (width <span class="math inline">4d</span>): <span class="math inline">2 \times 2 \times 4d^2 = 16d^2</span> — that is, <em>per token</em>: <span class="math inline">\;24d^2 + 4nd</span> FLOPs.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>(i) Each of the <span class="math inline">mp</span> entries of <span class="math inline">C=AB</span> is a dot product of length <span class="math inline">n</span> (n multiplications + n−1 additions ≈ 2n FLOPs). (ii) special case with <span class="math inline">m=n</span> tokens, <span class="math inline">p = d_\mathrm{out}</span>. (iii): apply (ii) to each projection; for <span class="math inline">QK^\top</span> (an <span class="math inline">n \times d</span> by <span class="math inline">d \times n</span> matrix): <span class="math inline">2n^2 d</span>, likewise for <span class="math inline">(\cdot)V</span> (<span class="math inline">n \times n</span> by <span class="math inline">n \times d</span>); MLP = two layers <span class="math inline">d \to 4d</span> then <span class="math inline">4d \to d</span>. Divide the total by <span class="math inline">n</span> tokens to express it per token: QKV projections (<span class="math inline">3 \times 2d^2</span>) + output (<span class="math inline">2d^2</span>) = <span class="math inline">8d^2</span>, quadratic part of attention <span class="math inline">4nd</span>, MLP <span class="math inline">16d^2</span>. <span class="qed">∎</span></p>
</div>
</div>
<div class="thm">
<p><span class="tag">Theorem 1.3 — The rule <span class="math inline">C \approx 6\,N\,D</span> (proved)</span> Pre-training a model with <span class="math inline">N</span> parameters (dense transformer) on <span class="math inline">D</span> tokens costs <span class="math display">C \;\approx\; 6\,N\,D \;\;\text{FLOPs} \qquad (\text{forward} \approx 2ND,\; \text{backward} \approx 4ND).</span></p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Forward pass: the model is a composition of linear layers and negligible operations (normalizations, softmax: <span class="math inline">O(nd)</span> or <span class="math inline">O(n^2)</span> without a <span class="math inline">d^2</span> factor); each parameter is used exactly once per token, at 2 FLOPs each (prop. 1.2 ii) — hence <span class="math inline">2ND</span>. Backward pass: for each layer, the gradient is computed by (a) applying the transpose of the weight to the upstream gradient (<span class="math inline">2ND</span>) and (b) multiplying the upstream gradient by the local input to form the weight gradient (<span class="math inline">2ND</span>) — that is <span class="math inline">2 \times 2ND</span>. Total <span class="math inline">6ND</span>. Experience (profiling of large training runs) confirms within ±10%, the gap coming from (shared) embeddings, the vocabulary and the heads. <span class="qed">∎</span></p>
</div>
</div>
<div class="def">
<p><span class="tag">Definition 1.4 — Training memory, line by line (Adam, mixed precision)</span> For <span class="math inline">N</span> parameters:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Tensor</th>
<th style="text-align: left;">Precision</th>
<th style="text-align: left;">Bytes/parameter</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">weights (bf16/fp16)</td>
<td style="text-align: left;">2 bytes</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">gradients (bf16)</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adam states <span class="math inline">m, v</span> (fp32)</td>
<td style="text-align: left;">4 + 4</td>
<td style="text-align: left;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">fp32 master weights (stability)</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>total states</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"><strong>16</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">activations (depend on <span class="math inline">n, d</span>, number of layers) — see ch.&nbsp;5</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;"><span class="math inline">\sim 2\,n\,d</span> per layer and per token</td>
</tr>
</tbody>
</table>
<p>Order of magnitude to remember: <strong>16 bytes per parameter</strong> of states + activations. A 7B model with Adam: <span class="math inline">7\times10^9 \times 16</span> ≈ 112&nbsp;GB — before any activation: a single 80&nbsp;GB GPU is not enough (ch.&nbsp;5 and 7).</p>
</div>
<div class="note">
<p><span class="tag">Scaling laws: from Kaplan to Chinchilla (the budget as a primary dimension)</span> <strong>Kaplan et al.&nbsp;2020</strong>: over decades, the loss follows a power law <span class="math inline">L(N, D) \approx (N_c/N)^{\alpha_N} + (D_c/D)^{\alpha_D} + L_\infty</span> — first reading: enlarging the model helps more than enlarging the data. <strong>Hoffmann et al.&nbsp;2022 (Chinchilla)</strong>: with the compute budget <span class="math inline">C = 6ND</span> <em>fixed</em>, the optimum is reached for <span class="math inline">D \approx 20 N</span> — the models of the Kaplan era were <em>undertrained</em>; GPT-3 (300B tokens for 175B parameters) was “too big” for its data, and a 70B on 1.5T tokens dominates it at equal budget. Method lesson for this module: the budget <span class="math inline">C</span> is not a side constraint, it is the axis along which one <em>designs</em> the model. (The M2 LLMs module, ch.&nbsp;3, revisits these laws in detail; the “energy” angle is in the Optimization and Responsible AI for Sustainability module, ch.&nbsp;1.)</p>
</div>
<div class="sourceCode" id="cb1"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> flops_transformer(N_params, D_tokens, fwd_ratio<span class="op">=</span><span class="fl">2.0</span>, bwd_ratio<span class="op">=</span><span class="fl">4.0</span>):</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (fwd_ratio <span class="op">+</span> bwd_ratio) <span class="op">*</span> N_params <span class="op">*</span> D_tokens</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>C <span class="op">=</span> flops_transformer(<span class="fl">6.7e9</span>, <span class="fl">1e12</span>)                  <span class="co"># LLaMA-7B ~ 6.7B params, 1T tokens</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>C<span class="sc">:.2e}</span><span class="ss"> FLOPs"</span>)                              <span class="co"># 4.02e22</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>peak, mfu <span class="op">=</span> <span class="fl">312e12</span>, <span class="fl">0.45</span>                             <span class="co"># A100 bf16, 45% MFU</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>hours <span class="op">=</span> C <span class="op">/</span> (peak <span class="op">*</span> mfu) <span class="op">/</span> <span class="dv">3600</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>hours<span class="sc">:,.0f}</span><span class="ss"> GPU-hours"</span>)                     <span class="co"># ~80,000 -- see ch. 7 and Touvron et al. 2023</span></span></code></pre></div>
<h2 id="ch2">2. Theoretical complexity of training</h2>
<p>Before stacking GPUs, a theory question: is there a <em>limit</em> to what parallelism can buy? Answer: yes, and it is <em>provable</em>. This chapter is the module’s signature (and the instructor’s — ch.&nbsp;8).</p>
<div class="def">
<p><span class="tag">Definition 2.1 — Decentralized distributed optimization over a graph</span> <span class="math inline">P</span> machines, each with its own convex function <span class="math inline">f_i</span>, connected by a graph <span class="math inline">G</span> (each machine talks only to its neighbors); common goal: <span class="math display">\min_x\; f(x) = \frac{1}{P}\sum_{i=1}^{P} f_i(x).</span> The <strong>execution time</strong> counts two currencies: the number of <em>local</em> iterations (compute: gradients up to the condition number — see the Optimization for AI module, ch.&nbsp;2–3) and the <strong>communication rounds</strong> (one gossip round = mixing the vectors between neighbors). The quality of the network is summarized by the <strong>spectral gap</strong> <span class="math inline">\gamma \in [0,1)</span> of the gossip matrix <span class="math inline">W</span> (second largest eigenvalue in modulus): mixing converges as <span class="math inline">\gamma^t</span> — the closer <span class="math inline">\gamma \to 1</span>, the slower the network reaches consensus.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 2.2 — Lower bounds and optimality (Scaman, Bach, Bubeck, Lee, Massoulié, ICML 2017; statement)</span> For <span class="math inline">f = \frac1P \sum f_i</span> <span class="math inline">\mu</span>-strongly convex and <span class="math inline">L</span>-smooth (<span class="math inline">\kappa = L/\mu</span>), <em>every</em> distributed algorithm (in the sense of def. 2.1) requires a time <span class="math display">T \;=\; \Omega\!\Big(\sqrt{\kappa}\;\cdot\;\frac{1}{\sqrt{1-\gamma}}\Big) \qquad\text{(up to constants, in homogeneous time)},</span> and this order is <strong>attained</strong> by the combination: Nesterov accelerated gradient descent (see the Optimization for AI module, ch.&nbsp;3) + <em>Chebyshev accelerated gossip</em> (replacing <span class="math inline">W</span> by a degree <span class="math inline">m</span> polynomial in <span class="math inline">W</span> chosen to flatten the spectrum over <span class="math inline">[\gamma, 1]</span> — the same trick that accelerates gradients, applied to the graph). The JMLR 2019 version extends the result to the non-strongly convex case: <span class="math inline">\Omega(\sqrt{L/\varepsilon})</span> is compounded by a network factor.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span><em>Sketch of the lower bound (the “adversary” argument).</em> One constructs a family of “local” quadratics at each node, whose solution <span class="math inline">x^\star</span> depends on spread-out information: for machine <span class="math inline">i</span> to learn what machine <span class="math inline">j</span> knew, the information must travel along the graph, and the <em>mixing of the graph</em> imposes <span class="math inline">\Omega(1/\sqrt{1-\gamma})</span> communication rounds (each gossip multiplies the imbalance by only <span class="math inline">\gamma</span>); independently, even sequentially, a quadratic with condition number <span class="math inline">\kappa</span> requires <span class="math inline">\Omega(\sqrt\kappa)</span> gradient accesses (Nesterov’s bound — Optimization for AI module, ch.&nbsp;3). The construction crosses the two obstacles into a quadratic <em>on the product</em> graph × condition number: no algorithm can beat the product of the two bounds. <span class="qed">∎</span></p>
</div>
</div>
<div class="note">
<p><span class="tag">Reading: the two regimes, and why they structure practice</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Regime</th>
<th style="text-align: left;">Condition</th>
<th style="text-align: left;">Dominant time</th>
<th style="text-align: left;">Practical equivalent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>sequential (compute)</strong></td>
<td style="text-align: left;">fast network, small <span class="math inline">\gamma</span> (NVLink, <span class="math inline">\gamma \approx 0{,}1</span>) $</td>
<td style="text-align: left;">qrt{}$: Nesterov reigns a sin</td>
<td style="text-align: left;">gle node, 8 welded GPUs</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>parallel (communication)</strong></td>
<td style="text-align: left;">slow network, <span class="math inline">\gamma \to 1</span> (Ethernet, large clusters) $\</td>
<td style="text-align: left;">sqrt{/(1-)}$: the network caps everything multi</td>
<td style="text-align: left;">-datacenter, federated (see the Emerging ML module, ch.&nbsp;3)</td>
</tr>
</tbody>
</table>
<p>Engineering consequence: <strong>adding machines does not reduce the time below the communication floor</strong>. This is the exact analogue of Amdahl’s law (ch.&nbsp;7) for optimization: the “sequential” part is no longer a program but the geometry of the network. All of ch.&nbsp;4 (all-reduce, compression, overlap) is a war against this <span class="math inline">\sqrt{1/(1-\gamma)}</span>.</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 2.3 — What parallelism <em>can</em> buy: the “finite sum” regime</span> The bound of theorem 2.2 concerns the time to <em>reach</em> an <span class="math inline">\varepsilon</span>-optimal point when the data are <em>partitioned</em> (each <span class="math inline">f_i</span> is opaque). If instead all machines can evaluate the <em>same</em> function (replicated data), parallelism reduces the variance of SGD (mini-batching: Optimization for AI module, ch.&nbsp;5) — but the optimal statistical rate bounds the gain (Dieuleveut et al., see the Optimization for AI module, ch.&nbsp;11). In short: parallelism speeds up <em>compute</em>, never (or marginally) the <em>statistical complexity</em> — a distinction that commercial announcements like to forget.</p>
</div>
<h2 id="ch3">3. Parallelism: data, tensor, pipeline</h2>
<p>Three axes for splitting a training run — often combined (the “3D parallelism” of large systems). For each: the principle, the time decomposition, the communication cost.</p>
<div class="def">
<p><span class="tag">Definition 3.1 — Data parallelism (DP)</span> Each GPU holds a <em>complete</em> copy of the model, processes a different mini-batch (<span class="math inline">B/P</span> examples), then the gradients are averaged by an <strong>all-reduce</strong> (ch.&nbsp;4). Time per step (batch size <span class="math inline">B</span>, forward+backward time <span class="math inline">\tau_\mathrm{calc}(B)</span>, gradient of size <span class="math inline">S</span> bytes): <span class="math display">T_\mathrm{DP} \;=\; \underbrace{\tau_\mathrm{calc}(B/P)}_{\text{compute, divided by } P} \;+\; \underbrace{2\,(P-1)\,\alpha + \tfrac{2(P-1)}{P}\tfrac{S}{b}}_{\text{ring all-reduce (ch. 4)}}.</span> <em>Strong</em> scalability (at fixed <span class="math inline">B</span>): the compute term shrinks, the communication term grows — the balance point defines the effective batch size; hence increasing <span class="math inline">B</span> with the step (LARS: Optimization for AI module, ch.&nbsp;10). This is the default mode of PyTorch DDP.</p>
</div>
<div class="def">
<p><span class="tag">Definition 3.2 — Tensor parallelism (TP — Megatron, Shoeybi et al.&nbsp;2019)</span> One splits the <em>matrices</em> of the model: the layer <span class="math inline">Y = XW_1 W_2</span> (MLP block) is distributed column/row-wise: each GPU holds a slice <span class="math inline">W_1^{[i]}, W_2^{[i]}</span>, computes <span class="math inline">X W_1^{[i]}</span> (no communication: column split), then an <strong>all-reduce</strong> reassembles <span class="math inline">Y = \sum_i XW_1^{[i]} W_2^{[i]}</span>… precisely: the column-then-row split makes the MLP block communication-frugal (1 all-reduce forward + 1 backward per block), attention is split <em>per head</em>. TP lives on the fastest links (intra-node NVLink): every layer pays a communication — this is the “mandatory high bandwidth” parallelism.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 3.3 — Pipeline parallelism: the bubble (proved)</span> <span class="math inline">p</span> stages (consecutive layers on each GPU), <span class="math inline">m</span> micro-batches, each micro-batch costs <span class="math inline">\tau</span> per stage. Under “1F1B” scheduling (one forward pass, one backward pass, staggered), the total time is <span class="math display">T_\mathrm{pipe} \;=\; (m + p - 1)\,\tau, \qquad \eta \;=\; \frac{m}{m + p - 1} \;\xrightarrow[m \to \infty]{}\; 1,</span> where <span class="math inline">\eta</span> is the efficiency; the “bubble” (stage idle time) accounts for <span class="math inline">\frac{p-1}{m+p-1}</span> of the total.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Fill-up: the first micro-batch crosses the <span class="math inline">p</span> stages in <span class="math inline">p\,\tau</span> (stage <span class="math inline">j</span> starts at <span class="math inline">j\tau</span>); afterwards each following micro-batch exits every <span class="math inline">\tau</span> units (the stages work staggered): the <span class="math inline">m</span>-th exits at <span class="math inline">(p + m - 1)\tau</span>. Ideal work (without bubble): each stage processes <span class="math inline">m</span> micro-batches, i.e.&nbsp;<span class="math inline">m\tau</span> busy; efficiency is the ratio <span class="math inline">m\tau / (m+p-1)\tau</span>. Each stage stays idle for <span class="math inline">(p-1)\tau</span> in total (fill-up and drain combined), i.e.&nbsp;a fraction <span class="math inline">(p-1)/(m+p-1)</span> of the total time. <span class="qed">∎</span></p>
</div>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Mode</th>
<th style="text-align: left;">What is split</th>
<th style="text-align: left;">Communication</th>
<th style="text-align: left;">Required hardware</th>
<th style="text-align: left;">Typical use</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">DP (3.1)</td>
<td style="text-align: left;">the batch</td>
<td style="text-align: left;">1 gradient all-reduce per step</td>
<td style="text-align: left;">decent inter-node network (InfiniBand)</td>
<td style="text-align: left;">default, up to hundreds of GPUs</td>
</tr>
<tr class="even">
<td style="text-align: left;">TP (3.2)</td>
<td style="text-align: left;">the matrices</td>
<td style="text-align: left;">all-reduce at <em>every layer</em> (forward+backward)</td>
<td style="text-align: left;">intra-node NVLink (8 GPUs)</td>
<td style="text-align: left;">very wide models (≥ 30B), or huge width</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PP (3.3)</td>
<td style="text-align: left;">the layers</td>
<td style="text-align: left;">point-to-point activations between stages</td>
<td style="text-align: left;">any network, bubble to amortize</td>
<td style="text-align: left;">depth; combined with DP/TP (“3D”)</td>
</tr>
<tr class="even">
<td style="text-align: left;">ZeRO (ch.&nbsp;5)</td>
<td style="text-align: left;">the <em>states</em> (optimizer, gradients, weights)</td>
<td style="text-align: left;">like DP (all-reduce) + on-the-fly gathers</td>
<td style="text-align: left;">same as DP</td>
<td style="text-align: left;">replacing TP when memory, not compute, is the blocker</td>
</tr>
</tbody>
</table>
<div class="note">
<p><span class="tag">Choosing: the practitioner’s decision tree</span> (1) Does the model fit on one GPU with activations? → DP, end of story. (2) The Adam states do not fit → ZeRO-2/3 (ch.&nbsp;5), not TP: less communication. (3) The weights alone do not fit (<span class="math inline">2N</span> bytes &gt; memory) → TP intra-node (8 NVLink GPUs) + PP inter-node + DP on top; tune <span class="math inline">m</span> ≥ 4<span class="math inline">p</span> to keep the bubble under 20% (theorem 3.3). (4) Always measure the MFU (ch.&nbsp;1): below 35%, the hierarchy is poorly chosen.</p>
</div>
<h2 id="ch4">4. Communication: all-reduce and friends</h2>
<p>The real bottleneck of distributed training is almost never compute: it is the <strong>exchange of gradients</strong>. A single operator to truly know — the all-reduce — and two reductions: bandwidth or latency.</p>
<div class="def">
<p><span class="tag">Definition 4.1 — All-reduce</span> <span class="math inline">P</span> machines each hold a vector <span class="math inline">g_i</span> of <span class="math inline">S</span> bytes; all must receive <span class="math inline">\bar g = \frac1P\sum_i g_i</span> (the gradient average in DP). Homogeneous network: latency <span class="math inline">\alpha</span> per message, bandwidth <span class="math inline">b</span> bytes/s.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 4.2 — Ring all-reduce: bandwidth-optimal (proved)</span> Arranging the <span class="math inline">P</span> machines in a ring and cutting the vector into <span class="math inline">P</span> chunks of <span class="math inline">S/P</span> bytes, the all-reduce proceeds in two phases (reduce-scatter then all-gather) of <span class="math inline">P-1</span> steps each: <span class="math display">T_\mathrm{ring} \;=\; 2\,(P-1)\,\alpha \;+\; \frac{2(P-1)}{P}\cdot\frac{S}{b} \;\xrightarrow[P \to \infty]{}\; 2\alpha P + \frac{2S}{b}.</span> The <em>bandwidth</em> term becomes independent of <span class="math inline">P</span> — each machine never sends more than <span class="math inline">\approx 2S/P</span> … that is, at most <span class="math inline">2S(P-1)/P &lt; 2S</span> bytes in total: optimal up to constants.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span><em>Reduce-scatter.</em> At step <span class="math inline">t</span>, machine <span class="math inline">i</span> sends a chunk (already partially summed) to <span class="math inline">i+1</span> and receives from <span class="math inline">i-1</span> a different chunk which it adds to its own: after <span class="math inline">P-1</span> steps, machine <span class="math inline">i</span> holds the <em>complete</em> sum of chunk <span class="math inline">i</span> — each machine has sent <span class="math inline">(P-1)\cdot S/P</span> bytes. <em>All-gather.</em> Same round in broadcast direction: the complete sums circulate, <span class="math inline">(P-1)\cdot S/P</span> bytes sent per machine. Total per machine: <span class="math inline">2(P-1)S/P</span> bytes at rate <span class="math inline">b</span>, that is <span class="math inline">2(P-1)S/(Pb)</span> — and the critical path is indeed the sequence of <span class="math inline">2(P-1)</span> steps of latency <span class="math inline">\alpha</span>. <span class="qed">∎</span></p>
</div>
</div>
<div class="prop">
<p><span class="tag">Proposition 4.3 — Tree all-reduce: latency-optimal</span> In a binary tree: reduction in <span class="math inline">\log_2 P</span> steps then broadcast in <span class="math inline">\log_2 P</span> steps, but each step transmits the <em>entire</em> vector: <span class="math inline">T_\mathrm{tree} = 2\log_2 P\,(\alpha + S/b)</span>. For small <span class="math inline">S</span> (short gradients, many small tensors): the tree wins (latency); for large <span class="math inline">S</span> (LLM gradients): the ring wins (bandwidth). Real libraries (NCCL) choose dynamically — and compose partial rings over the actual topology (intra NVLink, inter IB).</p>
</div>
<div class="note">
<p><span class="tag">Three wars against <span class="math inline">\gamma</span>: overlap, bucketing, compression</span></p>
<ul>
<li><strong>Overlap</strong>: while the GPU computes layer <span class="math inline">k+1</span>, the gradient of layer <span class="math inline">k</span> is already on the network (async by buckets); provided <span class="math inline">T_\mathrm{comm} \leq T_\mathrm{calc}</span>, communication disappears from the critical path — the raison d’être of PyTorch DDP’s “bucketing”.</li>
<li><strong>Gradient compression</strong>: quantizing the gradients (8 bits, even 1 bit) before exchange divides <span class="math inline">S</span> by 2–16; <em>error feedback</em> (compensating the quantization error at the next step) preserves convergence — at the price of a delicate variance/theory trade-off (see the Emerging ML module, ch.&nbsp;2–3 for the federated case, where communication is the limiting factor).</li>
<li><strong>Locality</strong>: reducing the number of communications (local steps, gossip) is exactly the strategy dictated by the bound of ch.&nbsp;2: fewer rounds, but more steps — the optimum of Scaman et al.&nbsp;is a precise point on this frontier.</li>
</ul>
</div>
<h2 id="ch5">5. Memory efficiency: checkpointing, ZeRO, mixed precision</h2>
<div class="thm">
<p><span class="tag">Theorem 5.1 — Activation checkpointing: <span class="math inline">O(\sqrt{L})</span> memory (proved)</span> A network of depth <span class="math inline">L</span>, activations <span class="math inline">a</span> bytes per layer (per token/batch): (i) without precautions, the backward pass requires <span class="math inline">M_\mathrm{full} = L\,a</span> bytes of activations; (ii) by storing only the inputs of a partition into <span class="math inline">\sqrt{L}</span> segments of <span class="math inline">\sqrt{L}</span> layers and recomputing each segment during the backward pass (gradient checkpointing, Chen et al.&nbsp;2016): <span class="math display">M_\mathrm{ckpt} \;\approx\; 2\sqrt{L}\,a \;+\; O(a), \qquad \text{additional cost} \approx +\tfrac{1}{3}\ \text{of time (one extra forward pass per segment).}</span></p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span><em>Memory.</em> We store <span class="math inline">\sqrt L</span> boundary activations; during the backward pass of a segment, we replay its local forward: at most <span class="math inline">\sqrt L</span> simultaneous activations <em>inside</em> the segment (which can itself be recursively checkpointed: the memory/time trade-off can be tuned over the whole range <span class="math inline">[a, La]</span>, see the <span class="math inline">\sqrt</span> “compass”). Total <span class="math inline">\sqrt L + \sqrt L = 2\sqrt L</span> live activations. <em>Time.</em> Each layer is recomputed exactly once more in the forward direction: the forward pass accounts for <span class="math inline">1/3</span> of the total cost (theorem 1.3: 2ND vs 6ND), hence about +33%. <span class="qed">∎</span></p>
</div>
</div>
<div class="def">
<p><span class="tag">Definition 5.2 — ZeRO (Rasley et al.&nbsp;2020): partitioning the states</span> Instead of replicating the training states on every GPU (classical DP: <span class="math inline">16N</span> bytes <em>per GPU</em>), ZeRO <em>partitions</em> them:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Stage</th>
<th style="text-align: left;">What is partitioned</th>
<th style="text-align: left;">Memory/GPU (states)</th>
<th style="text-align: left;">Communication</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ZeRO-1</td>
<td style="text-align: left;">Adam states (<span class="math inline">m, v</span>, masters): 12N</td>
<td style="text-align: left;"><span class="math inline">4N + 12N/P</span></td>
<td style="text-align: left;">= DP</td>
</tr>
<tr class="even">
<td style="text-align: left;">ZeRO-2</td>
<td style="text-align: left;">+ gradients (<span class="math inline">2N</span>)</td>
<td style="text-align: left;"><span class="math inline">4N + 14N/P</span></td>
<td style="text-align: left;">= DP</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ZeRO-3</td>
<td style="text-align: left;">+ weights (<span class="math inline">2N</span>)</td>
<td style="text-align: left;"><span class="math inline">16N/P</span></td>
<td style="text-align: left;">slightly &gt; DP (on-the-fly gathers)</td>
</tr>
</tbody>
</table>
<p>Example 7B on 8 GPUs: ZeRO-3 brings the states down to <span class="math inline">112/8 = 14</span> GB per GPU — the model becomes trainable on a single node, without TP or pipeline bubble (ch.&nbsp;3); DeepSpeed/FSDP implement exactly this continuum.</p>
</div>
<div class="note">
<p><span class="tag">Mixed precision: the “free” compression</span> Computing in bf16 (2 bytes) instead of fp32 (4): half the memory and (on tensor cores) 2–8× the throughput; fp32 is kept for accumulators and master weights (long sums and small updates; historical fp16 additionally required <em>loss scaling</em> — see the Deep Learning module, ch.&nbsp;10). Theorem 1.3 remains valid: we count FLOPs, precision changes the price of a FLOP. <em>Integer</em> quantization (int8/int4) only serves <em>inference</em> — ch.&nbsp;6; its error analysis is in the Optimization and Responsible AI for Sustainability module, ch.&nbsp;3 (proved proposition: error <span class="math inline">\leq \sum_\ell \frac{\Delta_\ell}{2}\prod_{m&gt;\ell}\mathrm{Lip}_m</span>).</p>
</div>
<h2 id="ch6">6. Efficient inference</h2>
<p>At scale (millions of requests), inference dominates the total cost: it deserves its own tools. Four levers, from the simplest to the deepest.</p>
<div class="def">
<p><span class="tag">Definition 6.1 — The memory-bandwidth wall of autoregressive inference</span> Generating one token requires <em>rereading all the weights</em> (2N bytes in bf16) and the <strong>KV cache</strong> — the keys/values of past layers, to be kept for attention: <span class="math display">\text{KV cache} \;=\; 2\;(\text{K and V})\times n_\mathrm{layers}\times n_\mathrm{ctx}\times d_\mathrm{model}\times 2\ \text{bytes} \;=\; 4\,n_\mathrm{layers}\,n_\mathrm{ctx}\,d_\mathrm{model}\ \text{bytes (bf16)}.</span> For 7B (32 layers, <span class="math inline">d = 4096</span>, context 2048): <span class="math inline">4 \times 32 \times 2048 \times 4096 \approx 1{,}1</span> GB — more than some believe, and <em>growing with the context</em>. Peak throughput (one GPU, memory bandwidth <span class="math inline">B_\mathrm{mem}</span>): <span class="math display">\text{tokens/s} \;\lesssim\; \frac{B_\mathrm{mem}}{2N\ \text{bytes}} \qquad (\text{e.g. } 2\,\text{TB/s} \div 14\,\text{GB} \approx 140\ \text{tok/s}).</span> This ceiling — and not FLOPs — governs token-by-token generation (ch.&nbsp;7, roofline); batching fills the compute units without moving the wall.</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 6.2 — PTQ/QAT quantization, pruning, distillation (compact map)</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Lever</th>
<th style="text-align: left;">Idea</th>
<th style="text-align: left;">Memory/speed effect</th>
<th style="text-align: left;">Ref. / cross-reference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">int8/int4 PTQ</td>
<td style="text-align: left;">round the trained weights, calibration only</td>
<td style="text-align: left;">2–8× memory, up to 4× CPU/latency</td>
<td style="text-align: left;">Jacob et al.&nbsp;2018; error bounds: Responsible AI module, ch.&nbsp;3</td>
</tr>
<tr class="even">
<td style="text-align: left;">QAT</td>
<td style="text-align: left;">simulate rounding <em>during</em> training (STE)</td>
<td style="text-align: left;">int8 nearly lossless, int4 on large models</td>
<td style="text-align: left;">Jacob et al.&nbsp;2018</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Structured pruning</td>
<td style="text-align: left;">remove whole heads/channels/layers</td>
<td style="text-align: left;"><em>effective</em> speedup (unlike unstructured)</td>
<td style="text-align: left;">Han et al.&nbsp;2016</td>
</tr>
<tr class="even">
<td style="text-align: left;">Distillation</td>
<td style="text-align: left;">student trained on the teacher’s logits (temperature <span class="math inline">\tau</span>) 1</td>
<td style="text-align: left;">0–100× fewer parameters at similar quality on the target task H</td>
<td style="text-align: left;">inton et al.&nbsp;2015; Responsible AI module, ch.&nbsp;3 (full lab)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Speculative decoding</td>
<td style="text-align: left;">small model proposes, large model verifies <em>in parallel</em> — same distribution in theory</td>
<td style="text-align: left;">2–3× tokens/s without loss</td>
<td style="text-align: left;">Leviathan et al.&nbsp;2023</td>
</tr>
<tr class="even">
<td style="text-align: left;">IO-aware attention</td>
<td style="text-align: left;">rewrite attention for the GPU memory hierarchy (tiling, no fusion)</td>
<td style="text-align: left;">2–4× training/inference on long contexts, <span class="math inline">O(n)</span> memory</td>
<td style="text-align: left;">Dao et al.&nbsp;2022 (FlashAttention, see M2 LLMs ch.&nbsp;2)</td>
</tr>
</tbody>
</table>
</div>
<div class="ex">
<p><span class="tag">Example 6.3 — Comparing honestly: the module’s protocol</span> Any compression claim is verified in four columns: (1) <em>quality metric</em> (perplexity/accuracy — not “it feels better”); (2) <em>latency</em> at p50 and p99 (tail latency pays for cache misses); (3) <em>throughput</em> (aggregate tokens/s); (4) <em>energy per request</em> (J/request — Optimization and Responsible AI for Sustainability module, ch.&nbsp;6). An improvement on three columns with the fourth constant is a result; on a single one, it is a communication angle.</p>
</div>
<h2 id="ch7">7. Real systems: roofline, GPU, and the complete budget of a 7B LLM</h2>
<div class="def">
<p><span class="tag">Definition 7.1 — Roofline model (why a “312 TFLOP/s” GPU delivers 45%)</span> An operation has an <strong>arithmetic intensity</strong> <span class="math inline">I = \mathrm{FLOPs}/\mathrm{bytes\ read+written}</span>. The achievable throughput is <span class="math display">P_\mathrm{achievable} \;=\; \min\big(P_\mathrm{peak},\; B_\mathrm{mem}\cdot I\big)</span> with <span class="math inline">P_\mathrm{peak}</span> the compute throughput and <span class="math inline">B_\mathrm{mem}</span> the memory bandwidth. A huge GEMM (large <span class="math inline">I</span>): compute-bound; an activation, a normalization, a tokenizer, token-by-token generation (low <span class="math inline">I</span>): <em>memory</em>-bound — increasing the GPU’s FLOP/s changes nothing there. The 35–50% MFU of LLMs is precisely the share of layers actually in the compute regime; FlashAttention (prop. 6.2) wins by <em>reducing bytes</em>, not FLOPs — a pure roofline move.</p>
</div>
<div class="thm">
<p><span class="tag">Proposition 7.2 — Amdahl’s law (proved) — the ceiling of all parallelism</span> If a fraction <span class="math inline">s</span> of the work is sequential (inevitably so), the speedup on <span class="math inline">P</span> processors is capped: <span class="math display">A(P) \;=\; \frac{1}{s + (1-s)/P} \;\leq\; \frac{1}{s}.</span></p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Sequential time <span class="math inline">T_1 = T_s + T_p</span> with <span class="math inline">s = T_s/T_1</span>. On <span class="math inline">P</span> processors, the parallel part divides at best by <span class="math inline">P</span>: <span class="math inline">T_P = T_s + T_p/P</span>, hence <span class="math inline">A(P) = T_1/T_P = 1/(s + (1-s)/P)</span>, increasing in <span class="math inline">P</span> and bounded above by <span class="math inline">1/s</span>. <span class="qed">∎</span></p>
</div>
</div>
<div class="ex">
<p><span class="tag">Example 7.3 — Complete case study: training a “7B” LLM (end-to-end computation)</span> Assumptions (close to Touvron et al.&nbsp;2023): <span class="math inline">N = 6{,}7\times10^9</span> parameters, <span class="math inline">D = 10^{12}</span> tokens, A100-80GB bf16 (312 TFLOP/s peak, 2 TB/s HBM, 400 W), one node = 8 GPUs + NVLink.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Question</th>
<th style="text-align: left;">Computation</th>
<th style="text-align: left;">Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Total FLOPs</td>
<td style="text-align: left;"><span class="math inline">6ND = 6 \times 6{,}7\times10^9 \times 10^{12}</span> $4{,}</td>
<td style="text-align: left;">0^{22}$ FLOPs</td>
</tr>
<tr class="even">
<td style="text-align: left;">GPU-hours (45% MFU)</td>
<td style="text-align: left;"><span class="math inline">4\times10^{22} / (312\times10^{12}\times0{,}45) / 3600</span> ≈ 79,</td>
<td style="text-align: left;">000 GPU·h — the paper announces 82,432: the <span class="math inline">6ND</span> rule is accurate to ±5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">States memory</td>
<td style="text-align: left;"><span class="math inline">16\,N = 16 \times 6{,}7\times10^9</span> 107</td>
<td style="text-align: left;">GB &gt; 80 GB: ZeRO-2/3 or TP required (ch.&nbsp;3, 5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Activations (checkpointing, batch 4×2048 tokens)</td>
<td style="text-align: left;"><span class="math inline">\approx 2\sqrt{32}\times(\text{layer act.})</span> a fe</td>
<td style="text-align: left;">w GB/GPU: checkpointing (th. 5.1) makes the batch viable</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Time on 256 GPUs (32 nodes)</td>
<td style="text-align: left;">79,000/256 h</td>
<td style="text-align: left;">≈ 13 days — hence the vital importance of MFU (half the time = 6 days saved)</td>
</tr>
<tr class="even">
<td style="text-align: left;">GPU-only energy</td>
<td style="text-align: left;">79,000 h × 0.4 kW (+ PUE, see the Responsible AI module, ch.&nbsp;6)</td>
<td style="text-align: left;">≈ 32 MWh before PUE; emissions by region: 1.6 t (FR) to ~15 t (world average)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fp16 inference</td>
<td style="text-align: left;">weights <span class="math inline">2N</span> = 13.4 GB; KV cache 2048 ctx ≈ 1.1 GB (def. 6.1)</td>
<td style="text-align: left;">fits on 1 80 GB GPU; throughput ≈ 140 tok/s (memory wall)</td>
</tr>
</tbody>
</table>
<p>This table — reused in exercise 7 — is the module’s typical deliverable: a quantified budget, every line traceable to a theorem of the course (1.3, 5.1, 6.1, 7.1), and an engineer’s conclusion (where to invest the next euro: MFU? memory? quantization?).</p>
</div>
<div class="note">
<p><span class="tag">The system’s keyboard: what to know about a GPU</span> Memory hierarchy (registers → SRAM ~20 MB → HBM ~80 GB → NVLink → IB); each level ~10× slower; winning kernels are those that maximize locality (tiling, fusion — FlashAttention again); “tensor cores” do bf16 GEMMs in 16×16×16 blocks — hence the importance of dimensions that are multiples of powers of 2, and why padding genuinely wastes. For the ML engineer: profile <em>before</em> optimizing (nsight, PyTorch profiler), look at the roofline’s “memory bound” line, and remember that the best code optimizer is a better algorithm (ch.&nbsp;6).</p>
</div>
<h2 id="ch8">8. Research of the instructor</h2>
<p><strong>Team update (2026-2027 catalog):</strong> the APM_52183_EP course unit “Apprentissage profond de la théorie à la pratique” is officially led by Alain Durmus (CMAP, École Polytechnique), with C. Battiloro, P. Bianchi, C. Bonet and B. Bonev on the instructional engineering team. The works presented below are those of Kevin Scaman (CMAP; previously MSR–INRIA), author of the lower-bound results underlying chapter 2: they are cited as classic references of the field, not as the works of the current official team. Three papers to know:</p>
<div class="note">
<p><span class="tag">Optimality of distributed optimization (the heart of ch.&nbsp;2)</span></p>
<ul>
<li>K. Scaman, F. Bach, S. Bubeck, Y. T. Lee, L. Massoulié, <a href="https://arxiv.org/abs/1702.08704">Optimal Algorithms for Smooth and Strongly Convex Distributed Optimization in Networks</a>, ICML 2017 — the paper establishing the lower bound of theorem 2.2 <em>and</em> the optimal algorithm (Nesterov × Chebyshev gossip): the optimal time depends on the product condition number × topology. This is the first complete characterization of the compute/communication trade-off over networks.</li>
<li>K. Scaman, F. Bach, S. Bubeck, L. Massoulié, <a href="http://www.jmlr.org/papers/volume20/19-543/19-543.pdf">Optimal Convergence Rates for Convex Distributed Optimization in Networks</a>, JMLR 2019 — the journal version, extended to the non-strongly convex case: the two regimes of chapter 2 are characterized there optimally.</li>
</ul>
</div>
<div class="note">
<p><span class="tag">Complexity of neural networks: Lipschitz regularity</span></p>
<ul>
<li>A. Virmaux, K. Scaman, <a href="https://arxiv.org/abs/1805.10965">Lipschitz regularity of deep neural networks: analysis and efficient estimation</a>, NeurIPS 2018 — proving that computing <em>exactly</em> the Lipschitz constant of a deep network is NP-hard, and designing the estimator (SeqLip, layer-wise power iteration) that became standard. The link with this module: the propagation bound of prop. 6.2/Responsible AI 3.2 involves precisely these <span class="math inline">\mathrm{Lip}_m</span> constants — and the paper says how far one can (not) compute them; on the robustness side, the Lipschitz constant is the certificate of adversarial guarantees (see the Emerging ML module, ch.&nbsp;1).</li>
</ul>
</div>
<div class="note">
<p><span class="tag">Reading thread</span> L1: read the ICML 2017 focusing on (i) the construction of the lower bound (theorem 2.2 above); L2: re-prove the pipeline bubble (3.3) on paper; L3: profile a mini distributed training run (exercise 8) and empirically verify the ring all-reduce formula 4.2. This is the theory → system → measurement chain that defines this module.</p>
</div>
<h2 id="ex">Exercises</h2>
<ol type="1">
<li><strong>Counting.</strong> Prove the “per token” formula <span class="math inline">24d^2 + 4nd</span> of a transformer block (prop. 1.2), then verify theorem 1.3 on a GPT-2 small (<span class="math inline">N \approx 124</span>M, 12 blocks, <span class="math inline">d = 768</span>): compute <span class="math inline">C</span> for <span class="math inline">D = 3</span>B tokens and compare with a <code>torch.profiler</code> (or <code>flops-profiler</code>) profile within ±10%. <em>Expected solution</em>: <span class="math inline">6ND \approx 2{,}2\times10^{21}</span> FLOPs.</li>
<li><strong>Pipeline bubble.</strong> Re-prove theorem 3.3 (draw the 1F1B Gantt chart for <span class="math inline">p=4</span>, <span class="math inline">m=8</span>). Then: what minimal <span class="math inline">m</span> for an efficiency ≥ 90% with <span class="math inline">p = 16</span> stages? <em>Solution</em>: <span class="math inline">m/(m+15) \geq 0{,}9 \Rightarrow m \geq 135</span>.</li>
<li><strong>All-reduce.</strong> Prove theorem 4.2 on the reduce-scatter (induction on the steps); then plot <span class="math inline">T_\mathrm{ring}</span> and <span class="math inline">T_\mathrm{tree}</span> (prop. 4.3) for <span class="math inline">S = 1</span> GB, <span class="math inline">\alpha = 2\,\mu s</span>, <span class="math inline">b = 25</span> GB/s, <span class="math inline">P = 2 \dots 512</span> on a log scale. Crossover? Which mode for a bf16 LLM-13B gradient? <em>Partial solution</em>: the ring wins as soon as <span class="math inline">S/P \gg \alpha b</span>.</li>
<li><strong>Checkpointing.</strong> A model with 30 blocks, activations 1.2 GB per block, 10 GB of memory available for activations. (a) Verify that full-recompute does not fit; (b) apply theorem 5.1: how many segments, what memory, what time overhead? (c) Generalize: for a memory budget <span class="math inline">M</span>, show that the time overhead is <span class="math inline">\Theta(L\,a/M)</span> recomputed activations — and not <span class="math inline">+\tfrac13</span> — when <span class="math inline">M \ll \sqrt{L}\,a</span>.</li>
<li><strong>Inference memory wall.</strong> (a) Recover the KV cache formula (def. 6.1) for a model with grouped-query attention (GQA: <span class="math inline">g</span> head groups instead of <span class="math inline">h</span>) — what saving? (b) Compute the peak throughput of a 13B fp16 on an A100 (2 TB/s) and on a 1 TB/s GPU; (c) show that int4 <em>exactly</em> doubles this ceiling (and why batching changes nothing there). <em>Solution</em>: (a) factor <span class="math inline">g/h</span>; (b) ≈ 77 then 38 tok/s; (c) in int4, the weights go from <span class="math inline">2N</span> to <span class="math inline">N/2</span> bytes — the wall thus exactly doubles.</li>
<li><strong>Roofline.</strong> A kernel reads <span class="math inline">X \in \mathbb{R}^{m \times n}</span> and <span class="math inline">w \in \mathbb{R}^n</span> and computes <span class="math inline">Xw</span> (<span class="math inline">2mn</span> FLOPs, <span class="math inline">(mn + n + m)\times4</span> bytes). (a) Intensity <span class="math inline">I(m)</span> as <span class="math inline">m \to \infty</span> (at fixed <span class="math inline">n=4096</span>)? (b) On an A100 (312 TFLOP/s, 2 TB/s), for which <span class="math inline">m</span> is the GEMV memory-bound? (c) Deduce why autoregressive decoding is memory-bound and what batching changes there (hint: <span class="math inline">I</span> grows with batch size — but not the wall per token).</li>
<li><strong>Complete budget (the capstone lab).</strong> Take up the table 7.3 with <span class="math inline">N = 13</span>B, <span class="math inline">D = 300</span>B tokens (a “Chinchilla-lite” budget: comment on the <span class="math inline">D/N</span> ratio), on 64 H100 GPUs (≈ 990 TFLOP/s bf16, 40% MFU, 700 W). Compute: FLOPs, GPU-hours, calendar time, states memory (ZeRO-3 over 8 nodes?), energy, FR/world emissions. Conclude with three sentences of architecture recommendation. <em>Partial answers</em>: <span class="math inline">2{,}3\times10^{22}</span> FLOPs; ≈ 16,500 GPU·h; ≈ 11 days; 208 GB of states → ZeRO mandatory.</li>
<li><strong>Paper + measurement.</strong> Choose: Megatron (TP), ZeRO, or FlashAttention. (a) Summarize the mechanism in 10 lines with the module’s formulas; (b) measure an effect on a small real setup (2 GPUs suffice): DP scaling 1→2→4 on a model that fits in memory (verify the <span class="math inline">\frac{2(P-1)}{P}\frac{S}{b}</span> term of theorem 4.2 with <code>torch.distributed</code> and a barrier-timer); (c) present in 10 minutes: key figure, one reproduced number, one limitation. <em>Grid</em>: accuracy of the quoted formulas, honesty of the measurement (error bars!), relevance of the chosen limitation.</li>
</ol>
<h2 id="refs">References</h2>
<ul>
<li>K. Scaman, F. Bach, S. Bubeck, Y. T. Lee, L. Massoulié, <a href="https://arxiv.org/abs/1702.08704">Optimal Algorithms for Smooth and Strongly Convex Distributed Optimization in Networks</a>, ICML 2017.</li>
<li>K. Scaman, F. Bach, S. Bubeck, L. Massoulié, <a href="http://www.jmlr.org/papers/volume20/19-543/19-543.pdf">Optimal Convergence Rates for Convex Distributed Optimization in Networks</a>, JMLR, 2019.</li>
<li>A. Virmaux, K. Scaman, <a href="https://arxiv.org/abs/1805.10965">Lipschitz regularity of deep neural networks: analysis and efficient estimation</a>, NeurIPS 2018.</li>
<li>J. Kaplan et al., <a href="https://arxiv.org/abs/2001.08361">Scaling Laws for Neural Language Models</a>, 2020.</li>
<li>J. Hoffmann et al., <a href="https://arxiv.org/abs/2203.15556">Training Compute-Optimal Large Language Models</a> (Chinchilla), NeurIPS 2022.</li>
<li>H. Touvron et al., <a href="https://arxiv.org/abs/2302.13971">LLaMA: Open and Efficient Foundation Language Models</a>, 2023 — the source of the 82,432 GPU-hours of ch.&nbsp;7.</li>
<li>M. Shoeybi et al., <a href="https://arxiv.org/abs/1909.08053">Megatron-LM: Training Multi-Billion Parameter Language Models Using Model Parallelism</a>, 2019 — tensor parallelism.</li>
<li>Y. Huang et al., <a href="https://arxiv.org/abs/1811.06965">GPipe: Efficient Training of Giant Neural Networks using Pipeline Parallelism</a>, NeurIPS 2019.</li>
<li>S. Rasley et al., <a href="https://arxiv.org/abs/1910.02054">ZeRO: Memory Optimizations Toward Training Trillion Parameter Models</a>, SC 2020.</li>
<li>T. Chen et al., <a href="https://arxiv.org/abs/1604.06174">Training Deep Nets with Sublinear Memory Cost</a> (checkpointing), 2016.</li>
<li>T. Dao, D. Y. Fu, S. Ermon, A. Rudra, C. Ré, <a href="https://arxiv.org/abs/2205.14135">FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness</a>, NeurIPS 2022.</li>
<li>P. Micikevicius et al., <a href="https://arxiv.org/abs/1710.03740">Mixed Precision Training</a>, ICLR 2018.</li>
<li>B. Jacob et al., <a href="https://arxiv.org/abs/1712.05877">Quantization and Training of Neural Networks for Efficient Integer-Arithmetic-Only Inference</a>, CVPR 2018.</li>
<li>S. Han, H. Mao, W. J. Dally, <a href="https://arxiv.org/abs/1510.00149">Deep Compression</a>, ICLR 2016.</li>
<li>G. Hinton, O. Vinyals, J. Dean, <a href="https://arxiv.org/abs/1503.02531">Distilling the Knowledge in a Neural Network</a>, 2015.</li>
<li>Y. Leviathan, M. Kalman, Y. Matias, <a href="https://arxiv.org/abs/2211.17192">Fast Inference from Transformers via Speculative Decoding</a>, ICML 2023.</li>
<li>Z. You et al., <a href="https://arxiv.org/abs/1708.03888">Large Batch Training of Convolutional Networks</a> (LARS), 2017.</li>
<li>Y. Nesterov, <em>Introductory Lectures on Convex Optimization</em>, Kluwer, 2004 — the foundation of ch.&nbsp;2 (see the Optimization for AI module, ch.&nbsp;3).</li>
<li><a href="https://pytorch.org/tutorials/distributed.html">PyTorch Distributed (DDP/FSDP)</a> and <a href="https://developer.nvidia.com/nccl-guide">NCCL</a> — the lab tools.</li>
</ul>

</main>
<footer class="foot"><p><a href="../../index.html">← Master's program</a></p></footer>
<script defer="" src="../../assets/theme.js"></script>




</body></html>