<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Graph Generative Models and Applications</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script>(function(){try{var t=localStorage.getItem("llga-theme");if(t==="dark"||t==="light")document.documentElement.setAttribute("data-theme",t);}catch(e){}})();</script>
<style>
  /* Keep paper.css as visual source of truth; tame Quarto chrome */
  #title-block-header { margin: 0 0 0.5rem; }
  #title-block-header .title { margin: 0 0 0.25rem; font-size: 1.85rem; font-weight: 700; }
  #title-block-header .subtitle { color: var(--soft, #555); margin: 0 0 1rem; font-size: 1.05rem; }
  div.sourceCode { background: var(--code-bg, #f7f7f7); border: 1px solid var(--hair, #e4e4e4); }
  code { background: var(--code-inline-bg, #f4f4f4); }

  /* Light (github) token colors — higher specificity beats paper.css */
  div.sourceCode pre.sourceCode code span.kw, div.sourceCode pre.sourceCode code span.cf, div.sourceCode pre.sourceCode code span.dt, div.sourceCode pre.sourceCode code span.at, div.sourceCode pre.sourceCode code span.bu, div.sourceCode pre.sourceCode code span.pp { color: #d73a49; }
  div.sourceCode pre.sourceCode code span.im, div.sourceCode pre.sourceCode code span.st, div.sourceCode pre.sourceCode code span.ch, div.sourceCode pre.sourceCode code span.ss, div.sourceCode pre.sourceCode code span.vs { color: #032f62; }
  div.sourceCode pre.sourceCode code span.co, div.sourceCode pre.sourceCode code span.an, div.sourceCode pre.sourceCode code span.cv, div.sourceCode pre.sourceCode code span.do, div.sourceCode pre.sourceCode code span.in { color: #6a737d; }
  div.sourceCode pre.sourceCode code span.fu { color: #6f42c1; }
  div.sourceCode pre.sourceCode code span.va { color: #e36209; }
  div.sourceCode pre.sourceCode code span.cn, div.sourceCode pre.sourceCode code span.bn, div.sourceCode pre.sourceCode code span.dv, div.sourceCode pre.sourceCode code span.fl, div.sourceCode pre.sourceCode code span.sc { color: #005cc5; }
  div.sourceCode pre.sourceCode code span.op { color: #24292e; }
  /* Dark mode token colors (github highlight is light-oriented) */
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.kw,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.cf,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.dt,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.at,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.bu,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.pp,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.op { color: #ff7b72; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.im { color: #ff7b72; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.st,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.ch,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.ss,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.vs { color: #a5d6ff; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.cn,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.bn,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.dv,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.fl,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.sc { color: #79c0ff; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.co,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.an,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.cv,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.do,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.in { color: #8b949e; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.va { color: #ffa657; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.fu { color: #d2a8ff; }
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.kw,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.cf,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.dt,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.at,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.bu,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.pp,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.op { color: #ff7b72; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.im { color: #ff7b72; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.st,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.ch,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.ss,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.vs { color: #a5d6ff; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.cn,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.bn,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.dv,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.fl,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.sc { color: #79c0ff; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.co,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.an,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.cv,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.do,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.in { color: #8b949e; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.va { color: #ffa657; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.fu { color: #d2a8ff; }
  }

</style>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../assets/paper.css">
</head>

<body>

<p class="crumb"><a href="../../index.html">MSc&amp;T LLGA · Course notes</a></p>
<main class="paper">

<header id="title-block-header">
<h1 class="title">Graph Generative Models and Applications</h1>
<p class="subtitle">M2 · P2 (brochure) · Year 2 · Period 2</p>

</header>


<h2 id="contents">Contents</h2>
<ul>
<li><a href="#intro">Introduction and overview</a></li>
<li><a href="#ch0">0. Recap: generating graphs in M1</a></li>
<li><a href="#ch1">1. The problem, formalized</a></li>
<li><a href="#ch2">2. Autoregressive models: DeepGMG and GraphRNN in depth</a></li>
<li><a href="#ch3">3. VAEs: GraphVAE, NeVAE and valence constraints</a></li>
<li><a href="#ch4">4. Normalizing flows: change of variables and GraphAF</a></li>
<li><a href="#ch5">5. Discrete diffusion: DiGress in detail</a></li>
<li><a href="#ch6">6. Evaluating rigorously: MMD, validity, FCD</a></li>
<li><a href="#ch7">7. Conditional generation and text-to-graph</a></li>
<li><a href="#ch8">8. Applications: drugs, materials, synthetic networks</a></li>
<li><a href="#ch9">9. Research of the LLGA team</a></li>
<li><a href="#ch10">10. Open problems</a></li>
<li><a href="#ex">Exercises / Labs</a></li>
<li><a href="#refs">References</a></li>
</ul>
<h2 id="intro">Introduction and overview</h2>
<table class="caption-top">
<tbody>
<tr class="odd">
<td style="text-align: left;">Module</td>
<td style="text-align: left;">Graph Generative Models and Applications</td>
</tr>
<tr class="even">
<td style="text-align: left;">Code</td>
<td style="text-align: left;">M2 · P2 (brochure) — official code not published (course description not published)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Team and workload</td>
<td style="text-align: left;">Instructor: master’s team (LLGA / DaSciM) · ~24 h · the M2 extension of the “graph generation” chapter of the M1 core course: autoregressive models, VAEs, flows and discrete diffusion taken all the way to the theorems, rigorous distributional evaluation, conditional generation and text-to-graph, molecule/material/synthetic-network applications — and the research of the LLGA team.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Status in the program</td>
<td style="text-align: left;"><span class="badge m2">M2</span><span class="badge position">Outside the recommended track</span> · M2 program being finalized</td>
</tr>
</tbody>
</table>
<p><strong>Audience</strong>: a graphs / chemistry / networks engineer who wants to <em>generate</em> valid structures. <strong>Empirical first</strong>: a generated molecule with impossible valence; “good” MMD on degrees but wrong motifs — then we name GraphRNN, GraphVAE, flows, DiGress.</p>
<p>Generative brick of relational ML: sequel to the M1 generation chapter.</p>
<h3 id="what-you-will-be-able-to-do">What you will be able to do</h3>
<ul>
<li>Formalize graph generation as a distributional problem (a distribution over a combinatorial space);</li>
<li>Explain the DeepGMG and GraphRNN autoregressive models in detail, from the stopping decision to the enumeration order;</li>
<li>Derive the ELBO of graph VAEs and handle valence constraints (GraphVAE, NeVAE);</li>
<li>Apply the change of variables of normalizing flows to mixed discrete/continuous variables (GraphAF);</li>
<li>Unroll the discrete diffusion of DiGress: noising processes, masking orders, denoising network;</li>
<li>Evaluate a generation rigorously: MMD on graph statistics, chemical validity, FCD;</li>
<li>Condition the generation (target properties) and generate graphs from text;</li>
<li>Situate the real applications — drugs, materials, networks — and read the recent research of the LLGA team.</li>
</ul>
<h3 id="official-objectives-and-syllabus">Official objectives and syllabus</h3>
<p><strong>Official course description not published (S3/S4 catalog empty)</strong>: as of the start of the 2026 academic year, the “LLGA 2 – Semestre 3” and “LLGA 2 – Semestre 4” tracks of the 2026-2027 SynapseS catalog still list no courses, and the master’s wiki indicates that the detailed M2 program is “under development” (period&nbsp;2: “to be completed soon”). The program below therefore reflects the master’s brochure (period&nbsp;2), with an indicative volume of ~24&nbsp;h; these course materials are calibrated to that volume, i.e.&nbsp;about two hours of work per chapter, labs included. The following table maps each brochure theme to the course sections; the materials’ own additions are marked “going beyond the syllabus”.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Brochure theme</th>
<th style="text-align: left;">Course section covering it</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">The graph generation problem, formalized</td>
<td style="text-align: left;">ch.&nbsp;1 (graph space, sampling, combinatorial complexity)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Autoregressive models</td>
<td style="text-align: left;">ch.&nbsp;2 (DeepGMG, GraphRNN in depth)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Graph VAEs</td>
<td style="text-align: left;">ch.&nbsp;3 (GraphVAE, NeVAE, valence constraints)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Normalizing flows</td>
<td style="text-align: left;">ch.&nbsp;4 (change of variables, GraphAF)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Discrete diffusion</td>
<td style="text-align: left;">ch.&nbsp;5 (DiGress in detail)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rigorous distributional evaluation</td>
<td style="text-align: left;">ch.&nbsp;6 (MMD, validity, FCD)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Conditional generation and text-to-graph</td>
<td style="text-align: left;">ch.&nbsp;7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Applications: molecules, materials, synthetic networks</td>
<td style="text-align: left;">ch.&nbsp;8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Research of the LLGA team</td>
<td style="text-align: left;">ch.&nbsp;9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Going beyond the syllabus — recap of the “generation” chapter of the M1 core course</td>
<td style="text-align: left;">ch.&nbsp;0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Going beyond the syllabus — open problems and internship topics</td>
<td style="text-align: left;">ch.&nbsp;10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Going beyond the syllabus — labs (GraphRNN, molecule VAE, MMD evaluation)</td>
<td style="text-align: left;"><a href="#">Exercises / Labs</a></td>
</tr>
</tbody>
</table>
<h3 id="where-this-course-fits-in-the-program">Where this course fits in the program</h3>
<p>An M2 module offered in period 2, outside the recommended track, with an explicitly research flavor: taught by the LLGA / DaSciM team, it prepares for internships and PhDs on the generation of discrete structures. <strong>Prerequisites</strong>: chapter 9 of <a href="../m1p2-graph-ml/index.html">Graph Machine and Deep Learning for Generative AI</a> (first encounter with graph generation, revisited in ch.&nbsp;0); the GNN architectures of <a href="../m2-advanced-gnn/index.html">Advanced Graph Neural Networks</a>, which serve as denoisers and encoders everywhere here; and the optimal transport of <a href="../m1p2-optimal-transport/index.html">Computational Optimal Transport for ML and Fairness</a>, whose Gromov-Wasserstein distance allows graphs to be compared and underlies evaluation metrics.</p>
<p><strong>Downstream</strong>: the module leads to the biological and industrial applications of generation (ch.&nbsp;8) and to the open problems (ch.&nbsp;10) — as many gateways to the research-oriented internship and, beyond, to the PhD; it also feeds the “LLMs × graphs” crossroads developed in <a href="../m2-advanced-topics-llms/index.html">Advanced Topics in Large Language Models</a> (ch.&nbsp;7).</p>
<h3 id="course-outline">Course outline</h3>
<ul>
<li><strong>Recap: generating graphs in M1</strong> — what was already covered in M1: introductive versions of graph VAEs and GANs, and the vocabulary of the problem.</li>
<li><strong>The problem, formalized</strong> — graph space, sampling, combinatorial complexity: why generating graphs is hard.</li>
<li><strong>Autoregressive models: DeepGMG and GraphRNN in depth</strong> — building the graph sequentially, decision by decision.</li>
<li><strong>VAEs: GraphVAE, NeVAE and valence constraints</strong> — the graph encoder-decoder and the art of obtaining valid molecules.</li>
<li><strong>Normalizing flows: change of variables and GraphAF</strong> — one-step generation by dense invertible flows, on mixed variables.</li>
<li><strong>Discrete diffusion: DiGress in detail</strong> — noising then denoising edges and attributes: the state of the art explained step by step.</li>
<li><strong>Evaluating rigorously: MMD, validity, FCD</strong> — why visual quality is not enough, and which distributional metrics to use.</li>
<li><strong>Conditional generation and text-to-graph</strong> — targeting a property, and generating from a natural-language description.</li>
<li><strong>Applications: drugs, materials, synthetic networks</strong> — three industrial and scientific territories examined seriously.</li>
<li><strong>Research of the LLGA team</strong> — the lab’s recent contributions, presented by their authors.</li>
<li><strong>Open problems</strong> — what the community does not yet know how to do, and the internship topics hiding there.</li>
<li><strong>Exercises / Labs</strong> — implement GraphRNN, train a small molecule VAE, evaluate by MMD.</li>
<li><strong>References</strong> — the reference papers of each family, to be read in the original.</li>
</ul>
<h3 id="how-to-study-this-module">How to study this module</h3>
<ul>
<li>Read the indicated papers <em>after</em> the corresponding chapter: they are written for specialists, the chapter gives you the keys to read them.</li>
<li>Implement GraphRNN in a toy version (graphs with fewer than 20 nodes) before moving to frameworks: the sequential logic is easier to see there.</li>
<li>Always check the chemical validity of the molecules generated in the labs: it is the permanent reminder that combinatorics is not an image.</li>
<li>For each model family, fill in a small “sampling speed / quality / failure mode” table: it is the reading grid of the field.</li>
<li>Take notes on ch.&nbsp;9 (the team’s research): it is the best preparation for research internship interviews.</li>
</ul>
<div class="note">
<p><span class="tag">The LLGA perspective</span> “Large Language Models, Graphs and Applications”: this module is the heart of the graph side of that motto. Graph generation is the place where molecules, materials and networks meet foundation models — the text-to-graph of ch.&nbsp;7 being the exact junction point between LLMs and discrete structures. For students aiming at research (the master’s research internship, a PhD) as for those aiming at the life-science and materials industries, this is where the LLGA master is furthest ahead of neighboring programs.</p>
</div>
<div class="note">
<p><span class="tag">Note Extrapolons</span> Place in the 2-year path: concrete failure modes first, then names and theorems.</p>
</div>
<h2 id="ch0">0. Recap: generating graphs in M1</h2>
<div class="recap">
<div class="recap-title">
<p>Recap of the Graph ML module (M1 P2, ch.&nbsp;9) — what is assumed known</p>
</div>
<ul>
<li><strong>The problem</strong>: sample <span class="math inline">G \sim p_\theta(G)</span> where <span class="math inline">p</span> is learned on a family of graphs (active molecules, networks…), with three specific difficulties: variable size, <em>discrete</em> outputs, a space quotiented by isomorphism;</li>
<li><strong>The limiting model</strong>: graphons <span class="math inline">W : [0,1]^2 \to [0,1]</span> and the Aldous-Hoover theorem — every sequence of <em>exchangeable</em> graphs admits a limiting graphon in the sense of the cut metric; estimation by step functions;</li>
<li><strong>Classical random models</strong>: Erdős-Rényi <span class="math inline">G(n,p)</span> (iid edges, degrees <span class="math inline">\sim \mathrm{Bin}(n-1,p)</span>, connectivity thresholds) and the SBM: <span class="math inline">P(A_{ij}=1 \mid z_i=a, z_j=b) = B_{ab}</span>, likelihood, EM/MCMC inference, the Kesten-Stigum threshold;</li>
<li><strong>An overview of the deep families</strong>: GraphVAE (one-shot decoder), NeVAE (sequential decoding constrained by valence), GraphRNN (sequentialization by adjacency rows, BFS orders), DiGress (categorical noising <span class="math inline">q(X_t\|X_{t-1}) = \mathrm{Cat}(Q_t X_{t-1})</span>, closed-form Bayesian denoising);</li>
<li><strong>First metrics</strong>: validity/uniqueness/novelty, MMD on histograms, FCD — the analogue of the image FID (cf.&nbsp;Multimodal GenAI module ch.&nbsp;8);</li>
<li><strong>The GNN foundation</strong>: message passing, MPNN, GIN and the 1-WL bound (cf.&nbsp;Advanced GNN module ch.&nbsp;1) — the <em>encoder</em> of all the models in this module.</li>
</ul>
</div>
<div class="note">
<p><span class="tag">The module’s approach</span> The M1 <em>told the story of</em> graph generation: each family was presented there with its idea and one equation. The M2 <em>proves it</em>: exact sampling conditions, changes of variables, closed-form posteriors, evaluation biases — then goes beyond the M1 on three axes: (i) <strong>flows</strong> (ch.&nbsp;4, absent from the M1); (ii) <strong>distributional evaluation</strong> pushed to its paradoxes (ch.&nbsp;6); (iii) <strong>conditional generation and text-to-graph</strong> with LLMs (ch.&nbsp;7), the 2026 frontier. The control of generators (hard constraints, guidance) is covered in detail in the <em>Control in Generative AI</em> module (M2, ch.&nbsp;8) — we lay here the foundations it relies on.</p>
</div>
<h2 id="ch1">1. The problem, formalized</h2>
<p>Concrete scene: a generator that produces statistically close… and chemically invalid graphs. This chapter fixes the space of graphs.</p>
<div class="note">
<p><span class="tag">What breaks</span> Ignoring permutation invariance; evaluating without motifs / orbits; masking valence too late.</p>
</div>
<div class="def">
<p><span class="tag">Definition 1.1 — The labeled graph space and its measure</span> A labeled graph is a triple <span class="math inline">G = (X, E, n)</span>: <span class="math inline">n</span> nodes, node types <span class="math inline">X \in \mathcal{X}^n</span> (atoms, tags, features), edge types <span class="math inline">E \in \mathcal{E}^{n \times n}</span> (single/double/triple bonds…). For fixed <span class="math inline">n</span>, the space <span class="math inline">\mathcal{G}_n = \mathcal{X}^n \times \mathcal{E}^{n\times n}</span> is <em>finite</em> (cardinality <span class="math inline">\sim \|\mathcal{E}\|^{n^2}</span>) but gigantic: with <span class="math inline">\|\mathcal{E}\| = 4</span> and <span class="math inline">n = 30</span> atoms, <span class="math inline">4^{900} \approx 10^{542}</span> adjacencies — hence the need for a strong structural prior. The total space is the disjoint union <span class="math inline">\mathcal{G} = \bigsqcup_{n \geq 1} \mathcal{G}_n</span>; a law <span class="math inline">p</span> on <span class="math inline">\mathcal{G}</span> mixes a law on size <span class="math inline">p(n)</span> and conditional laws <span class="math inline">p(G \mid n)</span>. <em>Generating</em> = being able to sample from <span class="math inline">p_\theta \approx p_\star</span>, the empirical law of a dataset <span class="math inline">\mathcal{D} = \{G_1, \dots, G_N\}</span>.</p>
</div>
<div class="def">
<p><span class="tag">Definition 1.2 — Exchangeability (in-depth recap)</span> A law <span class="math inline">p</span> on <span class="math inline">\mathcal{G}</span> is <strong>exchangeable</strong> if for every permutation <span class="math inline">\pi</span> of <span class="math inline">\{1..n\}</span>: <span class="math display">p\big((X_{\pi(1)},\dots,X_{\pi(n)}),\ (\pi E \pi^\top),\ n\big) = p(X, E, n).</span> The Aldous-Hoover theorem — precisely: <strong>Aldous (1981) and Hoover (1979)</strong>, see Lovász (2012) — states that exchangeable laws are exactly those representable by a graphon: <span class="math inline">x_i \sim \mathcal{U}([0,1])</span>, <span class="math inline">A_{ij} \sim \mathrm{Bern}(W(x_i,x_j))</span>. Practical consequence: a <em>correct</em> generator must be permutation-invariant, either <em>by construction</em> (one-shot VAEs, diffusion: exchangeable GNN architectures), or <em>on average</em> (autoregressive models: randomize the construction order, cf.&nbsp;ch.&nbsp;2).</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 1.3 — Aldous-Hoover, forward direction (guided sketch)</span> If <span class="math inline">p</span> is exchangeable, there exists <span class="math inline">W</span> such that <span class="math inline">p</span> is the law of the graphon model.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Exchangeability <span class="math inline">\Rightarrow</span> the law of the adjacencies is invariant under every subgroup of permutations; the <em>De Finetti representation</em> for exchangeable arrays (extension of the De Finetti theorem from exchangeable sequences to symmetric matrices) then gives the existence of iid uniform latent variables <span class="math inline">(x_i)</span> and a conditioning measurable function <span class="math inline">W</span>: conditionally on the <span class="math inline">x_i</span>, the <span class="math inline">A_{ij}</span> are independent with laws <span class="math inline">W(x_i, x_j)</span>. The idea of De Finetti’s proof (sequence case): the empirical frequency <span class="math inline">\hat F_k = \frac{1}{k}\sum_{i \leq k} \mathbf{1}[S_i]</span> of an event converges a.s. to a random variable <span class="math inline">F</span> (bounded martingale, martingale convergence theorem — cf.&nbsp;Refresher Statistics module); exchangeability forces conditional independence given <span class="math inline">F</span>, and <span class="math inline">F</span> plays the role of the latent parameter. The symmetric-array case adds the product structure <span class="math inline">[0,1]^2</span>. <span class="qed">∎</span></p>
</div>
</div>
<div class="thm">
<p><span class="tag">Theorem 1.4 — Counting to generate: subgraph counting determines the graphon</span> Two graphons <span class="math inline">W, W'</span> are equal in cut metric <span class="math inline">\delta_\square</span> <em>iff</em> they have the same homomorphism densities <span class="math inline">t(F, W)</span> for all graphs <span class="math inline">F</span>: <span class="math display">t(F, W) = \int_{[0,1]^{\|F\|}} \prod_{(i,j) \in E(F)} W(x_i, x_j)\, dx_1 \dots dx_{\|F\|}.</span> Now <span class="math inline">t(F, W)</span> is estimated on a large graph by the <em>subgraph density</em>: <span class="math inline">t(F, G_n) \to t(F, W)</span> a.s. (counting lemma). This is the theoretical foundation of ch.&nbsp;6: comparing generators by their <em>motif</em> statistics (triangles, paths, stars) amounts to comparing their limiting graphons — orbit-MMD evaluation is a finite, empirical version of this theorem.</p>
</div>
<div class="note">
<p><span class="tag">The four families, one reading grid</span> Each family answers the three questions differently: (i) <em>exchangeability</em>? (ii) <em>exact likelihood or bound</em>? (iii) <em>hard constraints</em> possible?</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Family</th>
<th style="text-align: left;">Exchangeability</th>
<th><span class="math inline">p_\theta</span> in closed form? Ha</th>
<th style="text-align: left;">rd constraints</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Autoregressive (ch.&nbsp;2)</td>
<td style="text-align: left;">via the order (BFS, random)</td>
<td>yes, product of the steps</td>
<td style="text-align: left;">natural (step masks)</td>
</tr>
<tr class="even">
<td style="text-align: left;">VAE (ch.&nbsp;3)</td>
<td style="text-align: left;">by architecture</td>
<td>no (ELBO only)</td>
<td style="text-align: left;">post-processing or dedicated heads</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Flows (ch.&nbsp;4)</td>
<td style="text-align: left;">autoregressive or by architecture</td>
<td>yes, exact</td>
<td style="text-align: left;">flow masks</td>
</tr>
<tr class="even">
<td style="text-align: left;">Discrete diffusion (ch.&nbsp;5)</td>
<td style="text-align: left;">by architecture</td>
<td>no (variational ELBO)</td>
<td style="text-align: left;">guidance + auxiliary losses</td>
</tr>
</tbody>
</table>
<p>This grid is the through-line of the module; it closes in ch.&nbsp;10 (open problems).</p>
</div>
<h2 id="ch2">2. Autoregressive models: DeepGMG and GraphRNN in depth</h2>
<p>The founding idea (You et al., 2018; Li et al., 2018): <em>sequentialize</em> the construction — a graph becomes a trajectory of local decisions (add a node, add an edge, choose a type), and all the machinery of sequential models (RNNs, then transformers) applies. Two competing formalizations: <strong>by nodes</strong> (GraphRNN) and <strong>by neighborhood expansion</strong> (DeepGMG).</p>
<div class="thm">
<p><span class="tag">Theorem 2.1 — DeepGMG (Li et al., ICML 2018): factorization by graph states</span> Let <span class="math inline">G_t</span> denote the partial graph after <span class="math inline">t</span> decisions. The construction chain defines the factorization <span class="math display">p_\theta(G) = \prod_{t=1}^{T} p_\theta(a_t \mid G_{t-1}),</span> where <span class="math inline">a_t \in \{\textsf{ADDNODE}(x),\ \textsf{ADDEDGE}(e),\ \textsf{STOP}\}</span>, each decision being a categorical parameterized by a <em>graph network</em>: <span class="math display">h_{G_{t-1}} = \mathrm{GN}\big(\{h_v\}, \{h_{uv}\}, u\big) \quad\text{(node, edge, and global states)},</span> and the heads <span class="math inline">p(a_t \mid h_{G_{t-1}}, h_v)</span> read these states — e.g.&nbsp;<span class="math inline">p(\textsf{ADDEDGE}(u,v)) = \mathrm{softmax}\big(f_e(h_u \oplus h_v)\big)</span>. Three technical points: (i) training follows a <em>canonical order</em> of the data (a fixed arbitrary order, e.g.&nbsp;that of the file); (ii) the likelihood is <em>exact</em> — no variational bound; (iii) the model is exchangeable only <em>on average</em>: if one trains on several random orders (<span class="math inline">\mathbb{E}_{\pi}[p(G \mid \pi)]</span>), the marginal law is exchangeable.</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 2.2 — GraphRNN (You et al., ICML 2018): two nested RNNs, proven complexity</span> With the BFS order of the nodes, the graph is the sequence of adjacency rows <span class="math inline">S^i = (A_{i,1}, \dots, A_{i,i-1}) \in \{0,1\}^{i-1}</span>: <span class="math display">h_i = \mathrm{RNN}_{node}(h_{i-1}, s_i), \qquad P(S^i \mid h_i) = \prod_{j \&lt; i} \mathrm{Bern}\big(\mathrm{RNN}_{edge}(h_i, s^i_{\&lt;j})\big).</span></p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span><strong>Complexity.</strong> The edge level emits <span class="math inline">i-1</span> bits for node <span class="math inline">i</span>, each in one RNN step: <span class="math inline">\sum_{i \leq n} (i-1) = \Theta(n^2)</span> steps in total, each in <span class="math inline">\mathcal{O}(1)</span> with respect to <span class="math inline">n</span> (the state <span class="math inline">h_i</span> has fixed size); the node level adds <span class="math inline">\Theta(n)</span> steps. Training cost per graph: <span class="math inline">\Theta(n^2)</span> RNN steps versus <span class="math inline">\Theta(n^3)</span> for a decoder that would recompute the whole history; memory <span class="math inline">\mathcal{O}(n)</span> states. <strong>Why BFS?</strong> an arbitrary order makes the prefix <span class="math inline">S^1..S^k</span> depend on the numbering; the BFS order depends only on the <em>explored neighborhood</em>: two BFS numberings of the same graph differ only by <em>intra-level</em> permutations, and the prefixes remain identical in law — exchangeability is approximate, not exact; aromatic rings “closed at the end of the order” remain the textbook failure case. <span class="qed">∎</span></p>
</div>
</div>
<div class="note">
<p><span class="tag">Modern variants: when the “token” becomes a node</span> Autoregressive graph generation has been absorbed by the LLM wave: (i) <strong>textual representation</strong> — generate SMILES (a linearized molecule) with an LLM: this is today’s industrial production (ch.&nbsp;7); (ii) <strong>graph tokenization</strong> — define a vocabulary of fragments (scaffolds, synthesis motifs) and generate the graph fragment by fragment, the generalization of <em>junction trees</em> (Jin et al., 2018: decompose the molecule into a tree of chemically valid fragments, generate the tree — structural validity guaranteed by construction); (iii) <strong>action-by-action</strong> — the chemical agent ChemCrow (Bran et al., 2023) orchestrates <em>tools</em> (synthesis NMR, docking) rather than atoms: the “local decision” becomes a tool call — cf.&nbsp;LLMs module (M2) ch.&nbsp;8 for the agent layer. The loop is closed: GraphRNN sequentialized the graph for an RNN; LLMs industrialize the same sequentialization.</p>
</div>
<ul>
<li><strong>Strengths</strong> of autoregressive models: exact likelihood, sequential sampling with natural stopping, local constraints injectable at every step (ch.&nbsp;8 of the Control in Generative AI module);</li>
<li><strong>Limits</strong>: <span class="math inline">\Theta(n^2)</span> cost in steps, exposure to the order, errors that propagate (a wrong node-type choice contaminates everything after it); diffusion (ch.&nbsp;5) answers exactly these last two limits.</li>
</ul>
<h2 id="ch3">3. VAEs: GraphVAE, NeVAE and valence constraints</h2>
<h3 id="the-graph-vae-elbo-and-one-shot-decoder">3.1. The graph VAE: ELBO and one-shot decoder</h3>
<div class="thm">
<p><span class="tag">Theorem 3.1 — GraphVAE (Simonovsky &amp; Komodakis, 2018) and the matching problem</span> GNN encoder <span class="math inline">q_\phi(z \mid G) = \mathcal{N}(\mu_\phi(G), \mathrm{diag}(\sigma^2_\phi(G)))</span>, <em>one-shot</em> decoder: <span class="math inline">p_\theta(G \mid z) = p(n \mid z) \cdot p_\theta(\hat A, \hat X \mid z)</span> with continuous adjacency <span class="math inline">\hat A \in [0,1]^{n\times n}</span> (independent sigmoids) and features <span class="math inline">\hat X</span>. The likelihood is written against the data via a <strong>correspondence matrix</strong> (Hungarian matching, an <span class="math inline">\mathcal{O}(n^3)</span> algorithm): the decoder does not emit in a canonical order, its nodes must be matched to those of <span class="math inline">G</span> — the price of one-shot decoding. The ELBO: <span class="math display">\log p_\theta(G) \geq \mathbb{E}_{q_\phi(z \mid G)}[\log p_\theta(G \mid z)] - \mathrm{KL}\big(q_\phi(z\mid G)\,\\|\,\mathcal{N}(0, I)\big),</span> proven in the M1 (Multimodal GenAI module ch.&nbsp;1); here the reconstruction term is not a simple sum of Bernoullis because of the matching — it is <em>lower-bounded</em> by the optimal matching (sum of the log-probabilities over the retained pairs), which preserves the validity of the ELBO.</p>
</div>
<h3 id="nevae-in-detail-valence-as-the-architect">3.2. NeVAE in detail: valence as the architect</h3>
<div class="thm">
<p><span class="tag">Theorem 3.2 — NeVAE (Samanta et al., AAAI 2019): granular VAE with constrained decoding</span> Four ingredients, to be known precisely:</p>
<ol type="1">
<li><strong>Sparse encoder</strong>: one embedding per atom <span class="math inline">z_i \in \mathbb{R}^d</span>, MPNN messages between <em>neighboring</em> atoms only — <span class="math inline">\mathcal{O}(n + m)</span> memory instead of <span class="math inline">\mathcal{O}(n^2)</span>: the molecular graph is sparse, exploiting this divides memory by <span class="math inline">\Theta(n)</span>; the posterior law is a product of local Gaussians <span class="math inline">q(z_i \mid G) = \mathcal{N}(\mu_i, \sigma_i^2)</span>;</li>
<li><strong>Remaining valence</strong> as state: let <span class="math inline">r_v^{(t)} \in \{0, \dots, 4\}</span> denote the <em>available</em> valence of atom <span class="math inline">v</span> at step <span class="math inline">t</span> (4 for C, 2 for O, 1 for H…). Each decoding head is <em>conditioned</em> on this state: <span class="math display">p\big(\text{bond }(u, v, b)\big) = \mathrm{softmax}\big(f\,[\,z_u, z_v, r_u, r_v\,]\big),</span> where the mask forbids any <span class="math inline">b</span> with <span class="math inline">b \&gt; r_u</span> or <span class="math inline">b \&gt; r_v</span> — a saturated carbon (r = 0) can <em>no longer</em> receive a bond, by construction;</li>
<li><strong>Aromaticity</strong>: aromatic rings are not alternating single/double bonds but a dedicated type; specific heads sample ring membership — otherwise the model massively underestimates benzene cores;</li>
<li><strong>Noise correction</strong>: during training, if a sampled bond violates valence, it is resampled among the legal ones <em>before</em> the loss is computed — the penalty on forbidden bonds is softened and the gradient does not break; measured result: chemical validity &gt; 90% <em>without</em> RDKit sanitization, versus a few percent for unconstrained GraphVAE.</li>
</ol>
</div>
<div class="prop">
<p><span class="tag">Proposition 3.3 — Why is the valence mask a good statistical idea?</span> Masking the forbidden outputs amounts to replacing <span class="math inline">p_\theta</span> by its <em>renormalization on the legal subset</em> <span class="math inline">\mathcal{L}</span>: <span class="math display">\tilde p_\theta(y \mid x) = \frac{p_\theta(y \mid x)\,\mathbf{1}[y \in \mathcal{L}]} {\sum_{y' \in \mathcal{L}} p_\theta(y' \mid x)}.</span></p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Two effects. (i) <em>Support correction</em>: the forbidden mass (typically <span class="math inline">\varepsilon</span> per step, but <span class="math inline">1 - (1-\varepsilon)^T \to 1</span> over <span class="math inline">T</span> steps) is redistributed; the support of <span class="math inline">\tilde p</span> is included in the valid molecules <em>by construction</em>, which no post-processing guarantees (post-processing <em>repairs</em>, it does not guarantee that the repaired law is close to the target law). (ii) <em>Bias</em>: if the model estimates the <em>ratios</em> of the legal options well, <span class="math inline">\tilde p_\theta \approx p_\star(\cdot \mid \mathcal{L})</span> — now molecular datasets are (almost) entirely in <span class="math inline">\mathcal{L}</span>, so <span class="math inline">p_\star(\cdot \mid \mathcal{L}) \approx p_\star</span>: the mask is nearly free in bias and massive in validity gain. The same analysis holds for all the decoding masks of the Control in Generative AI module (ch.&nbsp;3). <span class="qed">∎</span></p>
</div>
</div>
<div class="note">
<p><span class="tag">From GraphVAE to NeVAE: the general lesson</span> Injecting domain knowledge <em>into the architecture</em> (valence, aromaticity) beats post-processing; this lesson will repeat: DiGress auxiliary losses (ch.&nbsp;5), chemically valid fragments of junction trees (ch.&nbsp;2), valence constraints of the Control module (ch.&nbsp;8). Trade-off: the model becomes specific to one domain (organic chemistry) — for general graphs (social networks), the “hard constraint” analogue does not exist, and that is precisely one of the open problems of ch.&nbsp;10.</p>
</div>
<div class="ex">
<p><span class="tag">Example 3.4 — NeVAE decoder step by step (by hand)</span> Prefix: C—C—O (remaining valences C: 3, C: 2, O: 1). Next step: choose the next atom and its bond. Heads: <span class="math inline">p(\text{atom}) = (\text{C}: 0.6,\ \text{O}: 0.3,\ \text{N}: 0.1)</span>; suppose C is drawn, attached to the O (the only usable <span class="math inline">r_v \neq 0</span> with high probability); bond masked to <span class="math inline">\{0, 1\}</span> (O has <span class="math inline">r=1</span>); after fixing C—O, the O has <span class="math inline">r = 0</span> — it is <em>closed</em> forever. To be written as a table over 4-5 steps: each row = a draw, the applied mask, the new <span class="math inline">r_v</span>; exercise 2 schedules it.</p>
</div>
<h2 id="ch4">4. Normalizing flows: change of variables and GraphAF</h2>
<h3 id="the-change-of-variables-proven">4.1. The change of variables, proven</h3>
<div class="thm">
<p><span class="tag">Theorem 4.1 — Additive/affine flows: exact likelihood</span> Let <span class="math inline">f_\theta : \mathbb{R}^d \to \mathbb{R}^d</span> be a diffeomorphism (a differentiable bijection with differentiable inverse) and <span class="math inline">z \sim p_Z</span> (e.g.&nbsp;<span class="math inline">\mathcal{N}(0, I)</span>). Then <span class="math inline">y = f_\theta(z)</span> has density <span class="math display">p_Y(y) = p_Z\big(f_\theta^{-1}(y)\big)\,\Big\|\det \frac{\partial f_\theta^{-1}}{\partial y}(y)\Big\| = p_Z(z)\,\Big\|\det \frac{\partial f_\theta}{\partial z}(z)\Big\|^{-1}.</span></p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>First point: for a diffeomorphism <span class="math inline">f</span> and a measurable set <span class="math inline">B</span>, <span class="math display">\mathbb{P}(Y \in B) = \mathbb{P}(z \in f^{-1}(B)) = \int_{f^{-1}(B)} p_Z(z)\,dz = \int_B p_Z\big(f^{-1}(y)\big)\Big\|\det J_{f^{-1}}(y)\Big\|\,dy</span> by the <strong>change of variables</strong> of multivariate integration (the volume element is multiplied by the Jacobian in absolute value — cf.&nbsp;Refresher Statistics module, Jacobians chapter); identify the integrand with <span class="math inline">p_Y(y)</span>. Second point: <span class="math inline">J_{f^{-1}}(y) = \big[J_f(z)\big]^{-1}</span> (derivative of an inverse), and <span class="math inline">\det(M^{-1}) = 1/\det(M)</span>. <span class="qed">∎</span></p>
</div>
</div>
<div class="prop">
<p><span class="tag">Proposition 4.2 — Composition and triangular Jacobians</span> (i) <span class="math inline">\det(f \circ g)' = \det(f') \cdot \det(g')</span> (product rule for determinants, <span class="math inline">\det(AB) = \det A \det B</span>): a flow is a composition <span class="math inline">f = f_L \circ \dots \circ f_1</span> and the log-Jacobian adds up. (ii) If each <span class="math inline">f_\ell</span> alters only one <em>coordinate</em> conditionally on the previous ones (coupling: <span class="math inline">y_a = x_a</span>, <span class="math inline">y_b = s(x_a) \odot x_b + t(x_a)</span>), its Jacobian is <strong>triangular</strong> — the determinant is the product of the diagonal elements <span class="math inline">\prod_i s_i(x_a)</span>, computable in <span class="math inline">\mathcal{O}(d)</span> instead of <span class="math inline">\mathcal{O}(d^3)</span>.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>The Jacobian of a coupling has blocks <span class="math inline">\begin{pmatrix} I &amp; 0 \\ \ast &amp; \mathrm{diag}(s) \end{pmatrix}</span> — block-triangular, determinant <span class="math inline">\prod_i s_i</span>. Limiting case: <em>autoregressive</em> masks (MADE): <span class="math inline">y_i = \tau(x_i\,;h_i(x_{\&lt;i}))</span> give a strictly <em>lower</em> triangular Jacobian with diagonal <span class="math inline">\partial y_i/\partial x_i</span> — this is exactly the building block of GraphAF below. <span class="qed">∎</span></p>
</div>
</div>
<h3 id="graphaf-the-autoregressive-flow-for-graphs">4.2. GraphAF: the autoregressive flow for graphs</h3>
<div class="thm">
<p><span class="tag">Theorem 4.3 — GraphAF (Shi et al., ICLR 2020): exact likelihood + guidable sampling</span> GraphAF combines the sequential factorization of ch.&nbsp;2 with the flow of ch.&nbsp;4.1: each decision (new atom, new bond) starts from a source <span class="math inline">z_t \sim \mathcal{N}(0,1)</span> transformed by a <em>conditional</em> flow: <span class="math display">x_t = f_\theta\big(z_t\,;\ s_t\big), \qquad s_t = \mathrm{GNN}\big(G_{t-1}, \text{candidates}\big),</span> where <span class="math inline">s_t</span> is the state of the partial graph (MPNN embeddings of the candidate nodes), and the density of the decision is read <em>exactly</em> via Theorem 4.1: <span class="math display">\log p_\theta(G) = \sum_t \Big[\log p_Z(z_t) - \log\big\|\det J_{f_\theta}(z_t\,;\ s_t)\Big\|\Big].</span> Key results: (i) <em>exact</em> likelihood (unlike VAEs); (ii) 68% of valid molecules <em>without</em> chemical rules, 100% <em>with</em> the valence mask of ch.&nbsp;3 — the mask and the flow are orthogonal; (iii) sampling remains sequential (<span class="math inline">\Theta(n^2)</span> steps), BUT each step is a draw from a discretized <em>continuous</em> law — hence <em>gradient guidance</em>: to maximize a property <span class="math inline">Q(G)</span> (solubility, docking), one moves <span class="math inline">z_t</span> along of <span class="math inline">\nabla_{z_t} Q\big(G_t\big)</span> <em>during</em> generation: guidance compatible with the exact likelihood — impossible with a VAE whose latent is not in bijective correspondence with the data.</p>
</div>
<div class="note">
<p><span class="tag">Discrete flows: the cardinal difficulty</span> Theorem 4.1 requires a <em>continuous</em> space (Jacobian!). Two answers: (i) GraphAF stays continuous upstream and discretizes downstream (the flow lives on <span class="math inline">z</span>); (ii) <strong>discrete flips</strong> (Tran et al., 2019; Hoogeboom et al., 2021): on categorical variables, replace the Jacobian with a learned correction term — the discrete analogue of the change of variables; GraphDF (Cai et al., 2020) applies them to graphs; each flip is a bijection on a finite set, the “density” becomes a mass law and the log-likelihood remains exact. To be known to exist; the module’s lab implements only the (continuous) GraphAF route, simpler and sufficient for the properties.</p>
</div>
<div class="sourceCode" id="cb1"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># GraphAF skeleton (pedagogical): one conditional flow step</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch, torch.nn <span class="im">as</span> nn</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> CouplingStep(nn.Module):</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""y_b = s(h) * x_b + t(h); diagonal Jacobian = prod(s)."""</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, d):</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.net <span class="op">=</span> nn.Linear(<span class="dv">64</span>, <span class="dv">2</span> <span class="op">*</span> d)      <span class="co"># GNN state (64) -&gt; (s, t)</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x_b, h):</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>        s, t <span class="op">=</span> <span class="va">self</span>.net(h).chunk(<span class="dv">2</span>, dim<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>        s <span class="op">=</span> torch.sigmoid(s <span class="op">+</span> <span class="fl">2.0</span>)           <span class="co"># s &gt; 0: positive det, stable</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>        y <span class="op">=</span> s <span class="op">*</span> x_b <span class="op">+</span> t</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> y, s.log().<span class="bu">sum</span>(<span class="op">-</span><span class="dv">1</span>)            <span class="co"># y and log|det J|</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># generation of an atom/bond decision:</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co">#   h = GNN(G_t); z ~ N(0,1); x, ld = flow(z, h)</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">#   atom = argmax or sample of softmax(x)  (+ valence mask!)</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co">#   log p(x) = log N(z) - ld   (change of variables theorem)</span></span></code></pre></div>
<ul>
<li><strong>Flow balance sheet</strong>: exact likelihood, interpretable latents, gradient guidance — at the price of a sequential cost equal to the autoregressive models and strong architectural constraints (triangular Jacobians);</li>
<li><strong>LLGA link</strong>: the internal GNN of GraphAF is an MPNN — replacing it by a PathNN (ch.&nbsp;9) or a graph transformer (cf.&nbsp;Advanced GNN module ch.&nbsp;4) is an open research question, at the boundary of the two M2 modules.</li>
</ul>
<h2 id="ch5">5. Discrete diffusion: DiGress in detail</h2>
<p>Continuous diffusion (Multimodal GenAI module ch.&nbsp;3) noises with Gaussians — pointless for categorical atom types. DiGress (Vignac et al., ICLR 2023) transposes the machinery to the <em>categorical</em>, via the D3PM framework (Austin et al., 2021): noising = Markov chains on the categories, denoising = closed-form Bayesian posterior. Goal of this chapter: master <em>all</em> the equations.</p>
<div class="def">
<p><span class="tag">Definition 5.1 — Forward process by transition matrices</span> A type <span class="math inline">x</span> (atom among <span class="math inline">K</span>) is represented as a one-hot <span class="math inline">X \in \{0,1\}^K</span>. The noising is a Markov chain <em>independent per node and per edge</em>: <span class="math display">q(X_t \mid X_{t-1}) = \mathrm{Cat}\big(X_t;\ Q_t X_{t-1}\big),</span> where <span class="math inline">Q_t \in [0,1]^{K \times K}</span> is stochastic (rows summing to 1): row <span class="math inline">k</span> is the law of the new type given the old one <span class="math inline">k</span>. The usual cases: <strong>uniform</strong> <span class="math inline">Q_t = (1 - \beta_t) I + \beta_t \frac{1}{K}\mathbf{1}\mathbf{1}^\top</span> (with probability <span class="math inline">\beta_t</span>, forget and redraw uniformly); <strong>absorbing</strong> (toward a mask state <code>[MASK]</code> — the analogue of BERT’s MLM, cf.&nbsp;LLMs module M2 ch.&nbsp;3); <strong>discretized Gaussian</strong> (transition toward neighboring types). The composition is exact: <span class="math inline">q(X_t \mid X_s) = \mathrm{Cat}(X_t\,;\ \bar Q_s^t X_s)</span> with <span class="math inline">\bar Q_s^t = Q_{s+1} \dots Q_t</span>.</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 5.2 — Stationary marginal (proven in the uniform case)</span> For the uniform kernel above, <span class="math inline">q(X_t \mid X_0) = \mathrm{Cat}\big((1-\bar\beta_t) X_0 + \bar\beta_t\, \mathbf{u}\big)</span> with <span class="math inline">\mathbf{u}</span> the uniform law and <span class="math inline">\bar\beta_t = 1 - \prod_{s \leq t}(1 - \beta_s)</span>: at large <span class="math inline">t = T</span>, the law is (almost) uniform — independent of <span class="math inline">X_0</span>, the condition for “total” noising.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>By recursion: let <span class="math inline">p_t = q(X_t \mid X_0)</span> (row vector); <span class="math inline">p_t^\top = Q_t\, p_{t-1}^\top = \big[(1-\beta_t) I + \frac{\beta_t}{K}\mathbf{1}\mathbf{1}^\top\big] p_{t-1}^\top = (1-\beta_t)\,p_{t-1}^\top + \beta_t\, \mathbf{u}^\top</span> since <span class="math inline">\mathbf{1}^\top p_{t-1}^\top = 1</span> (mass law); unrolling, <span class="math inline">p_t^\top = \big(\prod_s (1-\beta_s)\big) X_0^\top + \big(1 - \prod_s(1-\beta_s)\big)\mathbf{u}^\top</span>. At <span class="math inline">t = T</span>, the weight of <span class="math inline">X_0</span> is <span class="math inline">\prod_s (1-\beta_s) \approx 0</span> (schedule <span class="math inline">\beta_s \to 1</span>): the <em>dataset</em> marginal law is also accessible — one can make it converge toward the empirical marginal <span class="math inline">\mathbf{m} = \frac{1}{N}\sum_i X_0^{(i)}</span> rather than the uniform, by replacing <span class="math inline">\mathbf{u}</span> with <span class="math inline">\mathbf{m}</span>: DiGress uses this option (“no bond” edges dominate, reflecting them in the final law helps the denoising). <span class="qed">∎</span></p>
</div>
</div>
<div class="thm">
<p><span class="tag">Theorem 5.3 — Posterior <span class="math inline">q(X_{t-1} \mid X_t, X_0)</span> in closed form (the heart of DiGress)</span> <span class="math display">q(X_{t-1} = j \mid X_t = i,\ X_0 = k) = \frac{(Q_{t-1})_{k j}\,(\bar Q_{t})_{j i}} {(\bar Q_{t-1})_{k i}},</span> all quantities being rows/columns of the transition matrices — direct computation, no network is involved; the network only serves to estimate <span class="math inline">\hat X_0</span>.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Bayes on the chain: <span class="math inline">q(X_{t-1} \mid X_t, X_0) \propto q(X_t \mid X_{t-1})\, q(X_{t-1} \mid X_0)</span> (Markov: <span class="math inline">X_t \perp X_0 \mid X_{t-1}</span>). In one-hot, <span class="math inline">q(X_t = i \mid X_{t-1} = j) = (Q_t)_{j i}</span> and <span class="math inline">q(X_{t-1} = j \mid X_0 = k) = (\bar Q_{t-1})_{k j}</span>; the denominator is the marginal <span class="math inline">q(X_t = i \mid X_0 = k) = \sum_j (Q_t)_{j i} (\bar Q_{t-1})_{k j} = (\bar Q_t)_{k i}</span> (matrix product — this is exactly the composition of Definition 5.1). <span class="qed">∎</span></p>
</div>
</div>
<div class="thm">
<p><span class="tag">Theorem 5.4 — DiGress: architecture, losses and topology perturbations</span></p>
<ol type="1">
<li><strong>Denoising network</strong>: a hybrid GNN (MPNN + global attention layers, graph-transformer style — cf.&nbsp;Advanced GNN module ch.&nbsp;4) predicts <span class="math inline">\hat X_0, \hat E_0 = \mathrm{softmax}_K\big(\mathrm{GNN}(X_t, E_t)\big)</span>; training maximizes the likelihood of the <em>clean</em> types at the drawn steps <span class="math inline">t</span>: <span class="math display">\mathcal{L} = \mathbb{E}_{t, G_0}\;\mathbb{E}_{q(X_t, E_t \mid X_0, E_0)} \big[-\log p_\theta(\hat X_0 = X_0) - \log p_\theta(\hat E_0 = E_0)\big]\,;</span></li>
<li><strong>Chemical auxiliary losses</strong>: penalties on derived features — valence violations, bond lengths, angles: weighted by <span class="math inline">\lambda</span>’s; they do not change the likelihood but steer the denoising toward chemically plausible regions (same lesson as NeVAE ch.&nbsp;3, transposed);</li>
<li><strong>Noised topology</strong>: edges also <em>appear/disappear</em>: at each step, a fraction of edges is redrawn (added/removed) around the density diagonal — without this, the number of edges would be frozen by the conditioning; exchangeability is <em>exact</em>: no node order exists in the process (unlike GraphRNN);</li>
<li><strong>Sampling</strong>: from <span class="math inline">(X_T, E_T)</span> (marginal law), iterate <span class="math inline">\hat X_0 \to q(X_{t-1} \mid X_t, \hat X_0)</span> (Theorem 5.3); cost: <span class="math inline">T</span> GNN passes (typically <span class="math inline">T</span> reduced by discrete DDIM), each <span class="math inline">\mathcal{O}(n^2)</span> — parallel over all nodes: the contrast with the <span class="math inline">\Theta(n^2)</span> <em>sequential</em> steps of GraphRNN;</li>
<li><strong>Guidance</strong>: classifier-free conditioning (recap from the Multimodal GenAI module ch.&nbsp;4): DiGress trains the network with a conditional descriptor <span class="math inline">c</span> sometimes masked; at sampling, <span class="math inline">\hat X_0^{cfg} \propto \hat X_0^{uncond}\cdot\big(\hat X_0^{cond}/\hat X_0^{uncond}\big)^{w}</span> — the “guided” sample sequences follow the target property (e.g.&nbsp;<span class="math inline">QED</span>, logP penalty) at a measured cost in diversity (the trade-off of ch.&nbsp;6 of the Control in Generative AI module);</li>
<li><strong>Inpainting</strong>: freeze a scaffold (known types and edges), noise the rest, generate: the posterior 5.3 is constrained trivially (the frozen positions are not denoised) — conditional generation by partial graph without retraining.</li>
</ol>
</div>
<div class="note">
<p><span class="tag">Cousins and descendants</span> <strong>EDP-GNN</strong> (Niu et al., 2020): <em>continuous</em> score matching on the permuted adjacency (with permutation annealing); <strong>GDSS</strong> (Jo et al., ICML 2022): a coupled node/edge SDE system, solved as a joint continuous diffusion; <strong>EDM/EDT</strong> (3D): equivariant positions in addition to types — the geometric entry point (cf.&nbsp;Geometric Deep Learning M2 module for equivariance); <strong>NGG</strong> (ch.&nbsp;9): the recipe moved into a <em>latent space</em> of graph features. The diffusion family dominates the 2023-2026 molecular state of the art on the quality/exchangeability trade-off — autoregressive models keep the exact likelihood, flows the gradient guidance: ch.&nbsp;6 shows how to compare them fairly.</p>
</div>
<h2 id="ch6">6. Evaluating rigorously: MMD, validity, FCD</h2>
<p>A graph generator is not scored image by image but <em>distribution against distribution</em> (M1 recap); at the M2 level, we require: the <strong>formulas</strong>, their <strong>biases</strong>, and their <strong>attacks</strong>. Why so much rigor? because evaluation <em>drives</em> research: a truncated metric produces truncated models (ch.&nbsp;10).</p>
<div class="def">
<p><span class="tag">Definition 6.1 — MMD (Maximum Mean Discrepancy) on graph features</span> For a kernel <span class="math inline">k</span> on <span class="math inline">\mathbb{R}^d</span> (e.g.&nbsp;Gaussian <span class="math inline">k(u,v) = e^{-\\|u-v\\|^2/2\sigma^2}</span>) and a feature <span class="math inline">\phi : \mathcal{G} \to \mathbb{R}^d</span> (degree histogram, clustering coefficients, orbit counts…): <span class="math display">\mathrm{MMD}^2\big(\{G_i\}_{i\leq n}, \{G'_j\}_{j\leq m}\big) = \Big\\|\frac{1}{n}\sum_i k(\phi(G_i), \cdot) - \frac{1}{m}\sum_j k(\phi(G'_j), \cdot)\Big\\|^2_{\mathcal{H}} = \frac{1}{n^2}\sum_{i,i'} k_{ii'} + \frac{1}{m^2}\sum_{j,j'} k_{jj'} - \frac{2}{nm}\sum_{i,j} k_{ij},</span> computable in <span class="math inline">\mathcal{O}(n^2 + m^2)</span>; the estimator is <em>unbiased</em> if one removes the diagonals (<span class="math inline">\frac{1}{n(n-1)}</span>). In practice: three canonical features (degrees, clustering, orbits) and a Gaussian kernel with median bandwidth.</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 6.2 — Orbits: the right scale of motifs</span> <em>Orbit counts</em> count the occurrences of each orbit of a small graph <span class="math inline">F</span> (4-5 nodes: triangles, squares, paws…) <em>modulo automorphisms</em>: the number of orbits of 4-node graphs is 15 (not the number of graphs, 6); each node of <span class="math inline">G</span> is classified into the orbit of its pattern neighborhood. Raw <em>subgraph</em> counts (without quotient by <span class="math inline">\mathrm{Aut}</span>) over-count: a complete triangle counts 3 times as “closed paths”; the quotient corrects this constant factor per pattern. The theoretical link: these features are exactly empirical <span class="math inline">t(F, \cdot)</span>’s of Theorem 1.4 — comparing orbit MMDs = comparing the graphons in the limiting sense (up to motif size).</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 6.3 — FCD: the Fréchet ChemNet distance (Preuer et al., 2018)</span> Let <span class="math inline">e : \text{molecule} \to \mathbb{R}^d</span> be the embedding of an activity-predictor network (ChemNet, pre-trained) assumed approximately Gaussian on each family; <span class="math display">\mathrm{FCD}(\mathcal{D}_{gén}, \mathcal{D}_{réf}) = \\|\mu_1 - \mu_2\\|^2 + \mathrm{tr}\big(\Sigma_1 + \Sigma_2 - 2(\Sigma_1 \Sigma_2)^{1/2}\big),</span> with <span class="math inline">(\mu_k, \Sigma_k)</span> the means/covariances of the embeddings of the two sets — exactly the <span class="math inline">d^2_{\mathcal{W}_2}</span> metric of two Gaussians (the analogue of the FID; Multimodal GenAI module ch.&nbsp;8); the matrix square root is computed via eigenvalues. Key property: the FCD <em>penalizes invalid molecules</em> (no embedding → infinite distance or fixed penalty): it integrates validity <em>and</em> distributional similarity of properties — why it became the reference metric of molecular benchmarks (GuacaMol, MOSES).</p>
</div>
<div class="note">
<p><span class="tag">The pitfalls of evaluation (to be known by heart)</span></p>
<ol type="1">
<li><strong>Validity ≠ quality</strong>: 100% validity is obtained by <em>memorizing</em> the dataset (perfect validity, 0 novelty); always report validity <em>and</em> uniqueness <em>and</em> novelty <em>and</em> FCD;</li>
<li><strong>MMD sensitive to sample size</strong>: the bias of the estimator grows like <span class="math inline">\mathcal{O}(1/n)</span>; comparing two models with different numbers of generated <span class="math inline">n</span> is invalid — protocol: same <span class="math inline">n</span>, same seeds, several trials; significance is tested by bootstrap;</li>
<li><strong>Chosen features = favored families</strong>: degrees + clustering ignore the motif-position correlation; a generator can pass the exam on marginal distributions and fail on the <em>joints</em> (molecules whose fragments are right but assembled absurdly); hence the addition of orbits, FCD, and transport distances (Gromov-Wasserstein, Optimal Transport module);</li>
<li><strong>Metric overfitting</strong>: optimizing against the FCD (e.g.&nbsp;by guidance) eventually inflates it — honest evaluation keeps one metric <em>kept secret</em> (the held-out principle, cf.&nbsp;healthy benchmarking: Dwivedi et al., JMLR 2023, recalled in the Advanced GNN module ch.&nbsp;6).</li>
</ol>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: left;">Granularity</th>
<th style="text-align: left;">Cost</th>
<th style="text-align: left;">Captures</th>
<th style="text-align: left;">Main limitation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Validity / uniqueness / novelty</td>
<td style="text-align: left;">per molecule</td>
<td style="text-align: left;">RDKit, <span class="math inline">\mathcal{O}(n)</span> s</td>
<td style="text-align: left;">yntactic legality, memorization b</td>
<td style="text-align: left;">lind to the distribution</td>
</tr>
<tr class="even">
<td style="text-align: left;">MMD degrees / clustering</td>
<td style="text-align: left;">marginal</td>
<td style="text-align: left;"><span class="math inline">\mathcal{O}(n^2)</span> kernel lo</td>
<td style="text-align: left;">cal structure ig</td>
<td style="text-align: left;">nores joints</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MMD orbits</td>
<td style="text-align: left;">motifs (4-5 nodes)</td>
<td style="text-align: left;">enum. costly</td>
<td style="text-align: left;">motifs modulo automorphisms</td>
<td style="text-align: left;">bounded size</td>
</tr>
<tr class="even">
<td style="text-align: left;">FCD</td>
<td style="text-align: left;">chemical properties</td>
<td style="text-align: left;">1 ChemNet pass</td>
<td style="text-align: left;">property distribution + validity</td>
<td style="text-align: left;">depends on the predictor</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gromov-Wasserstein</td>
<td style="text-align: left;">whole graphs</td>
<td style="text-align: left;">OT <span class="math inline">\mathcal{O}(n^3)</span> st</td>
<td style="text-align: left;">ructure without correspondence co</td>
<td style="text-align: left;">st, choice of intra distance</td>
</tr>
</tbody>
</table>
<h2 id="ch7">7. Conditional generation and text-to-graph</h2>
<h3 id="three-conditioning-mechanisms">7.1. Three conditioning mechanisms</h3>
<div class="def">
<p><span class="tag">Definition 7.1 — Conditioning a graph generator</span> One goes from <span class="math inline">p_\theta(G)</span> to <span class="math inline">p_\theta(G \mid c)</span> where <span class="math inline">c</span> is the conditioning; three mechanisms, with different properties:</p>
<ul>
<li><strong>at the input</strong> (concat/fusion): the GNN receives <span class="math inline">c</span> (property vector, text embedding) — trained on pairs <span class="math inline">(G, c)</span> or classifier-free (dropout of <span class="math inline">c</span>); simple, <em>soft</em> control;</li>
<li><strong>by guidance</strong>: a predictor <span class="math inline">Q(c \mid G)</span> or a classifier steers the sampling (gradients for flows ch.&nbsp;4, CFG for diffusion ch.&nbsp;5); <em>strong</em> control, zero or light retraining, price: diversity;</li>
<li><strong>by search</strong>: generate massively then filter/optimize (Bayesian optimization in the latent space — the classic QSAR pipeline); <em>exact</em> control a posteriori, high sampling cost.</li>
</ul>
<p>The control-fidelity / diversity trade-off is quantified in ch.&nbsp;9 of the <em>Control in Generative AI</em> module; here we retain: for graphs, “hard” conditioning (scaffold, valences) and “soft” (properties, text) combine — inpainting + CFG in DiGress.</p>
</div>
<h3 id="text-to-graph-the-llm-graphs-encounter">7.2. Text-to-graph: the LLM × graphs encounter</h3>
<div class="thm">
<p><span class="tag">Theorem 7.2 — Four text-to-graph routes (2022-2026)</span></p>
<ol type="1">
<li><strong>Molecule ↔︎ text translation</strong>: MolT5 (Edwards et al., EMNLP 2022) pre-trains a T5 on text + SMILES and treats description → molecule as a <em>translation</em>; the text is the conditioning, the SMILES the target; graph generation is delegated to the SMILES grammar (valence ≈ free);</li>
<li><strong>The LLM writes the generator</strong>: instead of generating the graph <em>directly</em>, the LLM writes <em>code</em> (NetworkX) that generates the graph; “Demystifying the Power of LLMs in Graph Generation” (Wang et al., Findings NAACL 2025) shows that network-science prompting (clustering, motifs) suffices to match generators trained on classic families; the agent produces <em>target properties</em>, the code implements them — control moves up one level of abstraction;</li>
<li><strong>Simulator agents</strong>: generate <em>dynamic</em> networks by making LLM agents interact (relations, citations, conversations): “Dynamic and Textual Graph Generation via Large-Scale LLM-based Agent Simulation” (Ji et al., 2024) reaches 10<sup>5</sup> nodes — the structure emerges from the interaction, the text animates the nodes;</li>
<li><strong>LLM + GNN hybrid</strong>: the LLM proposes, the GNN evaluates, the loop optimizes (Chen et al., 2023; ChemCrow, Bran et al., 2023: 18 tools including property predictors and docking) — the “proposal/evaluation” loop of ch.&nbsp;9 of the M1 Graph ML, industrialized by agent tools (cf.&nbsp;LLMs module M2 ch.&nbsp;8).</li>
</ol>
</div>
<div class="note">
<p><span class="tag">Why SMILES won (for now)</span> Generating graphs by direct LLM (edge lists) fails at small scale: local (valence) and global (connectivity) coherence constraints drowned in the long sequence; SMILES encodes valence <em>in the grammar</em> (parentheses, aromaticity): the next token has little illegal freedom — the same lesson as NeVAE (ch.&nbsp;3): <em>move the constraints from post-processing into the syntax</em>. The counterpart: SMILES is not canonical (one molecule, several encodings; cf.&nbsp;GOAT, ch.&nbsp;9, on the cost of orders); SELFIES (Krenn et al., 2020) makes the grammar <em>totally</em> valid: every sequence decodes — the practical reference for the 2026 labs.</p>
</div>
<div class="ex">
<p><span class="tag">Example 7.3 — Toy molecular CFG (pen and paper)</span> For the target <span class="math inline">c =</span> “high logP”; logits of step <span class="math inline">t</span> of the denoiser without conditioning: <span class="math inline">(C: 2.0,\ O: 1.5,\ N: 0.5)</span>; with conditioning: <span class="math inline">(C: 3.0,\ O: 0.5,\ N: 0.5)</span>; guidance <span class="math inline">w = 3</span>: guided logits = uncond + <span class="math inline">w</span>(cond − uncond) = <span class="math inline">(C: 5.0,\ O: -1.0,\ N: 0.5)</span>; probabilities <span class="math inline">\approx (0.95,\ 0.007,\ 0.04)</span>; carbon dominates: high logP = carbon chains — chemically coherent. Increasing <span class="math inline">w</span> → collapse onto carbon (diversity drops): the fidelity/diversity curve of the Control module, readable on a single step.</p>
</div>
<h2 id="ch8">8. Applications: drugs, materials, synthetic networks</h2>
<p>Generating graphs is not an end in itself: it is the operational arm of <strong>inverse design</strong> — specify what one wants (a property, a structure, a statistic) and let the model explore the space <span class="math inline">\mathcal{G}</span> on our behalf. This chapter visits the module’s three application territories, each time with the same three questions: which <em>hard constraints</em>? which <em>objectives</em>? which <em>evaluation</em>?</p>
<div class="def">
<p><span class="tag">Definition 8.1 — Inverse design, Pareto, scalarization</span> We have predictors <span class="math inline">Q_1, \dots, Q_m : \mathcal{G} \to \mathbb{R}</span> (solubility, synthesizability, predicted activity…). <strong>Inverse design</strong> seeks to maximize a <em>vector</em> objective <span class="math inline">Q = (Q_1, \dots, Q_m)</span>: in general no <span class="math inline">G</span> optimizes all the <span class="math inline">Q_i</span> at once (solubility against permeability, activity against toxicity). One defines <strong>Pareto dominance</strong>: <span class="math inline">G \succ G'</span> if <span class="math inline">Q_i(G) \geq Q_i(G')</span> for all <span class="math inline">i</span>, with at least one strict inequality; the non-dominated ones form the <strong>Pareto frontier</strong>. Two usual scalarizations bring the problem back to a scalar objective: <span class="math display">J(G) = \sum_{i} w_i\, Q_i(G) \quad\text{(weighted)}, \qquad J_{\times}(G) = \prod_{i} \pi_i\big(Q_i(G)\big)^{w_i} \quad\text{(geometric)},</span> where <span class="math inline">\pi_i : \mathbb{R} \to [0,1]</span> maps each property into <span class="math inline">[0,1]</span> (sigmoids, normalization); the geometric form (that of GuacaMol’s MPO tasks) penalizes <em>heavily</em> any collapsed objective: a product does not forgive a zero. The role of the generator: proposing candidates where direct combinatorial optimization (<span class="math inline">10^{500}</span> adjacencies, ch.&nbsp;1) is hopeless — the gradient guidance of ch.&nbsp;4, the CFG of ch.&nbsp;5 and the reinforcement-learning optimization of ch.&nbsp;7 are the three interfaces between <span class="math inline">p_\theta</span> and <span class="math inline">J</span>.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 8.2 — Drug discovery: where does the generator plug in?</span> The industrial pipeline, simplified but faithful:</p>
<ol type="1">
<li><strong>Target and hypothesis</strong>: a protein involved in a disease;</li>
<li><strong>Proposal</strong>: the generator samples <span class="math inline">G \sim p_\theta(\cdot \mid c)</span> (c = target descriptor, properties) or optimizes <span class="math inline">J</span> in the latent space — GraphAF guidance (ch.&nbsp;4), DiGress CFG (ch.&nbsp;5), RL policies on SMILES (industrial pipelines of the REINVENT type);</li>
<li><strong>Filtering</strong>: validity (valence, ch.&nbsp;3), <span class="math inline">QED</span> — the “drug-likeness” score on <span class="math inline">[0,1]</span> (Bickerton et al., 2012) —, synthesizability <span class="math inline">SA</span>, logP, diversity (ch.&nbsp;6);</li>
<li><strong>Costly evaluation</strong>: docking (predicted interaction energy), ADMET models (absorption, toxicity) — each step costs orders of magnitude more than the previous one;</li>
<li><strong>Synthesis and trials</strong>: the real bottleneck — hence the operational metric: the quality of the <em>top-k</em> (the k candidates actually synthesized), not the batch average.</li>
</ol>
<p>An often-ignored consequence: optimizing the mean of <span class="math inline">J</span> over 10<sup>4</sup> molecules can be <em>worse</em> than optimizing the maximum — the useful generator is the one that explores the corners of the Pareto frontier; this is exactly the fidelity/diversity curve of the <em>Control in Generative AI</em> module (ch.&nbsp;9), reread from the application side.</p>
</div>
<div class="note">
<p><span class="tag">Molecular benchmarks: ZINC, MOSES, GuacaMol</span></p>
<ul>
<li><strong>ZINC</strong> (Sterling &amp; Irwin, 2015): the database of <em>purchasable</em> compounds — the reservoir; the subset <strong>ZINC-250k</strong> (≈ 250,000 lead-like molecules, popularized by grammar VAEs) is the standard training set of chapters 3-5 (NeVAE, GraphAF train and evaluate on it);</li>
<li><strong>MOSES</strong> (Polykovskiy et al., 2020): ~1.9M ZINC molecules with <em>scaffold split</em> (the test scaffolds are unknown at training time) and standardized metrics: validity, uniqueness, novelty, FCD, scaffold similarity — the “distribution-learning” protocol of ch.&nbsp;6;</li>
<li><strong>GuacaMol</strong> (Brown et al., 2019): two families of tasks — <em>distribution-learning</em> (reproduce a library: FCD, KL divergences on physico-chemical properties, validity/novelty) and <em>goal-directed</em> (rediscover a given molecule, similarity, isomers, and the <strong>MPO</strong> tasks: maximize the geometric product of properties — Definition 8.1 in action).</li>
</ul>
<p>The common trap: metric learning (ch.&nbsp;6, point 4); on goal-directed tasks, a model can memorize the targets — hence the evaluation on targets kept secret. These benchmarks are to molecular generation what CIFAR/ImageNet are to vision (cf.&nbsp;Deep Learning module): convenient stops, not the destination.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 8.3 — Materials: the periodic constraint (CDVAE, MatterGen)</span> A crystal is not a molecule: it is a triple <span class="math inline">(\Lambda, X, L)</span> — lattice <span class="math inline">\Lambda</span> (three cell vectors), positions <span class="math inline">X</span> of <span class="math inline">n</span> atoms <em>in the cell</em>, the invariance being the group of integer translations: every quantity (distances, energies, densities) is computed <em>modulo the periodic images</em>. Two models bound the domain:</p>
<ol type="1">
<li><strong>CDVAE</strong> (Xie et al., ICLR 2022): a VAE whose decoder <em>denoises</em> by diffusion; the initialization places the atoms far from any equilibrium and the diffusion makes them “fall” toward realistic bonds — the physical inductive bias (stability is a local energy minimum) is inscribed <em>in the dynamics</em>: the exact analogue of the valence mask of ch.&nbsp;3, moved into the space of positions;</li>
<li><strong>MatterGen</strong> (Zeni et al., Nature 2025): joint diffusion on atom types, coordinates <em>and</em> lattice — with conditioning by <strong>adapter</strong>: the base model (learned on the whole periodic table) is frozen, a small per-task module redirects the denoising toward the target property (composition, symmetry, magnetism…) — the industrial analogue of the classifier-free guidance of ch.&nbsp;5: one large model, a thousand cheap adaptations.</li>
</ol>
<p>Evaluation specific to materials: <strong>stable</strong> fraction (predicted energy close to the convex hull of known phases), <strong>novelty</strong> against crystallographic databases (the analogue of the novelty of ch.&nbsp;6), symmetry validity (space groups). The module’s lesson repeats: periodicity is a <em>hard</em> constraint — it is architectural (equivariance to translations, cf.&nbsp;Geometric Deep Learning M2 module), never a post-processing.</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 8.4 — Synthetic networks: generating to protect</span> Sharing a real graph (contacts, transactions, calls) means exposing individuals: the structure itself re-identifies — knowing the neighbors of a node suffices to find it again in most real networks, and anonymizations by masking are systematically broken. Generating a <em>synthetic</em> network that reproduces the useful statistics (degrees, clustering, motifs — the features of ch.&nbsp;6) without copying the individuals is the alternative; <strong>NetGAN</strong> (Bojchevski et al., ICML 2018) opened the way: learn the distribution of the graph’s biased <em>random walks</em> (a GAN on node sequences), then reconstruct the adjacency from the co-occurrences of the walks — the graph is never copied, only its “walk signature” is.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span><strong>The fidelity/confidentiality trade-off, quantified.</strong> Fidelity is measured by MMD on degrees/clustering/orbits (ch.&nbsp;6); confidentiality by node-level membership inference tests (the graph counterpart of the attacks of the <em>Security and Robustness</em> M2 module): a generator that <em>memorizes</em> (overfitting on a single graph) spits out exact subgraphs — detectable, real damage. Mastering the trade-off goes through (i) the regularization of <span class="math inline">p_\theta</span> (limiting memorization as one limits overfitting — cf.&nbsp;Machine Learning module ch.&nbsp;7); (ii) noise at the node/edge level (the analogue of the Gaussian mechanism of DP — cf.&nbsp;Emerging ML ch.&nbsp;5 and Privacy and Uncertainty M2 modules); (iii) evaluation <em>on both sides</em>: publishing a synthetic network without an attack test is a rerun of the “100% validity” of ch.&nbsp;6 — half a proof. <span class="qed">∎</span></p>
</div>
</div>
<div class="ex">
<p><span class="tag">Example 8.5 — Pareto by hand (pen and paper)</span> Four candidates, two normalized objectives (<span class="math inline">Q_1</span> = predicted activity, <span class="math inline">Q_2</span> = synthesizability): <span class="math inline">A = (0.9;\ 0.2)</span>, <span class="math inline">B = (0.7;\ 0.7)</span>, <span class="math inline">C = (0.6;\ 0.9)</span>, <span class="math inline">D = (0.2;\ 0.95)</span>. Dominance: does <span class="math inline">B</span> dominate <span class="math inline">D</span>? <span class="math inline">0.7 \&gt; 0.2</span> but <span class="math inline">0.7 \&lt; 0.95</span> — no; step by step, all four are on the frontier. Weighted scalarization <span class="math inline">J = w Q_1 + (1-w) Q_2</span>: at <span class="math inline">w = 0.3</span>, <span class="math inline">C</span> wins (<span class="math inline">J = 0.81</span>) ahead of <span class="math inline">D</span> (0.725) and <span class="math inline">B</span> (0.70); at <span class="math inline">w = 0.6</span>, <span class="math inline">C</span> prevails again (0.72) against <span class="math inline">B</span> (0.70) and <span class="math inline">A</span> (0.62); <span class="math inline">A</span> overtakes <span class="math inline">C</span> only for <span class="math inline">w \geq 0.7</span> — the ranking <em>pivots</em> with the weights: report the frontier, never an isolated argmax. Geometric version <span class="math inline">J_\times = Q_1 Q_2</span>: <span class="math inline">C</span> (0.54) and <span class="math inline">B</span> (0.49) dominate, <span class="math inline">A</span> (0.18) and <span class="math inline">D</span> (0.19) are eliminated — unbalanced profiles are crushed: the signature of MPO.</p>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Domain</th>
<th style="text-align: left;">Object</th>
<th style="text-align: left;">Hard constraint</th>
<th style="text-align: left;">Typical objectives</th>
<th style="text-align: left;">Evaluation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Molecules</td>
<td style="text-align: left;">2D graph (types, bonds) or SMILES</td>
<td style="text-align: left;">valence, aromaticity (ch.&nbsp;3)</td>
<td style="text-align: left;">QED, SA, logP, docking, MPO</td>
<td style="text-align: left;">validity/uniqueness/novelty, FCD (ch.&nbsp;6), GuacaMol, MOSES</td>
</tr>
<tr class="even">
<td style="text-align: left;">Materials</td>
<td style="text-align: left;">crystal <span class="math inline">(\Lambda, X, L)</span> p</td>
<td style="text-align: left;">eriodicity, equivariance (Geometric DL) s</td>
<td style="text-align: left;">tability, band gap, magnetism s</td>
<td style="text-align: left;">table fraction, novelty vs crystallographic databases</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Networks</td>
<td style="text-align: left;">simple graph, sometimes labeled</td>
<td style="text-align: left;">size, target degrees</td>
<td style="text-align: left;">target statistics (spectrum, degrees, clustering)</td>
<td style="text-align: left;">MMD (ch.&nbsp;6), membership tests (privacy)</td>
</tr>
</tbody>
</table>
<h2 id="ch9">9. Research of the LLGA team</h2>
<p>The LLGA master is driven by the <strong>DaSciM</strong> laboratory (Data Science and Mining, LIX, CNRS — École Polytechnique: M. Vazirgiannis, J. Lutzeyer, G. Nikolentzos and their PhD students), the host laboratory of the internships and PhDs. This chapter presents four of its works, chosen because they touch <em>directly</em> on the objects of this module: the encoder of the generators (PathNN), the order question (GOAT), a latent-diffusion generator conditioned by features (NGG) and the LLM × graphs frontier (pseudo-code prompting). The other axes of the laboratory are covered by the Graph ML (ch.&nbsp;10) and Advanced GNN (ch.&nbsp;8) modules; here, each paper reads as the <em>extension of a chapter</em>.</p>
<div class="thm">
<p><span class="tag">Work 9.1 — PathNN: aggregating paths, not neighbors (Michel, Nikolentzos, Lutzeyer &amp; Vazirgiannis, ICML 2023)</span> Standard message passing (ch.&nbsp;0) aggregates <em>immediate neighbors</em>; PathNN aggregates <strong>paths</strong> starting from the node: <span class="math display">h_v^{(\ell)} = \mathrm{AGG}\Big(\big\{\, \mathrm{LSTM}\big(h_v^{(0)}, h_{u_1}^{(0)}, \dots, h_{u_\ell}^{(0)}\big)\ :\ (v, u_1, \dots, u_\ell) \in \mathcal{P}_v^{(\ell)} \,\big\}\Big),</span> where <span class="math inline">\mathcal{P}_v^{(\ell)}</span> is a set of paths of length <span class="math inline">\ell</span> — three variants: shortest paths (to all destinations), random walks, sampled simple paths. Two reasons to be interested here: (i) <em>expressivity</em>: paths of length <span class="math inline">\ell</span> capture multi-hop dependencies that <span class="math inline">\ell</span> layers of MPNN irretrievably mix — strictly above 1-WL on chosen pairs (cf.&nbsp;Advanced GNN module ch.&nbsp;1-2); since the number of simple paths grows exponentially, sampling <span class="math inline">\mathcal{P}_v</span> bounds the cost: an expressivity/cost trade-off tuned <em>in the encoder</em>; (ii) <em>role in this module</em>: PathNN is an encoder — the natural candidate for the <span class="math inline">q_\phi(z \mid G)</span> of the VAEs (ch.&nbsp;3) and the backbone of the NGG below; replacing the MPNN with a more expressive encoder is the simplest improvement lever for latent-based generators.</p>
</div>
<div class="thm">
<p><span class="tag">Work 9.2 — GOAT: rehabilitating the order of neighbors (Chatzianastasis, Lutzeyer, Dasoulas &amp; Vazirgiannis, AAAI 2023)</span> The whole module has run into order: autoregressive models <em>impose</em> a canonical order on it (BFS, ch.&nbsp;2), the one-shot decoder must <em>match</em> its nodes (Hungarian matching, ch.&nbsp;3). GOAT attacks the root: the usual aggregators (sum, mean, max, attention) are invariant — they throw away <em>all</em> order information between neighbors, while this order carries signal (synergies, redundancies between neighbors). The GOAT layer is a <strong>permutation-sensitive</strong> attention: each node learns a <em>local order</em> of its neighborhood (position scores) and encodes the neighbors <em>in that learned order</em> — global invariance is preserved (the order is a function of the graph, not of a numbering), local sensitivity is restored. Results: prediction of centrality metrics (betweenness…) where invariant GNNs struggle. The “generation” reading: an encoding that distinguishes neighborhoods that 1-WL confounds gives the latent <em>more to say</em> — the flip side of the matching problem of ch.&nbsp;3: better encoding the order means better recovering it at decoding.</p>
</div>
<div class="thm">
<p><span class="tag">Work 9.3 — NGG: latent diffusion conditioned by graph features (Evdaimon, Nikolentzos, Xypolopoulos, Kammoun, …, Vazirgiannis, 2024)</span> The <em>Neural Graph Generator</em> applies the <strong>latent diffusion</strong> recipe to graphs (recap: Multimodal GenAI module ch.&nbsp;3-4):</p>
<ol type="1">
<li><strong>Encoder</strong>: a GNN compresses <span class="math inline">G \mapsto h_G</span> (latent);</li>
<li><strong>Conditioned latent diffusion</strong>: a denoiser learns to denoise <span class="math inline">h_G</span> <em>given a vector of target features</em> <span class="math inline">c</span> — spectrum of the Laplacian (the first eigenvalues), degree statistics, clustering coefficient… descriptors that are <em>global, interpretable, measurable</em>;</li>
<li><strong>Decoder</strong>: from the denoised latent to the adjacency. Sampling: choose <span class="math inline">c</span> — the statistical “specification sheet” — then generate.</li>
</ol>
<p>Position with respect to the chapters: DiGress (ch.&nbsp;5) denoises <em>the complete object</em> (types, edges); NGG denoises <em>a representation</em> — the exchangeability is that of the encoder, the per-step cost much lower, and the conditioning is “macro” (global features) where the molecular CFG of ch.&nbsp;7 is “micro” (a property of one molecule). The evaluation is that of ch.&nbsp;6: MMD on degrees/clustering/orbits between generated graphs and target families (SBM, citation networks…). It is also the “synthetic networks” building block of ch.&nbsp;8: specify a spectrum and a degree distribution, obtain whole graphs.</p>
</div>
<div class="thm">
<p><span class="tag">Work 9.4 — Pseudo-code prompting: reasoning about graphs with programs (Skianis, Nikolentzos &amp; Vazirgiannis, 2024)</span> A series of graph problems (connectivity, shortest path, existence of cycles, maximum flow, spanning tree…) is submitted to LLMs: the same instruction formulated in <strong>pseudo-code</strong> (algorithmic specification: loops, conditions, invariants) systematically beats its natural-language formulation — on both axes: understanding (executing the described algorithm) and producing (writing the algorithm for the posed problem). The reading for this module: (i) it is the experimental confirmation of route 2 of ch.&nbsp;7 (“the LLM writes the generator”): the <em>program</em> is the most reliable graph representation for an LLM — unambiguous, verifiable, executable; (ii) the natural bridge with tool-using agents (ch.&nbsp;7, ChemCrow): describe the task in pseudo-code then have it verified by a solver (NetworkX) — the proposal/verification loop of the Control module (ch.&nbsp;10), instantiated on graphs.</p>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Work</th>
<th style="text-align: left;">Question</th>
<th style="text-align: left;">Central idea</th>
<th style="text-align: left;">Related chapters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PathNN (ICML 2023)</td>
<td style="text-align: left;">what to read on a graph?</td>
<td style="text-align: left;">aggregate paths (LSTM) instead of neighborhoods</td>
<td style="text-align: left;">ch.&nbsp;3-5 (encoders)</td>
</tr>
<tr class="even">
<td style="text-align: left;">GOAT (AAAI 2023)</td>
<td style="text-align: left;">the local order of neighbors</td>
<td style="text-align: left;">permutation-sensitive attention, learned order</td>
<td style="text-align: left;">ch.&nbsp;2-3 (orders, matching)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NGG (2024)</td>
<td style="text-align: left;">generate with given features</td>
<td style="text-align: left;">latent diffusion conditioned by spectrum/degrees</td>
<td style="text-align: left;">ch.&nbsp;5-6, ch.&nbsp;8 (synthetic networks)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pseudo-code prompting (2024)</td>
<td style="text-align: left;">have graph algorithms executed</td>
<td style="text-align: left;">pseudo-code beats natural language</td>
<td style="text-align: left;">ch.&nbsp;7 (text-to-graph)</td>
</tr>
</tbody>
</table>
<div class="note">
<p><span class="tag">Pedagogical instructions for use</span> Recommended reading order: NGG first (closest to the heart of the module — exercise 8 extends it); GOAT next (after redoing the matching of ch.&nbsp;3); PathNN (with the Advanced GNN module ch.&nbsp;2 alongside); pseudo-code prompting last (after ch.&nbsp;7). Each paper lends itself to a presentation session: problem, idea, one equation, one critical experiment, one limitation — the format of the module’s defenses.</p>
</div>
<h2 id="ch10">10. Open problems</h2>
<p>The grid of ch.&nbsp;1 (exchangeability, likelihood, constraints) closes here: four work sites where it still has no satisfactory answer — and a fifth, theoretical one. For each: the 2026 state, the promising direction, and the master’s modules that contribute to it.</p>
<div class="thm">
<p><span class="tag">Problem 10.1 — Evaluation: a metric without a theory of the measure</span> Chapter 6 showed the biases; the heart of the problem is that there is <em>no</em> canonical distance on <span class="math inline">\mathcal{G}</span>: the edit distance is NP-hard to compute, Gromov-Wasserstein costs <span class="math inline">\mathcal{O}(n^3)</span> per pair (cf.&nbsp;Optimal Transport module), and MMD depends on an arbitrary choice of features and kernel — a generator can satisfy degrees + clustering + orbits and fail on every untested statistic. The FCD itself depends on a frozen bioactivity predictor (ChemNet, 2015): the metric ages with it. Promising directions: (i) <em>task-based</em> evaluation (do the generated graphs improve a downstream predictor, as augmentation data?); (ii) learned “critics” (a generated/real classifier trained to discriminate — if it succeeds, the distribution is betrayed); (iii) cheap surrogates of GW. Methodological reference: the lesson of healthy benchmarking (Dwivedi et al., JMLR 2023 — Advanced GNN module ch.&nbsp;6).</p>
</div>
<div class="thm">
<p><span class="tag">Problem 10.2 — Global hard constraints</span> The valence mask (ch.&nbsp;3) is <em>local</em>: each decision only looks at the remaining valences — hence its tractability. The useful constraints are often <em>global</em>: connectivity, cycle sizes, total number of edges, quotas per type, stability. The automaton that would enforce them at decoding is exponential (the technical point of the Control module ch.&nbsp;3, on text, carries over as is); the auxiliary losses of DiGress (ch.&nbsp;5) <em>penalize</em> them without <em>guaranteeing</em> them; post-processing <em>repairs</em> them at the price of the bias of ch.&nbsp;3. Direction: constrained generation <em>with guarantee</em> — projection at each diffusion step onto the admissible set (the discrete posterior of thm. 5.3 is no longer in closed form as soon as it is constrained: the whole challenge), solvers in the loop, learned rejection methods. This is <em>the</em> shared work site with the Control in Generative AI module (ch.&nbsp;8).</p>
</div>
<div class="thm">
<p><span class="tag">Problem 10.3 — Scaling up</span> All the complexities of the module are at best <span class="math inline">\mathcal{O}(n^2)</span> per object: square adjacency, <span class="math inline">\Theta(n^2)</span> sequential steps for GraphRNN, <span class="math inline">T</span> GNN passes for DiGress — and <span class="math inline">\mathcal{O}(n^2)</span> tokens to describe a graph to an LLM (ch.&nbsp;7). Real networks reach 10<sup>8</sup>-10<sup>9</sup> nodes. Leads: generation <em>by fragments</em> (junction trees, ch.&nbsp;2 — the fragment as the decision unit divides the number of steps); <em>latent</em> generation (NGG, ch.&nbsp;9: one denoises a fixed-size representation); training on subgraphs (mini-batch — at the price of a sampling bias); sparsification. Underlying open question: sample complexity — how many graphs are needed to learn a law at large <span class="math inline">n</span>? (the generational counterpart of the generalization problem of the Statistical Learning Theory module).</p>
</div>
<div class="thm">
<p><span class="tag">Problem 10.4 — The integration of LLMs</span> Chapter 7 showed four routes; their blind spots: (i) <em>tokenization</em> — no canonical serialization of graphs is satisfactory (SMILES is not canonical, the edge list is <span class="math inline">\mathcal{O}(n^2)</span> tokens, cf.&nbsp;GOAT ch.&nbsp;9 on the cost of orders); (ii) <em>guarantee</em> — the LLM hallucinates invalid adjacencies; the remedy is grammatical (SELFIES) or agentic (the tool verifies); (iii) <em>memorization</em> — an LLM can spit out training graphs (the privacy problem of ch.&nbsp;8, displaced); (iv) <em>evaluation</em> — text-to-graph does not yet have its GuacaMol. Directions: graph foundation models (multi-family pre-training, adaptation by prompt — cf.&nbsp;Boosting and Foundation Models M2 module), LLM + GNN hybrids (propose/verify), and standardized evaluation (the “code” protocol of ch.&nbsp;7 as a provisional standard).</p>
</div>
<div class="thm">
<p><span class="tag">Problem 10.5 — Theory: beyond exchangeability and likelihood</span> Two frontiers. (i) <em>Limits</em>: the Aldous-Hoover theorem (ch.&nbsp;1) describes <em>exchangeable</em> laws — now real networks grow (preferential attachment), evolve (temporal), and their limits require non-exchangeable extensions (graphexes): what is the theory of <em>neural</em> generators on these objects? (ii) <em>Likelihood against quality</em>: the ELBO of VAEs and diffusions (ch.&nbsp;3, 5) is an <em>uncontrolled</em> bound — the gap between ELBO and log-likelihood can be enormous without the samples suffering, or the opposite; and for autoregressive models (ch.&nbsp;2), the exact likelihood depends on an arbitrary order — what invariant quantity do they <em>really</em> optimize? These two questions condition any theory of learning for graph generators — the natural extension of the Statistical Learning Theory and Advanced Deep Learning modules.</p>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Problem</th>
<th style="text-align: left;">2026 state</th>
<th style="text-align: left;">Direction</th>
<th style="text-align: left;">Related modules</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Evaluation (10.1)</td>
<td style="text-align: left;">conventional MMD/FCD, known biases</td>
<td style="text-align: left;">learned critics, task-based evaluation, affordable GW</td>
<td style="text-align: left;">OT, Multimodal GenAI ch.&nbsp;8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Global constraints (10.2)</td>
<td style="text-align: left;">auxiliary losses, repair</td>
<td style="text-align: left;">guaranteed projection in diffusion, solvers</td>
<td style="text-align: left;">Control in GenAI ch.&nbsp;3, 8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Scale (10.3)</td>
<td style="text-align: left;">generalized <span class="math inline">\mathcal{O}(n^2)</span> fr</td>
<td style="text-align: left;">agments, latent, subgraphs St</td>
<td style="text-align: left;">atistical Learning Theory</td>
</tr>
<tr class="even">
<td style="text-align: left;">LLMs (10.4)</td>
<td style="text-align: left;">SMILES + efficient agents, weak guarantees</td>
<td style="text-align: left;">graph foundations, verified hybrids</td>
<td style="text-align: left;">LLMs M2, Boosting/Foundation M2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Theory (10.5)</td>
<td style="text-align: left;">exchangeable complete, non-exchangeable open</td>
<td style="text-align: left;">graphexes, likelihood invariants</td>
<td style="text-align: left;">Stat. Learning Theory, Adv. Deep Learning</td>
</tr>
</tbody>
</table>
<div class="note">
<p><span class="tag">The grid of ch.&nbsp;1, closed</span> Reread the table of ch.&nbsp;1 (exchangeability / likelihood / constraints): each filled cell calls for the next empty one — VAEs trade exact likelihood for architectural exchangeability; flows buy likelihood at the price of sequential cost; diffusion buys exchangeability and parallelism at the price of hard constraints. Problem 10.2 is precisely the empty cell of the last column. Typical exam question: “place NGG, DiGress and GraphAF in the grid, and say which cell each leaves open” — if you can answer that, the module is acquired.</p>
</div>
<h2 id="ex">Exercises / Labs</h2>
<ol type="1">
<li><p><strong>Guided lab: a complete “home-grown” evaluation (the module’s lab, ch.&nbsp;6).</strong> (a) Build three reference families: 500 Erdős-Rényi graphs <span class="math inline">G(n, p{=}0.15)</span>, 500 two-block SBMs (<span class="math inline">p_{in} = 0.3</span>, <span class="math inline">p_{out} = 0.05</span>), 500 Barabási-Albert (<span class="math inline">m = 2</span>), with <span class="math inline">n \sim \mathcal{U}\{20, \dots, 40\}</span>; (b) implement the features (degree histograms, clustering coefficients, counts of 4 motifs: triangle, path of length 3, star) and the Gaussian-kernel MMD (def. 6.1), unbiased estimator; (c) compute the 3×3 MMDs families against families; (d) redo (c) with <span class="math inline">n = 50</span> then <span class="math inline">n = 2{,}000</span> samples and plot the bias; (e) bootstrap: 95% intervals on each MMD (200 resamplings); (f) write the table of ch.&nbsp;6 and conclude: which families does the MMD-spectrum separate, which does it confuse?</p>
<pre class="code"><code># lab skeleton (networkx + numpy)
import networkx as nx, numpy as np

def features(gs):                     # gs: list of graphs
    return np.array([[np.mean(list(nx.degree(g))),                  # a mean degree
                      np.mean(list(nx.clustering(g).values())),     # b clustering
                      sum(nx.triangles(g).values()) / g.number_of_nodes()]  # c triangles
                     for g in gs])

def mmd(X, Y, sigma=None):            # Gaussian kernel, median bandwidth
    Z = np.vstack([X, Y]); n, m = len(X), len(Y)
    sigma = sigma or np.median(np.linalg.norm(Z[:, None] - Z[None], axis=-1))
    K = np.exp(-np.linalg.norm(Z[:, None] - Z[None], axis=-1) ** 2 / (2 * sigma ** 2))
    return np.sqrt(K[:n, :n].sum() / (n * (n - 1)) + K[n:, n:].sum() / (m * (m - 1))
                   - 2 * K[:n, n:].mean())                          # diagonals removed</code></pre>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Guidance (expected results): the MMD clearly separates ER from the other two on degrees (Poisson distribution against heavy tail); SBM and BA are distinguished by clustering (strong in the SBM, weak in BA); with fixed features, the MMD decreases roughly as <span class="math inline">1/\sqrt{n}</span> — comparing two models at different sample sizes is invalid (ch.&nbsp;6, trap 2), the lab <em>measures</em> it. Triangles alone do not separate ER from SBM at equal mean <span class="math inline">p</span>: always report several features. The bootstrap shows overlapping intervals between close families: an MMD without an interval is not a conclusion. <span class="qed">∎</span></p>
</div></li>
<li><p><strong>Valence mask (ch.&nbsp;3).</strong> Alphabet <span class="math inline">\{C, O, N\}</span> with valences <span class="math inline">\{4, 2, 3\}</span>, single bonds only. (a) Write the masked sequential decoder (state = remaining valences <span class="math inline">r_v</span>, Proposition 3.3); (b) sample 1,000 molecules without the mask (unconstrained heads, logits <span class="math inline">\mathcal{N}(0,1)</span>) then with the mask, up to 12 atoms; (c) measure the validity (all valences exactly zero at the end of generation) and compare it with the reasoning of Proposition 3.3.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Solution: without the mask, each sampled bond violates a valence with increasing probability as generation proceeds (the <span class="math inline">r_v</span> are no longer respected); the observed validity is typically a few percent at 12 atoms — and <span class="math inline">1-(1-\varepsilon)^T \to 1</span> explains the collapse (prop. 3.3). With the mask: 100% validity <em>by construction</em> (the support is restricted to legal outputs), at the price of a slight bias if the logits are poorly calibrated — the renormalization redistributes the forbidden mass onto the legal ones. The code: maintain <span class="math inline">r_v</span>, forbid bonds <span class="math inline">b</span> with <span class="math inline">b \&gt; r_u</span> or <span class="math inline">b \&gt; r_v</span>, resample among the legal ones — eight lines, the most profitable investment of the module. <span class="qed">∎</span></p>
</div></li>
<li><p><strong>The absorbing posterior, in closed form (ch.&nbsp;5).</strong> For the <em>absorbing</em> kernel (stay in state <span class="math inline">k</span> with probability <span class="math inline">\alpha_t = 1 - \beta_t</span>, be masked otherwise: sink state <span class="math inline">[\textsf{MASK}]</span>), prove: <span class="math display">q(X_{t-1} = X_0 \mid X_t = \textsf{MASK},\ X_0) = \frac{A_{t-1}\,\beta_t}{1 - A_t}, \qquad A_t = \prod_{s \leq t} \alpha_s,</span> and check that the remaining mass is on <span class="math inline">X_{t-1} = \textsf{MASK}</span>.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Solution: <span class="math inline">X_t = \textsf{MASK}</span> occurs with probability <span class="math inline">1 - A_t</span> (complement of “never masked up to t”); jointly <span class="math inline">X_{t-1} = X_0, X_t = \textsf{MASK}</span> requires “never masked up to <span class="math inline">t-1</span> <em>then</em> masked exactly at <span class="math inline">t</span>”: probability <span class="math inline">A_{t-1}\beta_t</span>. The quotient gives the formula; the remaining mass equals <span class="math inline">(1 - A_{t-1})/(1 - A_t)</span> — the two sum to 1 since <span class="math inline">1 - A_t = (1 - A_{t-1}) + A_{t-1}\beta_t</span>. This is the D3PM-absorbing posterior: when <span class="math inline">X_t</span> is masked, <span class="math inline">X_{t-1}</span> is <em>never</em> revealed — the network must <em>guess</em> it (<span class="math inline">\hat X_0</span>) then sample it with these probabilities: the inpainting machine of ch.&nbsp;5. <span class="qed">∎</span></p>
</div></li>
<li><p><strong>Flow and guidance (ch.&nbsp;4).</strong> (a) For the <code>CouplingStep</code> of ch.&nbsp;4, show that the log-determinant of the Jacobian equals <span class="math inline">\sum_i \log s_i</span> and is computed in <span class="math inline">\mathcal{O}(d)</span>; (b) derive the guidance step: to maximize <span class="math inline">Q(G_t)</span>, show that <span class="math display">\nabla_{z_t} Q\big(G_t\big) = J_{f_\theta}(z_t)^\top\, \nabla_{x_t}\, Q\big(\mathrm{disc}(x_t)\big),</span> where <span class="math inline">\mathrm{disc}</span> is the discretization (argmax/sampling); discuss going through the discretization (straight-through gradient / Gumbel-softmax).</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Hints: (a) the Jacobian is block-triangular <span class="math inline">\begin{pmatrix} I &amp; 0 \\ \ast &amp; \mathrm{diag}(s) \end{pmatrix}</span> (prop. 4.2): the determinant is the product of the diagonals; (b) chain rule on <span class="math inline">z_t \mapsto x_t = f_\theta(z_t) \mapsto G_t</span>; since the discretization is not differentiable, one replaces it with a relaxation (temperature softmax) or propagates back the gradient of the continuous predictor: the guidance step moves <span class="math inline">z_t</span> <em>without</em> changing the weights — but each displacement pulls the trajectory away from the learned law: too large, it fabricates out-of-distribution graphs that the predictor scores well but that chemistry rejects (the fidelity/diversity trade-off of the Control module ch.&nbsp;9). <span class="qed">∎</span></p>
</div></li>
<li><p><strong>The CFG sweep (ch.&nbsp;7).</strong> Take up example 7.3 (unconditioned logits <span class="math inline">(2.0;\ 1.5;\ 0.5)</span>, conditioned <span class="math inline">(3.0;\ 0.5;\ 0.5)</span>) and plot <span class="math inline">w \mapsto</span> (probability of carbon, entropy) for <span class="math inline">w \in \{0, 1, 2, 3, 8\}</span>. Where is the “elbow”?</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Solution: guided logits <span class="math inline">u + w(c - u) = (2 + w;\ 1.5 - w;\ 0.5)</span>. <span class="math inline">w = 0</span>: probs <span class="math inline">(0.55;\ 0.33;\ 0.12)</span>, <span class="math inline">H \approx 1.15</span> nats; <span class="math inline">w = 1</span>: <span class="math inline">(0.86;\ 0.07;\ 0.07)</span>, <span class="math inline">H \approx 0.50</span>; <span class="math inline">w = 2</span>: <span class="math inline">(0.96;\ 0.01;\ 0.03)</span>, <span class="math inline">H \approx 0.19</span>; <span class="math inline">w = 3</span>: <span class="math inline">(0.987;\ 0.002;\ 0.011)</span>, <span class="math inline">H \approx 0.08</span>; <span class="math inline">w = 8</span>: carbon at 99.99%, <span class="math inline">H \approx 0</span>. Fidelity (probability of carbon) is already nearly maximal at <span class="math inline">w = 2</span> while entropy has been divided by six: the elbow is at <span class="math inline">w \approx 2</span> — beyond, one pays diversity without gaining the target. The exact curve of Theorem 9.2 of the Control module, on a single step. <span class="qed">∎</span></p>
</div></li>
<li><p><strong>Step-function graphon and triangle density (ch.&nbsp;1 and 6).</strong> Let <span class="math inline">W</span> be constant by blocks on <span class="math inline">[0,1]^2</span> with two blocks: density <span class="math inline">p</span> in the block 1 (<span class="math inline">x, y \leq \tfrac{1}{2}</span>), <span class="math inline">q</span> in block 2, <span class="math inline">r</span> between blocks. (a) Show <span class="math display">t(K_3, W) = \tfrac{1}{8}\big(p^3 + q^3 + 3 p r^2 + 3 q r^2\big)</span> (integral over the 8 block combinations); (b) verify numerically with <span class="math inline">p = 0.9</span>, <span class="math inline">q = 0.6</span>, <span class="math inline">r = 0.05</span> and by sampling a graph with <span class="math inline">n = 100</span> nodes (50/50) — why do the two coincide to within <span class="math inline">\mathcal{O}(1/\sqrt{n})</span>?</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Solution: each triplet <span class="math inline">(a, b, c)</span> of blocks contributes <span class="math inline">\tfrac{1}{8} W_{ab} W_{bc} W_{ac}</span>; <span class="math inline">(1,1,1)</span> gives <span class="math inline">p^3</span>, <span class="math inline">(2,2,2)</span> gives <span class="math inline">q^3</span>, the three permutations of <span class="math inline">(1,1,2)</span> give <span class="math inline">p r^2</span> each, those of <span class="math inline">(2,2,1)</span> give <span class="math inline">q r^2</span>. Numerically <span class="math inline">t = (0.729 + 0.216 + 0.0068 + 0.0045)/8 \approx 0.1195</span>. The sampling realizes Bernoulli variables with parameters <span class="math inline">W(x_i, x_j)</span>, iid conditionally on the latents: the empirical triangle density is an average of bounded variables — concentration (Hoeffding) around <span class="math inline">t(K_3, W)</span> at rate <span class="math inline">\mathcal{O}(1/\sqrt{n})</span>: this is the counting lemma of Theorem 1.4, verified hands in the mud. <span class="qed">∎</span></p>
</div></li>
<li><p><strong>FCD in dimension 2 (ch.&nbsp;6).</strong> Two Gaussian embedding families of diagonal <span class="math inline">\mathbb{R}^2</span>: <span class="math inline">\mu_1 = (0, 0)</span>, <span class="math inline">\Sigma_1 = \mathrm{diag}(1, 4)</span>; <span class="math inline">\mu_2 = (1, 0)</span>, <span class="math inline">\Sigma_2 = \mathrm{diag}(4, 9)</span>. Compute the Fréchet distance; what does it become if the two families have the same mean?</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Solution: for diagonal covariances, <span class="math inline">(\Sigma_1 \Sigma_2)^{1/2}</span> is diagonal with square roots of the products: <span class="math inline">\sqrt{1 \times 4} = 2</span>, <span class="math inline">\sqrt{4 \times 9} = 6</span>. Hence <span class="math inline">\\|\mu_1 - \mu_2\\|^2 = 1</span> and <span class="math inline">\mathrm{tr}(\Sigma_1 + \Sigma_2 - 2(\Sigma_1\Sigma_2)^{1/2}) = (1 + 4 + 4 + 9) - 2(2 + 6) = 2</span>: FCD <span class="math inline">= 3</span>. With equal means, only the trace remains (here 2): the FCD separates means <em>and</em> covariances — why it detects at once a shift in mean properties (logP…) and an impoverishment of diversity (reduced variances), the two typical failures of generators. <span class="qed">∎</span></p>
</div></li>
<li><p><strong>Open: text-to-graph and target features (ch.&nbsp;7, 9).</strong> (a) Ask an LLM to produce NetworkX <em>code</em> generating 500 graphs with a statistical specification (mean degree 4, clustering 0.3, n between 20 and 40) — the “Demystifying” route of ch.&nbsp;7; (b) evaluate with the MMD of lab 1 against an SBM family calibrated to the same features; (c) critique: did the LLM <em>optimize</em> the features (by reading them in the prompt) or <em>generate</em> a law (unrequested distributional properties)? Compare with the NGG approach (conditioning by features, ch.&nbsp;9): what additional guarantees does the trained model give? (Synthesis question — defense.)</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Hints: also measure <em>unrequested</em> features (spectrum, diameter, motifs): the LLM/SBM difference there is proof that the LLM satisfies the letter of the specification without capturing its distributional spirit (or the opposite); NGG, for its part, learns the law <em>conditional on the features</em> from real data — the unspecified correlations come from the data, not from the prompt. This is the exact frontier of open problem 10.4. <span class="qed">∎</span></p>
</div></li>
</ol>
<h2 id="refs">References</h2>
<ul>
<li><strong>Theory: graphons and limits</strong>: L. Lovász, <a href="https://www.ams.org/books/surv/060/">Large Networks and Graph Limits</a>, AMS Colloquium Publications 60, 2012 — the reference for the theorems of ch.&nbsp;1 (Aldous 1981 and Hoover 1979 are presented there in detail).</li>
<li><strong>Autoregressive models (ch.&nbsp;2)</strong>: J. You, R. Ying, X. Ren, W. Hamilton, J. Leskovec, <a href="https://arxiv.org/abs/1805.02663">GraphRNN: Generating Realistic Graphs with an Auto-Regressive Model</a>, ICML 2018; Y. Li, O. Vinyals, C. Dyer, R. Pascanu, P. Battaglia, <a href="https://arxiv.org/abs/1803.03324">Learning Deep Generative Models of Graphs</a> (DeepGMG), ICML 2018; W. Jin, R. Barzilay, T. Jaakkola, <a href="https://arxiv.org/abs/1802.04364">Junction Tree Variational Autoencoder</a>, NeurIPS 2018 (generation by fragments).</li>
<li><strong>VAE (ch.&nbsp;3)</strong>: M. Simonovsky, N. Komodakis, <a href="https://arxiv.org/abs/1802.03480">GraphVAE: Towards Generation of Small Graphs Using Variational Autoencoders</a>, 2018; B. Samanta, A. De, G. Jana, V. Gokkale, A. Ganguly, M. Chakraborti, <a href="https://arxiv.org/abs/1802.05283">NeVAE: A Deep Generative Model for Molecular Graphs</a>, AAAI 2019.</li>
<li><strong>Flows (ch.&nbsp;4)</strong>: C. Shi, M. Xu, Z. Zhu, W. Zhang, M. Zhang, J. Tang, <a href="https://arxiv.org/abs/2001.09382">GraphAF: A Flow-based Autoregressive Model for Molecular Graph Generation</a>, ICLR 2020; H. Cai, S. Zheng, D. Cai, T. Mu, L. Wang, <a href="https://arxiv.org/abs/2106.02634">GraphDF: A Discrete Flow Model for Molecular Graph Generation</a>, ICML 2020; D. Tran, K. H. Mai, N. Izzo, Y. Bengio, <a href="https://arxiv.org/abs/1905.10347">Discrete Flows: Invertible Generative Models of Discrete Data</a>, NeurIPS 2019; E. Hoogeboom, D. Jimenez Rezende, T. van den Berg, V. Fortuin, M. Welling, <a href="https://arxiv.org/abs/2102.05379">Argmax Flows and Multinomial Diffusion</a>, ICML 2021 (categorical discrete flips).</li>
<li><strong>Diffusion (ch.&nbsp;5)</strong>: J. Austin, D. Johnson, J. Ho, D. Tarlow, R. van den Berg, <a href="https://arxiv.org/abs/2107.03006">Structured Denoising Diffusion Models in Discrete State Spaces</a> (D3PM), NeurIPS 2021; C. Vignac, I. Krawczuk, A. Siraudin, B. Wang, V. Cevher, P. Frossard, <a href="https://arxiv.org/abs/2209.14734">DiGress: Discrete Denoising Diffusion for Graph Generation</a>, ICLR 2023 (<a href="https://github.com/cvignac/DiGress">code</a>); C. Niu, Y. Song, J. Song, S. Ermon, <a href="https://arxiv.org/abs/2003.00638">Permutation Invariant Graph Generation via Score-Based Generative Modeling</a> (EDP-GNN), AISTATS 2020; J. Jo, S. Lee, S. J. Hwang, <a href="https://arxiv.org/abs/2202.02514">Score-based Generative Modeling of Graphs via the System of Stochastic Differential Equations</a> (GDSS), ICML 2022.</li>
<li><strong>Evaluation (ch.&nbsp;6)</strong>: K. Preuer, P. Renz, T. Unterthiner, S. Hochreiter, G. Klambauer, <a href="https://arxiv.org/abs/1803.09518">Fréchet ChemNet Distance</a>, J. Chem. Inf. Model. 2018 (<a href="https://github.com/bioinf-jku/FCD">code</a>); V. P. Dwivedi, C. K. Joshi, A. T. Luu, T. Laurent, Y. Bengio, X. Bresson, <a href="https://arxiv.org/abs/2003.00982">Benchmarking Graph Neural Networks</a>, JMLR 2023.</li>
<li><strong>Molecular benchmarks (ch.&nbsp;8)</strong>: T. Sterling, J. Irwin, <a href="https://doi.org/10.1021/acs.jcim.5b00559">ZINC 15 — Ligand Discovery for Everyone</a>, J. Chem. Inf. Model. 2015; N. Brown, M. Fiscato, M. H. S. Segler, A. C. Vaucher, <a href="https://arxiv.org/abs/1811.09621">GuacaMol: Benchmarking Models for De Novo Molecular Design</a>, J. Chem. Inf. Model. 2019; D. Polykovskiy et al., <a href="https://arxiv.org/abs/1811.12823">Molecular Sets (MOSES): A Benchmarking Platform for Molecular Generation Models</a>, Front. Pharmacol. 2020; G. R. Bickerton, G. V. Paolini, J. Besnard, S. Muresan, A. L. Hopkins, <a href="https://doi.org/10.1038/nchem.1243">Quantifying the Chemical Beauty of Drugs</a> (QED), Nature Chemistry 2012; M. Olivecrona, T. Blaschke, O. Engkvist, <em>Molecular De-novo Design through Deep Reinforcement Learning</em> (REINVENT), J. Cheminformatics 9:48, 2017.</li>
<li><strong>Materials and networks (ch.&nbsp;8)</strong>: T. Xie, X. Fu, O.-E. Ganea, R. Barzilay, T. Jaakkola, <a href="https://arxiv.org/abs/2110.06197">Crystal Diffusion Variational Autoencoder for Periodic Material Generation</a> (CDVAE), ICLR 2022; C. Zeni et al., <a href="https://arxiv.org/abs/2312.03687">A Generative Model for Inorganic Materials Design</a> (MatterGen), Nature 638, 2025 (<a href="https://huggingface.co/microsoft/mattergen">models</a>); A. Bojchevski, O. Shchur, D. Zügner, S. Günnemann, <a href="https://arxiv.org/abs/1803.00816">NetGAN: Generating Graphs via Random Walks</a>, ICML 2018.</li>
<li><strong>LLMs × graphs (ch.&nbsp;7)</strong>: E. Edwards, C. Zhai, M. Ji, <a href="https://arxiv.org/abs/2204.11817">Translation between Molecules and Natural Language</a> (MolT5), EMNLP 2022; M. Krenn et al., <a href="https://arxiv.org/abs/1905.13741">SELFIES: A Robust Representation for Semantically Valid Graphs</a>, 2020; A. Bran et al., <a href="https://arxiv.org/abs/2304.05376">Augmenting Large Language Models with Chemistry Tools</a> (ChemCrow), Nature Machine Intelligence 2024; Y. Wang, R. A. Rossi, N. Park, N. K. Ahmed, D. Koutra, F. Dernoncourt, <em>Demystifying the Power of Large Language Models in Graph Generation</em>, Findings of NAACL 2025; J. Ji et al., <a href="https://arxiv.org/abs/2410.09824">Dynamic and Textual Graph Generation via Large-Scale LLM-based Agent Simulation</a>, 2024; Y. Yao et al., <a href="https://arxiv.org/abs/2403.14358">Exploring the Potential of Large Language Models in Graph Generation</a>, 2024.</li>
<li><strong>Research of the DaSciM team (ch.&nbsp;9)</strong>: G. Michel, G. Nikolentzos, J. F. Lutzeyer, M. Vazirgiannis, <a href="https://arxiv.org/abs/2306.05955">Path Neural Networks: Expressive and Accurate Graph Neural Networks</a>, ICML 2023 (<a href="https://github.com/gasmichel/PathNNs_expressive">code</a>); M. Chatzianastasis, J. F. Lutzeyer, G. Dasoulas, M. Vazirgiannis, <a href="https://arxiv.org/abs/2204.05351">Graph Ordering Attention Networks</a> (GOAT), AAAI 2023; I. Evdaimon, G. Nikolentzos, C. Xypolopoulos, A. Kammoun, et al., <a href="https://arxiv.org/abs/2403.01535">Neural Graph Generator: Feature-Conditioned Graph Generation using Latent Diffusion Models</a>, 2024 (<a href="https://github.com/iakovosevdaimon/Neural-Graph-Generator">code</a>); K. Skianis, G. Nikolentzos, M. Vazirgiannis, <a href="https://arxiv.org/abs/2409.17906">Graph Reasoning with Large Language Models via Pseudo-code Prompting</a>, 2024 (<a href="https://github.com/y3nk0/graph-reasoning-llms">code</a>); laboratory page: <a href="https://www.lix.polytechnique.fr/dascim/">DaSciM (LIX, École Polytechnique)</a>.</li>
<li><strong>Related modules</strong>: M1 foundation and overview: <a href="../m1p2-graph-ml/index.html">Graph Machine and Deep Learning</a> (ch.&nbsp;9); expressive encoders: <a href="../m2-advanced-gnn/index.html">Advanced GNN (M2)</a>; control and constraints: <a href="../m2-control-generative-ai/index.html">Control in Generative AI (M2)</a>; continuous diffusion and FID: <a href="../m1p2-multimodal-genai/index.html">Multimodal GenAI ch.&nbsp;3-4, 8</a>; agents and LLMs: <a href="../m2-large-language-models/index.html">Large Language Models (M2) ch.&nbsp;8</a>; privacy of synthetic networks: <a href="../m2-privacy-uncertainty/index.html">Privacy and Uncertainty (M2)</a>.</li>
</ul>

</main>
<footer class="foot"><p><a href="../../index.html">← Master's program</a></p></footer>
<script defer="" src="../../assets/theme.js"></script>




</body></html>