<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Deep Learning</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script>(function(){try{var t=localStorage.getItem("llga-theme");if(t==="dark"||t==="light")document.documentElement.setAttribute("data-theme",t);}catch(e){}})();</script>
<style>
  /* Keep paper.css as visual source of truth; tame Quarto chrome */
  #title-block-header { margin: 0 0 0.5rem; }
  #title-block-header .title { margin: 0 0 0.25rem; font-size: 1.85rem; font-weight: 700; }
  #title-block-header .subtitle { color: var(--soft, #555); margin: 0 0 1rem; font-size: 1.05rem; }
  div.sourceCode { background: var(--code-bg, #f7f7f7); border: 1px solid var(--hair, #e4e4e4); }
  code { background: var(--code-inline-bg, #f4f4f4); }

  /* Light (github) token colors — higher specificity beats paper.css */
  div.sourceCode pre.sourceCode code span.kw, div.sourceCode pre.sourceCode code span.cf, div.sourceCode pre.sourceCode code span.dt, div.sourceCode pre.sourceCode code span.at, div.sourceCode pre.sourceCode code span.bu, div.sourceCode pre.sourceCode code span.pp { color: #d73a49; }
  div.sourceCode pre.sourceCode code span.im, div.sourceCode pre.sourceCode code span.st, div.sourceCode pre.sourceCode code span.ch, div.sourceCode pre.sourceCode code span.ss, div.sourceCode pre.sourceCode code span.vs { color: #032f62; }
  div.sourceCode pre.sourceCode code span.co, div.sourceCode pre.sourceCode code span.an, div.sourceCode pre.sourceCode code span.cv, div.sourceCode pre.sourceCode code span.do, div.sourceCode pre.sourceCode code span.in { color: #6a737d; }
  div.sourceCode pre.sourceCode code span.fu { color: #6f42c1; }
  div.sourceCode pre.sourceCode code span.va { color: #e36209; }
  div.sourceCode pre.sourceCode code span.cn, div.sourceCode pre.sourceCode code span.bn, div.sourceCode pre.sourceCode code span.dv, div.sourceCode pre.sourceCode code span.fl, div.sourceCode pre.sourceCode code span.sc { color: #005cc5; }
  div.sourceCode pre.sourceCode code span.op { color: #24292e; }
  /* Dark mode token colors (github highlight is light-oriented) */
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.kw,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.cf,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.dt,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.at,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.bu,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.pp,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.op { color: #ff7b72; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.im { color: #ff7b72; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.st,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.ch,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.ss,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.vs { color: #a5d6ff; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.cn,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.bn,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.dv,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.fl,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.sc { color: #79c0ff; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.co,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.an,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.cv,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.do,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.in { color: #8b949e; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.va { color: #ffa657; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.fu { color: #d2a8ff; }
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.kw,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.cf,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.dt,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.at,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.bu,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.pp,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.op { color: #ff7b72; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.im { color: #ff7b72; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.st,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.ch,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.ss,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.vs { color: #a5d6ff; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.cn,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.bn,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.dv,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.fl,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.sc { color: #79c0ff; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.co,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.an,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.cv,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.do,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.in { color: #8b949e; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.va { color: #ffa657; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.fu { color: #d2a8ff; }
  }

</style>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../assets/paper.css">
</head>

<body>

<p class="crumb"><a href="../../index.html">MSc&amp;T LLGA · Course notes</a></p>
<main class="paper">

<header id="title-block-header">
<h1 class="title">Deep Learning</h1>
<p class="subtitle">CSC_51054_EP · Year 1 · Period 1</p>

</header>


<h2 id="contents">Contents</h2>
<ul>
<li><a href="#intro">Introduction and overview</a></li>
<li><a href="#ch0">0. Review: matrix differential calculus and numerical stability</a></li>
<li><a href="#ch1">1. From the neuron to the deep network</a></li>
<li><a href="#ch2">2. Backpropagation</a></li>
<li><a href="#ch3">3. Optimization in practice</a></li>
<li><a href="#ch4">4. Convolutional networks (CNN)</a></li>
<li><a href="#ch5">5. Sequences: RNN, LSTM</a></li>
<li><a href="#ch6">6. Attention and transformers</a></li>
<li><a href="#ch7">7. Generative models: AE, VAE, GAN</a></li>
<li><a href="#ch8">8. Transfer learning and fine-tuning</a></li>
<li><a href="#ch9">9. Research at DaSciM (Vazirgiannis, Lutzeyer, Zhu)</a></li>
<li><a href="#ch10">10. Training in practice</a></li>
<li><a href="#ex">Exercises</a></li>
<li><a href="#refs">References</a></li>
</ul>
<h2 id="intro">Introduction and overview</h2>
<table class="caption-top">
<tbody>
<tr class="odd">
<td style="text-align: left;">Module</td>
<td style="text-align: left;">Deep Learning — SynapseS sheet 2026-2027: “Programme d’approfondissement — Apprentissage automatique et apprentissage profond” (occurrence: “Machine and Deep learning”, computer science department)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Code</td>
<td style="text-align: left;">CSC_51054_EP</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Team and workload</td>
<td style="text-align: left;">Course coordinator: Michalis Vazirgiannis · instructors: Davide Buscaldi, Jérémie Dentan, Iakovos Evdaimon, Xiao Fei, Johannes Lutzeyer (occurrence coordinator), Christos Xypolopoulos (École Polytechnique) · 36&nbsp;h in person (lecture / small-class split not published on the sheet) · 4.5&nbsp;ECTS · teaching language: English · from perceptrons to transformers, with the “graph” reading that prepares the Graph ML module.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Status in the program</td>
<td style="text-align: left;"><span class="badge recommended">Recommended — LLGA track</span> M1 · S1 / Period&nbsp;1 (fall semester, from 17/09/26 to 18/12/26)</td>
</tr>
</tbody>
</table>
<p><strong>Audience</strong>: an engineer who has already trained an MNIST-like MLP (or a toy CNN) and wants to understand <em>why</em> it converges — or blows up into NaNs — before opening Cybenko. <strong>Empirical first</strong>: a stuck loss, a vanishing gradient, 99% train / 70% test accuracy; only then do we name depth, activations, backprop.</p>
<p>From perceptrons to transformers: networks, backpropagation, CNNs, RNNs, attention, generative models. The program’s LLMs are transformers; without this module, architecture, training and fine-tuning stay opaque. Guiding thread: a network <em>is</em> a computation graph; attention is reread as a GNN in Period&nbsp;2.</p>
<h3 id="what-you-will-be-able-to-do">What you will be able to do</h3>
<ul>
<li>Build a neural network from scratch: layers, activations, initialization, and understand what depth buys.</li>
<li>Unroll backpropagation by hand on a small network, and code it in PyTorch without copying a tutorial.</li>
<li>Diagnose a failing training run: gradient explosion/vanishing, learning rate, normalization, numerical stabilization.</li>
<li>Choose an architecture according to the data: CNNs for images, RNN/LSTM for sequences, transformers for everything else.</li>
<li>Explain the attention mechanism and the transformer architecture, up to the explicit link with GNNs.</li>
<li>Distinguish the generative families: autoencoders, VAEs, GANs — their objectives, their losses, their uses.</li>
<li>Adapt a pretrained model to a new task by transfer learning and fine-tuning, with the right layer freezing/tuning reflexes.</li>
<li>Launch a realistic training run: GPU, mixed precision, experiment tracking, reproducibility.</li>
</ul>
<h3 id="official-objectives-and-syllabus-2026-2027-catalog">Official objectives and syllabus (2026-2027 catalog)</h3>
<p><strong>Official objectives</strong>: the SynapseS sheet does not publish a separate “objectives” block (“not disclosed”); the intentions of the course can be read in its detailed syllabus and its official keywords — <em>machine learning, deep learning, artificial intelligence, graph neural networks</em>. Reformulated: build the complete path of machine learning, from the fundamental paradigms (supervised, unsupervised, reinforcement) to neural networks and deep learning (convolutional and recurrent architectures, modern NLP, generative models); the official presence of “graph neural networks” among the keywords confirms the “graph” reading adopted by this material. The following table maps the nine blocks of the official detailed syllabus to our chapters.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Block of the official syllabus</th>
<th style="text-align: left;">Course section that covers it</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">General introduction to machine learning (paradigms, pipelines)</td>
<td style="text-align: left;">twin module <a href="../m1p1-machine-learning/index.html">Machine Learning</a> (MDC_51006_EP), ch.&nbsp;1 and 9; here, ch.&nbsp;0 as immediate preparation</td>
</tr>
<tr class="even">
<td style="text-align: left;">Supervised learning (generative and non-generative methods, naive Bayes classification, decision trees)</td>
<td style="text-align: left;"><a href="../m1p1-machine-learning/index.html">Machine Learning</a> module, ch.&nbsp;1, 2, 3 and 5 — the official course covers ML <em>and</em> DL in a single sheet; the “machine learning” half is carried by this twin module of the track</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Unsupervised learning (dimensionality reduction, clustering)</td>
<td style="text-align: left;"><a href="../m1p1-machine-learning/index.html">Machine Learning</a> module, ch.&nbsp;6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Advanced concepts (regularization, model selection, feature selection, ensemble methods)</td>
<td style="text-align: left;"><a href="../m1p1-machine-learning/index.html">Machine Learning</a> module, ch.&nbsp;2, 5 and 9; here ch.&nbsp;3 (regularization through optimization) and ch.&nbsp;8 (reuse of pretrained models)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kernels (introduction, support vector machines)</td>
<td style="text-align: left;"><a href="../m1p1-machine-learning/index.html">Machine Learning</a> module, ch.&nbsp;3 (SVM) and 4 (kernels and RKHS)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Neural networks (perceptrons, backpropagation of the gradient)</td>
<td style="text-align: left;">ch.&nbsp;1 (from the neuron to the deep network) and ch.&nbsp;2 (backpropagation)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Deep learning I (convolutional¹, recurrent networks, applications)</td>
<td style="text-align: left;">ch.&nbsp;4 (CNN) and ch.&nbsp;5 (RNN, LSTM)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Deep learning II (modern natural language processing, unsupervised deep learning, embeddings, autoencoders, generative adversarial networks)</td>
<td style="text-align: left;">ch.&nbsp;6 (attention and transformers), ch.&nbsp;7 (AE, VAE, GAN) and ch.&nbsp;8 (transfer learning)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Reinforcement learning</td>
<td style="text-align: left;">section 1.4 “Beyond supervised: reinforcement learning” (introduction to the paradigm); the full treatment is in the <a href="../m1p2-reinforcement-learning/index.html">Reinforcement Learning and Autonomous Agents</a> module (Period&nbsp;2)</td>
</tr>
</tbody>
</table>
<p>¹&nbsp;The official sheet writes “réseaux de neurones conventionnels” (“conventional neural networks”), to be read as “convolutional” in view of the listed applications. These materials follow the “deep learning” half of the course and refer the “machine learning” half to the twin module <a href="../m1p1-machine-learning/index.html">Machine Learning</a>: this is an organizational choice of the LLGA track, honestly flagged here. In return, these materials go beyond the official syllabus on three points: the detailed treatment of attention and transformers (the syllabus stops at “modern natural language processing”), transfer learning and fine-tuning (ch.&nbsp;8), and large-scale training in practice (ch.&nbsp;10: GPU, mixed precision, reproducibility) — deliberate additions of the track.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Official field</th>
<th style="text-align: left;">Published value (SynapseS 2026-2027)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Fields</td>
<td style="text-align: left;">Computer Science</td>
</tr>
<tr class="even">
<td style="text-align: left;">Workload</td>
<td style="text-align: left;">36&nbsp;h in person (lecture / small-class split not published) · enrollment / 156</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Period / language</td>
<td style="text-align: left;">Fall semester, period 1 (17/09/26 – 18/12/26) · English</td>
</tr>
<tr class="even">
<td style="text-align: left;">Prerequisites</td>
<td style="text-align: left;">Not disclosed (empty tab on the sheet)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Assessment</td>
<td style="text-align: left;">Numerical grade out of 20 · resit allowed (depending on the degree: resit grade kept or max of the two); course validated if final grade ≥ 10 · the grade counts toward the GPA · ECTS: 5 for École Polytechnique degrees, masters and exchange programs; 4.5 for MScT tracks (value retained for the LLGA) · the breakdown of assessments is not published (“not disclosed”)</td>
</tr>
</tbody>
</table>
<h3 id="where-this-course-fits-in-the-program">Where this course fits in the program</h3>
<p>Recommended option of the LLGA track in Year&nbsp;1 · Period&nbsp;1 (36&nbsp;h, 4.5&nbsp;ECTS), right after the <a href="../m1p1-machine-learning/index.html">Machine Learning</a> module, of which it is the natural continuation: the perceptron is reread there as a linear model, optimization as stochastic gradient descent. The official 2026-2027 sheet publishes no formal prerequisites (“not disclosed”); the positioning below describes the foundations actually assumed. The two refreshers — <a href="../m1p1-refresher-statistics/index.html">Refresher in Statistics</a> and <a href="../m1p1-refresher-cs/index.html">Refresher in Computer Science</a> — are assumed acquired, notably NumPy matrix computation for the labs.</p>
<p>Downstream, this module is the mandatory gateway to the whole “large models” part of the program: <a href="../m1p2-nlp-text-mining/index.html">Introduction to Text Mining and NLP</a> and <a href="../m2-large-language-models/index.html">Large Language Models</a> (M2) build directly on the “Attention and transformers” chapter; <a href="../m1p2-multimodal-genai/index.html">Multimodal Generative AI</a> extends the generative models (VAE, GAN) and fine-tuning. The attention chapter is also reread as a GNN in the <a href="../m1p2-graph-ml/index.html">Graph Machine and Deep Learning for Generative AI</a> module: a transformer processes a set of tokens as a complete graph, and this reading unifies the two sides of the program.</p>
<p>The “Training in practice” chapter finally prepares the large-scale projects of Period&nbsp;2 and the internships: this is where research code becomes engineering code.</p>
<h3 id="course-outline">Course outline</h3>
<ul>
<li><strong>Review: matrix differential calculus and numerical stability</strong>: gradients of matrix functions and conditioning — the background that avoids 80% of training bugs.</li>
<li><strong>From the neuron to the deep network</strong>: perceptron, activations, initialization, expressivity of depths — and, in closing (section&nbsp;1.4), the reinforcement learning paradigm required by the official syllabus.</li>
<li><strong>Backpropagation</strong>: the chain rule on a computation graph, unrolled then automated.</li>
<li><strong>Optimization in practice</strong>: SGD and variants (momentum, Adam), learning-rate scheduling, batch normalization.</li>
<li><strong>Convolutional networks (CNN)</strong>: convolution, pooling, classical architectures — learned vision.</li>
<li><strong>Sequences: RNN, LSTM</strong>: processing the sequential before attention, and understanding their limits.</li>
<li><strong>Attention and transformers</strong>: the mechanism underlying LLMs, also read as message passing on a graph.</li>
<li><strong>Generative models: AE, VAE, GAN</strong>: representing and generating data, three strategies compared.</li>
<li><strong>Transfer learning and fine-tuning</strong>: reusing a pretrained model — the most frequent professional gesture.</li>
<li><strong>Research at DaSciM (Vazirgiannis, Lutzeyer, Zhu)</strong>: the research of Michalis Vazirgiannis, Johannes Lutzeyer and Ye Zhu, from transformers to graphs.</li>
<li><strong>Training in practice</strong>: GPU, mixed precision, experiment tracking — from research code to reproducible code.</li>
</ul>
<h3 id="how-to-study-this-module">How to study this module</h3>
<ul>
<li>Take the review chapter seriously: numerical stability and matrix computation are presented there because they condition backpropagation, the pivotal chapter of the course.</li>
<li>Unroll backpropagation by hand on a two-layer network before coding it: this is the exercise that separates those who understand from those who copy.</li>
<li>Run all the notebooks: the course alternates derivation and experiment, and each chapter has its PyTorch lab whose reflexes (shapes, dtypes, device) serve until M2.</li>
<li>After the attention chapter, redraw the transformer diagram from memory and identify where a “graph” would be: this reading will be asked of you again in the <a href="../m1p2-graph-ml/index.html">Graph ML</a> module.</li>
<li>Actually fine-tune a small pretrained model on your own data: the transfer learning chapter is a gesture, not a reading.</li>
<li>If you have a gap in optimization or generalization, go back to the <a href="../m1p1-machine-learning/index.html">Machine Learning</a> module: chapters 2 and 3 here are its direct continuation.</li>
</ul>
<div class="note">
<p><span class="tag">Extrapolons note</span> LLMs × graphs: this module is the hub — the transformer already reads as a network on a graph. Large-model engineering or a PhD: hands-on training mastery (shapes, LR, NaNs) matters as much as the architecture on the slide.</p>
</div>
<h2 id="ch0">0. Review: matrix differential calculus and numerical stability</h2>
<p>Deep learning is, 90% of it, differential calculus applied to functions with billions of parameters. This chapter consolidates the L3 tools we will need every week: differentiation of matrix functions, the central limit theorem (to understand why SGD works) and a bit of numerical stability (to understand why naive implementations produce <code>NaN</code>s).</p>
<div class="recap">
<div class="recap-title">
<p>L3 review — the basic mechanics</p>
</div>
<ul>
<li><strong>Chain rule</strong>: <span class="math inline">(g \circ f)'(x) = g'(f(x))\, f'(x)</span>; in dimension: <span class="math inline">\nabla (g \circ f)(x) = J_f(x)^\top \nabla g(f(x))</span>, where <span class="math inline">J_f</span> is the Jacobian matrix <span class="math inline">(J_f)_{ij} = \partial f_i / \partial x_j</span>.</li>
<li><strong>Gradient of quadratic forms</strong>: <span class="math inline">\nabla_x \tfrac12\|Ax - b\|^2 = A^\top(Ax - b)</span> and <span class="math inline">\nabla_x x^\top A x = (A + A^\top)x</span>.</li>
<li><strong>Derivatives of the usual activations</strong>: <span class="math inline">\sigma' = \sigma(1-\sigma)</span>, <span class="math inline">\tanh' = 1 - \tanh^2</span>, <span class="math inline">\mathrm{ReLU}' = \mathbf{1}_{x&gt;0}</span>, and for the softmax <span class="math inline">\hat y = \mathrm{softmax}(z)</span>: <span class="math inline">\partial \hat y_k / \partial z_j = \hat y_k(\delta_{kj} - \hat y_j)</span>.</li>
<li><strong>CLT</strong>: the mean of <span class="math inline">m</span> iid variables with variance <span class="math inline">\sigma^2</span> fluctuates around its expectation with standard deviation <span class="math inline">\sigma/\sqrt m</span> (cf.&nbsp;Refresher Statistics module).</li>
</ul>
</div>
<h3 id="differentiation-of-matrix-functions">0.1. Differentiation of matrix functions</h3>
<p>A network’s parameters are <em>matrices</em>; one must know how to differentiate with respect to a matrix. The most convenient convention: the gradient of a function <span class="math inline">f : \mathbb{R}^{m \times n} \to \mathbb{R}</span> is the matrix <span class="math inline">G</span> such that <span class="math inline">f(X + H) = f(X) + \langle G, H\rangle + o(\|H\|)</span> with the Frobenius inner product <span class="math inline">\langle G, H \rangle = \mathrm{tr}(G^\top H)</span>. Three identities suffice for this whole course.</p>
<div class="prop">
<p><span class="tag">Proposition 0.1 — Useful differential identities</span> For <span class="math inline">X \in \mathbb{R}^{m \times n}</span>, <span class="math inline">a \in \mathbb{R}^m</span>, <span class="math inline">b \in \mathbb{R}^n</span>, <span class="math inline">A</span> of compatible size: <span class="math display">\frac{\partial}{\partial X}\,\mathrm{tr}(A^\top X) = A, \qquad \frac{\partial}{\partial X}\, a^\top X b = a\, b^\top, \qquad \frac{\partial}{\partial X}\, \tfrac12\|X A - B\|_F^2 = (XA - B)A^\top.</span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>We prove the second (the others are identical). Write <span class="math inline">a^\top X b = \sum_{i,j} a_i X_{ij} b_j = \mathrm{tr}(b a^\top X)</span>. The differential is <span class="math inline">d(a^\top X b) = a^\top H b = \langle a b^\top, H\rangle</span> for any perturbation <span class="math inline">H</span>, so the gradient (in the Frobenius sense) is <span class="math inline">ab^\top</span>. For the third: <span class="math inline">f(X) = \tfrac12\|XA - B\|_F^2</span>, <span class="math inline">df = \langle XA - B,\; HA\rangle = \langle (XA-B)A^\top,\; H\rangle</span>, using the cyclicity of the trace <span class="math inline">\mathrm{tr}(M^\top H A) = \mathrm{tr}((M A^\top)^\top H)</span> with <span class="math inline">M = XA - B</span>. <span class="qed">∎</span></p>
</div>
<div class="note">
<p><span class="tag">Practical rule</span> In a network, “the gradient climbs back through the transposes”: if the forward pass contains <span class="math inline">z = Wx</span>, the backward pass contains <span class="math inline">\nabla_x = W^\top \nabla_z</span> and <span class="math inline">\nabla_W = \nabla_z\, x^\top</span>. Always check the <em>dimensions</em>: <span class="math inline">\nabla_W</span> has the size of <span class="math inline">W</span>, <span class="math inline">\nabla_x</span> that of <span class="math inline">x</span>. This is the most effective quality control against backprop bugs.</p>
</div>
<h3 id="clt-and-mini-batch-noise">0.2. CLT and mini-batch noise</h3>
<p>Why optimize on <em>mini-batches</em> rather than on the whole dataset? Let <span class="math inline">\mathcal{D} = (\xi_1, \dots, \xi_N)</span> be iid and the empirical loss <span class="math inline">L(\theta) = \frac1N \sum_i \ell(\theta; \xi_i)</span>. The mini-batch gradient <span class="math inline">B = (\xi_{i_1}, \dots, \xi_{i_m})</span> is <span class="math inline">\hat g(\theta) = \frac1m \sum_{j=1}^m \nabla_\theta \ell(\theta; \xi_{i_j})</span>.</p>
<div class="prop">
<p><span class="tag">Proposition 0.2 — The stochastic gradient is an unbiased estimator with <span class="math inline">1/\sqrt m</span> noise</span> <span class="math inline">\mathbb{E}[\hat g] = \nabla L</span> and, if the individual gradients have finite covariance <span class="math inline">\Sigma = \mathrm{Cov}(\nabla \ell(\theta; \xi))</span>, then <span class="math display">\mathrm{Cov}(\hat g) = \frac{1}{m}\,\Sigma.</span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Linearity of expectation and uniform sampling: <span class="math inline">\mathbb{E}[\nabla \ell(\theta;\xi_i)] = \nabla L</span>. For the covariance, the draws are independent: <span class="math inline">\mathrm{Cov}(\tfrac1m\sum_j G_j) = \tfrac{1}{m^2}\sum_j \mathrm{Cov}(G_j) = \tfrac1m \Sigma</span>, where <span class="math inline">G_j = \nabla \ell(\theta; \xi_{i_j})</span>. The standard deviation of the estimation therefore decreases as <span class="math inline">\|\Sigma\|^{1/2}/\sqrt m</span>: multiplying the batch size by 100 divides the noise by only 10 — an economic argument for small batches, completed in chapter 3 (the noise also has a <em>beneficial</em> exploration effect). <span class="qed">∎</span></p>
</div>
<h3 id="numerical-stability-softmax-and-the-log-sum-exp-trick">0.3. Numerical stability: softmax and the log-sum-exp trick</h3>
<p>The softmax <span class="math inline">\hat y_i = e^{z_i} / \sum_j e^{z_j}</span> appears in all classification losses and in attention. In floating-point precision (float32, max <span class="math inline">\approx 3{,}4 \times 10^{38}</span>), the naive implementation <em>overflows</em>: <span class="math inline">e^{1000} = \infty</span>, and <span class="math inline">\infty/\infty = \mathrm{NaN}</span>. The universal trick is to subtract the maximum before exponentiating.</p>
<div class="prop">
<p><span class="tag">Proposition 0.3 — log-sum-exp identity and stable softmax</span> Set <span class="math inline">\mathrm{LSE}(z) = \log \sum_{j=1}^n e^{z_j}</span> and <span class="math inline">m = \max_j z_j</span>. Then: <span class="math display">\mathrm{LSE}(z) = m + \log \sum_{j=1}^n e^{z_j - m}, \qquad m \;\le\; \mathrm{LSE}(z) \;\le\; m + \log n,</span> <span class="math display">\mathrm{softmax}(z)_i = \frac{e^{z_i - m}}{\sum_j e^{z_j - m}},</span> and this last form never overflows.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Factorization: <span class="math inline">\sum_j e^{z_j} = e^{m} \sum_j e^{z_j - m}</span>, hence <span class="math inline">\mathrm{LSE}(z) = m + \log \sum_j e^{z_j - m}</span>. Since <span class="math inline">0 &lt; e^{z_j - m} \le e^0 = 1</span> and at least one term equals exactly 1 (that of the maximum), the sum lives in <span class="math inline">[1, n]</span>, giving the bracket. For the softmax, dividing numerator and denominator by <span class="math inline">e^m &gt; 0</span> does not change the value. Stability: all the exponents <span class="math inline">z_i - m \le 0</span>, so each <span class="math inline">e^{z_i - m} \in (0, 1]</span>: no overflow, and the dominant term of the denominator equals exactly 1, so the result stays accurate even when the other terms underflow toward 0 (which is harmless: the softmax simply tends toward a one-hot). <span class="qed">∎</span></p>
</div>
<div class="sourceCode" id="cb1"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>z <span class="op">=</span> torch.tensor([<span class="fl">1000.</span>, <span class="fl">1001.</span>, <span class="fl">999.</span>])</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># print(torch.softmax(z, 0))          # NaN with a naive implementation</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(torch.logsumexp(z, <span class="dv">0</span>))          <span class="co"># 1001.4076: stable (PyTorch always applies it)</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(torch.softmax(z <span class="op">-</span> z.<span class="bu">max</span>(), <span class="dv">0</span>))  <span class="co"># stable form: [0.2447, 0.6652, 0.0900]</span></span></code></pre></div>
<div class="note">
<p><span class="tag">Numerical culture</span> This section also prepares chapter 10: most NaNs during training come from an unprotected softmax/exponent, from the log of a zero probability (one minimizes <span class="math inline">-\log p</span> via log-softmax, never <span class="math inline">-\log(\mathrm{softmax})</span>), or from a too-large learning rate. The rule: when a NaN appears, walk back up the forward pass layer by layer until you find the first infinite activation.</p>
</div>
<h2 id="ch1">1. From the neuron to the deep network</h2>
<p>Concrete scene: 2-layer MLP on MNIST-like data, ReLU, SGD. After 5 epochs, train loss ~0.08 and test ~0.35; you add an 8th layer and the loss freezes (or becomes NaN). This is not “deep learning is magic”: it is mis-calibrated initialization, activation and depth. This chapter names these objects — neuron, MLP, non-linearity — before the universal approximation theorem.</p>
<div class="note">
<p><span class="tag">What breaks</span> Stacking linear layers with no activation (the net collapses to one affine map); skipping initialization (vanishing); judging a run on train alone. All three sabotage an LLM fine-tune as badly as a toy MLP.</p>
</div>
<div class="def">
<p><span class="tag">Definition 1.1 — Artificial neuron and MLP</span> A neuron computes <span class="math inline">h = \sigma(\langle w, x\rangle + b)</span> with <span class="math inline">\sigma</span> a nonlinear <strong>activation function</strong>. A <strong>multilayer perceptron</strong> of depth <span class="math inline">L</span> stacks: <span class="math display">h^{(0)} = x, \qquad h^{(\ell)} = \sigma\big(W^{(\ell)} h^{(\ell-1)} + b^{(\ell)}\big), \qquad f_\theta(x) = W^{(L)} h^{(L-1)} + b^{(L)}.</span> Without <span class="math inline">\sigma</span>, the network would reduce to a single affine map (exercise 2): nonlinearity is the price of expressivity. Parameter size: <span class="math inline">\|\theta\| = \sum_\ell (n_{\ell} n_{\ell-1} + n_\ell)</span>.</p>
</div>
<h3 id="the-universal-approximation-theorem">1.1. The universal approximation theorem</h3>
<div class="thm">
<p><span class="tag">Theorem 1.2 — Universal approximation (Cybenko, 1989; Hornik, 1991)</span> Let <span class="math inline">\sigma</span> be continuous and <em>discriminatory</em> (it is not constant on any interval where a nontrivial signed measure vanishes — the sigmoid and <span class="math inline">\tanh</span> qualify). Then for every <span class="math inline">f \in \mathcal{C}(K)</span> on a compact <span class="math inline">K \subset \mathbb{R}^d</span> and every <span class="math inline">\varepsilon &gt; 0</span>, there exists <span class="math inline">g(x) = \sum_{j=1}^{J} \alpha_j\, \sigma(w_j^\top x + b_j)</span> (a single hidden layer) such that <span class="math inline">\sup_{x \in K} \|f(x) - g(x)\| \le \varepsilon</span>.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Guided sketch, in two parts — part (ii) is the technical core of Cybenko, part (i) gives its constructive intuition.</p>
<p><strong>(i) Construction by sigmoidal “gates” (one-dimensional case).</strong> Let <span class="math inline">f</span> be continuous on <span class="math inline">[0,1]</span>. A steep sigmoid <span class="math inline">\sigma(k(x-a))</span> tends toward the indicator <span class="math inline">\mathbf{1}_{x &gt; a}</span> as <span class="math inline">k \to \infty</span>; by taking differences, <span class="math display">\pi_{k}(x) = \sigma(k(x - a)) - \sigma(k(x - b)), \qquad a &lt; b,</span> tends toward <span class="math inline">\mathbf{1}_{[a,b]}(x)</span> (a gate). Since <span class="math inline">f</span> is uniformly continuous, the step function <span class="math inline">s_n = \sum_{i} f(t_i)\,\mathbf{1}_{[t_i, t_{i+1})}</span> on a subdivision of step <span class="math inline">1/n</span> satisfies <span class="math inline">\|f - s_n\|_\infty \le \omega_f(1/n) \to 0</span>. Replacing each indicator by a steep gate <span class="math inline">\pi_k</span> with <span class="math inline">k</span> large enough (the error is concentrated on two intervals of width <span class="math inline">\sim 1/k</span> around <span class="math inline">a</span> and <span class="math inline">b</span>, where it is bounded), one obtains <span class="math inline">\|f - g\|_\infty \le \varepsilon</span> with <span class="math inline">g = \sum_i f(t_i)\,\pi_{k,i}</span> — a finite linear combination of sigmoids.</p>
<p><strong>(ii) Density by Hahn–Banach (the general argument).</strong> Let <span class="math inline">\mathcal{G}</span> be the vector space spanned by the <span class="math inline">x \mapsto \sigma(w^\top x + b)</span>. Suppose the closure of <span class="math inline">\mathcal{G}</span> for <span class="math inline">\|\cdot\|_\infty</span> is not <span class="math inline">\mathcal{C}(K)</span>. By the Hahn–Banach theorem (separation of a missing dense subspace), there exists a nonzero finite signed measure <span class="math inline">\mu</span> on <span class="math inline">K</span> such that <span class="math inline">\int g \,d\mu = 0</span> for every <span class="math inline">g \in \mathcal{G}</span>, hence in particular <span class="math display">\int_K \sigma(w^\top x + b)\, d\mu(x) = 0 \qquad \forall\, w \in \mathbb{R}^d,\ b \in \mathbb{R}.</span> Cybenko’s technical lemma then asserts that <span class="math inline">\mu = 0</span> — a contradiction. The idea of the lemma: if <span class="math inline">\hat\mu(t) = \int e^{t^\top x} d\mu(x)</span> denotes the Fourier–Laplace transform of <span class="math inline">\mu</span>, the vanishing above for a “rich enough” sigmoid forces <span class="math inline">\hat\mu \equiv 0</span> on an open set, hence <span class="math inline">\mu = 0</span> by injectivity of the Fourier transform on finite measures.</p>
<p><span class="qed">∎</span></p>
</div>
<div class="note">
<p><span class="tag">What the theorem does not say</span> It guarantees the <em>existence</em> of good weights, not that one can <em>find</em> them by optimization: the proof constructs sigmoids of slope <span class="math inline">k \to \infty</span>, a regime gradient descent does not explore; and the required number of neurons <span class="math inline">J</span> can be exponential in <span class="math inline">d</span>. Depth partially corrects this last point.</p>
</div>
<div class="note">
<p><span class="tag">Why depth?</span> Some functions require an <em>exponential</em> number of neurons on one layer but a <em>polynomial</em> number on several (e.g.&nbsp;parity, products). Depth factorizes representations: edges → textures → objects (vision), characters → words → syntax (NLP), neighbors → communities → graphs (Graph ML).</p>
</div>
<h3 id="initialization-derivation-of-xavier-and-he">1.2. Initialization: derivation of Xavier and He</h3>
<p>A bad initialization produces activations that explode or vanish <em>from the forward pass onward</em>. Analyze a linear layer <span class="math inline">a = Wh</span> with <span class="math inline">h \in \mathbb{R}^{n_{\mathrm{in}}}</span>, <span class="math inline">W \in \mathbb{R}^{n_{\mathrm{out}} \times n_{\mathrm{in}}}</span>, iid centered weights of variance <span class="math inline">v_W</span>, iid centered inputs of variance <span class="math inline">v_h</span>, independent of the weights.</p>
<div class="prop">
<p><span class="tag">Proposition 1.3 — Forward and backward variance</span> <span class="math display">\mathrm{Var}(a_i) = n_{\mathrm{in}}\, v_W\, v_h \quad\text{(forward pass)}, \qquad \mathrm{Var}\big[(\nabla_h)_j\big] = n_{\mathrm{out}}\, v_W\, v_\delta \quad\text{(backward pass, } \nabla_h = W^\top \delta\text{)}.</span> To preserve the variance in both directions, one needs <span class="math inline">v_W = 1/n_{\mathrm{in}}</span> and <span class="math inline">v_W = 1/n_{\mathrm{out}}</span> simultaneously; the harmonic compromise of Glorot &amp; Bengio (2010) is <span class="math inline">v_W = 2/(n_{\mathrm{in}} + n_{\mathrm{out}})</span>.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Forward pass: <span class="math inline">a_i = \sum_{j=1}^{n_{\mathrm{in}}} W_{ij} h_j</span>. The terms are independent and centered, so the variance of the sum is the sum of the variances: <span class="math inline">\mathrm{Var}(a_i) = \sum_j \mathrm{Var}(W_{ij})\,\mathrm{Var}(h_j) = n_{\mathrm{in}} v_W v_h</span> (<span class="math inline">\mathbb{E}[W_{ij}h_j] = \mathbb{E}[W_{ij}]\mathbb{E}[h_j] = 0</span>). Backward pass: symmetric computation on the columns, <span class="math inline">(\nabla_h)_j = \sum_{i=1}^{n_{\mathrm{out}}} W_{ij} \delta_i</span>. Wanting <span class="math inline">n_{\mathrm{in}} v_W \approx 1</span> and <span class="math inline">n_{\mathrm{out}} v_W \approx 1</span>, the harmonic mean <span class="math inline">2/(n_{\mathrm{in}}+n_{\mathrm{out}})</span> approximates both constraints. <span class="qed">∎</span></p>
</div>
<div class="note">
<p><span class="tag">He (2015) for ReLU</span> ReLU zeroes half of its inputs: if <span class="math inline">h = \mathrm{ReLU}(a)</span> with <span class="math inline">a</span> centered, then <span class="math inline">\mathbb{E}[h^2] = \tfrac12 \mathrm{Var}(a)</span>. To compensate this <span class="math inline">\tfrac12</span> factor, He et al.&nbsp;(2015) propose <span class="math inline">v_W = 2/n_{\mathrm{in}}</span> (and similarly a <span class="math inline">2/(n_{\mathrm{in}} n_{\mathrm{prev}}^{2})</span>-style term for the backward pass). In practice: <code>nn.init.kaiming_normal_</code> for ReLU/GELU, <code>xavier_normal_</code> for tanh. Finally, <em>zero</em> initialization breaks the symmetry forever: all the neurons of a layer would receive the same gradient and remain identical.</p>
</div>
<h3 id="activation-functions-compared">1.3. Activation functions, compared</h3>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Activation</th>
<th style="text-align: left;">Definition / derivative</th>
<th style="text-align: left;">Advantages</th>
<th style="text-align: left;">Pathologies</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sigmoid</td>
<td style="text-align: left;"><span class="math inline">\sigma' = \sigma(1-\sigma) \le \tfrac14</span> proba</td>
<td style="text-align: left;">bilities, LSTM gates satur</td>
<td style="text-align: left;">ation, max gradient 1/4, not centered</td>
</tr>
<tr class="even">
<td style="text-align: left;">tanh</td>
<td style="text-align: left;"><span class="math inline">1 - \tanh^2</span> ce</td>
<td style="text-align: left;">ntered (Xavier) sa</td>
<td style="text-align: left;">turation at the extremes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ReLU</td>
<td style="text-align: left;"><span class="math inline">\max(0,x)</span>, derivative <span class="math inline">\mathbf{1}_{x&gt;0}</span> cons</td>
<td style="text-align: left;">tant derivative 1, sparse, fast dyin</td>
<td style="text-align: left;">g ReLU: neuron stuck at 0 if pre-activation always negative</td>
</tr>
<tr class="even">
<td style="text-align: left;">Leaky ReLU</td>
<td style="text-align: left;"><span class="math inline">\max(\alpha x, x)</span> no</td>
<td style="text-align: left;">nzero gradient for <span class="math inline">x&lt;0</span> hyp</td>
<td style="text-align: left;">erparameter <span class="math inline">\alpha</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">GELU</td>
<td style="text-align: left;"><span class="math inline">x\,\Phi(x) = \tfrac{x}{2}\big(1 + \mathrm{erf}(x/\sqrt2)\big)</span> smooth,</td>
<td style="text-align: left;">self-gated, transformers standard cost of</td>
<td style="text-align: left;">erf (usual tanh approximation)</td>
</tr>
</tbody>
</table>
<p>The usual approximation of GELU, used in BERT/GPT, is <span class="math inline">0.5x\big(1 + \tanh\big(\sqrt{2/\pi}\,(x + 0.044715\,x^3)\big)\big)</span>. Note the kinship with ReLU — GELU weights <span class="math inline">x</span> by the probability <span class="math inline">\Phi(x)</span> that <span class="math inline">x</span> is “activated” according to a standard Gaussian: it is a soft gate, differentiable at 0.</p>
<h3 id="beyond-supervised-reinforcement-learning">1.4. Beyond supervised: reinforcement learning</h3>
<p>Everything in this chapter assumes labeled pairs <span class="math inline">(x, y)</span>. The official syllabus of the course lists a third paradigm, <strong>reinforcement learning</strong>: an <em>agent</em> interacts with an <em>environment</em> through <em>actions</em> and observes no label, but a scalar <em>reward</em>. This section sets up the framework; the full treatment (algorithms, theory, autonomous agents) is in the <a href="../m1p2-reinforcement-learning/index.html">Reinforcement Learning and Autonomous Agents</a> module (Period&nbsp;2).</p>
<div class="def">
<p><span class="tag">Definition 1.4 — Markov decision process (MDP) and policy</span> An MDP is a tuple <span class="math inline">(\mathcal{S}, \mathcal{A}, P, r, \gamma)</span>: states, actions, transition kernel <span class="math inline">P(s' \mid s, a)</span>, reward <span class="math inline">r(s, a)</span>, discount factor <span class="math inline">\gamma \in [0,1)</span>. A <strong>policy</strong> <span class="math inline">\pi(a \mid s)</span> chooses the action as a function of the state; the objective of the agent is to maximize the expectation of the discounted return <span class="math display">J(\pi) = \mathbb{E}_\pi\Big[\sum_{t \geq 0} \gamma^t\, r(S_t, A_t)\Big].</span> The <em>value function</em> <span class="math inline">V^\pi(s) = \mathbb{E}_\pi[\sum_t \gamma^t r_t \mid S_0 = s]</span> satisfies the Bellman equation <span class="math inline">V^\pi(s) = \mathbb{E}_{a \sim \pi}\big[r(s,a) + \gamma\,\mathbb{E}_{s'} V^\pi(s')\big]</span>. This is the recursion that underlies all the algorithms: evaluate <span class="math inline">V^\pi</span> (prediction), then improve <span class="math inline">\pi</span> (control).</p>
</div>
<div class="note">
<p><span class="tag">Why this paradigm concludes the chapter</span></p>
<ul>
<li><strong>Reinforcement meets depth</strong> when <span class="math inline">V^\pi</span>, <span class="math inline">\pi</span> or the function <span class="math inline">Q(s,a)</span> are <em>approximated by a network</em> (this chapter): this is deep RL — DQN for <span class="math inline">Q</span>, parametrized policies <span class="math inline">\pi_\theta</span> optimized by policy gradient. The training machinery (ch.&nbsp;2 and 3) applies as is, with in addition non-stationarity: the data depend on the current policy.</li>
<li><strong>Sequence link</strong>: an agent produces a trajectory — the exposure bias of RNNs (ch.&nbsp;5) is a degenerate special case of it, where the “reward” is the true past output.</li>
<li><strong>Program side</strong>: multi-agent RL meets the collaborative learning of the <a href="../m1p1-emerging-ml/index.html">Emerging Subjects in ML</a> module; RL is also the framework for LLM alignment (RLHF) covered in M2.</li>
</ul>
</div>
<h2 id="ch2">2. Backpropagation</h2>
<h3 id="the-theorem-and-its-proof">2.1. The theorem and its proof</h3>
<div class="thm">
<p><span class="tag">Theorem 2.1 — Backpropagation (chain rule on a computation graph)</span> Consider an acyclic computation graph whose nodes <span class="math inline">v</span> carry tensors, each node being a differentiable function of its predecessors, and <span class="math inline">L</span> the loss node. For every node <span class="math inline">v</span> other than <span class="math inline">L</span>, with successors <span class="math inline">s_1, \dots, s_k</span>: <span class="math display">\frac{\partial L}{\partial v} = \sum_{i=1}^{k} \frac{\partial L}{\partial s_i}\, \frac{\partial s_i}{\partial v},</span> with base case <span class="math inline">\partial L/\partial L = 1</span>. In particular, for an MLP where <span class="math inline">a^{(\ell)} = W^{(\ell)} h^{(\ell-1)} + b^{(\ell)}</span> and <span class="math inline">\delta^{(\ell)} = \partial \mathcal{L}/\partial a^{(\ell)}</span>: <span class="math display">\delta^{(L)} = \nabla_{a^{(L)}} \mathcal{L}, \qquad \delta^{(\ell)} = \big(W^{(\ell+1)\top} \delta^{(\ell+1)}\big) \odot \sigma'(a^{(\ell)}), \qquad \frac{\partial \mathcal{L}}{\partial W^{(\ell)}} = \delta^{(\ell)} \, h^{(\ell-1)\top}, \qquad \frac{\partial \mathcal{L}}{\partial b^{(\ell)}} = \delta^{(\ell)}.</span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>By descending induction along a reverse topological order (from outputs toward inputs). <strong>Base.</strong> <span class="math inline">\partial L/\partial L = 1</span>. <strong>Heredity.</strong> Fix <span class="math inline">v</span> and assume the formula true for all its successors <span class="math inline">s_i</span>. Since the graph is acyclic, <span class="math inline">L</span> depends on <span class="math inline">v</span> only through the values of <span class="math inline">s_1, \dots, s_k</span>; writing <span class="math inline">L = \Psi(s_1(v), \dots, s_k(v))</span> locally, the multivariate chain rule gives exactly <span class="math inline">\frac{dL}{dv} = \sum_i \frac{\partial L}{\partial s_i}\frac{ds_i}{dv}</span>. The MLP matrix formulas are merely the coordinate-by-coordinate application of this identity; the product <span class="math inline">W^{(\ell+1)\top}\delta^{(\ell+1)}</span> transposes the linearity <span class="math inline">a^{(\ell+1)} = W^{(\ell+1)}h^{(\ell)} + \dots</span>, and the term <span class="math inline">\odot\,\sigma'(a^{(\ell)})</span> comes from <span class="math inline">h^{(\ell)} = \sigma(a^{(\ell)})</span> applied component by component. <span class="qed">∎</span></p>
</div>
<div class="ex">
<p><span class="tag">Example 2.2 — Backprop by hand on a 5-node graph</span> Take <span class="math inline">f(w_1, w_2) = \tfrac12\big(w_2 \tanh(w_1 x) - t\big)^2</span> with <span class="math inline">x = 1{,}5</span>, <span class="math inline">w_1 = 0{,}3</span>, <span class="math inline">w_2 = -0{,}8</span>, <span class="math inline">t = 1</span>. Intermediate nodes: <span class="math inline">a = w_1 x</span>, <span class="math inline">h = \tanh(a)</span>, <span class="math inline">y = w_2 h</span>, <span class="math inline">\mathcal{L} = \tfrac12(y-t)^2</span>.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Forward pass</th>
<th style="text-align: left;">value</th>
<th style="text-align: left;">Local derivatives</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">a = w_1 x</span></td>
<td style="text-align: left;"><span class="math inline">0{,}45</span></td>
<td style="text-align: left;"><span class="math inline">\partial a/\partial w_1 = x = 1{,}5</span>, <span class="math inline">\partial a/\partial x = w_1</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">h = \tanh(a)</span> $</td>
<td style="text-align: left;">0{,}4219$ $</td>
<td style="text-align: left;">h/a = 1-h^2 = 0{,}8220$</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">y = w_2 h</span></td>
<td style="text-align: left;"><span class="math inline">-0{,}3375</span></td>
<td style="text-align: left;"><span class="math inline">\partial y/\partial w_2 = h</span>, <span class="math inline">\partial y/\partial h = w_2</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\mathcal{L} = \tfrac12(y-t)^2</span> $0{</td>
<td style="text-align: left;">,}8944$ $</td>
<td style="text-align: left;">artial /y = y - t = -1{,}3375$</td>
</tr>
</tbody>
</table>
<p>Backward pass (products of local derivatives): <span class="math display">\frac{\partial \mathcal{L}}{\partial w_2} = -1{,}3375 \times 0{,}4219 = -0{,}5643, \qquad \frac{\partial \mathcal{L}}{\partial w_1} = \underbrace{(-1{,}3375)(-0{,}8)}_{\partial\mathcal{L}/\partial h = 1{,}0700} \times\; 0{,}8220 \times 1{,}5 = 1{,}3193.</span> The message <span class="math inline">\partial\mathcal{L}/\partial h = 1{,}07</span> is literally the gradient “passing backward” through the multiplication — same structure as the message passing of GNNs, but on the computation graph.</p>
</div>
<h3 id="cost-memory-compute-and-how-to-reduce-them">2.2. Cost: memory, compute, and how to reduce them</h3>
<ul>
<li><strong>Complexity.</strong> A single forward pass + one backward pass cost <span class="math inline">\mathcal{O}(\|\theta\|)</span> operations (up to a constant factor): the gradient of <em>all</em> the weights for the price of about two evaluations — this is the decisive contribution of reverse mode (Linnainmaa, 1970; Rumelhart, Hinton &amp; Williams, 1986) over forward-mode differentiation, which would require <span class="math inline">\|\theta\|</span> passes.</li>
<li><strong>Memory.</strong> The backward pass needs the activations <em>of every layer</em>: memory grows like the batch size <span class="math inline">\times</span> the number of activations, not like <span class="math inline">\|\theta\|</span>. For a transformer, this is the limiting factor.</li>
<li><strong>Checkpointing</strong> (Griewank; Chen, 2016): store only one layer out of <span class="math inline">\sqrt L</span> and recompute the missing intermediates during the backward pass — <span class="math inline">\mathcal{O}(\sqrt L)</span> memory instead of <span class="math inline">\mathcal{O}(L)</span>, for ~33% extra compute. <code>torch.utils.checkpoint</code>.</li>
<li><strong>Mixed precision</strong>: store/compute in float16 or bfloat16 (2× memory and tensor throughput), while keeping float32 master copies of the weights and scaling up the loss (<em>loss scaling</em>) to prevent small gradients from canceling in fp16. bfloat16 has the same exponent range as fp32 — more robust.</li>
</ul>
<div class="sourceCode" id="cb2"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>x, y <span class="op">=</span> torch.randn(<span class="dv">8</span>), torch.randn(<span class="dv">2</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>W1 <span class="op">=</span> torch.randn(<span class="dv">64</span>, <span class="dv">8</span>, requires_grad<span class="op">=</span><span class="va">True</span>)   <span class="co"># autograd tracks the operations</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>W2 <span class="op">=</span> torch.randn(<span class="dv">2</span>, <span class="dv">64</span>, requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>loss <span class="op">=</span> <span class="fl">0.5</span> <span class="op">*</span> ((y <span class="op">-</span> W2 <span class="op">@</span> torch.relu(W1 <span class="op">@</span> x))<span class="op">**</span><span class="dv">2</span>).<span class="bu">sum</span>()</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>loss.backward()          <span class="co"># automatic backprop</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(W1.grad.shape, W2.grad.shape)           <span class="co"># same shapes as W1, W2</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Verification by finite difference (do this for every new custom gradient)</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>eps <span class="op">=</span> <span class="fl">1e-6</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> torch.no_grad():</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    W2[<span class="dv">0</span>, <span class="dv">0</span>] <span class="op">+=</span> eps<span class="op">;</span> lp <span class="op">=</span> <span class="fl">0.5</span> <span class="op">*</span> ((y <span class="op">-</span> W2 <span class="op">@</span> torch.relu(W1 <span class="op">@</span> x))<span class="op">**</span><span class="dv">2</span>).<span class="bu">sum</span>()</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    W2[<span class="dv">0</span>, <span class="dv">0</span>] <span class="op">-=</span> <span class="dv">2</span> <span class="op">*</span> eps<span class="op">;</span> lm <span class="op">=</span> <span class="fl">0.5</span> <span class="op">*</span> ((y <span class="op">-</span> W2 <span class="op">@</span> torch.relu(W1 <span class="op">@</span> x))<span class="op">**</span><span class="dv">2</span>).<span class="bu">sum</span>()</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    W2[<span class="dv">0</span>, <span class="dv">0</span>] <span class="op">+=</span> eps</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>((lp <span class="op">-</span> lm) <span class="op">/</span> (<span class="dv">2</span> <span class="op">*</span> eps), W2.grad[<span class="dv">0</span>, <span class="dv">0</span>])   <span class="co"># ~ -0.0723 twice</span></span></code></pre></div>
<div class="note">
<p><span class="tag">Computation graph</span> <code>autograd</code> dynamically builds the graph of operations (vertices = tensors, edges = operations) and applies the chain rule in reverse-mode differentiation. Deep learning <em>is</em> computation on a graph — the same idea will be applied to the data themselves in the Graph ML module. And since the graph is acyclic by construction, the induction of theorem 2.1 always runs without deadlock; RNNs (chapter 5) are “unrolled” in time precisely to recover an acyclic graph.</p>
</div>
<h2 id="ch3">3. Optimization in practice</h2>
<p>Training minimizes <span class="math inline">\mathcal{J}(\theta) = \mathbb{E}_{(x,y)\sim\mathcal{D}}\big[\ell(f_\theta(x), y)\big]</span> by <em>stochastic</em> gradient descent: at each step, the gradient is estimated on a mini-batch (proposition 0.2). This chapter analyzes <em>why</em> each ingredient of the modern recipe (momentum, Adam, warmup, normalization, regularization) is there.</p>
<h3 id="convergence-of-sgd-the-quadratic-case-fully-proved">3.1. Convergence of SGD: the quadratic case, fully proved</h3>
<p>The generic model of non-convexity is hard; the quadratic case, for its part, is solved exactly and illuminates all the others. Let <span class="math inline">f(\theta) = \tfrac12 \theta^\top A \theta - b^\top \theta</span> with <span class="math inline">A</span> symmetric positive definite, eigenvalues <span class="math inline">\lambda_1 \ge \dots \ge \lambda_d &gt; 0</span>, <span class="math inline">\lambda_1 = L</span> (Lipschitz constant of the gradient), <span class="math inline">\lambda_d = \mu</span>, condition number <span class="math inline">\kappa = L/\mu</span>. The minimizer <span class="math inline">\theta^\star = A^{-1}b</span> satisfies <span class="math inline">\nabla f(\theta^\star) = 0</span>, and the (for now deterministic) descent reads <span class="math inline">\theta_{k+1} = \theta_k - \eta (A\theta_k - b)</span>.</p>
<div class="thm">
<p><span class="tag">Theorem 3.1 — Guaranteed decrease if and only if <span class="math inline">\eta &lt; 2/L</span></span> Setting <span class="math inline">e_k = \theta_k - \theta^\star</span>: <span class="math display">e_{k+1} = (I - \eta A)\, e_k, \qquad \|e_k\| \le \rho^k \|e_0\|, \quad \rho = \max_i \|1 - \eta\lambda_i\|.</span> Convergence takes place for every <span class="math inline">e_0</span> if and only if <span class="math inline">0 &lt; \eta &lt; 2/L</span>; the optimal rate is reached for <span class="math inline">\eta = 2/(L+\mu)</span> and equals <span class="math inline">\rho = \frac{\kappa - 1}{\kappa + 1} \approx 1 - \frac{2}{\kappa}</span>.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Since <span class="math inline">\theta^\star</span> is a fixed point of the iteration, <span class="math inline">e_{k+1} = \theta_{k+1} - \theta^\star = (I - \eta A)(\theta_k - \theta^\star) = (I-\eta A)e_k</span>, hence <span class="math inline">e_k = (I - \eta A)^k e_0</span>. Diagonalize <span class="math inline">A = Q \Lambda Q^\top</span> (orthonormal): <span class="math inline">I - \eta A = Q\,\mathrm{diag}(1 - \eta\lambda_i)\,Q^\top</span>, so in the eigenbasis <span class="math inline">\|e_k\|^2 = \sum_i (1-\eta\lambda_i)^{2k} (q_i^\top e_0)^2</span>. Each eigenmode contracts by <span class="math inline">\|1-\eta\lambda_i\|</span> per step. The maximum <span class="math inline">\rho</span> of the <span class="math inline">\|1 - \eta\lambda_i\|</span> is reached at <span class="math inline">\lambda_1 = L</span> or <span class="math inline">\lambda_d = \mu</span>: one wants <span class="math inline">1 - \eta L &gt; -1</span> (i.e.&nbsp;<span class="math inline">\eta &lt; 2/L</span>) to avoid expanding the stiff modes, and <span class="math inline">\eta</span> large to contract the flat modes. The minimal <span class="math inline">\rho(\eta) = \max(\|1-\eta L\|,\, \|1-\eta\mu\|)</span> equalizes the two terms, <span class="math inline">1 - \eta\mu = \eta L - 1</span>, i.e.&nbsp;<span class="math inline">\eta = 2/(L+\mu)</span> and <span class="math inline">\rho = (L-\mu)/(L+\mu)</span>. For <span class="math inline">\kappa \gg 1</span>, <span class="math inline">\rho \approx 1 - 2/\kappa</span>: <span class="math inline">\mathcal{O}(\kappa)</span> iterations are needed to divide the error by a constant. <span class="qed">∎</span></p>
</div>
<div class="note">
<p><span class="tag">Reading for what follows</span> 1) The step is bounded by the <em>stiff</em> directions but the slowness comes from the <em>flat</em> directions: the whole art of deep optimization consists in decoupling these scales — momentum (3.2), adaptive preconditioning (3.3), activation normalization (3.5). 2) In noisy SGD, the same step <span class="math inline">2/L</span> remains the stability condition, and the residual noise fluctuates around the minimum at a distance proportional to <span class="math inline">\eta</span>: decreasing <span class="math inline">\eta</span> at the end of training (scheduling) amounts to “annealing”. 3) On real networks, the landscape is non-convex, but saddle points — not local minima — are the main obstacle, and SGD noise helps precisely to escape them.</p>
</div>
<h3 id="momentum-convergence-rates">3.2. Momentum: convergence rates</h3>
<div class="def">
<p><span class="tag">Definition 3.2 — SGD with momentum (Polyak’s heavy ball)</span> <span class="math display">v_{k+1} = \beta v_k + \hat g_k, \qquad \theta_{k+1} = \theta_k - \eta\, v_{k+1}, \qquad \beta \in [0,1),</span> with <span class="math inline">\hat g_k</span> the mini-batch estimator of the gradient. The velocity <span class="math inline">v</span> exponentially averages the past gradients: in a narrow valley where the gradient alternates <span class="math inline">+g, -g, +g, \dots</span> (zigzag), the average cancels in the direction of the oscillation and accumulates in the direction of progress.</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 3.3 — What momentum changes, mode by mode</span> On the quadratic case of theorem 3.1 (exact gradient), the error follows <span class="math inline">e_{k+1} = (1 + \beta - \eta\lambda)\, e_k - \beta\, e_{k-1}</span>. With the step <span class="math inline">\eta = (1-\beta)/L</span>: (i) the stiff mode <span class="math inline">\lambda = L</span> converges like <span class="math inline">(\sqrt\beta)^k</span>; (ii) on a flat mode, the effective rate is <span class="math inline">1 - \frac{\eta}{1-\beta}\lambda</span> — everything happens as if the step were multiplied by <span class="math inline">1/(1-\beta)</span> on the slow directions without destabilizing the stiff ones. The complete analysis (Polyak, 1964) gives a global rate in <span class="math inline">\mathcal{O}(1 - c/\sqrt\kappa)</span> instead of <span class="math inline">\mathcal{O}(1 - c/\kappa)</span>, a rate optimally reached by Nesterov’s variant.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Inject the iteration into <span class="math inline">e_k</span>: <span class="math inline">e_{k+1} = e_k - \eta A e_k + \beta(e_k - e_{k-1})</span>, giving the announced difference equation. Per eigenmode (<span class="math inline">e_k</span> collinear with the eigenvector <span class="math inline">q_i</span>), the solutions are of the form <span class="math inline">e_k = z^k q_i</span> where <span class="math inline">z</span> solves the characteristic polynomial <span class="math display">z^2 - (1 + \beta - \eta\lambda)\, z + \beta = 0.</span> Write <span class="math inline">s = 1 + \beta - \eta\lambda</span>. The product of the two roots equals <span class="math inline">\beta</span>.</p>
<p><strong>(i) Stiff modes.</strong> The roots are complex conjugates as soon as <span class="math inline">s^2 \le 4\beta</span>, and their modulus then equals <span class="math inline">\sqrt{\beta}</span> (product = <span class="math inline">\beta</span>, equal modulus for two conjugates). With <span class="math inline">\eta = (1-\beta)/L</span> and <span class="math inline">\lambda \le L</span>, one has <span class="math inline">\eta\lambda \le 1-\beta</span>, so <span class="math inline">s \in [\,2\beta,\; 1+\beta)</span>. For <span class="math inline">\lambda = L</span>: <span class="math inline">s = 2\beta</span>, and <span class="math inline">2\beta \le 2\sqrt\beta</span> whenever <span class="math inline">\beta \le 1</span> — condition satisfied, the stiff mode is damped by <span class="math inline">\sqrt\beta</span> per step.</p>
<p><strong>(ii) Flat modes.</strong> For <span class="math inline">\eta\lambda \ll 1</span>, look for the root close to 1 in the form <span class="math inline">z = 1 - c\,\eta\lambda + o(\eta\lambda)</span>. Expanding <span class="math inline">z^2 - sz + \beta = 0</span> to first order with <span class="math inline">s = 1 + \beta - \eta\lambda</span>: <span class="math inline">(1 - 2c\eta\lambda) - (1 + \beta - \eta\lambda)(1 - c\eta\lambda) + \beta = \eta\lambda\big(1 - c(1-\beta)\big) + o(\eta\lambda) = 0</span>, hence <span class="math inline">c = 1/(1-\beta)</span> and <span class="math inline">z_+ \approx 1 - \frac{\eta\lambda}{1-\beta}</span>: the effective step of the flat modes is <span class="math inline">\eta/(1-\beta)</span> — the moving average amplifies the displacement in the directions where the gradient is coherent, whereas (i) shows that it bounds the oscillation in the directions where it alternates.</p>
<p><span class="qed">∎</span></p>
</div>
<h3 id="adam-derived-step-by-step">3.3. Adam, derived step by step</h3>
<div class="thm">
<p><span class="tag">Algorithm 3.4 — Adam (Kingma &amp; Ba, 2014)</span> At each step <span class="math inline">t</span>, with stochastic gradient <span class="math inline">g_t</span>, <span class="math inline">\beta_1 = 0{,}9</span>, <span class="math inline">\beta_2 = 0{,}999</span>: <span class="math display">m_t = \beta_1 m_{t-1} + (1-\beta_1) g_t \quad\text{(moving average of the gradient)},</span> <span class="math display">v_t = \beta_2 v_{t-1} + (1-\beta_2) g_t^2 \quad\text{(moving average of squares, element-wise)},</span> <span class="math display">\hat m_t = \frac{m_t}{1 - \beta_1^t}, \qquad \hat v_t = \frac{v_t}{1 - \beta_2^t} \quad\text{(bias correction)},</span> <span class="math display">\theta_{t+1} = \theta_t - \eta\, \frac{\hat m_t}{\sqrt{\hat v_t} + \varepsilon}.</span></p>
</div>
<div class="prop">
<p><span class="tag">Proposition 3.5 — Why the bias correction is exact</span> If the gradient is constant <span class="math inline">g_t \equiv g</span>, then <span class="math inline">m_t = (1 - \beta_1^t)\, g</span> and <span class="math inline">v_t = (1-\beta_2^t)\, g^2</span> (element by element). The correction therefore divides precisely by the underestimation factor: <span class="math inline">\hat m_t = g</span>, <span class="math inline">\hat v_t = g^2</span>.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>By induction. <span class="math inline">m_t = (1-\beta_1)\sum_{k=1}^{t} \beta_1^{t-k} g_k</span>. If <span class="math inline">g_k \equiv g</span>: <span class="math inline">m_t = (1-\beta_1)\, g \sum_{j=0}^{t-1} \beta_1^{j} = (1-\beta_1)\, g\, \frac{1 - \beta_1^t}{1 - \beta_1} = (1-\beta_1^t)\, g</span> (geometric sum). Without correction, the moving average would start from <span class="math inline">m_0 = 0</span> and underestimate the gradient by a factor <span class="math inline">1-\beta_1^t</span> — by 90% at step 1 with <span class="math inline">\beta_1 = 0{,}9</span>; Adam’s first step would be ~10× too small (and for <span class="math inline">v</span>, with <span class="math inline">\beta_2 = 0{,}999</span>, ~1000× too small, which would make the update <span class="math inline">\hat m/\sqrt{\hat v}</span> <em>explode</em>). The computation is identical for <span class="math inline">v_t</span> with <span class="math inline">g^2</span>. <span class="qed">∎</span></p>
</div>
<div class="note">
<p><span class="tag">What Adam does, intuitively</span> If the gradient is constant, <span class="math inline">\hat m_t / \sqrt{\hat v_t} \approx g/\|g\| = \mathrm{sign}(g)</span>: Adam moves by a step of size ~<span class="math inline">\eta</span> <em>per coordinate</em>, independent of the gradient scale — a diagonal preconditioner that solves the decoupling <span class="math inline">\lambda_{\max}/\lambda_{\min}</span> of theorem 3.1. It is also its weakness: the weight of “calm” coordinates is relatively amplified, and the <span class="math inline">\varepsilon</span> in the denominator must stay small (<span class="math inline">10^{-8}</span>) so as not to crush small gradients.</p>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Optimizer</th>
<th style="text-align: left;">Update</th>
<th style="text-align: left;">Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SGD</td>
<td style="text-align: left;"><span class="math inline">\theta \leftarrow \theta - \eta\, \hat g</span> useful</td>
<td style="text-align: left;">noise (escapes saddle points); <span class="math inline">\eta &lt; 2/L</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Momentum</td>
<td style="text-align: left;"><span class="math inline">v \leftarrow \beta v + \hat g</span>; <span class="math inline">\theta \leftarrow \theta - \eta v</span> inertia</td>
<td style="text-align: left;">, damps zigzags (prop. 3.3)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RMSProp</td>
<td style="text-align: left;">adaptive normalization by <span class="math inline">v</span> alone</td>
<td style="text-align: left;">per-coordinate step, no momentum</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adam</td>
<td style="text-align: left;">bias-corrected first and second moments</td>
<td style="text-align: left;">universal default; tune <code>lr</code> first</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AdamW</td>
<td style="text-align: left;">Adam + decoupled decay</td>
<td style="text-align: left;">see 3.6 — the transformers standard</td>
</tr>
</tbody>
</table>
<h3 id="step-scheduling-and-warmup">3.4. Step scheduling and warmup</h3>
<ul>
<li><strong>Warmup</strong> (linear from 0 to <span class="math inline">\eta</span> over a few hundred/thousand steps): at the very start of training, the features are random and the first gradients have a large norm; moreover, the bias correction of <span class="math inline">\hat v_t</span> (prop. 3.5) divides by <span class="math inline">1 - \beta_2^t</span>, which varies fast when <span class="math inline">t</span> is small — the ratio <span class="math inline">\hat m/\sqrt{\hat v}</span> is then very noisy. A small step at the start lets the statistics settle. Pre-norm architectures (chapter 6) strongly reduce this need.</li>
<li><strong>Decay</strong>: cosine <span class="math inline">\eta_t = \eta_{\min} + \tfrac12(\eta - \eta_{\min})(1 + \cos(\pi t/T))</span>, or steps (<span class="math inline">\times 1/10</span>). Quadratic motif (theorem 3.1): close to the minimum, too large a step makes the SGD noise orbit around the solution — decreasing <span class="math inline">\eta</span> divides the oscillation radius.</li>
<li><strong>LR range test</strong> (Smith, 2015): grow <span class="math inline">\eta</span> geometrically over one epoch and plot the loss; the optimal <span class="math inline">\eta</span> sits just before the minimum of this curve (chapter 10).</li>
</ul>
<h3 id="batchnorm-and-layernorm">3.5. BatchNorm and LayerNorm</h3>
<div class="def">
<p><span class="tag">Definition 3.6 — BatchNorm (Ioffe &amp; Szegedy, 2015) and LayerNorm (Ba et al., 2016)</span> BatchNorm normalizes each <em>feature</em> over the batch (the <span class="math inline">j</span>-th coordinate of the activations, for a batch of size <span class="math inline">m</span>): <span class="math display">\hat h_{ij} = \frac{h_{ij} - \mu_j}{\sqrt{\sigma_j^2 + \varepsilon}}, \qquad \mu_j = \frac1m \sum_i h_{ij}, \quad \sigma_j^2 = \frac1m \sum_i (h_{ij} - \mu_j)^2, \qquad y_{ij} = \gamma_j \hat h_{ij} + \beta_j.</span> At inference, <span class="math inline">\mu, \sigma</span> are frozen moving averages. LayerNorm normalizes each <em>example</em> over its features (same formulas, but the means are taken over <span class="math inline">j</span> at fixed <span class="math inline">i</span>): independent of the batch, it is the norm of transformers.</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 3.7 — Reparameterization invariance</span> BatchNorm makes the layer output invariant when one replaces <span class="math inline">W</span> by <span class="math inline">cW</span> and <span class="math inline">b</span> by <span class="math inline">cb</span> (<span class="math inline">c &gt; 0</span>): the statistics become <span class="math inline">c\mu, c^2\sigma^2</span>, and <span class="math inline">\hat h</span> is unchanged. The scaling effect is absorbed by <span class="math inline">\gamma</span>.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>If <span class="math inline">h' = cWh + cb = c\,h</span>, then <span class="math inline">\mu' = c\mu</span>, <span class="math inline">{\sigma^2}' = c^2\sigma^2</span> and <span class="math inline">\hat h' = (ch - c\mu)/\sqrt{c^2\sigma^2 + \varepsilon}</span>. For <span class="math inline">\varepsilon</span> small compared to <span class="math inline">\sigma^2</span>, <span class="math inline">\hat h' \approx c(h-\mu)/(c\sigma) = \hat h</span>. The gradient of the loss with respect to the scale <span class="math inline">c</span> of the weights is then ~zero: the optimization no longer “wastes” capacity correcting the scale of the activations, only their direction. <span class="qed">∎</span></p>
</div>
<div class="note">
<p><span class="tag">The ICS controversy</span> The historical explanation — “reducing internal covariate shift” — was largely debunked by Santurkar et al.&nbsp;(2018): BatchNorm works mainly because it <em>reparameterizes</em> the problem in a Lipschitz way (smoother loss landscape, better-conditioned gradients), not because it stabilizes distributions. Practical consequences: BatchNorm requires fairly large batches (the statistics become noisy otherwise) and behaves badly at inference with batch size 1; LayerNorm has no such dependencies. In transformers, LayerNorm is applied before each sub-block (pre-norm, chapter 6).</p>
</div>
<h3 id="regularization-the-complete-tour">3.6. Regularization: the complete tour</h3>
<ul>
<li><strong>Dropout</strong> (Srivastava et al., 2014): during training, each activation is multiplied by an iid mask <span class="math inline">M_j \sim \mathrm{Bernoulli}(1-p)</span> then divided by <span class="math inline">1-p</span> (“inverted”); at inference, identity. <em>Proof that the expectation is preserved</em>: <span class="math inline">\mathbb{E}[M_j/(1-p)] = 1</span>, hence <span class="math inline">\mathbb{E}[\tilde h_j] = h_j</span> — no scaling is needed at test time. Ensemble interpretation: each mask defines a sub-network; training samples <span class="math inline">2^{n}</span> architectures sharing their weights, and inference approximately averages their consensus (the exact “mean network” approximation holds for a single final linear block; Gal &amp; Ghahramani, 2016, give it a Bayesian reading, cf.&nbsp;Emerging ML module).</li>
<li><strong>Weight decay</strong> <span class="math inline">\tfrac{\lambda}{2}\|\theta\|^2</span>: SGD + decay gives <span class="math inline">\theta \leftarrow (1 - \eta\lambda)\theta - \eta \hat g</span> — multiplicative shrinkage at each step (implicit ridge). <strong>AdamW</strong> (Loshchilov &amp; Hutter, 2017) applies the decay <em>directly</em> to the weights and not through Adam’s preconditioner: via <span class="math inline">\hat m/\sqrt{\hat v}</span>, the decay would undergo a per-coordinate normalization that makes it uneven; decoupled, it becomes a homogeneous ridge again. It is the standard for transformers (typically <span class="math inline">\lambda \sim 10^{-2}</span>, much larger than in the SGD era).</li>
<li><strong>Label smoothing</strong> <span class="math inline">\varepsilon \in [0{,}05, 0{,}2]</span>: the target becomes <span class="math inline">q_k = (1 - \varepsilon)\,\mathbf{1}[k = y] + \varepsilon/K</span>. The cross-entropy penalizes <span class="math inline">-\log p_k \to \infty</span> as <span class="math inline">p_k \to 0</span>: a hard target pushes the model toward <span class="math inline">\log p^\star \to \infty</span> (overconfidence), the smoothed target bounds the optimum at <span class="math inline">p^\star = q &lt; 1</span> and improves calibration.</li>
<li><strong>Data augmentation</strong>: inject the known invariances (rotations/crops in vision, synonyms in NLP) — the cheapest regularization in parameters; it acts on the <em>data</em>, not on the model.</li>
<li><strong>Early stopping</strong>: stop when the validation loss rises again — a regularization at zero compute cost, equivalent to an implicit penalization of the norm (cf.&nbsp;Machine Learning module, bias-variance).</li>
</ul>
<div class="note">
<p><span class="tag">Overfitting, order of profitability</span> Diagnosis: a train/validation gap that opens while the train loss decreases. Remedies in order: 1) more data / augmentation, 2) augmentation, 3) dropout, 4) weight decay, 5) shrink the model as a last resort. A model that cannot overfit a small batch (chapter 10) is often too small or badly wired — the capacity to overfit is first and foremost a <em>health check</em>.</p>
</div>
<h2 id="ch4">4. Convolutional networks (CNN)</h2>
<h3 id="discrete-convolution-general-definition-and-dimension-arithmetic">4.1. Discrete convolution: general definition and dimension arithmetic</h3>
<div class="def">
<p><span class="tag">Definition 4.1 — 1D convolution with stride, padding, dilation</span> For an input <span class="math inline">x</span> of length <span class="math inline">I</span>, a kernel <span class="math inline">k</span> of length <span class="math inline">K</span>, stride <span class="math inline">s \in \mathbb{N}^\*</span>, padding <span class="math inline">p</span> (zeros added on each side) and dilation <span class="math inline">d</span> (gap between the kernel taps): <span class="math display">(x \* k)(u) = \sum_{j=0}^{K-1} x(u + d j - d(K-1))\; k(K{-}1{-}j),</span> the output being sampled at positions <span class="math inline">u = u_0 + s\,t</span>, <span class="math inline">t = 0, 1, 2, \dots</span> In 2D, the same formula applies on each axis (kernel <span class="math inline">K_1 \times K_2</span>). The same filter is applied at every point: <strong>shared weights</strong> ⇒ translation invariance and a parameter count independent of the image size — <span class="math inline">\#</span>params <span class="math inline">= C_{\mathrm{in}} K_1 K_2 C_{\mathrm{out}} + C_{\mathrm{out}}</span>.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 4.2 — Output dimension formula (and proof)</span> <span class="math display">O = \left\lfloor \frac{I + 2p - d(K-1) - 1}{s} \right\rfloor + 1.</span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>With padding <span class="math inline">p</span>, the effective input has valid indices in <span class="math inline">[-p,\, I - 1 + p]</span>. An output position <span class="math inline">t</span> places the kernel’s <em>first</em> tap at <span class="math inline">u = s\,t - p</span> and the last at <span class="math inline">u + d(K-1)</span>; the convolution is defined only if <em>all</em> the taps fall within the valid indices: <span class="math inline">s t - p \ge 0</span> and <span class="math inline">s t - p + d(K-1) \le I - 1</span>. The number of allowed steps <span class="math inline">t</span> is therefore the number of integers in <span class="math inline">\big[0,\; \frac{I - 1 + p - d(K-1)}{s}\big]</span>, that is <span class="math inline">\lfloor (I + 2p - d(K-1) - 1)/s \rfloor + 1</span> (length of a discrete interval <span class="math inline">[0, n]</span> = <span class="math inline">n + 1</span>, with a floor for stride alignment). <span class="qed">∎</span></p>
</div>
<div class="ex">
<p><span class="tag">Example 4.3 — Immediate checks</span> Conv 3×3, padding 1, stride 1 (<span class="math inline">I=I'</span>): <span class="math inline">\lfloor (I + 2 - 2 - 1)/1 \rfloor + 1 = I</span>. Downsampling /2 with 3×3, padding 1: <span class="math inline">\lfloor (I + 2 - 2 - 1)/2 \rfloor + 1 = \lfloor (I-1)/2 \rfloor + 1</span> (for <span class="math inline">I = 224</span> (ImageNet): 112). Two 3×3 convs (stride 1) have the same receptive field as a 5×5 conv for ~2.7× fewer parameters and more nonlinearity — VGG’s argument.</p>
</div>
<h3 id="receptive-field">4.2. Receptive field</h3>
<div class="prop">
<p><span class="tag">Proposition 4.4 — Receptive field, formula by induction</span> For convolutional layers with kernels <span class="math inline">k_\ell</span>, strides <span class="math inline">s_\ell</span> (dilation 1), the receptive field of a unit of layer <span class="math inline">\ell</span> equals <span class="math display">\mathrm{RF}_1 = k_1, \qquad \mathrm{RF}_\ell = \mathrm{RF}_{\ell-1} + (k_\ell - 1)\prod_{i &lt; \ell} s_i.</span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>By induction. <em>Initialization</em>: a unit of layer 1 reads <span class="math inline">k_1</span> pixels. <em>Heredity</em>: let <span class="math inline">\Delta_{\ell}</span> be the distance (in input pixels) between the receptive fields of two <em>adjacent</em> units of layer <span class="math inline">\ell</span>. Clearly <span class="math inline">\Delta_1 = s_1</span> (shifting the output by one unit shifts the window by <span class="math inline">s_1</span>), and <span class="math inline">\Delta_\ell = s_\ell \Delta_{\ell-1} = \prod_{i \le \ell} s_i</span>. A unit of layer <span class="math inline">\ell</span> aggregates <span class="math inline">k_\ell</span> <em>contiguous</em> units of layer <span class="math inline">\ell - 1</span>: its field covers the field of one unit (RF<span class="math inline">_{\ell-1}</span>) plus the gap between the centers of the first and last aggregated neighbors, <span class="math inline">(k_\ell - 1)\Delta_{\ell-1}</span>. Hence the formula. <span class="qed">∎</span></p>
</div>
<div class="note">
<p><span class="tag">Two stacked 3×3 convs</span> RF <span class="math inline">= 3 + 2\times 1 = 5</span>: stacking beats a large kernel — depth again. In practice the theoretical receptive fields quickly exceed the image, but the <em>effective</em> field (visualized by occlusion or Cadieu et al.) grows much more slowly; low layers encode edges, high layers concepts.</p>
</div>
<h3 id="transposed-conv-deconvolution">4.3. Transposed conv (deconvolution)</h3>
<p>The gradient of the convolution with respect to the <em>input</em> is itself a convolution, by the flipped kernel and with adjusted padding — called transposed convolution, and used as is to upsample (GANs, segmentation, autoencoders). Case with no stride, no dilation: a “valid” conv (<span class="math inline">p=0</span>) maps <span class="math inline">I \to O = I - K + 1</span>; its transpose maps <span class="math inline">O \to I = O + K - 1</span> by inserting <span class="math inline">K-1</span> border zeros and convolving with the flipped kernel (proof: write <span class="math inline">\mathrm{conv}</span> as a linear map <span class="math inline">y = Cx</span> by blocks; then <span class="math inline">\nabla_x = C^\top \nabla_y</span>, and <span class="math inline">C^\top</span> is the matrix of the transposed conv). With stride and padding, the general formula: <span class="math display">I' = s\,(O - 1) - 2p + d(K-1) + \mathrm{op} + 1,</span> where <span class="math inline">\mathrm{op}</span> is an optional extra padding — the exact mirror image of theorem 4.2. Tap overlap when <span class="math inline">s &gt; 1</span> creates “checkerboard” artifacts, fixed by upsample + conv.</p>
<h3 id="historical-architectures-parameters-on-the-counter">4.4. Historical architectures, parameters on the counter</h3>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Network</th>
<th style="text-align: left;">Year</th>
<th style="text-align: left;">Key idea</th>
<th style="text-align: left;">Parameters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">LeNet-5</td>
<td style="text-align: left;">1998</td>
<td style="text-align: left;">conv + pooling + FC, gradient by backpropagation</td>
<td style="text-align: left;">$$60&nbsp;k</td>
</tr>
<tr class="even">
<td style="text-align: left;">AlexNet</td>
<td style="text-align: left;">2012</td>
<td style="text-align: left;">ReLU, dropout, GPU, augmentation — wins ImageNet</td>
<td style="text-align: left;">$$60&nbsp;M</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VGG-16</td>
<td style="text-align: left;">2014</td>
<td style="text-align: left;">uniformity: only 3×3, depth 16-19</td>
<td style="text-align: left;">$$138&nbsp;M</td>
</tr>
<tr class="even">
<td style="text-align: left;">ResNet-50</td>
<td style="text-align: left;">2015</td>
<td style="text-align: left;">residual connections, 50 layers and more</td>
<td style="text-align: left;">$$25.6&nbsp;M</td>
</tr>
</tbody>
</table>
<div class="ex">
<p><span class="tag">Example 4.5 — Counting VGG-16 parameters (a computation to redo)</span> A 3×3 block from <span class="math inline">C_{\mathrm{in}} \to C_{\mathrm{out}}</span> channels costs <span class="math inline">9\,C_{\mathrm{in}} C_{\mathrm{out}} + C_{\mathrm{out}}</span>. The first (3 → 64): <span class="math inline">9 \times 3 \times 64 + 64 = 1\,792</span>. A 64 → 64 block: <span class="math inline">9 \times 64^2 + 64 = 36\,928</span>. Summing the five stages (64, 128, 256, 512, 512), the convolutions total <span class="math inline">\approx 14{,}7</span> M — but the three fully connected layers (after flattening <span class="math inline">7 \times 7 \times 512 = 25\,088</span> features) weigh <span class="math inline">25\,088 \times 4\,096 + 4\,096 \times 4\,096 + 4\,096 \times 1\,000 \approx 123</span> M: 90% of the parameters live in the classifier! Hence global pooling (GoogLeNet) then residual blocks: ResNet-50 does better with 25.6 M — of which ~23 M in 1×1/3×3 bottleneck convs.</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 4.6 — Why residuals allow depth</span> A residual block learns <span class="math inline">h^{(\ell+1)} = h^{(\ell)} + F(h^{(\ell)})</span> (then activation/normalization). 1) <em>Trivial identity</em>: the choice <span class="math inline">F \equiv 0</span> realizes the exact identity — with standard initialization, <span class="math inline">F</span> is small, so every added block starts “close to the identity”: adding layers no longer degrades the initial model. 2) <em>Gradient without attenuation</em>: by the chain rule, <span class="math display">\frac{\partial \mathcal{L}}{\partial h^{(\ell)}} = \frac{\partial \mathcal{L}}{\partial h^{(\ell+1)}}\Big( I + \frac{\partial F}{\partial h^{(\ell)}} \Big),</span> the <span class="math inline">I</span> term transports the gradient as is, whatever the depth — direct contrast with the product of <span class="math inline">L</span> factors <span class="math inline">&lt;1</span> of RNNs (chapter 5). 3) Landscape: loss-function visualizations (Li et al., 2018) show markedly smoother valleys along the residual directions.</p>
</div>
<div class="note">
<p><span class="tag">Residuals everywhere</span> We will find <em>exactly</em> these skip connections in transformers (<span class="math inline">x + \mathrm{Attention}(\mathrm{LN}(x))</span>, chapter 6) and GNNs (skip connections of message passing, Graph ML module): everywhere one stacks blocks, the identity path protects the gradient.</p>
</div>
<div class="sourceCode" id="cb3"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn <span class="im">as</span> nn</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>conv <span class="op">=</span> nn.Conv2d(in_channels<span class="op">=</span><span class="dv">3</span>, out_channels<span class="op">=</span><span class="dv">32</span>, kernel_size<span class="op">=</span><span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># parameters: 3*3*3*32 + 32 = 896, independent of the H x W size</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.randn(<span class="dv">16</span>, <span class="dv">3</span>, <span class="dv">64</span>, <span class="dv">64</span>)        <span class="co"># batch of 16 RGB 64x64 images</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(conv(x).shape)                   <span class="co"># [16, 32, 64, 64]  (theorem 4.2 formula)</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> ResBlock(nn.Module):</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, c):</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.conv1 <span class="op">=</span> nn.Conv2d(c, c, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.conv2 <span class="op">=</span> nn.Conv2d(c, c, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.norm1, <span class="va">self</span>.norm2 <span class="op">=</span> nn.BatchNorm2d(c), nn.BatchNorm2d(c)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>        h <span class="op">=</span> torch.relu(<span class="va">self</span>.norm1(<span class="va">self</span>.conv1(x)))</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> torch.relu(x <span class="op">+</span> <span class="va">self</span>.norm2(<span class="va">self</span>.conv2(h)))   <span class="co"># skip connection</span></span></code></pre></div>
<div class="note">
<p><span class="tag">CNNs and graphs</span> A convolution is a filter applied to a regular neighborhood (a grid). The GNNs of the Graph ML module generalize this idea to <em>irregular</em> neighborhoods: the filter becomes a function of the aggregated neighbors. Same DNA: weight sharing + local aggregation. For the full link with signal processing (circular convolution, convolution theorem, spectral graph filters), cf.&nbsp;the Signal Processing module and the Graph ML module.</p>
</div>
<h2 id="ch5">5. Sequences: RNN, LSTM</h2>
<h3 id="rnn-and-backpropagation-through-time">5.1. RNN and backpropagation through time</h3>
<div class="def">
<p><span class="tag">Definition 5.1 — RNN (Elman)</span> <span class="math display">h_t = \tanh(W_h h_{t-1} + W_x x_t + b), \qquad y_t = W_y h_t</span> A hidden state that summarizes the past; weights shared across time (like the CNN kernel across space). The sequence <span class="math inline">(x_1, \dots, x_T)</span> is processed by <em>unrolling</em> the network: <span class="math inline">T</span> copies of the same block — the computation graph becomes acyclic again (chapter 2), and backprop applies to it “through time” (BPTT). Memory cost: <span class="math inline">\mathcal{O}(T)</span> activations.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 5.2 — Exponential explosion or vanishing of the gradient</span> For a loss at the final step <span class="math inline">T</span>, writing <span class="math inline">D_t = \mathrm{diag}\big(\tanh'(a_t)\big)</span>: <span class="math display">\frac{\partial \mathcal{L}_T}{\partial h_0} = \Big( \prod_{t=1}^{T} D_t\, W_h^\top \Big) \frac{\partial \mathcal{L}_T}{\partial h_T} \quad\Rightarrow\quad \Big\| \frac{\partial \mathcal{L}_T}{\partial h_0} \Big\| \;\le\; \|W_h\|^{T}\, \prod_{t=1}^{T}\|\tanh'(a_t)\|_\infty\, \Big\| \frac{\partial \mathcal{L}_T}{\partial h_T} \Big\|.</span> If <span class="math inline">\|W_h\| \cdot \max_t \|\tanh'(a_t)\|_\infty &lt; 1</span>, the gradient decays exponentially with <span class="math inline">T</span> (vanishing); if <span class="math inline">\|W_h\| &gt; 1</span> with activations away from saturation, it explodes.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>By theorem 2.1 applied to the unrolled graph, <span class="math inline">\partial \mathcal{L}_T/\partial h_{t-1} = (\partial h_t / \partial h_{t-1})^\top \partial \mathcal{L}_T/\partial h_t</span> since <span class="math inline">h_{t-1}</span> has only one successor <span class="math inline">h_t</span>. Now <span class="math inline">h_t = \tanh(W_h h_{t-1} + W_x x_t + b)</span>, so the Jacobian equals <span class="math inline">J_t = D_t W_h</span> with <span class="math inline">D_t</span> diagonal (derivative of tanh component by component). Composing from <span class="math inline">t = T</span> down to <span class="math inline">t = 1</span> and using sub-multiplicativity <span class="math inline">\|ABC\| \le \|A\|\,\|B\|\,\|C\|</span> (operator norm): <span class="math inline">\|\prod_t J_t^\top\| \le \prod_t \|J_t^\top\| \le \prod_t \|D_t\|\,\|W_h\|</span>, and <span class="math inline">\|D_t\| = \max_i \|\tanh'(a_{t,i})\| \le 1</span>, with strict inequality &lt; 1 as soon as one coordinate approaches saturation. Hence the bound: exponential decay in <span class="math inline">T</span> as soon as the per-step factor is &lt; 1, possible exponential growth when <span class="math inline">\|W_h\| &gt; 1</span> (the bound is only an upper bound, but experiments confirm both regimes; explosion is handled by <em>gradient clipping</em> — truncating <span class="math inline">\|\hat g\|</span> at a threshold — vanishing, for its part, is structural). <span class="qed">∎</span></p>
</div>
<h3 id="lstm-complete-equations-and-the-role-of-the-gates">5.2. LSTM: complete equations and the role of the gates</h3>
<div class="def">
<p><span class="tag">Definition 5.3 — LSTM (Hochreiter &amp; Schmidhuber, 1997)</span> Four “gates” (vectors of <span class="math inline">[0,1]^d</span> via sigmoids, acting as multiplicative valves) and a cell state <span class="math inline">c_t</span> that transitions <em>additively</em>: <span class="math display">f_t = \sigma(W_f h_{t-1} + U_f x_t), \qquad i_t = \sigma(W_i h_{t-1} + U_i x_t),</span> <span class="math display">o_t = \sigma(W_o h_{t-1} + U_o x_t), \qquad \tilde c_t = \tanh(W_c h_{t-1} + U_c x_t),</span> <span class="math display">c_t = f_t \odot c_{t-1} + i_t \odot \tilde c_t, \qquad h_t = o_t \odot \tanh(c_t).</span></p>
</div>
<ul>
<li><strong><span class="math inline">f_t</span>, forget gate</strong>: fraction of the old memory kept — it is what carries long memory; often initialized with <span class="math inline">b_f &gt; 0</span> (positive forget bias) so that <span class="math inline">f \approx 1</span> at the start.</li>
<li><strong><span class="math inline">i_t</span>, input gate</strong>: how much of the candidate <span class="math inline">\tilde c_t</span> is written; <strong><span class="math inline">\tilde c_t</span></strong>: the proposed content.</li>
<li><strong><span class="math inline">o_t</span>, output gate</strong>: how much of the cell is exposed in <span class="math inline">h_t</span>.</li>
<li><strong>Why it mitigates vanishing</strong>: the cell follows <span class="math inline">c_t = f_t \odot c_{t-1} + (\dots)</span>, an <em>additive highway</em> — the gradient <span class="math inline">\partial c_t/\partial c_{t-1} = \mathrm{diag}(f_t) + i_t</span>-terms stays close to the identity when <span class="math inline">f_t \approx 1</span> and <span class="math inline">i_t</span> modest, where the RNN systematically multiplied by <span class="math inline">W_h^\top D_t</span>. The product of the Jacobians can stay ~1 over long horizons: long dependencies get through. (The problem is not <em>solved</em>: for very long dependencies, attention will fix it — chapter 6.)</li>
</ul>
<div class="note">
<p><span class="tag">GRU (Cho et al., 2014) and comparison</span> <span class="math display">z_t = \sigma(W_z h_{t-1} + U_z x_t), \quad r_t = \sigma(W_r h_{t-1} + U_r x_t), \quad h_t = (1 - z_t) \odot h_{t-1} + z_t \odot \tanh\big(W h_{t-1} \odot r_t + U x_t\big).</span> Two gates instead of three, no separate cell state (<span class="math inline">z_t</span> merges forget and write, <span class="math inline">r_t</span> filters the read past): ~25% fewer parameters, generally comparable performance. In practice LSTM for long series, GRU for small datasets.</p>
</div>
<div class="note">
<p><span class="tag">Teacher forcing and exposure bias</span> When training a sequence-to-sequence model, the decoder is fed the <em>true</em> tokens (teacher forcing): the loss is computed in a single parallel pass, but the model only learns to predict <em>given the exact past</em>. At inference, it feeds on its own (possibly wrong) outputs — an exposure mismatch that makes long generations drift; mitigated by scheduled sampling or reinforcement learning (cf.&nbsp;RL module, and NLP module).</p>
</div>
<h2 id="ch6">6. Attention and transformers</h2>
<h3 id="scaled-dot-product-why-sqrtd_k">6.1. Scaled dot-product: why <span class="math inline">\sqrt{d_k}</span></h3>
<div class="def">
<p><span class="tag">Definition 6.1 — Scaled dot-product attention (Vaswani et al., 2017)</span> For tokens <span class="math inline">i = 1..n</span> with embeddings <span class="math inline">x_i</span>, one computes <span class="math display">q_i = W_q x_i,\quad k_i = W_k x_i,\quad v_i = W_v x_i,</span> <span class="math display">\mathrm{Attention}(Q, K, V) = \mathrm{softmax}\!\Big(\frac{Q K^\top}{\sqrt{d_k}}\Big) V, \qquad \alpha_{ij} = \frac{\exp(q_i^\top k_j / \sqrt{d_k})}{\sum_{j'} \exp(q_i^\top k_{j'} / \sqrt{d_k})}.</span> <strong>Multi-head</strong>: <span class="math inline">h</span> attention heads in parallel (projections <span class="math inline">W^q_m, W^k_m, W^v_m</span>, dimensions <span class="math inline">d_k = d/h</span>), concatenated then projected — several independent “communication channels”.</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 6.2 — The variance of the scores grows like <span class="math inline">d_k</span></span> If the components of <span class="math inline">q</span> and <span class="math inline">k</span> are iid, centered, with variance 1, then <span class="math inline">q^\top k = \sum_{\ell=1}^{d_k} q_\ell k_\ell</span> is centered with variance exactly <span class="math inline">d_k</span>. Without normalization, the standard deviation of the scores is <span class="math inline">\sqrt{d_k}</span> (32 for <span class="math inline">d_k = 1024</span>): the softmax becomes a one-hot argmax, its gradients vanish — saturation, cf.&nbsp;chapter 0, proposition 0.3. Dividing by <span class="math inline">\sqrt{d_k}</span> brings the variance back to 1, independent of the dimension.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Centering: <span class="math inline">\mathbb{E}[q_\ell k_\ell] = \mathbb{E}[q_\ell]\,\mathbb{E}[k_\ell] = 0</span> (independence). Variance: the terms <span class="math inline">q_\ell k_\ell</span> are mutually iid, so <span class="math inline">\mathrm{Var}(\sum_\ell q_\ell k_\ell) = \sum_\ell \mathrm{Var}(q_\ell k_\ell) = d_k\, \mathbb{E}[q_\ell^2]\mathbb{E}[k_\ell^2] = d_k</span>. After dividing by <span class="math inline">\sqrt{d_k}</span>, the variance of the normalized score equals <span class="math inline">1</span>. Consequence for saturation: the typical gaps between normalized scores are <span class="math inline">\mathcal{O}(1)</span>, the exponential ratios <span class="math inline">\exp(s_i - s_j)</span> stay in a reasonable range and the softmax keeps a nonzero gradient; without scaling, gaps of order <span class="math inline">\sqrt{d_k} \gg 1</span> produce a near one-hot distribution, whose gradient (<span class="math inline">\hat y_k(\delta_{kj} - \hat y_j)</span>) tends to 0. <span class="qed">∎</span></p>
</div>
<h3 id="block-architecture-pre-norm-rope">6.2. Block architecture: pre-norm, RoPE</h3>
<ul>
<li><strong>Post-norm</strong> (Vaswani et al., original): <span class="math inline">y = \mathrm{LN}(x + \mathrm{Att}(x))</span> — the residual connection passes <em>through</em> the normalization. <strong>Pre-norm</strong> (GPT-2 and after): <span class="math inline">y = x + \mathrm{Att}(\mathrm{LN}(x))</span> — the identity path is <em>intact</em> (proposition 4.6): the gradient reaches the input without attenuation, which makes training stable at large depth and reduces the need for warmup; a final LayerNorm compensates for the absence of output normalization. The current standard.</li>
<li><strong>RoPE</strong> (rotary position embedding, Su et al., 2021): instead of <em>adding</em> a positional code, one <em>rotates</em> each pair of coordinates <span class="math inline">(q_{2i}, q_{2i+1})</span> by an angle <span class="math inline">m\,\theta_i</span> depending on the position <span class="math inline">m</span> of the token (and on <span class="math inline">i</span>), with <span class="math inline">\theta_i = b^{-2i/d}</span>. Proof of the “relative” character: planar rotations commute and <span class="math inline">R(m)^\top R(n) = R(n - m)</span>, so <span class="math display">\langle R(m)\, q,\; R(n)\, k \rangle = q^\top R(m)^\top R(n)\, k = q^\top R(n-m)\, k,</span> the score depends only on the gap <span class="math inline">n - m</span>: position is encoded <em>within</em> the interaction, with unbounded length support — this is the encoding of modern LLMs (cf.&nbsp;LLMs module, M2).</li>
</ul>
<h3 id="costs-and-efficient-attention">6.3. Costs and efficient attention</h3>
<ul>
<li><strong>Complexity</strong>: <span class="math inline">\mathcal{O}(n^2 d)</span> time and <span class="math inline">\mathcal{O}(n^2)</span> memory (<span class="math inline">QK^\top</span> matrix of size <span class="math inline">n \times n</span> per head) — the LLM bottleneck. The MLP is <span class="math inline">\mathcal{O}(n d^2)</span>: attention dominates as soon as <span class="math inline">n \gtrsim d</span>.</li>
<li><strong>FlashAttention</strong> (Dao et al., 2022): <em>exact</em>, but IO-aware — it tiles the computation of softmax(QK^T)V into blocks loaded into SRAM (the GPU’s fast memory) and <em>never</em> writes the <span class="math inline">n \times n</span> matrix to HBM, maintaining online log-sum-exp statistics (proposition 0.3 makes the softmax incremental: blocks are merged with <span class="math inline">m</span> and the partial sum). Result: same FLOPs, <span class="math inline">\mathcal{O}(n)</span> memory, ×2 to ×4 speed in practice.</li>
<li><strong>Approximations</strong>: sparse, linear, sliding window (cf.&nbsp;LLMs module, M2).</li>
</ul>
<div class="note">
<p><span class="tag">“Graph” reading (Karpathy, 2025-2026) — the bridge to the Graph ML module</span> A transformer is a <strong>neural network on a dynamic graph</strong>:</p>
<ul>
<li>each <strong>token = a node</strong> carrying a vector;</li>
<li>attention computes <strong>weighted edges</strong> <span class="math inline">\alpha_{ij}</span> <em>from the data</em> (dynamic graph, unlike GNNs);</li>
<li><span class="math inline">\sum_j \alpha_{ij} v_j</span> is a <strong>message passing</strong>: the nodes exchange their “values”;</li>
<li>the <strong>MLP block = the local computation</strong> of each node; residual + LayerNorm = plumbing so that the “graph” stays trainable;</li>
<li>a transformer layer = <em>communication</em> (attention) then <em>computation</em> (MLP), exactly the alternation of a GNN.</li>
</ul>
<p>The LLGA program exploits this double reading: the same mathematical object seen “from inside the LLM” (M2 module) and “on structured data” (Graph ML module).</p>
</div>
<h3 id="a-complete-block-in-pytorch">6.4. A complete block in PyTorch</h3>
<div class="sourceCode" id="cb4"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch, torch.nn <span class="im">as</span> nn, torch.nn.functional <span class="im">as</span> F</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> Block(nn.Module):</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""A pre-norm transformer block: multi-head causal attention + MLP."""</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, d, n_heads, p_drop<span class="op">=</span><span class="fl">0.1</span>):</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.ln1, <span class="va">self</span>.ln2 <span class="op">=</span> nn.LayerNorm(d), nn.LayerNorm(d)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.n_heads, <span class="va">self</span>.d_head <span class="op">=</span> n_heads, d <span class="op">//</span> n_heads</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.qkv <span class="op">=</span> nn.Linear(d, <span class="dv">3</span> <span class="op">*</span> d)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.proj <span class="op">=</span> nn.Linear(d, d)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.mlp <span class="op">=</span> nn.Sequential(nn.Linear(d, <span class="dv">4</span> <span class="op">*</span> d), nn.GELU(), nn.Linear(<span class="dv">4</span> <span class="op">*</span> d, d))</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.drop <span class="op">=</span> nn.Dropout(p_drop)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):                          <span class="co"># x: (B, n, d)</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>        B, n, d <span class="op">=</span> x.shape</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>        q, k, v <span class="op">=</span> <span class="va">self</span>.qkv(<span class="va">self</span>.ln1(x)).chunk(<span class="dv">3</span>, <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>        <span class="co"># multi-head: (B, n, d) -&gt; (B, n, h, d_head) -&gt; (B, h, n, d_head)</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>        <span class="kw">def</span> split(t): <span class="cf">return</span> t.view(B, n, <span class="va">self</span>.n_heads, <span class="va">self</span>.d_head).transpose(<span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>        q, k, v <span class="op">=</span> split(q), split(k), split(v)</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>        mask <span class="op">=</span> torch.tril(torch.ones(n, n, device<span class="op">=</span>x.device))     <span class="co"># causal mask</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>        att <span class="op">=</span> F.scaled_dot_product_attention(q, k, v,            <span class="co"># softmax(QK^T/sqrt(d_head))V</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>                                             attn_mask<span class="op">=</span>mask, dropout_p<span class="op">=</span><span class="fl">0.0</span>)</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>        att <span class="op">=</span> att.transpose(<span class="dv">1</span>, <span class="dv">2</span>).reshape(B, n, d)               <span class="co"># merge the heads back</span></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> x <span class="op">+</span> <span class="va">self</span>.drop(<span class="va">self</span>.proj(att))                        <span class="co"># residual 1 (pre-norm)</span></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> x <span class="op">+</span> <span class="va">self</span>.drop(<span class="va">self</span>.mlp(<span class="va">self</span>.ln2(x)))                 <span class="co"># residual 2</span></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> x</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">0</span>)</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.randn(<span class="dv">2</span>, <span class="dv">16</span>, <span class="dv">128</span>)</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> nn.Sequential(<span class="op">*</span>[Block(<span class="dv">128</span>, <span class="dv">4</span>) <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">4</span>)])</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model(x).shape)                              <span class="co"># [2, 16, 128]</span></span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Position: the transformer is permutation-invariant -&gt; RoPE or encoding added to x</span></span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>max_n, d <span class="op">=</span> <span class="dv">512</span>, <span class="dv">128</span></span></code></pre></div>
<ul>
<li><strong>Position</strong>: attention does not know the order → <em>positional encodings</em> (sinusoidal, learned, or RoPE, 6.2) — and on graphs: the analogue is the problem of <em>positional/structural encodings</em>, at the heart of chapter 9 and of the Advanced GNN module (M2);</li>
<li><strong>MLP</strong>: two layers with GELU, expansion ratio ~4 — this is where most of the parameters live (~2/3);</li>
<li><strong>Causal mask</strong>: forbid <span class="math inline">j &gt; i</span> for autoregression — exactly the factorization <span class="math inline">\mathbb{P}(x) = \prod_t \mathbb{P}(x_t \mid x_{&lt;t})</span> of chapter 7.</li>
</ul>
<h2 id="ch7">7. Generative models: AE, VAE, GAN</h2>
<h3 id="deterministic-autoencoder-and-its-pathology">7.1. Deterministic autoencoder and its pathology</h3>
<p>An autoencoder compresses <span class="math inline">x</span> into a code <span class="math inline">z = E_\phi(x)</span> and reconstructs <span class="math inline">\hat x = D_\theta(z)</span>, trained on <span class="math inline">\|x - \hat x\|^2</span>. Useful for representation learning though it is, it is not a <em>generative</em> model: the latent space has no imposed structure — sampling <span class="math inline">z</span> at random gives aberrant reconstructions. The VAE corrects precisely this.</p>
<h3 id="vae-the-elbo-fully-derived">7.2. VAE: the ELBO fully derived</h3>
<div class="def">
<p><span class="tag">Definition 7.1 — VAE (Kingma &amp; Welling, 2013)</span> Diagonal Gaussian encoder <span class="math inline">q_\phi(z \mid x) = \mathcal{N}\big(\mu_\phi(x), \mathrm{diag}(\sigma_\phi^2(x))\big)</span>, decoder <span class="math inline">p_\theta(x \mid z)</span>, prior <span class="math inline">z \sim \mathcal{N}(0, I)</span>. One maximizes the <strong>ELBO</strong> (evidence lower bound): <span class="math display">\mathcal{L}(\theta, \phi; x) = \mathbb{E}_{q_\phi}\big[\log p_\theta(x \mid z)\big] - \mathrm{KL}\big(q_\phi(z \mid x)\,\|\,\mathcal{N}(0, I)\big).</span></p>
</div>
<div class="thm">
<p><span class="tag">Theorem 7.2 — Exact decomposition of the log-likelihood</span> <span class="math display">\log p_\theta(x) = \mathcal{L}(\theta, \phi; x) + \mathrm{KL}\big(q_\phi(z\mid x)\,\big\|\,p_\theta(z \mid x)\big) \;\ge\; \mathcal{L}(\theta, \phi; x).</span> Maximizing the ELBO = maximizing a lower bound of <span class="math inline">\log p_\theta(x)</span> <em>and</em> bringing <span class="math inline">q_\phi(z\|x)</span> closer to the exact posterior <span class="math inline">p_\theta(z\|x)</span>.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Start from the definition of the KL between <span class="math inline">q_\phi(\cdot \mid x)</span> and the posterior <span class="math inline">p_\theta(\cdot \mid x)</span>, both over <span class="math inline">z</span> (at fixed <span class="math inline">x</span>), and expand with <span class="math inline">p_\theta(x, z) = p_\theta(x \mid z)\, p(z)</span> (Bayes): <span class="math display">\mathrm{KL}\big(q_\phi \| p_\theta(\cdot\|x)\big) = \mathbb{E}_q[\log q] - \mathbb{E}_q[\log p_\theta(x\|z)] - \mathbb{E}_q[\log p(z)] + \log p_\theta(x).</span> Now, by definition of the KL against the prior, <span class="math inline">\mathbb{E}_q[\log q] - \mathbb{E}_q[\log p(z)] = \mathrm{KL}(q_\phi \| \mathcal{N}(0,I))</span>. Substituting: <span class="math display">\mathrm{KL}\big(q_\phi \| p_\theta(\cdot\|x)\big) = \mathrm{KL}(q_\phi \| \mathcal{N}) - \mathbb{E}_q[\log p_\theta(x\|z)] + \log p_\theta(x),</span> that is, rearranging: <span class="math display">\log p_\theta(x) = \underbrace{\mathbb{E}_q[\log p_\theta(x\|z)] - \mathrm{KL}(q_\phi \| \mathcal{N})}_{=\ \mathcal{L}(\theta,\phi;x)} + \mathrm{KL}\big(q_\phi \| p_\theta(\cdot\|x)\big).</span> The KL is nonnegative (Jensen applied to <span class="math inline">\mathbb{E}_q[\log(q/p)] \ge -\log \mathbb{E}_q[p/q] = 0</span>), giving the bound. Equality iff <span class="math inline">q_\phi(z\|x) = p_\theta(z\|x)</span> exactly. <span class="qed">∎</span></p>
</div>
<div class="note">
<p><span class="tag">Reading the proof</span> One cannot optimize <span class="math inline">\log p_\theta(x) = \log \int p_\theta(x\|z)\, p(z)\, dz</span> directly: the integral is intractable. The ELBO is the only quantity that requires only (i) <em>samples</em> from <span class="math inline">q_\phi</span> (Monte Carlo: a single one suffices in practice) and (ii) a <em>closed-form</em> KL. It is the same trade-off as in EM (Machine Learning module): the residual KL measures exactly what the bound loses.</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 7.3 — Reparameterization: why <span class="math inline">z = \mu + \sigma \odot \varepsilon</span> works</span> If <span class="math inline">\varepsilon \sim \mathcal{N}(0, I)</span> and <span class="math inline">z = \mu_\phi(x) + \sigma_\phi(x) \odot \varepsilon</span>, then <span class="math inline">z \sim \mathcal{N}(\mu_\phi(x), \mathrm{diag}(\sigma_\phi^2(x)))</span> <em>and</em> <span class="math inline">\nabla_\phi \mathbb{E}_{q_\phi}[f(z)] = \mathbb{E}_\varepsilon\big[\nabla_\phi f(\mu_\phi + \sigma_\phi \odot \varepsilon)\big]</span>: the gradient gets through. Sampling <span class="math inline">z \sim q_\phi</span> directly blocks the gradient (the sampling operation has no derivative with respect to its parameters).</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>The law of <span class="math inline">z</span> is obtained by an affine change of variable (the Jacobian <span class="math inline">\partial z/\partial \varepsilon = \mathrm{diag}(\sigma)</span> is constant): the density of <span class="math inline">z</span> is that of a Gaussian with mean <span class="math inline">\mu</span>, covariance <span class="math inline">\mathrm{diag}(\sigma^2)</span>. For the gradient: the expectation under <span class="math inline">q_\phi</span> rewrites as an expectation under the <em>fixed</em> law of <span class="math inline">\varepsilon</span>, <span class="math inline">\mathbb{E}_{q_\phi}[f(z)] = \mathbb{E}_{\varepsilon}[f(\mu_\phi + \sigma_\phi \odot \varepsilon)]</span>; the distribution is <em>no longer</em> parameterized by <span class="math inline">\phi</span> — <span class="math inline">\phi</span> now appears only in the integrand, which gradient descent knows how to differentiate (theorem 2.1). <span class="qed">∎</span></p>
</div>
<div class="prop">
<p><span class="tag">Proposition 7.4 — Closed-form KL between diagonal Gaussians</span> For <span class="math inline">q = \mathcal{N}(\mu, \mathrm{diag}(\sigma^2))</span> and <span class="math inline">p = \mathcal{N}(0, I)</span> in dimension <span class="math inline">k</span>: <span class="math display">\mathrm{KL}(q \| p) = \frac12 \sum_{i=1}^{k} \big(\mu_i^2 + \sigma_i^2 - 1 - \log \sigma_i^2\big).</span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span><span class="math inline">\mathrm{KL}(q\|p) = \mathbb{E}_q[\log q(z) - \log p(z)]</span>. Coordinate by coordinate (the densities factorize), with <span class="math inline">\varphi</span> the standard Gaussian density: <span class="math inline">\log q(z_i) - \log \varphi(z_i) = -\tfrac12\log\sigma_i^2 - \frac{(z_i - \mu_i)^2}{2\sigma_i^2} + \frac{z_i^2}{2}</span>. Under <span class="math inline">q</span>, <span class="math inline">z_i \sim \mathcal{N}(\mu_i, \sigma_i^2)</span>, so <span class="math inline">\mathbb{E}_q[(z_i - \mu_i)^2] = \sigma_i^2</span> and <span class="math inline">\mathbb{E}_q[z_i^2] = \mu_i^2 + \sigma_i^2</span>. Taking the expectation: <span class="math inline">-\tfrac12\log\sigma_i^2 - \tfrac12 + \tfrac12(\mu_i^2 + \sigma_i^2)</span>, that is <span class="math inline">\tfrac12(\mu_i^2 + \sigma_i^2 - 1 - \log \sigma_i^2)</span>. Along the way one checks that each term is <span class="math inline">\ge 0</span>, zero iff <span class="math inline">\mu_i = 0, \sigma_i = 1</span> (study of <span class="math inline">u - 1 - \log u \ge 0</span>). <span class="qed">∎</span></p>
</div>
<div class="note">
<p><span class="tag">The ELBO trade-off in practice</span> First term: reconstruction. Second: a regularizer that keeps the codes close to the prior — too strong, everything blurs together (codes ignored, blurry sampling); too weak, the latent space develops “holes” (partial posterior collapse). The connection with variational inference and EM is taken up again in the Machine Learning module; the extensions (<span class="math inline">\beta</span>-VAE, VQ-VAE) are in Multimodal Generative AI.</p>
</div>
<h3 id="gan-the-minimax-game-and-its-equilibrium">7.3. GAN: the minimax game and its equilibrium</h3>
<div class="def">
<p><span class="tag">Definition 7.5 — GAN (Goodfellow et al., 2014)</span> Minimax game between a generator <span class="math inline">G</span> (often <span class="math inline">G(z)</span> with <span class="math inline">z \sim \mathcal{N}(0, I)</span>) and a discriminator <span class="math inline">D : \mathcal{X} \to (0,1)</span>: <span class="math display">\min_G \max_D \ V(G, D), \qquad V(G, D) = \mathbb{E}_{x \sim p_{\mathrm{data}}}\big[\log D(x)\big] + \mathbb{E}_{z \sim p(z)}\big[\log(1 - D(G(z)))\big].</span></p>
</div>
<div class="thm">
<p><span class="tag">Theorem 7.6 — Optimal discriminator and global equilibrium</span> 1) For fixed <span class="math inline">G</span>, the maximand reads <span class="math inline">V(G,D) = \int \big[p_{\mathrm{data}}(x)\log D(x) + p_G(x) \log(1 - D(x))\big] dx</span> (with <span class="math inline">p_G</span> the law of <span class="math inline">G(z)</span>), maximized pointwise at <span class="math display">D^\star(x) = \frac{p_{\mathrm{data}}(x)}{p_{\mathrm{data}}(x) + p_G(x)}.</span> 2) The value of the game is then <span class="math inline">V(G, D^\star) = -\log 4 + 2\,\mathrm{JSD}(p_{\mathrm{data}} \| p_G)</span>, minimized over <span class="math inline">G</span> exactly when <span class="math inline">p_G = p_{\mathrm{data}}</span>: the global equilibrium exists and coincides with the law of the data.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span><strong>1)</strong> For each fixed <span class="math inline">x</span>, maximize <span class="math inline">a\log D + b\log(1-D)</span> with <span class="math inline">a = p_{\mathrm{data}}(x)</span>, <span class="math inline">b = p_G(x)</span>: the derivative <span class="math inline">a/D - b/(1-D) = 0</span> gives <span class="math inline">D^\star = a/(a+b)</span> (strict concavity in <span class="math inline">D \in (0,1)</span>). <strong>2)</strong> Rewrite <span class="math inline">\log D^\star = \log \frac{p_{\mathrm{data}}}{p_{\mathrm{data}}+p_G} = \log\frac{p_{\mathrm{data}}}{m} - \log 2</span> and <span class="math inline">\log(1 - D^\star) = \log \frac{p_G}{m} - \log 2</span>, where <span class="math inline">m = \frac12(p_{\mathrm{data}} + p_G)</span>. Then <span class="math display">V(G, D^\star) = \int p_{\mathrm{data}} \log\frac{p_{\mathrm{data}}}{m} + \int p_G \log\frac{p_G}{m} - 2\log 2 = 2\,\mathrm{JSD}(p_{\mathrm{data}} \| p_G) - \log 4,</span> by definition of the Jensen–Shannon divergence (average of the KLs toward <span class="math inline">m</span>). Since <span class="math inline">\mathrm{JSD} \ge 0</span> with equality if and only if <span class="math inline">p_{\mathrm{data}} = p_G</span> almost everywhere (the two laws share the same harmonic mean <span class="math inline">m</span>), the minimum <span class="math inline">-\log 4</span> is reached exactly at equilibrium. <strong>Gaussian case</strong>: if <span class="math inline">p_{\mathrm{data}} = \mathcal{N}(\mu_d, \sigma_d^2)</span> and <span class="math inline">G(z) = \mu + \sigma z</span>, then <span class="math inline">p_G = \mathcal{N}(\mu, \sigma^2)</span> and the equilibrium corresponds to the exact parameters <span class="math inline">(\mu, \sigma) = (\mu_d, \sigma_d)</span>; the logit of <span class="math inline">D^\star</span>, <span class="math inline">\log p_{\mathrm{data}} - \log p_G</span>, is a degree-2 polynomial in <span class="math inline">x</span> — a quadratic discriminator suffices. <span class="qed">∎</span></p>
</div>
<div class="note">
<p><span class="tag">Why it is unstable nonetheless</span> The theorem describes the equilibrium, not the <em>dynamics</em>: the two players descend their gradients <em>simultaneously</em>, and if <span class="math inline">D</span> becomes too good too fast, the gradient of <span class="math inline">G</span> vanishes (<span class="math inline">\log(1 - D)</span> saturates). Emblematic pathology: <strong>mode collapse</strong> — <span class="math inline">G</span> concentrates on the “easiest” modes of <span class="math inline">p_{\mathrm{data}}</span> (a few very credible faces instead of all of them). Historical remedies: Wasserstein-GAN (transportation distance instead of JSD — cf.&nbsp;Optimal Transport module), gradient penalization, feature matching. In imaging, the family was superseded by <strong>diffusion</strong> (iterative denoising): Ye Zhu’s models (chapter 9) are recent developments of it, and the Multimodal Generative AI module treats them in detail. LLMs, for their part, remain autoregressive: <span class="math inline">\mathbb{P}(x_t \mid x_{&lt;t})</span>, cross-entropy loss over tokens (LLMs module, M2).</p>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Family</th>
<th style="text-align: left;">Principle</th>
<th style="text-align: left;">Sampling</th>
<th style="text-align: left;">In the program</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">VAE</td>
<td style="text-align: left;">ELBO, Gaussian latent</td>
<td style="text-align: left;">decoder from <span class="math inline">z \sim \mathcal{N}</span> Mu</td>
<td style="text-align: left;">ltimodal GenAI</td>
</tr>
<tr class="even">
<td style="text-align: left;">GAN</td>
<td style="text-align: left;">adversarial min-max</td>
<td style="text-align: left;">implicit</td>
<td style="text-align: left;">Multimodal GenAI</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diffusion</td>
<td style="text-align: left;">iterative noising/denoising</td>
<td style="text-align: left;">(reverse) process</td>
<td style="text-align: left;">Multimodal GenAI</td>
</tr>
<tr class="even">
<td style="text-align: left;">Autoregressive</td>
<td style="text-align: left;">modeling <span class="math inline">\mathbb{P}(x_t \mid x_{&lt;t})</span> toke</td>
<td style="text-align: left;">n by token LLMs</td>
<td style="text-align: left;">(M2), Graph GenAI</td>
</tr>
</tbody>
</table>
<h2 id="ch8">8. Transfer learning and fine-tuning</h2>
<p>Training “from scratch” has become the exception: the dominant practice consists in starting from a model pre-trained on immense corpora (ImageNet for vision, terabytes of text for LLMs) and adapting it. This chapter gives the framework and the vocabulary; the LLMs module (M2) applies it at scale.</p>
<h3 id="the-three-adaptation-regimes">8.1. The three adaptation regimes</h3>
<ul>
<li><strong>Frozen features / linear probing</strong>: freeze the whole backbone, train a linear classifier (or a small head) on the pre-trained representations. A valuable diagnostic: feature quality is measured by the performance of a simple softmax on top (see exercise 12).</li>
<li><strong>Full fine-tuning</strong>: retrain all the weights with a smaller step (typically 10 to 100× smaller than pre-training) — the risk of <em>catastrophic forgetting</em> (loss of pre-trained knowledge) is managed by a decaying step and few epochs.</li>
<li><strong>Parameter-efficient fine-tuning (PEFT)</strong>: train only a small fraction of new parameters, the rest staying frozen — all the more relevant as models grow.</li>
</ul>
<div class="note">
<p><span class="tag">Why it works</span> The low layers learn quasi-universal features (chapter 4: edges, textures; chapter 9: graph morphology); task specificity lives in the high layers. The performance versus number of labeled domain examples curve shifts massively to the left — this is the most measurable practical benefit of modern deep learning.</p>
</div>
<h3 id="domain-adaptation-in-a-nutshell">8.2. Domain adaptation, in a nutshell</h3>
<p>When the target has <em>no</em> labels (labeled source domain → unlabeled target domain), domain adaptation aligns the distributions: adversarial (a discriminator tries to guess the domain from the features: they must become non-discriminative), or via distribution distances (MMD, Wasserstein distances — see the Optimal Transport module). The guiding idea: learn representations <em>invariant</em> to the domain but <em>discriminative</em> for the task.</p>
<h3 id="lora-a-mathematical-sketch">8.3. LoRA: a mathematical sketch</h3>
<div class="def">
<p><span class="tag">Definition 8.1 — LoRA (Hu et al., 2021)</span> For a pre-trained matrix <span class="math inline">W_0 \in \mathbb{R}^{d_{\mathrm{out}} \times d_{\mathrm{in}}}</span>, one freezes <span class="math inline">W_0</span> and learns a low-rank update: <span class="math display">W = W_0 + \Delta W = W_0 + \frac{\alpha}{r}\, B A, \qquad B \in \mathbb{R}^{d_{\mathrm{out}} \times r},\ A \in \mathbb{R}^{r \times d_{\mathrm{in}}},\ r \ll \min(d_{\mathrm{in}}, d_{\mathrm{out}}),</span> with <span class="math inline">B</span> initialized to zero and <span class="math inline">A</span> Gaussian: <span class="math inline">\Delta W = 0</span> at the start, training departs exactly from the pre-trained model. <span class="math inline">\alpha/r</span> sets the effective scale of the update.</p>
</div>
<div class="note">
<p><span class="tag">Why a low rank suffices</span> The working hypothesis, backed by Aghajanyan et al.&nbsp;(2020), is that weight updates during adaptation have a low “intrinsic rank”: <span class="math inline">\Delta W</span> is well approximated by a product <span class="math inline">BA</span> of small rank <span class="math inline">r</span> (4 to 64 in practice). Let us count: adapting a <span class="math inline">d \times d</span> layer with <span class="math inline">r = 8</span> costs <span class="math inline">2dr = 16d</span> parameters instead of <span class="math inline">d^2</span> — for <span class="math inline">d = 4096</span>, a factor of 1000. Other benefits: a single <span class="math inline">W_0</span> kept in memory + per-task interchangeable <span class="math inline">(A, B)</span> pairs (instant swap); and for inference latency, one can merge <span class="math inline">W = W_0 + BA</span> at no extra cost. The generalizations (QLoRA: quantized backbone + LoRA) are covered in the LLMs module (M2).</p>
</div>
<div class="sourceCode" id="cb5"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch, torch.nn <span class="im">as</span> nn</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> LoRALinear(nn.Module):</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, base: nn.Linear, r<span class="op">=</span><span class="dv">8</span>, alpha<span class="op">=</span><span class="dv">16</span>):</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.base <span class="op">=</span> base                       <span class="co"># W0 frozen</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> p <span class="kw">in</span> <span class="va">self</span>.base.parameters(): p.requires_grad <span class="op">=</span> <span class="va">False</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.A <span class="op">=</span> nn.Parameter(torch.randn(r, base.in_features) <span class="op">*</span> <span class="fl">0.01</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.B <span class="op">=</span> nn.Parameter(torch.zeros(base.out_features, r))</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.scale <span class="op">=</span> alpha <span class="op">/</span> r</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.base(x) <span class="op">+</span> <span class="va">self</span>.scale <span class="op">*</span> (x <span class="op">@</span> <span class="va">self</span>.A.T <span class="op">@</span> <span class="va">self</span>.B.T)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co"># trainable params: r*(in+out) instead of in*out</span></span></code></pre></div>
<h2 id="ch9">9. Research at DaSciM (Vazirgiannis, Lutzeyer, Zhu)</h2>
<p>This chapter connects the course to the current research of the three instructors, all three rooted in the previous chapters. The arXiv references are in the bibliography.</p>
<h3 id="michalis-vazirgiannis-from-the-graph-of-words-to-textual-gnns">9.1. Michalis Vazirgiannis: from the “Graph of Words” to textual GNNs</h3>
<div class="ex">
<p><span class="tag">Worked example — Graph of Words (Rousseau &amp; Vazirgiannis, CIKM 2013)</span> The <em>bag-of-words</em> representation throws away syntactic and order structure; the <strong>word graph</strong> restores it at almost no cost:</p>
<ul>
<li><strong>Construction</strong>: each distinct term of the document = one node; a <em>sliding window</em> of size <span class="math inline">w</span> over the text creates an edge between two terms if they co-occur in the window (weighted by the co-occurrence frequency). The document becomes a small, sparse weighted graph.</li>
<li><strong>From TF-IDF to TW-IDF</strong>: in a bag of words, the weight of a term is its frequency; in a word graph, it is its <em>centrality</em> — TW-IDF weights the term by its average weighted degree across documents — the group then used the k-core decomposition of the word graph for keyword extraction (Rousseau, Kiagias &amp; Vazirgiannis, ECIR 2015). “Ad hoc” retrieval gains over TF-IDF: structurally important words emerge even when they are rare.</li>
<li><strong>Positioning with respect to the course</strong>: this is the first building block of the program — <em>the data itself becomes a graph</em>. The NLP module reuses these representations; the Graph ML module generalizes them.</li>
</ul>
</div>
<div class="note">
<p><span class="tag">GNN lineage: texts, expressivity, generation</span></p>
<ul>
<li><strong>Inductive text classification via GNNs</strong> (Skianis, Rousseau &amp; Vazirgiannis, ACL 2020): each <em>document</em> is its own word graph; a GNN applied to the document graph can then process words never seen at training time (inductivity) whereas TextGCN (Yao et al., AAAI 2019) built a single corpus graph.</li>
<li><strong>DGoW-GNN</strong> (Abbahaddou, Lutzeyer &amp; Vazirgiannis, NeurIPS 2023): <em>discriminative</em> word graphs — the edges are no longer fixed co-occurrences but are filtered/learned for the task, then a GNN propagates the representations. The loop is closed with chapter 2: the computation graph (backprop) and the data graph (message passing) answer each other.</li>
<li><strong>PathNN</strong> (Michel, Nikolentzos &amp; Vazirgiannis, ICML 2023): going beyond classical message passing by aggregating <em>paths</em> (shortest paths, simple paths) emanating from each node; two variants are strictly more expressive than the Weisfeiler–Lehman test. This is the language of the Graph ML module, expanded in Advanced GNN (M2).</li>
</ul>
</div>
<h3 id="johannes-lutzeyer-where-are-the-parameters-expressivity-and-position">9.2. Johannes Lutzeyer: where are the parameters? Expressivity and position</h3>
<div class="note">
<p><span class="tag">Sparsifying the update step (Lutzeyer, Wu &amp; Vazirgiannis, 2021)</span> An MPNN (message passing neural network) chains two phases: the aggregation of neighbor messages and an “update step” — precisely the linear transformation + non-linearity of chapter 1, applied node by node. The paper’s question: what remains if one <em>sparsifies</em> this trainable step, initializing it directly sparse (ExpanderGNN, with a tunable sparsity rate) or even reducing it to a non-linearity alone (Activation-Only GNN)? Key result: performance comparable to dense models with far fewer parameters — a direct empirical insight into how expressivity is distributed between aggregation (structure, not parametrized) and the update (parametrized), in the spirit of ch.&nbsp;1 (what, in a network, carries the expressivity?).</p>
</div>
<div class="note">
<p><span class="tag">Positional encodings on graphs (SHAKE-GNN, Cui, Lutzeyer et al., 2025)</span> Chapter 6 showed that a transformer needs a positional <em>encoding</em> because attention is permutation-invariant. On a graph, the problem is deeper: there is <em>no canonical ordering</em> of the nodes — the “position” of a node is a <em>structural</em> notion (Laplacian spectrum, distances, spanning forests). SHAKE-GNN proposes hierarchical encodings based on Kirchhoff forests, computed in a scalable way. The parallel to remember: RoPE (relative absolute position, suited to sequences) vs spectral/structural encodings (position defined by the geometry of the graph); both answer the same fundamental invariance (exercise 4). The Advanced GNN module (M2) systematizes this question.</p>
</div>
<h3 id="ye-zhu-steering-diffusion-models">9.3. Ye Zhu: steering diffusion models</h3>
<div class="note">
<p><span class="tag">From the loss to semantic control</span> Chapter 7 left diffusion in sketch form (noising/denoising); the work of Ye Zhu shows how to <em>steer</em> it:</p>
<ul>
<li><strong>BoundaryDiffusion</strong> (Zhu et al., NeurIPS 2023): control the semantics of generation <em>without retraining</em> (learning-free), by warping the decision boundaries of the model’s latent space in the guidance plane — an elegant point of contact with prop. 7.6: where the GAN sought an equilibrium, here already-learned latent regions are moved geometrically.</li>
<li><strong>Discrete contrastive diffusion</strong> (ICLR 2023) and <strong>Diffusion in Diffusion</strong> (ICLR 2024): <em>discrete</em> cross-modal music-image diffusion and cyclic text-vision conditioning — the argument of the ch.&nbsp;7 table (“multimodal”) made concrete.</li>
<li><strong>NoiseQuery</strong> (ICCV 2025): the initial noise <span class="math inline">z_T</span> as an <em>implicit control signal</em> for goal-guided generation — it reverses the perspective: the “noise” becomes a structured input, which connects to the sensitivity to the initial noise studied for GANs/diffusion.</li>
</ul>
<p>This work directly extends ch.&nbsp;7 and is expanded in the Multimodal Generative AI module.</p>
</div>
<h2 id="ch10">10. Training in practice</h2>
<p>A network that does not learn almost always has a mundane bug. This chapter is the diagnostic protocol we will apply in the labs, in the order in which it must be applied.</p>
<h3 id="the-training-recipe-in-order">10.1. The training recipe, in order</h3>
<ol type="1">
<li><strong>Shape sanity check</strong>: one forward pass without errors, the dimensions of every activation verified (rule of ch.&nbsp;0: gradients have the shape of their variable).</li>
<li><strong>Overfit a single batch</strong>: 32 examples, train until the loss is <span class="math inline">\approx 0</span>. If the model cannot do it, the bug is <em>structural</em> (data, loss, initialization, wild learning rate) — no point training longer.&nbsp;A model unable to memorize 32 examples is broken or too small; this is THE test that avoids weeks of silent error.</li>
<li><strong>LR range test</strong> (Smith, 2015): <span class="math inline">\eta</span> increasing geometrically from <span class="math inline">10^{-7}</span> to <span class="math inline">10^{0}</span>, plot the loss: plateau → descent → divergence. Take the <span class="math inline">\eta</span> at the dip (or slightly before): it sets AdamW/SGD in one epoch.</li>
<li><strong>Small full training run</strong> on ~10% of the data, with the train/val curves: check that the dynamics are healthy before scaling up.</li>
<li><strong>Scaling + regularization</strong>: larger batch (or gradient accumulation), mixed precision, data augmentation, dropout, weight decay — in that order of payoff (ch.&nbsp;3).</li>
<li><strong>Checkpointing</strong>: save regularly (weights + optimizer state + current step + data generator seed), to resume exactly.</li>
</ol>
<h3 id="monitoring-reading-your-curves">10.2. Monitoring: reading your curves</h3>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Symptom</th>
<th style="text-align: left;">Likely cause</th>
<th style="text-align: left;">Response</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">loss = NaN</td>
<td style="text-align: left;">lr too large, log(0), unprotected softmax (ch.&nbsp;0), fp16 overflow</td>
<td style="text-align: left;">divide lr by 10, log-softmax, loss scaling</td>
</tr>
<tr class="even">
<td style="text-align: left;">one-off loss spikes</td>
<td style="text-align: left;">aberrant batch, lr near the edge of 2/L (thm. 3.1)</td>
<td style="text-align: left;">inspect the data, lower the lr, gradient clipping</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exploding gradient norm</td>
<td style="text-align: left;">poorly conditioned recurrences (ch.&nbsp;5)</td>
<td style="text-align: left;">clip <span class="math inline">\|\hat g\|</span> to a threshold (standard: 1.0)</td>
</tr>
<tr class="even">
<td style="text-align: left;">train goes down, val stagnates</td>
<td style="text-align: left;">overfitting</td>
<td style="text-align: left;">ch.&nbsp;3.6, in order of payoff</td>
</tr>
<tr class="odd">
<td style="text-align: left;">neither train nor val moves</td>
<td style="text-align: left;">lr too small, blockage (dead ReLUs), loss mis-wired</td>
<td style="text-align: left;">LR range test, per-layer activation statistics</td>
</tr>
</tbody>
</table>
<p>Tools: tensorboard/wandb; systematically log the loss, accuracy, gradient norm, weight norm, the fraction of zero activations (dying ReLU), and the activation histograms of a few layers.</p>
<h3 id="gpu-the-levers-that-matter">10.3. GPU: the levers that matter</h3>
<ul>
<li><strong>Mixed precision</strong> (bf16 preferably): ~2× throughput, memory divided by ~2 — the first reflex (ch.&nbsp;2).</li>
<li><strong>Batch and accumulation</strong>: saturate the GPU (measure utilization); if memory runs out, accumulate small batches; adjust the BatchNorm statistics accordingly.</li>
<li><strong>DataLoader</strong>: workers &gt; 0, pin_memory, prefetch — a GPU waiting for data is a wasted GPU (CPU preprocessing is often the real bottleneck).</li>
<li><strong>torch.compile</strong>, fused kernels (FlashAttention, ch.&nbsp;6), avoid CPU→GPU synchronizations inside the loop (the .item() / prints at each step).</li>
</ul>
<h3 id="reproducibility">10.4. Reproducibility</h3>
<div class="sourceCode" id="cb6"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch, numpy <span class="im">as</span> np, random</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> seed_everything(seed<span class="op">=</span><span class="dv">42</span>):</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    random.seed(seed)<span class="op">;</span> np.random.seed(seed)<span class="op">;</span> torch.manual_seed(seed)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    torch.cuda.manual_seed_all(seed)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>seed_everything(<span class="dv">42</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>torch.backends.cudnn.deterministic <span class="op">=</span> <span class="va">True</span>    <span class="co"># determinism (speed cost)</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>torch.backends.cudnn.benchmark <span class="op">=</span> <span class="va">False</span>       <span class="co"># disable non-deterministic autotuning</span></span></code></pre></div>
<p>Set the seeds (python/numpy/torch/cuda), the data shuffling, and record the library versions; some CUDA kernels remain non-deterministic by nature (atomics); aim for reproducibility <em>up to a tolerance</em> rather than bit-for-bit, and document configurations and seeds in every experiment. Reproducibility is also a debugging tool: a random bug you know how to reproduce is half fixed.</p>
<h2 id="ex">Exercises</h2>
<ol type="1">
<li><strong>Backprop on paper.</strong> Recover the formulas of example 2.2 (two layers, ReLU), then check them numerically by finite differences <span class="math inline">\frac{\mathcal{L}(\theta + \epsilon e_j) - \mathcal{L}(\theta - \epsilon e_j)}{2\epsilon}</span> on a small network.</li>
<li><strong>Activation.</strong> Show that if <span class="math inline">\sigma</span> is linear, an MLP of arbitrary depth represents exactly the affine maps. Deduce why <em>linear cascades</em> are useless.</li>
<li><strong>He initialization.</strong> Recover the factor 2 of He initialization: for <span class="math inline">h = \mathrm{ReLU}(a)</span> with <span class="math inline">a</span> symmetric zero-mean, compute <span class="math inline">\mathbb{E}[h^2]</span> then the variance of the next layer.</li>
<li><strong>1D attention by hand.</strong> For <span class="math inline">n = 3</span> tokens, <span class="math inline">d_k = 2</span>, compute by hand <span class="math inline">QK^\top/\sqrt{d_k}</span>, the row-wise softmax, and the result <span class="math inline">\mathrm{softmax}(\cdot)V</span>. Implement it, compare, and check that the rows of the attention matrix sum to 1.</li>
<li><strong>Permutation-invariance.</strong> Check experimentally that a transformer block <em>without</em> positional encoding is invariant to the permutation of tokens, and that adding a positional encoding breaks this invariance.</li>
<li><strong>Quadratic SGD.</strong> For <span class="math inline">A = \mathrm{diag}(4, 1)</span>, <span class="math inline">b = 0</span>, <span class="math inline">\theta_0 = (1, 1)</span>: write the sequence <span class="math inline">(\theta_k)</span> for <span class="math inline">\eta = 1/2</span> then <span class="math inline">\eta = 1</span>, and verify theorem 3.1 (per-mode contraction, bound <span class="math inline">2/L</span>).</li>
<li><strong>Adam bias correction.</strong> Prove proposition 3.5 for <span class="math inline">v_t</span> (second moment), then compute the update <span class="math inline">\hat m_1/\sqrt{\hat v_1}</span> at the first step and explain why the warmup protects.</li>
<li><strong>Convolution arithmetic.</strong> A <span class="math inline">32 \times 32</span> input, three successive convs (5×5, stride 2, padding 2; 3×3, stride 1, padding 1; 3×3, stride 1, padding 1, dilation 2): intermediate output sizes and final receptive field (proposition 4.4).</li>
<li><strong>Gaussian KL.</strong> Derive the formula of proposition 7.4 in dimension 1, plot <span class="math inline">\mathrm{KL}(\mathcal{N}(\mu, \sigma^2) \| \mathcal{N}(0,1))</span> as a function of <span class="math inline">\mu</span> and <span class="math inline">\sigma</span>, and locate the minimum.</li>
<li><strong>Gaussian GAN.</strong> For <span class="math inline">p_{\mathrm{data}} = \mathcal{N}(0, 1)</span> and <span class="math inline">p_G = \mathcal{N}(\mu, \sigma^2)</span>, write the logit of <span class="math inline">D^\star</span> (difference of the log-densities) and check that it is a trinomial in <span class="math inline">x</span>. Where does the equilibrium lie?</li>
<li><strong>LoRA.</strong> Count the trainable parameters of a GPT-like model with 12 blocks (<span class="math inline">d = 768</span>, attention + MLP) adapted by LoRA <span class="math inline">r = 8</span> on the attention projections only, and compare with full fine-tuning.</li>
<li><strong>Project.</strong> In PyTorch: classify MNIST with (a) an MLP, (b) a small CNN, (c) a mini-transformer on patches (16 patches of 4×4). Plot the train/val curves, compare the parameter counts and accuracy, comment with the bias-variance decomposition, then apply the protocol of chapter 10 (overfitting a batch, LR range test).</li>
</ol>
<div class="note">
<p><span class="tag">Solutions and hints (even-numbered exercises)</span></p>
<p><strong>Ex. 2.</strong> By induction: if <span class="math inline">h^{(\ell)} = \sigma(W^{(\ell)} h^{(\ell-1)} + b^{(\ell)})</span> with <span class="math inline">\sigma(t) = \alpha t</span>, then <span class="math inline">h^{(\ell)} = \alpha W^{(\ell)} h^{(\ell-1)} + \alpha b^{(\ell)}</span> remains affine in <span class="math inline">h^{(0)} = x</span> — composing, <span class="math inline">f_\theta(x) = W x + c</span> with <span class="math inline">W = \prod_\ell \alpha W^{(\ell)}</span>: a single matrix, all the deep layers collapse into one.&nbsp; <strong>Ex. 4.</strong> The row-wise softmax makes each row a vector of positive weights of sum 1; the multiplication by <span class="math inline">V</span> makes each output a weighted average of the <em>values</em>: this is a convex interpolation, exactly the message passing of chapter 6.&nbsp; <strong>Ex. 6.</strong> Decoupled modes: <span class="math inline">(\theta_k)_1 = (1 - 4\eta)^k</span>, <span class="math inline">(\theta_k)_2 = (1-\eta)^k</span>. For <span class="math inline">\eta = 1/2</span>: factors <span class="math inline">-1</span> (oscillation without decay: exactly <span class="math inline">\eta = 2/L</span>, limiting case) and <span class="math inline">1/2</span>. For <span class="math inline">\eta = 1</span>: factors <span class="math inline">-3</span> (divergence: <span class="math inline">\eta &gt; 2/L</span>) and <span class="math inline">0</span> (convergence in one step: <span class="math inline">\eta = 1/\lambda_2</span>).&nbsp; <strong>Ex. 8.</strong> Theorem 4.2: <span class="math inline">32 \to 16 \to 16 \to 14</span> (the third one: <span class="math inline">\lfloor (16 + 2 - 2\cdot 2 - 1)/1 \rfloor + 1 = 14</span>). Receptive field (proposition 4.4, with dilation: replace <span class="math inline">(k-1)</span> by <span class="math inline">d(k-1)</span>): <span class="math inline">\mathrm{RF}_1 = 5</span>, <span class="math inline">\mathrm{RF}_2 = 5 + 2 \cdot 2 = 9</span>, <span class="math inline">\mathrm{RF}_3 = 9 + (2 \cdot 2)\cdot 2 = 17</span> pixels, for a product of strides <span class="math inline">\prod s = 2</span>.&nbsp; <strong>Ex. 10.</strong> Unique global minimum at <span class="math inline">(\mu, \sigma) = (0, 1)</span>; the logit of <span class="math inline">D^\star</span> is <span class="math inline">\frac{x^2}{2}\big(\frac{1}{\sigma^2} - 1\big) - \frac{x\mu}{\sigma^2} + \frac{\mu^2}{2\sigma^2} + \log\sigma</span>: a trinomial in <span class="math inline">x</span>, identically zero at the equilibrium <span class="math inline">(\mu, \sigma) = (0, 1)</span>.</p>
</div>
<div class="note">
<p><span class="tag">Hints (odd-numbered exercises)</span></p>
<p><strong>Ex. 1.</strong> Take <span class="math inline">\epsilon \sim 10^{-6}</span> in float64 for the check; the error of the central finite difference is <span class="math inline">\mathcal{O}(\epsilon^2)</span>.&nbsp; <strong>Ex. 3.</strong> <span class="math inline">\mathbb{E}[h^2] = \mathbb{E}[a^2 \mathbf{1}_{a&gt;0}] = \tfrac12\mathbb{E}[a^2]</span> by symmetry of <span class="math inline">a</span>: the variance of the next layer is halved, hence <span class="math inline">\mathrm{Var}(W) = 2/n_{\mathrm{in}}</span>.&nbsp; <strong>Ex. 5.</strong> Permute the rows of the input batch (<span class="math inline">x[\mathrm{perm}]</span>) and compare the outputs up to a transformation: the property is exact (not an approximation), the softmax being unchanged by re-indexing.&nbsp; <strong>Ex. 7.</strong> Re-derive the geometric sum with <span class="math inline">g_k^2</span> constant; at step 1, <span class="math inline">\hat m_1 = g_1</span> and <span class="math inline">\hat v_1 = g_1^2</span> — the ratio is <span class="math inline">\mathrm{sign}(g_1)</span>, a step of size <span class="math inline">\eta</span> whether <span class="math inline">g_1</span> is tiny or huge: hence the caution of the warmup when <span class="math inline">g_1</span> is atypical.&nbsp; <strong>Ex. 9.</strong> The minimum of <span class="math inline">\tfrac12(\mu^2 + \sigma^2 - 1 - \log\sigma^2)</span> zeroes <span class="math inline">\mu</span> and <span class="math inline">\sigma</span> (derivative with respect to <span class="math inline">\sigma^2</span>: <span class="math inline">\tfrac12(1 - 1/\sigma^2) = 0</span>).&nbsp; <strong>Ex. 11.</strong> Per block: 4 attention matrices <span class="math inline">d \times d</span>, i.e.&nbsp;<span class="math inline">4 \times 2 \times 8 \times 768 = 49{,}152</span> LoRA parameters, versus <span class="math inline">4 \times 768^2 \approx 2.36</span> M for full — and the MLP is not adapted; LoRA total ~0.6 M for ~85 M full.</p>
</div>
<h2 id="refs">References</h2>
<h3 id="textbooks-and-courses">Textbooks and courses</h3>
<ul>
<li>I. Goodfellow, Y. Bengio, A. Courville, <em>Deep Learning</em>, MIT Press, 2016 — <a href="https://www.deeplearningbook.org/">free online</a>; chapters 6-8 for this module.</li>
<li>A. Zhang, Z. Lipton, M. Li, A. Smola, <em>Dive into Deep Learning</em>, 2023 — <a href="https://d2l.ai">d2l.ai</a>: code-first interactive course (PyTorch), very close to the labs.</li>
<li>A. Karpathy, <a href="https://karpathy.ai/zero-to-hero.html">Neural Networks: Zero to Hero</a> — building a GPT from scratch; and his “transformer = graph” reading (<em>Software 3.0</em>, Stanford, 2025-2026) which grounds the LLGA bridge.</li>
<li>S. Raschka, <em>Machine Learning with PyTorch and Scikit-Learn</em>, Packt, 2022 — for practice.</li>
</ul>
<h3 id="founding-papers-course-chronology">Founding papers (course chronology)</h3>
<ul>
<li>G. Cybenko, <em>Approximation by Superpositions of a Sigmoidal Function</em>, Mathematics of Control, Signals and Systems, 1989 — theorem 1.2.</li>
<li>X. Glorot, Y. Bengio, <em>Understanding the Difficulty of Training Deep Feedforward Neural Networks</em>, AISTATS 2010 — Xavier initialization.</li>
<li>A. Krizhevsky, I. Sutskever, G. Hinton, <em>ImageNet Classification with Deep CNNs</em>, NeurIPS 2012 (AlexNet); K. Simonyan, A. Zisserman, <a href="https://arxiv.org/abs/1409.1556">Very Deep Convolutional Networks</a> (VGG), ICLR 2015.</li>
<li>D. Kingma, J. Ba, <a href="https://arxiv.org/abs/1412.6980">Adam: A Method for Stochastic Optimization</a>, ICLR 2015 — algorithm 3.4, derived step by step.</li>
<li>K. He et al., <a href="https://arxiv.org/abs/1502.01852">Delving Deep into Rectifiers</a> (He init), ICCV 2015; <a href="https://arxiv.org/abs/1512.03385">Deep Residual Learning for Image Recognition</a> (ResNet), CVPR 2016.</li>
<li>S. Ioffe, C. Szegedy, <a href="https://arxiv.org/abs/1502.03167">Batch Normalization</a>, ICML 2015; J. Ba, J. Kiros, G. Hinton, <a href="https://arxiv.org/abs/1607.06450">Layer Normalization</a>, 2016; S. Santurkar et al., <a href="https://arxiv.org/abs/1805.11604">How Does Batch Normalization Help Optimization?</a>, NeurIPS 2018.</li>
<li>N. Srivastava et al., <em>Dropout</em>, JMLR 15, 2014; I. Loshchilov, F. Hutter, <a href="https://arxiv.org/abs/1711.05101">Decoupled Weight Decay Regularization</a> (AdamW), ICLR 2019.</li>
<li>D. Hendrycks, K. Gimpel, <a href="https://arxiv.org/abs/1606.08415">Gaussian Error Linear Units</a> (GELU), 2016.</li>
<li>A. Vaswani et al., <a href="https://arxiv.org/abs/1706.03762">Attention Is All You Need</a>, NeurIPS 2017 — the paper to read line by line.</li>
<li>J. Su et al., <a href="https://arxiv.org/abs/2104.09864">RoFormer: Enhanced Transformer with Rotary Position Embedding</a>, 2021; T. Dao et al., <a href="https://arxiv.org/abs/2205.14135">FlashAttention</a>, NeurIPS 2022.</li>
<li>D. Kingma, M. Welling, <a href="https://arxiv.org/abs/1312.6114">Auto-Encoding Variational Bayes</a>, ICLR 2014; I. Goodfellow et al., <a href="https://arxiv.org/abs/1406.2661">Generative Adversarial Nets</a>, NeurIPS 2014.</li>
<li>E. Hu et al., <a href="https://arxiv.org/abs/2106.09685">LoRA: Low-Rank Adaptation of Large Language Models</a>, ICLR 2022; Aghajanyan et al., <em>Intrinsic Dimensionality</em>, ICML 2021.</li>
<li>L. Smith, <a href="https://arxiv.org/abs/1506.01186">Cyclical Learning Rates for Training Neural Networks</a>, WACV 2017 (LR range test); T. Chen et al., <a href="https://arxiv.org/abs/1604.06174">Training Deep Nets with Sublinear Memory Cost</a>, 2016 (checkpointing).</li>
</ul>
<h3 id="research-at-dascim-vazirgiannis-lutzeyer-zhu">Research at DaSciM (Vazirgiannis, Lutzeyer, Zhu)</h3>
<ul>
<li>F. Rousseau, M. Vazirgiannis, <em>Graph-of-Word and TW-IDF: New Approach to Ad Hoc IR</em>, CIKM 2013 — the “Graph of Words” of chapter 9; F. Rousseau, E. Kiagias, M. Vazirgiannis, <a href="https://link.springer.com/chapter/10.1007/978-3-319-16354-3_42">Main Core Retention on Graph-of-Words for Single-Document Keyword Extraction</a>, ECIR 2015.</li>
<li>D. Skianis, F. Rousseau, M. Vazirgiannis, <a href="https://aclanthology.org/2020.acl-main.31.pdf">Inductive Text Classification via Graph Neural Networks</a>, ACL 2020.</li>
<li>G. Michel, G. Nikolentzos, M. Vazirgiannis, <a href="https://arxiv.org/abs/2306.05955">Path Neural Networks: Expressive and Accurate Graph Neural Networks</a>, ICML 2023.</li>
<li>J. Lutzeyer, C. Wu, M. Vazirgiannis, <a href="https://arxiv.org/abs/2109.00909">Sparsifying the Update Step in Graph Neural Networks</a>, 2021.</li>
<li>Y. Abbahaddou, J. Lutzeyer, M. Vazirgiannis, <a href="https://arxiv.org/abs/2410.20469">Graph Neural Networks on Discriminative Graphs of Words</a>, NeurIPS 2023 (extended version).</li>
<li>Z. Cui, J. Lutzeyer et al., <a href="https://arxiv.org/abs/2509.22100">SHAKE-GNN: Scalable Hierarchical Kirchhoff-Forest Graph Neural Network</a>, 2025.</li>
<li>Y. Zhu et al., <a href="https://arxiv.org/abs/2302.08357">Boundary Guided Learning-Free Semantic Control with Diffusion Models</a>, NeurIPS 2023; <a href="https://arxiv.org/abs/2206.07771">Discrete Contrastive Diffusion for Cross-Modal Music and Image Generation</a>, ICLR 2023; <a href="https://arxiv.org/abs/2306.08247">Diffusion in Diffusion</a>, ICLR 2024; <a href="https://arxiv.org/abs/2412.05101">The Silent Assistant: NoiseQuery as Implicit Guidance</a>, ICCV 2025.</li>
</ul>

</main>
<footer class="foot"><p><a href="../../index.html">← Master's program</a></p></footer>
<script defer="" src="../../assets/theme.js"></script>




</body></html>