<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DataBase Management System</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script>(function(){try{var t=localStorage.getItem("llga-theme");if(t==="dark"||t==="light")document.documentElement.setAttribute("data-theme",t);}catch(e){}})();</script>
<style>
  /* Keep paper.css as visual source of truth; tame Quarto chrome */
  #title-block-header { margin: 0 0 0.5rem; }
  #title-block-header .title { margin: 0 0 0.25rem; font-size: 1.85rem; font-weight: 700; }
  #title-block-header .subtitle { color: var(--soft, #555); margin: 0 0 1rem; font-size: 1.05rem; }
  div.sourceCode { background: var(--code-bg, #f7f7f7); border: 1px solid var(--hair, #e4e4e4); }
  code { background: var(--code-inline-bg, #f4f4f4); }

  /* Light (github) token colors — higher specificity beats paper.css */
  div.sourceCode pre.sourceCode code span.kw, div.sourceCode pre.sourceCode code span.cf, div.sourceCode pre.sourceCode code span.dt, div.sourceCode pre.sourceCode code span.at, div.sourceCode pre.sourceCode code span.bu, div.sourceCode pre.sourceCode code span.pp { color: #d73a49; }
  div.sourceCode pre.sourceCode code span.im, div.sourceCode pre.sourceCode code span.st, div.sourceCode pre.sourceCode code span.ch, div.sourceCode pre.sourceCode code span.ss, div.sourceCode pre.sourceCode code span.vs { color: #032f62; }
  div.sourceCode pre.sourceCode code span.co, div.sourceCode pre.sourceCode code span.an, div.sourceCode pre.sourceCode code span.cv, div.sourceCode pre.sourceCode code span.do, div.sourceCode pre.sourceCode code span.in { color: #6a737d; }
  div.sourceCode pre.sourceCode code span.fu { color: #6f42c1; }
  div.sourceCode pre.sourceCode code span.va { color: #e36209; }
  div.sourceCode pre.sourceCode code span.cn, div.sourceCode pre.sourceCode code span.bn, div.sourceCode pre.sourceCode code span.dv, div.sourceCode pre.sourceCode code span.fl, div.sourceCode pre.sourceCode code span.sc { color: #005cc5; }
  div.sourceCode pre.sourceCode code span.op { color: #24292e; }
  /* Dark mode token colors (github highlight is light-oriented) */
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.kw,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.cf,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.dt,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.at,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.bu,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.pp,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.op { color: #ff7b72; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.im { color: #ff7b72; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.st,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.ch,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.ss,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.vs { color: #a5d6ff; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.cn,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.bn,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.dv,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.fl,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.sc { color: #79c0ff; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.co,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.an,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.cv,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.do,
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.in { color: #8b949e; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.va { color: #ffa657; }
  [data-theme="dark"] div.sourceCode pre.sourceCode code span.fu { color: #d2a8ff; }
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.kw,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.cf,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.dt,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.at,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.bu,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.pp,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.op { color: #ff7b72; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.im { color: #ff7b72; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.st,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.ch,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.ss,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.vs { color: #a5d6ff; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.cn,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.bn,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.dv,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.fl,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.sc { color: #79c0ff; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.co,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.an,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.cv,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.do,
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.in { color: #8b949e; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.va { color: #ffa657; }
    :root:not([data-theme="light"]) div.sourceCode pre.sourceCode code span.fu { color: #d2a8ff; }
  }

</style>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../assets/paper.css">
</head>

<body>

<p class="crumb"><a href="../../index.html">MSc&amp;T LLGA · Course notes</a></p>
<main class="paper">

<header id="title-block-header">
<h1 class="title">DataBase Management System</h1>
<p class="subtitle">CSC_51053_EP · Year 1 · Period 1</p>

</header>


<h2 id="contents">Contents</h2>
<ul>
<li><a href="#intro">Introduction and overview</a></li>
<li><a href="#ch0">0. Review: sets, relations, complexity</a></li>
<li><a href="#ch1">1. The relational model and algebra</a></li>
<li><a href="#ch2">2. SQL: queries, aggregates, windowing</a></li>
<li><a href="#ch3">3. Design: dependencies and normal forms</a></li>
<li><a href="#ch4">4. Storage: pages, files, external sorting</a></li>
<li><a href="#ch5">5. Indexes: B+ trees and hashing</a></li>
<li><a href="#ch6">6. Transactions and concurrency</a></li>
<li><a href="#ch7">7. The log and crash recovery</a></li>
<li><a href="#ch8">8. Query optimization</a></li>
<li><a href="#ch9">9. Beyond relational: NoSQL, graphs, vectors</a></li>
<li><a href="#ch10">10. Web data and heterogeneous integration</a></li>
<li><a href="#ch11">11. Course research notes — CEDAR (Mohanty)</a></li>
<li><a href="#ex">Exercises</a></li>
<li><a href="#refs">References</a></li>
</ul>
<h2 id="intro">Introduction and overview</h2>
<table class="caption-top">
<tbody>
<tr class="odd">
<td style="text-align: left;">Module</td>
<td style="text-align: left;">DataBase Management Systems (official catalog title: “Système de Gestion de Base de Données”)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Code</td>
<td style="text-align: left;">CSC_51053_EP</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Team and workload</td>
<td style="text-align: left;">Coordinator: Madhulika Mohanty (Inria Saclay, CEDAR team · École Polytechnique) · 36&nbsp;h in person · 4.5 ECTS · from the relational model and SQL to transactions, B+ trees, and query optimization — up to knowledge graphs, vector databases, and data fact-checking, the research themes of the CEDAR team.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Period</td>
<td style="text-align: left;">Fall 2026 · period 1 (from 09/17/2026 to 12/18/2026) · course taught in English</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Assessment</td>
<td style="text-align: left;">50% final written exam (paper documents allowed) · 50% three 30-minute tests in small classes starting mid-October</td>
</tr>
<tr class="even">
<td style="text-align: left;">Status in the program</td>
<td style="text-align: left;"><span class="badge option">P1 elective</span><span class="badge position">Outside the recommended track</span></td>
</tr>
</tbody>
</table>
<p><strong>Audience</strong>: an engineer who already wires an LLM / graph to data and wants reliability (SQL, indexes, transactions). <strong>Empirical first</strong>: a query that works in the lab and times out in prod for lack of an index; RAG that hallucinates because the join was dirty — then we name relational model, ACID, optimizer, vector stores.</p>
<p>The “data” side of the program: store, query, harden before learning.</p>
<h3 id="what-you-will-be-able-to-do">What you will be able to do</h3>
<ul>
<li>Express a query in both relational algebra and SQL, including aggregates and window functions.</li>
<li>Design a clean schema: functional dependencies, normal forms, and know when to denormalize wisely.</li>
<li>Explain how a query actually executes: pages, files, external sorting, B+ trees, hashing.</li>
<li>Reason about a transaction: ACID, isolation levels, concurrency, deadlocks.</li>
<li>Describe the crash recovery guarantee provided by the log (WAL) — what makes a database trustworthy.</li>
<li>Read an execution plan and optimize a slow query (indexes, rewriting, cost).</li>
<li>Choose between relational, NoSQL, graph database, and vector database depending on the workload and the data model.</li>
<li>Integrate heterogeneous web data and assess its trustworthiness, up to data fact-checking.</li>
</ul>
<h3 id="official-objectives-and-syllabus-2026-2027-catalog">Official objectives and syllabus (2026-2027 catalog)</h3>
<p>In the official catalog, the course unit <em>Système de Gestion de Base de Données</em> (X3A&nbsp;VE3) sets itself the objective of a “broad and in-depth presentation of the fundamental concepts in very large-scale data management”, drawing on PostgreSQL to introduce declarative queries, query optimization, data modeling, concurrency control and crash recovery, with labs where students load and query a real database, including through a web application. This is exactly the arc followed by these materials, from the relational model to optimization — and our opening chapters (NoSQL, web data) extend this foundation toward the RAG and GraphRAG systems of the master’s program. The sheet lists no prerequisites (not disclosed); the assessment combines a final written exam and three graded tests in small classes.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Official program theme</th>
<th style="text-align: left;">Course section</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Data modeling: entity-association model, relational model</td>
<td style="text-align: left;">Chapter 1 (Def. 1.1 for the relational model, Def. 1.8 for the entity-association → relational mapping), extended in chapter 3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Relational algebra, relational calculus</td>
<td style="text-align: left;">Chapter 1 (Def. 1.3 and Th. 1.7 — algebra/calculus equivalence)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The query language of relational databases: SQL</td>
<td style="text-align: left;">Chapter 2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Quality of relational schemas, normal forms</td>
<td style="text-align: left;">Chapter 3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Subsystem of relational DBMS: disks, files, buffers</td>
<td style="text-align: left;">Chapter 4 (Def. 4.1 for pages and files, Def. 4.5 for the buffer pool)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Indexing: tree structures, array structures</td>
<td style="text-align: left;">Chapter 5 (B+ trees and hashing)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Evaluation of relational operators</td>
<td style="text-align: left;">Chapter 8 (Def. 8.2 for joins, Def. 8.5 for selection access paths)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Optimization of SQL queries</td>
<td style="text-align: left;">Chapter 8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Transaction management</td>
<td style="text-align: left;">Chapter 6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Concurrency control</td>
<td style="text-align: left;">Chapter 6</td>
</tr>
</tbody>
</table>
<p>Every official theme of the syllabus is covered; crash recovery, mentioned in the official description, is the subject of chapter 7. Our additions, beyond the official syllabus: the review chapter 0 (sets, relations, complexity), chapter 9 (NoSQL, graph and vector databases), chapter 10 (web data and heterogeneous integration) and chapter 11 (the work of the CEDAR team). Note: this course unit does not appear in the LLGA-1-S1 track list of the 2026-2027 catalog, although its sheet remains published there and scheduled in period 1.</p>
<h3 id="where-this-course-fits-in-the-program">Where this course fits in the program</h3>
<p>Elective of Year&nbsp;1 · Period&nbsp;1 (36&nbsp;h, 4.5&nbsp;ECTS), outside the recommended track: the “data” choice of the period. Official prerequisites: not stated on the sheet; these materials lay down the <a href="../m1p1-refresher-cs/index.html">Refresher in Computer Science</a> module as their foundation, whose sets, relations and complexity analysis they constantly mobilize — external sorting and indexes are reasoned about in algorithmic cost.</p>
<p>Downstream, this module feeds three parts of the master’s program. The <a href="../m1p2-graph-ml/index.html">Graph Machine and Deep Learning for Generative AI</a> module builds on the graph databases seen in the “Beyond relational” chapter, up to GraphRAG architectures that combine GNNs and graph querying; the M2 module <a href="../m2-large-language-models/index.html">Large Language Models</a> assumes the culture of vector databases and RAG (retrieval-augmented generation) laid down here; <a href="../m2-mlops-llm-engineering/index.html">ML Ops and LLM Engineering Principles</a> reuses transactions, reliability, and data pipeline integration for industrialization. The research of the CEDAR team (Inria) on knowledge graphs and fact-checking also announces concrete internship topics.</p>
<h3 id="course-outline">Course outline</h3>
<ul>
<li><strong>Review: sets, relations, complexity</strong>: the mathematical and algorithmic foundation taken up from the Refresher in Computer Science.</li>
<li><strong>The relational model and algebra</strong>: the theory behind SQL — operators, semantics, equivalences.</li>
<li><strong>SQL: queries, aggregates, windowing</strong>: the most directly reusable skill of the master’s program.</li>
<li><strong>Design: dependencies and normal forms</strong>: designing schemas without redundancy or anomalies.</li>
<li><strong>Storage: pages, files, external sorting</strong>: what happens under the query, when data overflows memory.</li>
<li><strong>Indexes: B+ trees and hashing</strong>: fetching information without reading everything — the real performance gain.</li>
<li><strong>Transactions and concurrency</strong>: ACID, isolation, locks — many users, one consistent database.</li>
<li><strong>The log and crash recovery</strong>: why a well-designed database loses nothing, even on a crash.</li>
<li><strong>Query optimization</strong>: execution plans, rewrites, costs — diagnosing and speeding up.</li>
<li><strong>Beyond relational: NoSQL, graphs, vectors</strong>: the modern database families, and when each one wins — the pivotal chapter for GraphRAG and RAG.</li>
<li><strong>Web data and heterogeneous integration</strong>: confronting multiple, inconsistent, sometimes false sources.</li>
<li><strong>Course research notes — CEDAR (Mohanty)</strong>: the research of the CEDAR team (Inria) — knowledge graphs and data fact-checking.</li>
</ul>
<h3 id="how-to-study-this-module">How to study this module</h3>
<ul>
<li>Practice SQL from the first week on a real database (SQLite or PostgreSQL): the SQL chapter is a gesture, kept up by typing queries.</li>
<li>For each internal mechanism (index, log, external sorting), ask yourself “what happens if the data is a hundred times the memory?” — that is the question that structures the course.</li>
<li>Go back if needed to the complexity chapter of the <a href="../m1p1-refresher-cs/index.html">Refresher in Computer Science</a> module: B+ trees and optimization are reasoned about in big-O.</li>
<li>Build a small schema yourself, populate it, then deliberately degrade it (concurrency, wild deletions) to observe transactions and the log at work.</li>
<li>Pay particular attention to the “Beyond relational” chapter: it is the one that directly connects to <a href="../m1p2-graph-ml/index.html">Graph ML</a> and to the M2 LLMs.</li>
<li>Do the optimization exercises on real execution plans (EXPLAIN): knowing how to read a plan is highly valued in internships and jobs alike.</li>
</ul>
<div class="note">
<p><span class="tag">Independent note</span> Crossing LLMs and graphs — the identity of the LLGA master’s program — requires knowing where and how data lives: relational databases, graph databases, vector databases. This module provides this command of the data foundation, shared by the engineers who deploy RAG systems and the researchers who make knowledge graphs speak.</p>
</div>
<h2 id="ch0">0. Review: sets, relations, complexity</h2>
<div class="recap">
<div class="recap-title">
<p>L3 review material used</p>
</div>
<ul>
<li><strong>Sets and Cartesian products</strong>: <span class="math inline">A_1 \times \cdots \times A_k</span>, cardinality of the product <span class="math inline">\|A_1 \times A_2\| = \|A_1\|\cdot\|A_2\|</span>, subsets, differences; a <em>relation</em> in the database sense is a subset of a Cartesian product;</li>
<li><strong>Binary relations</strong>: reflexivity, transitivity, transitive closure — the hidden tool behind the theory of functional dependencies (ch.&nbsp;3) and recursive queries (ch.&nbsp;2);</li>
<li><strong>First-order logic</strong>: quantifiers <span class="math inline">\forall, \exists</span>, negation of quantifiers (<span class="math inline">\neg\forall x\, P \equiv \exists x\, \neg P</span>) — SQL is nothing but an evaluable fragment of this logic;</li>
<li><strong>Complexity</strong>: notations <span class="math inline">O, \Theta, \Omega</span>, logarithms (<span class="math inline">\log_b x = \ln x / \ln b</span>), average complexity of hash tables (L3 algorithms review), sorting and merging;</li>
<li><strong>A bit of probability</strong>: uniform draws, expectation, the “<span class="math inline">n</span> balls into <span class="math inline">m</span> bins” paradigm used in ch.&nbsp;5 (hashing).</li>
</ul>
</div>
<div class="prop">
<p><span class="tag">Proposition 0.1 — Sizes of products and projections</span> Let <span class="math inline">R \subseteq A \times B</span> be a finite binary relation. Then <span class="math display">\|\pi_A(R)\| \leq \|R\| \leq \|\pi_A(R)\| \cdot \|\pi_B(R)\|,</span> where <span class="math inline">\pi_A</span> denotes the projection (the set of values of <span class="math inline">A</span> actually present). The left bound is attained as soon as one value of <span class="math inline">A</span> appears in several pairs; the right one is attained for the complete product <span class="math inline">R = \pi_A(R) \times \pi_B(R)</span>. These bounds, trivial in appearance, are the foundation of <em>all</em> the cardinality estimates of chapter 8: an optimizer never knows the exact content of the tables, only statistics (number of distinct values, histograms), and must bracket the sizes of intermediate results in order to choose an execution plan.</p>
</div>
<div class="note">
<p><span class="tag">Note — Why this module in an LLGA master’s program?</span> Every model lives on data: extracting it, cleaning it, integrating it, indexing it, then serving models in production (vector search). This module covers the layer beneath ML: where the <em>Machine Learning</em> module (ch.&nbsp;1) assumes clean tables, we explain where they come from. Links given along the way: Graph ML (ch.&nbsp;9), LLMs (ch.&nbsp;9-10), NLP (ch.&nbsp;10).</p>
</div>
<h2 id="ch1">1. The relational model and algebra</h2>
<p>Concrete scene: a wrong business dashboard because a join duplicated rows. This chapter sets the relational model.</p>
<div class="note">
<p><span class="tag">What breaks</span> Ignoring keys / FDs; SELECT * in prod; confusing isolation with “it looks consistent”.</p>
</div>
<p>The relational model, proposed by E.&nbsp;F. Codd in 1970, rests on a radically simple idea: representing data as (mathematical) <em>relations</em>, that is, sets of tuples, and querying them with operations that are <em>closed</em> on these sets. The physical structure is invisible: this separation between the declarative and the physical is what made the model successful, and it is what will make the automatic optimization of chapter 8 possible.</p>
<div class="def">
<p><span class="tag">Definition 1.1 — Schema, relation, instance</span> A <strong>relation schema</strong> is a name and a list of attributes <span class="math inline">R(A_1\!: D_1, \dots, A_n\!: D_n)</span>, where <span class="math inline">D_i</span> is a domain of values. An <strong>instance</strong> of <span class="math inline">R</span> is a finite set <span class="math inline">r \subseteq D_1 \times \cdots \times D_n</span> (no duplicates: a relation is a <em>set</em>). A <strong>database schema</strong> is a set of relation schemas. A <strong>key constraint</strong> <span class="math inline">K \subseteq \{A_1,\dots,A_n\}</span> requires that two distinct tuples do not coincide on <span class="math inline">K</span>.</p>
</div>
<div class="ex">
<p><span class="tag">Example 1.2 — Running example database</span> Three relations suffice for the whole chapter:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Student (<span style="text-decoration:underline">id</span>, name, major)</th>
<th style="text-align: left;">Course (<span style="text-decoration:underline">code</span>, title, credits)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(1043, Anna, DS)&nbsp;· (1088, Bruno, AI)&nbsp;· (2101, Chloé, DS)</td>
<td style="text-align: left;">(DB, Databases, 4)&nbsp;· (DL, Deep Learning, 5)&nbsp;· (OT, Optimal Transport, 3)</td>
</tr>
</tbody>
</table>
<p>and the association relation <code>Enrolled(id, code, year)</code> with the tuples (1043, DB, 2025), (1043, DL, 2026), (1088, DB, 2025), (1088, OT, 2025), (2101, DL, 2025). The pair (id, code) is the key of <code>Enrolled</code>.</p>
</div>
<div class="def">
<p><span class="tag">Definition 1.3 — Relational algebra</span> Relational algebra is the smallest family of operations, all closed (an operation on relations returns a relation):</p>
<ul>
<li><strong>selection</strong> <span class="math inline">\sigma_p(R)</span>: tuples of <span class="math inline">R</span> satisfying the predicate <span class="math inline">p</span> (comparisons and logical connectives);</li>
<li><strong>projection</strong> <span class="math inline">\pi_L(R)</span>: restriction to the attributes of <span class="math inline">L</span>, with duplicate elimination;</li>
<li><strong>Cartesian product</strong> <span class="math inline">R \times S</span>, <strong>union</strong> <span class="math inline">R \cup S</span> (compatible schemas), <strong>difference</strong> <span class="math inline">R - S</span>, <strong>renaming</strong> <span class="math inline">\rho_{A \to B}(R)</span>;</li>
<li><strong>join</strong> <span class="math inline">R \Join_p S := \sigma_p(R \times S)</span> and <strong>natural join</strong> <span class="math inline">R \Join S</span> (equality of identically named attributes, then projection of duplicated columns);</li>
<li><strong>aggregation</strong> <span class="math inline">{}_G\gamma_{f(A)}(R)</span>: partition of <span class="math inline">R</span> according to the attributes <span class="math inline">G</span>, computation of the group function <span class="math inline">f</span> (<span class="math inline">\texttt{count}, \texttt{sum}, \texttt{avg}, \texttt{min}, \texttt{max}</span>) — an extension of Codd’s initial algebra, indispensable in practice.</li>
</ul>
</div>
<div class="prop">
<p><span class="tag">Proposition 1.4 — Fundamental equivalence laws</span> The following equivalences hold for all instances (verified by expanding the set-theoretic definitions):</p>
<ul>
<li><span class="math inline">\sigma_{p_1 \wedge p_2}(R) = \sigma_{p_1}(\sigma_{p_2}(R))</span> and <span class="math inline">\sigma_{p_1}(\sigma_{p_2}(R)) = \sigma_{p_2}(\sigma_{p_1}(R))</span> (commutativity);</li>
<li>if <span class="math inline">p</span> only involves attributes of <span class="math inline">R</span>: <span class="math inline">\sigma_p(R \Join S) = \sigma_p(R) \Join S</span> — this is the <em>selection push-down</em> law, the heart of the heuristics of ch.&nbsp;8;</li>
<li><span class="math inline">\pi_{L_1}(\pi_{L_2}(R)) = \pi_{L_1}(R)</span> whenever <span class="math inline">L_1 \subseteq L_2</span>;</li>
<li><span class="math inline">R \Join_p S = S \Join_p S'</span> with symmetrized predicate (commutativity) and <span class="math inline">(R \Join S) \Join T = R \Join (S \Join T)</span> (associativity) — hence the freedom of choice of the <em>join order</em>, exponential but fruitful.</li>
</ul>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Proof of the push-down law (the others are in the same style). Let <span class="math inline">t</span> be a tuple of <span class="math inline">R \Join S</span> that satisfies <span class="math inline">p</span>. By definition <span class="math inline">t = (u, v)</span> with <span class="math inline">u \in R</span>, <span class="math inline">v \in S</span>, and the join predicate satisfied; since <span class="math inline">p</span> mentions only attributes of <span class="math inline">R</span>, <span class="math inline">p(t)</span> depends only on <span class="math inline">u</span>, hence <span class="math inline">u \in \sigma_p(R)</span> and <span class="math inline">t \in \sigma_p(R) \Join S</span>. Conversely the inclusion is immediate since <span class="math inline">\sigma_p(R) \subseteq R</span>. <span class="qed">∎</span></p>
</div>
<div class="ex">
<p><span class="tag">Example 1.5 — Step-by-step evaluation</span> “Majors of the students enrolled in 2025 in a course of at least 4 credits”: <span class="math display">\pi_{\texttt{major}}\Big(\sigma_{\texttt{year}=2025}\big(\texttt{Enrolled}\big) \Join \pi_{\texttt{code}}\big(\sigma_{\texttt{credits}\geq 4}(\texttt{Course})\big) \Join \texttt{Student}\Big).</span> On Example 1.2: the courses kept are {DB, DL}; <span class="math inline">\sigma_{2025}</span> keeps (1043, DB), (1088, DB), (1088, OT), (2101, DL); the join eliminates (1088, OT); after the join with Student and projection: {DS, AI, DS} → {DS, AI} by eliminating duplicates. The order of the operations above (the most restrictive first) is not the only possible one: starting with <span class="math inline">\texttt{Enrolled} \Join \texttt{Student}</span> would be correct but more costly — the whole subject of ch.&nbsp;8.</p>
</div>
<div class="def">
<p><span class="tag">Definition 1.6 — Relational division</span> The <strong>division</strong> <span class="math inline">R \div S</span> (with the schema of <span class="math inline">S</span> included in that of <span class="math inline">R</span>) returns the tuples <span class="math inline">u</span> over the remaining attributes such that <span class="math inline">\{u\} \times S \subseteq R</span>. It expresses the <em>universal</em> quantifier: “the <span class="math inline">x</span> associated with <strong>all</strong> the <span class="math inline">y</span> of <span class="math inline">S</span>”. It is programmed without a dedicated operator by the scheme <span class="math inline">\pi_X(R) - \pi_X\big((\pi_X(R) \times S) - R\big)</span>, where <span class="math inline">X</span> are the attributes of <span class="math inline">R</span> absent from <span class="math inline">S</span>.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 1.7 — Codd: algebra and relational calculus</span> Relational algebra (with renaming) is <em>equivalent</em> to the safe tuple relational calculus: every query expressible in one is expressible in the other. This result (1972) establishes the <strong>relational completeness</strong> of SQL: everything that is computable in a finite, set-oriented way on relations is expressible in SQL. On the other hand, neither the basic algebra nor SQL can express the <em>transitive closure</em> of a graph (queries of the “ancestors” type), except by using the recursion of ch.&nbsp;2 or specific extensions.</p>
<div class="proof" style="margin-top:.5rem;">
<p><span class="proof-title"><em>Proof</em>. </span>Sketch. For the calculus → algebra direction, one translates a safe formula $ {x (x)} $ by structural induction: the positive use of <span class="math inline">\exists</span> becomes a projection of a product (with renaming for the free variables), conjunction a join, negation a difference — safeness (domains remain finite) guarantees that these constructions terminate. The algebra → calculus direction is an immediate induction over the operators. The inexpressiveness of transitive closure is proved by bounding arguments (any non-recursive query “sees” a number of joins fixed in advance, hence a bounded diameter in the graph). <span class="qed">∎</span></p>
</div>
</div>
<div class="def">
<p><span class="tag">Definition 1.8 — Entity-association (E-A) model and the move to relational</span> Design starts at the <em>conceptual</em> level, before any relation schema: an <strong>entity-association</strong> model describes <strong>entities</strong> (students, courses), their <strong>attributes</strong>, and <strong>associations</strong> between them, each association carrying a <em>cardinality</em> (1-1, 1-N, N-M) — for example <code>Student</code>—Enrolled(year)—<code>Course</code> is an N-M association carrying the attribute <code>year</code>. The translation to the relational model is mechanical: each entity becomes a relation (its identifier becomes the key); a 1-N association is absorbed by a foreign key on the N side; an N-M association becomes a relation in its own right whose key is the union of the keys of the linked entities (exactly the <code>Enrolled</code> relation of Example 1.2). This E-A → relational passage is the first step of the normalized design of ch.&nbsp;3.</p>
</div>
<div class="note">
<p><span class="tag">Note — Set semantics vs.&nbsp;multiset semantics</span> The algebra described here is <em>set-based</em> (no duplicates). Real engines manipulate <em>multisets</em>: without <code>DISTINCT</code>, duplicates survive, and the cardinalities of ch.&nbsp;8 account for them. Duplicate elimination costs a sort or a hash — never free; that is why SQL does not do it by default.</p>
</div>
<h2 id="ch2">2. SQL: queries, aggregates, windowing</h2>
<p>SQL is a <em>declarative</em> language: one describes the result, not the algorithm. Its logical semantics is understood in three stages, which one must know in order to predict what a query returns — and which every optimizer rewrites in its own way (ch.&nbsp;8): <code>FROM</code> produces the Cartesian product/joins, <code>WHERE</code> selects row by row, then <code>GROUP BY</code> + <code>SELECT</code> group, aggregate, and project.</p>
<div class="def">
<p><span class="tag">Definition 2.1 — Semantics of the basic block</span> The query <code>SELECT [DISTINCT] L FROM R1, …, Rk WHERE p</code> returns <span class="math display">\pi_L\big(\sigma_p(R_1 \times \cdots \times R_k)\big)</span> (multiset if <code>DISTINCT</code> is absent, set otherwise). A <strong>subquery</strong> is a nested query; <code>IN</code> and <code>EXISTS</code> correspond to semi-joins: <code>WHERE EXISTS (SELECT …)</code> tests that the answer is non-empty, which makes it possible in particular to express differences with <code>NOT EXISTS</code>.</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 2.2 — Translating quantifiers</span> “The <span class="math inline">x</span> such that <span class="math inline">\forall y \in S,\; \theta(x,y)</span>” is translated in SQL by anti-join: <code>… WHERE NOT EXISTS (SELECT 1 FROM S WHERE NOT θ)</code>. “There exists” is a simple <code>EXISTS</code>. This double negation is the direct legacy of the fact that SQL has no universal quantifier — and of Proposition 1.7: the division of ch.&nbsp;1 does not exist as an operator, it is programmed.</p>
</div>
<div class="def">
<p><span class="tag">Definition 2.3 — Aggregates and the HAVING clause</span> A query with <code>GROUP BY g</code> partitions the selected rows according to the values of <span class="math inline">g</span>, and each group produces <em>one</em> row: the <code>SELECT</code> may mention only <span class="math inline">g</span> and aggregates. The <code>HAVING</code> clause filters <em>the groups</em> (after aggregation), whereas <code>WHERE</code> filters the rows (before): <span class="math display">\pi_{g,f}\big({}_g\gamma_f( \sigma_p(R))\big) \;=\; \texttt{SELECT g, f(a) … WHERE p GROUP BY g HAVING q(f)}.</span></p>
</div>
<div class="ex">
<p><span class="tag">Example 2.4 — Windowing (window functions)</span> Window functions compute an aggregate <em>without grouping</em>: each row keeps its identity and additionally receives the value computed over its “window” (all the rows sharing its partition, possibly ordered). On:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">student</th>
<th style="text-align: left;">subject</th>
<th style="text-align: left;">grade</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Anna</td>
<td style="text-align: left;">ALG</td>
<td style="text-align: left;">16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Anna</td>
<td style="text-align: left;">PROG</td>
<td style="text-align: left;">14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Anna</td>
<td style="text-align: left;">STATS</td>
<td style="text-align: left;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bruno</td>
<td style="text-align: left;">PROG</td>
<td style="text-align: left;">18</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chloé</td>
<td style="text-align: left;">ALG</td>
<td style="text-align: left;">15</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chloé</td>
<td style="text-align: left;">PROG</td>
<td style="text-align: left;">17</td>
</tr>
</tbody>
</table>
<p>the query <code>SELECT student, grade, ROW_NUMBER() OVER (PARTITION BY student ORDER BY grade DESC) AS personal_rank, AVG(grade) OVER (PARTITION BY student) AS average, RANK() OVER (ORDER BY grade DESC) AS global_rank FROM Grades</code> returns:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">student</th>
<th style="text-align: left;">grade</th>
<th style="text-align: left;">personal_rank</th>
<th style="text-align: left;">average</th>
<th style="text-align: left;">global_rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Anna</td>
<td style="text-align: left;">16</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">14.0</td>
<td style="text-align: left;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Anna</td>
<td style="text-align: left;">14</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">14.0</td>
<td style="text-align: left;">5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Anna</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">14.0</td>
<td style="text-align: left;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bruno</td>
<td style="text-align: left;">18</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">18.0</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chloé</td>
<td style="text-align: left;">17</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">16.0</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chloé</td>
<td style="text-align: left;">15</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">16.0</td>
<td style="text-align: left;">4</td>
</tr>
</tbody>
</table>
<p>Note the behavior of <code>RANK()</code> (ties = same rank, next rank shifted: after two 5s there would be a 7) and the partition/global difference. Windows, standardized in 2003, are today the standard tool for top-<span class="math inline">k</span> per group, running totals (running sums via <code>ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW</code>), and cross-period comparisons.</p>
</div>
<div class="def">
<p><span class="tag">Definition 2.5 — NULL and three-valued logic</span> SQL distinguishes “unknown value” (<code>NULL</code>) from actual values. Any comparison with <code>NULL</code> returns <code>UNKNOWN</code>, and <code>WHERE</code> keeps only the <code>TRUE</code> rows — the <code>UNKNOWN</code> ones are silently eliminated. Truth tables extend naturally:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">AND</th>
<th style="text-align: left;">T</th>
<th style="text-align: left;">U</th>
<th style="text-align: left;">F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">T</td>
<td style="text-align: left;">T</td>
<td style="text-align: left;">U</td>
<td style="text-align: left;">F</td>
</tr>
<tr class="even">
<td style="text-align: left;">U</td>
<td style="text-align: left;">U</td>
<td style="text-align: left;">U</td>
<td style="text-align: left;">F</td>
</tr>
<tr class="odd">
<td style="text-align: left;">F</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">F</td>
</tr>
</tbody>
</table>
<p>Trapping consequence: <code>NOT (a = 1)</code> is not <code>a != 1</code> if <code>a</code> can be <code>NULL</code>; one needs <code>a IS DISTINCT FROM 1</code> (SQL:1999) or an explicit <code>OR a IS NULL</code>. Aggregates ignore <code>NULL</code>s (<code>AVG</code> divides by the number of non-<code>NULL</code> values), while <code>COUNT(*)</code> counts them — two <code>COUNT</code>s that differ are the classic symptom of incomplete data.</p>
</div>
<div class="def">
<p><span class="tag">Definition 2.6 — Recursion: WITH RECURSIVE</span> SQL:1999 filled the gap of Theorem 1.7: a recursive CTE <code>WITH RECURSIVE T AS (base UNION ALL SELECT … FROM T …)</code> computes the <em>least fixed point</em> of the equation: one starts from the <code>base</code> query and iterates the recursive part until no new tuples are produced. This is exactly a transitive closure: DBMSs implement it as a semi-naive data graph (a “delta” rewrite that re-evaluates only the new tuples), and ch.&nbsp;9 will find this fixed-point semantics again for querying knowledge graphs.</p>
</div>
<div class="ex">
<p><span class="tag">Example 2.7 — Ancestors in a tree in SQLite</span></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="op">--</span> directed graph parent(y, x): y <span class="kw">is</span> a parent of x</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>WITH RECURSIVE ancestor(a, d) AS (          <span class="op">--</span> a ancestor of d</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  SELECT parent, child FROM parent</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  UNION                                    <span class="op">--</span> UNION (without ALL) <span class="op">=</span> deduplicated</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  SELECT p.parent, a.d</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  FROM ancestor a JOIN parent p ON p.child <span class="op">=</span> a.a</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>SELECT d, COUNT(DISTINCT a) AS num_ancestors FROM ancestor GROUP BY d<span class="op">;</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="op">--</span> semantics: fixed point<span class="op">;</span> at each iteration, only the tuples</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="op">--</span> produced at the previous iteration are expanded (semi<span class="op">-</span>naive evaluation).</span></code></pre></div>
</div>
<div class="ex">
<p><span class="tag">Example 2.8 — SQLite and SQLAlchemy in Python</span></p>
<div class="sourceCode" id="cb2"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sqlite3</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sqlalchemy <span class="im">import</span> create_engine, MetaData, Table, Column, Integer, String, ForeignKey, select</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># --- 1. SQLite: everything lives in one file, ACID transactions included</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>con <span class="op">=</span> sqlite3.<span class="ex">connect</span>(<span class="st">"school.db"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>con.execute(<span class="st">"PRAGMA foreign_keys = ON"</span>)        <span class="co"># optional but recommended</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>con.executescript(<span class="st">"""</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="st">CREATE TABLE IF NOT EXISTS student(</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="st">  id INTEGER PRIMARY KEY, name TEXT NOT NULL, major TEXT);</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="st">CREATE TABLE IF NOT EXISTS course(</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="st">  code TEXT PRIMARY KEY, title TEXT, credits INTEGER CHECK (credits &gt; 0));</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="st">CREATE TABLE IF NOT EXISTS enrolled(</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="st">  id INTEGER REFERENCES student(id),</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="st">  code TEXT REFERENCES course(code),</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="st">  year INTEGER, PRIMARY KEY (id, code));</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span>)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>con.executemany(<span class="st">"INSERT OR IGNORE INTO student VALUES (?,?,?)"</span>,</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>                [(<span class="dv">1043</span>, <span class="st">"Anna"</span>, <span class="st">"DS"</span>), (<span class="dv">1088</span>, <span class="st">"Bruno"</span>, <span class="st">"AI"</span>), (<span class="dv">2101</span>, <span class="st">"Chloé"</span>, <span class="st">"DS"</span>)])</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co"># average per student, with a window to rank each one's courses</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>q <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT e.name, c.title, i.year,</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="st">       RANK() OVER (PARTITION BY e.id ORDER BY i.year) AS year_rank,</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="st">       COUNT(*) OVER (PARTITION BY e.id)                AS num_courses</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="st">FROM enrolled i</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="st">JOIN student e ON e.id = i.id</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a><span class="st">JOIN course   c ON c.code = i.code</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="st">WHERE c.credits &gt;= 3</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> row <span class="kw">in</span> con.execute(q):</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(row)</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a><span class="co"># explicit transaction: all or nothing</span></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>    con.execute(<span class="st">"BEGIN"</span>)</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>    con.execute(<span class="st">"UPDATE student SET major='AI' WHERE id=2101"</span>)</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>    con.execute(<span class="st">"INSERT INTO enrolled VALUES (2101, 'DB', 2026)"</span>)</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>    con.commit()</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> sqlite3.IntegrityError <span class="im">as</span> err:        <span class="co"># e.g. foreign key violated</span></span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>    con.rollback()</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"cancelled:"</span>, err)</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a><span class="co"># execution plan (useful for ch. 8):</span></span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> row <span class="kw">in</span> con.execute(<span class="st">"EXPLAIN QUERY PLAN "</span> <span class="op">+</span> q):</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(row)</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a><span class="co"># --- 2. SQLAlchemy Core: composable queries, DBMS-independent</span></span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>engine <span class="op">=</span> create_engine(<span class="st">"sqlite:///school.db"</span>, echo<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>md <span class="op">=</span> MetaData()</span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a>student <span class="op">=</span> Table(<span class="st">"student"</span>, md, Column(<span class="st">"id"</span>, Integer, primary_key<span class="op">=</span><span class="va">True</span>),</span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>                 Column(<span class="st">"name"</span>, String), Column(<span class="st">"major"</span>, String))</span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>enrolled <span class="op">=</span> Table(<span class="st">"enrolled"</span>, md, Column(<span class="st">"id"</span>, Integer, ForeignKey(<span class="st">"student.id"</span>),</span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>                 primary_key<span class="op">=</span><span class="va">True</span>), Column(<span class="st">"code"</span>, String, primary_key<span class="op">=</span><span class="va">True</span>),</span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a>                 Column(<span class="st">"year"</span>, Integer))</span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> engine.<span class="ex">connect</span>() <span class="im">as</span> cn:</span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>    stmt <span class="op">=</span> (select(student.c.name, enrolled.c.code)</span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a>            .join(enrolled, student.c.<span class="bu">id</span> <span class="op">==</span> enrolled.c.<span class="bu">id</span>)</span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a>            .where(enrolled.c.year <span class="op">==</span> <span class="dv">2025</span>).order_by(student.c.name))</span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(cn.execute(stmt).fetchall())</span></code></pre></div>
</div>
<div class="note">
<p><span class="tag">Note — Views and constraints</span> A <strong>view</strong> is a named, stored query, reused like a table (re-evaluated or materialized depending on the engine): an abstraction on a par with a function. Constraints (<code>PRIMARY KEY</code>, <code>FOREIGN KEY</code>, <code>CHECK</code>, <code>UNIQUE</code>, <code>NOT NULL</code>) are checked <em>at every write</em>: postponing validation until after loading (the “data lake” approach of ch.&nbsp;10) shifts the cost, it does not remove it.</p>
</div>
<h2 id="ch3">3. Design: dependencies and normal forms</h2>
<p>A poorly designed database leads to the three classic <em>anomalies</em>: insertion (impossible to record one fact without another), deletion (losing one fact while deleting another), update (repeating the same fact in several places). Normalization theory, also due to Codd and developed by Bernstein, Rissanen and others, diagnoses and corrects these defects through <strong>functional dependencies</strong>.</p>
<div class="def">
<p><span class="tag">Definition 3.1 — Functional dependency (FD)</span> Let <span class="math inline">R</span> be a schema and <span class="math inline">r</span> an instance. A <strong>functional dependency</strong> <span class="math inline">X \to Y</span> (where <span class="math inline">X, Y</span> are sets of attributes) is satisfied by <span class="math inline">r</span> if <span class="math display">\forall\, t_1, t_2 \in r,\quad t_1[X] = t_2[X] \;\Rightarrow\; t_1[Y] = t_2[Y].</span> <span class="math inline">X</span> “functionally determines” <span class="math inline">Y</span>: knowing <span class="math inline">X</span> suffices (in <span class="math inline">r</span>) to know <span class="math inline">Y</span>. A set <span class="math inline">F</span> of FDs is a <em>logical</em> object: it is required to hold for <em>all</em> instances allowed by the schema. <span class="math inline">X \to Y</span> with <span class="math inline">Y \subseteq X</span> is called <em>trivial</em>.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 3.2 — Armstrong’s axioms (validity and completeness)</span> The following three rules are <strong>valid</strong> (every derivable FD is satisfied by every instance satisfying <span class="math inline">F</span>):</p>
<ul>
<li><strong>reflexivity</strong>: if <span class="math inline">Y \subseteq X</span> then <span class="math inline">X \to Y</span>;</li>
<li><strong>augmentation</strong>: if <span class="math inline">X \to Y</span> then <span class="math inline">XZ \to YZ</span>;</li>
<li><strong>transitivity</strong>: if <span class="math inline">X \to Y</span> and <span class="math inline">Y \to Z</span> then <span class="math inline">X \to Z</span>.</li>
</ul>
<p>They are moreover <strong>complete</strong>: every FD logically implied by <span class="math inline">F</span> is derivable by these rules.</p>
<div class="proof" style="margin-top:.5rem;">
<p><span class="proof-title"><em>Proof</em>. </span>Validity (direct proofs). Reflexivity: if <span class="math inline">t_1[X]=t_2[X]</span> and <span class="math inline">Y\subseteq X</span>, the restrictions to <span class="math inline">Y</span> coincide. Augmentation: assume <span class="math inline">X\to Y</span> and <span class="math inline">t_1[XZ]=t_2[XZ]</span>; then <span class="math inline">t_1[X]=t_2[X]</span> hence <span class="math inline">t_1[Y]=t_2[Y]</span>, and <span class="math inline">t_1[Z]=t_2[Z]</span> by hypothesis; therefore <span class="math inline">t_1[YZ]=t_2[YZ]</span>. Transitivity: <span class="math inline">t_1[X]=t_2[X]</span> gives <span class="math inline">t_1[Y]=t_2[Y]</span>, which gives <span class="math inline">t_1[Z]=t_2[Z]</span>. Completeness: one shows that if <span class="math inline">X \to Y</span> is not derivable, then the two-tuple instance built as follows violates it while satisfying <span class="math inline">F</span>: <span class="math inline">t_1</span> carries distinct values per equivalence class of <span class="math inline">X^{+}</span> (the closure of Def. 3.3), <span class="math inline">t_2</span> equals <span class="math inline">t_1</span> on <span class="math inline">X^{+}</span> and differs elsewhere; every FD <span class="math inline">V \to W \in F</span> is then preserved (either <span class="math inline">V \subseteq X^{+}</span> and <span class="math inline">W</span> stays there, or <span class="math inline">V \not\subseteq X^{+}</span> and the tuples already differ on <span class="math inline">V</span>), while <span class="math inline">X\to Y</span> is violated. <span class="qed">∎</span></p>
</div>
</div>
<div class="def">
<p><span class="tag">Definition 3.3 — Closure <span class="math inline">X^+</span> and key</span> The <strong>closure</strong> of <span class="math inline">X</span> under <span class="math inline">F</span> is <span class="math inline">X^{+} = \{A \mid X \to A \text{ derivable from } F \text{ by Armstrong}\}</span>; it is computed in <span class="math inline">O(\|F\|)</span> passes (greedy algorithm: add the attributes determined by what we already have, up to a fixed point). <span class="math inline">K</span> is a <strong>key</strong> if <span class="math inline">K^{+}</span> contains all the attributes and no proper subset of <span class="math inline">K</span> does; attributes belonging to some key are called <strong>prime</strong>.</p>
</div>
<div class="def">
<p><span class="tag">Definition 3.4 — Normal forms</span> Let <span class="math inline">R</span> be equipped with <span class="math inline">F</span>, and <span class="math inline">K</span> a key:</p>
<ul>
<li><strong>1NF</strong>: all values are atomic (no lists or structured values in a cell);</li>
<li><strong>2NF</strong>: 1NF and no FD <span class="math inline">X \to Y</span> with <span class="math inline">X</span> a <em>strict</em> subset of a key and <span class="math inline">Y</span> non-prime (no <em>partial</em> dependency on the key);</li>
<li><strong>3NF</strong>: 2NF and for every nontrivial FD <span class="math inline">X \to Y</span>: <span class="math inline">X</span> is a superkey, <em>or</em> <span class="math inline">Y</span> is prime;</li>
<li><strong>BCNF</strong> (Boyce-Codd): for every nontrivial FD <span class="math inline">X \to Y</span>, <span class="math inline">X</span> is a superkey — the purest condition, without the “prime attribute” escape hatch.</li>
</ul>
</div>
<div class="thm">
<p><span class="tag">Theorem 3.5 — Lossless binary decomposition</span> Let <span class="math inline">R</span> be decomposed into <span class="math inline">\rho = (R_1, R_2)</span>, with <span class="math inline">R_1 \cup R_2 = R</span>. The decomposition is <strong>lossless</strong> (for every instance <span class="math inline">r</span> satisfying <span class="math inline">F</span>: <span class="math inline">r = \pi_{R_1}(r) \Join \pi_{R_2}(r)</span>) if and only if <span class="math display">(R_1 \cap R_2) \to R_1 \quad\text{or}\quad (R_1 \cap R_2) \to R_2 \;\in\; F^{+}.</span></p>
<div class="proof" style="margin-top:.5rem;">
<p><span class="proof-title"><em>Proof</em>. </span>Forward direction (the only one proved in full). Assume <span class="math inline">X = R_1 \cap R_2</span> and <span class="math inline">X \to R_1</span>. The inclusion <span class="math inline">r \subseteq \pi_{R_1}(r) \Join \pi_{R_2}(r)</span> always holds. Conversely, take <span class="math inline">t_1 \in \pi_{R_1}(r)</span> and <span class="math inline">t_2 \in \pi_{R_2}(r)</span> agreeing on <span class="math inline">X</span>, and let us show that their join <span class="math inline">s = t_1 \circ t_2</span> is in <span class="math inline">r</span>. Let <span class="math inline">u_1, u_2 \in r</span> be witnesses (<span class="math inline">u_1[R_1] = t_1</span>, <span class="math inline">u_2[R_2] = t_2</span>). Since <span class="math inline">t_1</span> and <span class="math inline">t_2</span> agree on <span class="math inline">X</span>, we have <span class="math inline">u_1[X] = u_2[X]</span>; the FD <span class="math inline">X \to R_1</span> forces <span class="math inline">u_1[R_1] = u_2[R_1]</span>, so <span class="math inline">u_2</span> equals <span class="math inline">t_1</span> on <span class="math inline">R_1</span> and <span class="math inline">t_2</span> on <span class="math inline">R_2</span>: <span class="math inline">u_2 = s</span> after all, and <span class="math inline">s \in r</span>. (The converse is proved by exhibiting, when neither FD holds, a two-tuple instance whose join produces a spurious tuple.) <span class="qed">∎</span></p>
</div>
</div>
<div class="ex">
<p><span class="tag">Example 3.6 — Normalizing an orders table</span> <span class="math inline">R(\text{order}, \text{item}, \text{qty}, \text{customer}, \text{city}, \text{unit\_price})</span> with <span class="math inline">F = \{</span>order·item <span class="math inline">\to</span> qty,&nbsp; order <span class="math inline">\to</span> customer,&nbsp; customer <span class="math inline">\to</span> city,&nbsp; item <span class="math inline">\to</span> unit_price<span class="math inline">\}</span>. Key: <span class="math inline">\{</span>order, item<span class="math inline">\}</span> (its closure generates everything). Visible anomalies: a customer’s city is repeated on each of their lines (update anomaly); an item with no order cannot exist (insertion). Normalization:</p>
<ul>
<li><strong>2NF</strong>: order <span class="math inline">\to</span> customer depends on a <em>part</em> of the key → extract Order(order, customer) and Line(order, item, qty); likewise item <span class="math inline">\to</span> unit_price → Item(item, unit_price);</li>
<li><strong>3NF</strong>: in Order(order, customer, city), the FD customer <span class="math inline">\to</span> city has a determinant that is not a superkey and city is not prime → extract Customer(customer, city);</li>
<li>result: Line(order, item, qty), Order(order, customer), Customer(customer, city), Item(item, unit_price) — each binary decomposition is validated by Theorem 3.5 (remember to check the intersection at each step).</li>
</ul>
</div>
<div class="note">
<p><span class="tag">Note — 3NF vs BCNF, and real life</span> Every relation admits a 3NF decomposition that is <em>lossless</em> and <em>dependency-preserving</em> (Bernstein synthesis: minimal cover, one schema per determinant, plus a key); some relations, on the other hand, have <em>no</em> BCNF decomposition that is both lossless and dependency-preserving — classic case: <span class="math inline">R(\text{city}, \text{street}, \text{zip\_code})</span> with \{city, street\} <span class="math inline">\to</span> zip_code and zip_code <span class="math inline">\to</span> city. 3NF is thus the minimal guarantee, BCNF the ideal when it preserves. In practice, warehouses <em>deliberately</em> denormalize (joins paid at write time rather than at read time): theory says what to pay, not whether to pay.</p>
</div>
<h2 id="ch4">4. Storage: pages, files, external sorting</h2>
<p>A DBMS lives on a hierarchy of memories with performance gaps of several orders of magnitude. The whole discipline of storage follows from this brute fact:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Level</th>
<th style="text-align: left;">Order of magnitude</th>
<th style="text-align: left;">Access</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Registers / L1-L3 cache</td>
<td style="text-align: left;">1-100 ns</td>
<td style="text-align: left;">words</td>
</tr>
<tr class="even">
<td style="text-align: left;">RAM</td>
<td style="text-align: left;">~100 ns, a few tens of GB</td>
<td style="text-align: left;">bytes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NVMe SSD</td>
<td style="text-align: left;">~20-100 µs per access, TB</td>
<td style="text-align: left;">pages (4-16 KiB)</td>
</tr>
<tr class="even">
<td style="text-align: left;">SATA SSD / HDD</td>
<td style="text-align: left;">~100 µs / ~5-10 ms, tens of TB</td>
<td style="text-align: left;">blocks</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Network / object store</td>
<td style="text-align: left;">~10-100 ms, unlimited</td>
<td style="text-align: left;">objects</td>
</tr>
</tbody>
</table>
<div class="def">
<p><span class="tag">Definition 4.1 — Page, record, organization</span> The <strong>page</strong> (block) is the unit of input/output: one reads and writes whole pages (typically 4 to 16 KiB), never isolated bytes. Records are stored in pages with <em>slots</em> (<em>slotted pages</em>: a directory at the head of the page gives the address of each record, allowing insertions, deletions, and variable-length records). A <strong>file organization</strong> defines how pages are linked: <em>heap</em> (append at the end, sequential read), <em>sorted</em> (order maintained: costly insertion, binary search), or <em>hashed</em> (ch.&nbsp;5).</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 4.2 — Cost of a sequential scan</span> For a file of <span class="math inline">N</span> pages and a sequential throughput <span class="math inline">D</span> pages/s, a full scan costs <span class="math inline">N/D</span>. Worked example: a 10 GB table in 8 KiB pages occupies <span class="math inline">N = 10^{10}/8192 \approx 1.22\times 10^6</span> pages; on HDD at 150 MB/s: <span class="math inline">\approx 67</span> s; on NVMe SSD at 3 GB/s: <span class="math inline">\approx 3.3</span> s; in random accesses at 10,000 IOPS: 122 s — hence the DBMS obsession with sequential access and prefetching.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 4.3 — External merge sort</span> With <span class="math inline">M</span> pages of buffer memory available and <span class="math inline">N</span> pages to sort, external merge sort produces sorted initial <em>runs</em> of <span class="math inline">M</span> pages, then merges them with arity <span class="math inline">M-1</span> (one output page). The number of passes equals <span class="math display">p \;=\; 1 + \Big\lceil \log_{M-1} \lceil N/M \rceil \Big\rceil,</span> and the total I/O cost is <span class="math inline">2Np</span> (each pass rereads and rewrites everything).</p>
<div class="proof" style="margin-top:.5rem;">
<p><span class="proof-title"><em>Proof</em>. </span>Pass 0 reads <span class="math inline">N</span> pages and writes <span class="math inline">\lceil N/M\rceil</span> sorted runs: cost <span class="math inline">2N</span>. At each merge pass, at most <span class="math inline">M-1</span> runs are consumed into one run (fan-in <span class="math inline">M-1</span> because one buffer page must be kept for output): the number of runs is divided by at least <span class="math inline">M-1</span>, hence <span class="math inline">\lceil\log_{M-1}\lceil N/M\rceil\rceil</span> merges. Each merge rereads/rewrites the pages involved, hence <span class="math inline">2N</span> per pass. <span class="qed">∎</span></p>
</div>
<div class="ex" style="margin-top:.4rem;">
<p><span class="tag">Example 4.4 — Numbers</span> <span class="math inline">N = 1000</span> pages, <span class="math inline">M = 50</span>: initial runs: 20; <span class="math inline">\log_{49}(20) \to 1</span> merge pass (fan-in 49&nbsp;≥&nbsp;20); <span class="math inline">p = 2</span>, cost <span class="math inline">2\times1000\times2 = 4000</span> pages read+written. With <span class="math inline">N = 10^6</span>, <span class="math inline">M = 10^3</span>: 1000 runs, fan-in 999, <span class="math inline">\lceil\log_{999}(1001)\rceil = 2</span>, <span class="math inline">p=3</span>, cost <span class="math inline">6\times10^6</span> — at 10,000 pages/s, about ten minutes: sorting remains <em>nearly linear</em> in practice thanks to the base (not the factor) of the logarithm.</p>
</div>
</div>
<div class="def">
<p><span class="tag">Definition 4.5 — Buffer pool</span> Between the disk and the processor, the DBMS manages a <strong>buffer pool</strong>: a RAM cache of page bytes, organized into <em>frames</em> the size of a page, with a <strong>page-to-frame mapping table</strong>. Every read goes through it: <em>hit</em> (the page is already there, RAM access) or <em>miss</em> (disk read then installation in a free frame). When no frame is free, a <strong>replacement policy</strong> chooses the victim — LRU as a first approximation, but real DBMSs prefer variants (LRU-K, clock with a reference bit, <em>least-frequently-used</em>): a massive sequential scan must not evict hot pages (hence the usage counter of scans). Writes: a modified page becomes <em>dirty</em> and is rewritten to disk only upon eviction — or earlier, by checkpointing (ch.&nbsp;7). The parameter <span class="math inline">M</span> of the sort and join algorithms (ch.&nbsp;8) is precisely the share of the buffer pool allocated to the operator: the whole physics of queries plays out in this cache.</p>
</div>
<div class="note">
<p><span class="tag">Note — Storing columns, not just rows</span> Modern warehouses (Parquet, BigQuery, Snowflake, DuckDB) store tables <em>by columns</em>: reading 3 columns out of 100 reads only ~3% of the data, with adapted encodings (dictionary, RLE) and min/max statistics per block to skip chunks. The logical model remains relational: a perfect illustration of logical/physical independence — and reading columns fast is producing learning matrices fast (see the <em>Machine Learning</em> module, ch.&nbsp;6).</p>
</div>
<h2 id="ch5">5. Indexes: B+ trees and hashing</h2>
<p>An index is a secondary structure that speeds up locating records without scanning them all. Two families dominate: <strong>B+ trees</strong> for range queries and sorting, <strong>hashing</strong> for exact equality. The DBMS maintains the index at every write: each additional index slows down insertions — there is no free index.</p>
<div class="def">
<p><span class="tag">Definition 5.1 — B+ tree</span> A B+ tree of order <span class="math inline">d</span> is a balanced tree in which every node contains between <span class="math inline">d</span> and <span class="math inline">2d</span> keys (only the root may contain fewer, at least 1), every internal node has (number of keys + 1) children, all the data resides in the leaves, and the leaves are chained together (range scan without going back up). The keys of an internal node are separators: the subtree between two keys contains the records of the corresponding open interval. When a leaf splits, the median key is <em>copied</em> to the parent (it remains present in the right leaf); when an internal node splits, it is <em>moved</em> up to the parent.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 5.2 — Height of a B+ tree</span> A B+ tree of order <span class="math inline">d</span> containing <span class="math inline">n</span> entries has height <span class="math display">h \;\leq\; 2 + \log_{d+1}(n/2),</span> so that search, insertion, and deletion cost <span class="math inline">\Theta(\log_d n)</span> logical I/Os — in practice 3 to 5 pages.</p>
<div class="proof" style="margin-top:.5rem;">
<p><span class="proof-title"><em>Proof</em>. </span>Count the minimal number of leaves of a tree of height <span class="math inline">h</span> (root at level 1, leaves at level <span class="math inline">h</span>, <span class="math inline">h \geq 2</span>). The root has at least 2 children; every internal non-root node has at least <span class="math inline">d+1</span> children (because at least <span class="math inline">d</span> keys); every leaf carries at least <span class="math inline">d</span> entries. The number of leaves is therefore at least <span class="math inline">2\,(d+1)^{h-2}</span>, and each contains at least <span class="math inline">d</span> entries: <span class="math inline">n \geq 2d\,(d+1)^{h-2} \geq 2\,(d+1)^{h-2}</span> (since <span class="math inline">d \geq 1</span>), hence <span class="math inline">(d+1)^{h-2} \leq n/2</span> and the announced bound. Search: one page per level; insertion: descent plus possible split cascades upward, one page per level; both are <span class="math inline">\Theta(h)</span>. <span class="qed">∎</span></p>
</div>
<div class="ex" style="margin-top:.4rem;">
<p><span class="tag">Example 5.3 — A billion entries in 4 hops</span> With 8 KiB pages, 16 B keys+pointers, a node holds up to ~512 keys: take <span class="math inline">d = 63</span> (fan-out 64 to 128). For <span class="math inline">n = 10^9</span> entries: <span class="math inline">h \leq 2 + \log_{64}(5\times10^8) = 2 + \frac{\ln(5\times10^8)}{\ln 64} = 2 + \frac{20.03}{4.16} \approx 6.8</span>, hence <span class="math inline">h \leq 6</span> (and even 5 for a fan-out of 128). The upper levels fit in RAM: an equality search costs 1-2 page reads instead of the <span class="math inline">1.2\times10^6</span> of the full scan (Prop. 4.2).</p>
</div>
</div>
<div class="ex">
<p><span class="tag">Example 5.4 — Cascading insertions (d = 1)</span> Insert 10, 20, 5, 15, 30, 25, 35, 40, 45 into a B+ tree of order 1 (1 to 2 keys per node). After 10, 20: leaf [10, 20]. The 5 overflows: split into [5, 10] and [20], copy of 20 to the new root. The 15 refills the first leaf: [5,10,15] → [5,10] and [15], root [15, 20], three leaves. The 30 fills the right leaf [20, 30]. The 25 makes it overflow: [20,25] / [30], copy of 30 — the root [15,20,30] overflows in turn: <em>internal</em> split, key 20 is moved to the new root [20]. The 35, the 40 (split of [30,35,40] → [30,35] / [40], copy of 40) and the 45 lead to the final tree (height 3):</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>                    [<span class="dv">20</span>]</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>             ┌────────┴────────┐</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>           [<span class="dv">15</span>]              [<span class="dv">30</span>, <span class="dv">40</span>]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>         ┌──┴──┐        ┌──────┼──────┐</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>      [<span class="dv">5</span>,<span class="dv">10</span>]  [<span class="dv">15</span>]   [<span class="dv">20</span>,<span class="dv">25</span>] [<span class="dv">30</span>,<span class="dv">35</span>] [<span class="dv">40</span>,<span class="dv">45</span>]</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>      ──────── leaves chained ────────▶</span></code></pre></div>
<p>Each leaf has between 1 and 2 keys, the root at least 1: the structure stays at least half full after each deletion rebalanced by borrowing or merging — this is what guarantees Theorem 5.2 <em>over time</em>.</p>
</div>
<div class="def">
<p><span class="tag">Definition 5.5 — Static and extendible hashing</span> An <strong>on-disk hash table</strong> applies <span class="math inline">h(k) = k \bmod B</span> to store the record with key <span class="math inline">k</span> in bucket <span class="math inline">h(k)</span>: exact equality in 1 + (overflows) I/Os. <strong>Extendible hashing</strong> grows <span class="math inline">B</span> dynamically: a directory of <span class="math inline">2^g</span> pointers (global depth <span class="math inline">g</span>) pointing to buckets, each of which uses only the <span class="math inline">p_i \leq g</span> high-order bits of the hash (local depth); when a bucket overflows, double the directory if needed (<span class="math inline">g{+}{=}g{+}1</span>) then split the bucket according to bit <span class="math inline">p_i{+}1</span>. Example: buckets of 2 slots, hashes 4 (100), 12 (1100) and 20 (10100) — all in 00; at <span class="math inline">g=2</span> bucket 00 overflows, moves to depth 1 and splits into 0 (4, 20) and 1 (12) without doubling the directory. The load factor stays under control without global reorganization; Litwin’s <em>linear hashing</em> achieves the same effect without a directory.</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 5.6 — What each index can do</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Criterion</th>
<th style="text-align: left;">B+ tree</th>
<th style="text-align: left;">Hashing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Equality (=)</td>
<td style="text-align: left;"><span class="math inline">\log</span> pages 1</td>
<td style="text-align: left;">page (ideal)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Range, prefix, order</td>
<td style="text-align: left;">excellent (leaves chained)</td>
<td style="text-align: left;">impossible</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Insertion</td>
<td style="text-align: left;"><span class="math inline">\log</span>, balance guaranteed a</td>
<td style="text-align: left;">mortized O(1), overflows</td>
</tr>
<tr class="even">
<td style="text-align: left;">Typical uses</td>
<td style="text-align: left;">primary keys, filtered/sorted columns, foreign keys</td>
<td style="text-align: left;">exact join tables, hash joins (ch.&nbsp;8), in-memory dedup</td>
</tr>
</tbody>
</table>
<p>Composite index rule: a B+ index on (a, b, c) serves predicates on <span class="math inline">a</span>, then (a, b), then (a, b, c) — but <em>not</em> b alone: the keys are sorted like a dictionary (a first). An index can also <em>cover</em> a query (all requested columns are in the index: the table is never read — a <em>covering index</em> often divides times by 10).</p>
</div>
<h2 id="ch6">6. Transactions and concurrency</h2>
<p>Several programs access the same data at the same time. The <strong>transaction</strong> is the unit of consistency: a sequence of read (r) and write (w) operations that must execute <em>as if</em> it were alone. The ACID acronym summarizes the contract: <em>Atomicity</em> (all or nothing), <em>Consistency</em> (constraints hold), <em>Isolation</em> (equivalence to a serial execution), <em>Durability</em> (a commit survives a crash — the subject of ch.&nbsp;7).</p>
<div class="def">
<p><span class="tag">Definition 6.1 — Schedules, conflicts, serializability</span> A <strong>schedule</strong> <span class="math inline">H</span> is a sequence of operations from several transactions, preserving the internal order of each. Two operations are <strong>in conflict</strong> if they belong to different transactions, bear on the same object, and at least one is a write. <span class="math inline">H</span> is <strong>conflict-serializable</strong> (CSR) if it is equivalent by conflicts to a serial schedule; the <strong>serialization graph</strong> <span class="math inline">SG(H)</span> has one vertex per transaction and an edge <span class="math inline">T_i \to T_j</span> as soon as a conflicting pair of operations places an operation of <span class="math inline">T_i</span> before one of <span class="math inline">T_j</span>.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 6.2 — The serialization graph criterion</span> <span class="math inline">H</span> is conflict-serializable if and only if <span class="math inline">SG(H)</span> is acyclic; in that case, every topological order of <span class="math inline">SG(H)</span> gives an equivalent serial execution.</p>
<div class="proof" style="margin-top:.5rem;">
<p><span class="proof-title"><em>Proof</em>. </span>If <span class="math inline">H</span> is equivalent to the serial schedule <span class="math inline">T_{\sigma(1)} \dots T_{\sigma(k)}</span>, every edge <span class="math inline">T_i \to T_j</span> of <span class="math inline">SG(H)</span> must be respected by <span class="math inline">\sigma</span> (conflict equivalence preserves the order of all conflicting pairs): the graph is embedded in a total order, hence acyclic. Conversely, if <span class="math inline">SG(H)</span> is acyclic with topological order <span class="math inline">\sigma</span>, one checks that the associated serial schedule has the same conflicting pairs in the same order: for a given pair, the directed edge in <span class="math inline">SG(H)</span> (which exists by definition) imposes the same relative order as <span class="math inline">\sigma</span>. <span class="qed">∎</span></p>
</div>
</div>
<div class="ex">
<p><span class="tag">Example 6.3 — Lost update</span> Let <span class="math inline">H = r_1(X)\, r_2(X)\, w_1(X)\, w_2(X)\, c_1\, c_2</span> with X a stock counter worth 100, <span class="math inline">T_1</span> adding 50 and <span class="math inline">T_2</span> subtracting 30. Serialized (<span class="math inline">T_1;T_2</span>): <span class="math inline">100 \to 150 \to 120</span>. In <span class="math inline">H</span>: both reads see 100, <span class="math inline">w_1</span> writes 150, then <span class="math inline">w_2</span> overwrites with 70: the update of <span class="math inline">T_1</span> is <em>lost</em>. Conflicts on X: <span class="math inline">r_1(X) &lt; w_2(X)</span> gives <span class="math inline">T_1 \to T_2</span>, and <span class="math inline">r_2(X) &lt; w_1(X)</span> gives <span class="math inline">T_2 \to T_1</span>: a cycle, <span class="math inline">H</span> is not serializable — the graph had announced it even before reading the values.</p>
</div>
<div class="def">
<p><span class="tag">Definition 6.4 — Two-phase locking (2PL)</span> A transaction follows <strong>2PL</strong> if it acquires all its locks before releasing a single one: growing phase (acquisitions), lock point, shrinking phase (releases). <strong>Strict 2PL</strong> (or rigorous) releases a write’s locks only after commit — it avoids cascading aborts. Locks can be shared (read) or exclusive (write), with S-S the only compatibility.</p>
</div>
<div class="thm">
<p><span class="tag">Theorem 6.5 — Every legal 2PL execution is serializable</span> If a schedule <span class="math inline">H</span> respects 2PL (for each transaction, legality of the locks being ensured: no lock acquired while the conflicting lock has not been released), then <span class="math inline">SG(H)</span> is acyclic, hence <span class="math inline">H</span> is CSR.</p>
<div class="proof" style="margin-top:.5rem;">
<p><span class="proof-title"><em>Proof</em>. </span>Reason by contradiction and assume a cycle <span class="math inline">T_1 \to T_2 \to \cdots \to T_k \to T_1</span>. For each edge <span class="math inline">T_i \to T_j</span> there exists an object <span class="math inline">q</span> and a conflicting pair <span class="math inline">o_i[q] &lt; o_j[q]</span>; since at least one of the two operations is a write, the locks of <span class="math inline">T_i</span> and <span class="math inline">T_j</span> on <span class="math inline">q</span> are incompatible, hence do not overlap: legality imposes <span class="math inline">\text{unlock}_i(q) &lt; \text{lock}_j(q)</span>. Let <span class="math inline">u_i</span> be the instant when <span class="math inline">T_i</span> releases its <em>first</em> lock (its lock point); then <span class="math inline">u_i \leq \text{unlock}_i(q) &lt; \text{lock}_j(q) \leq u_j</span>, the last inequality coming from 2PL: <span class="math inline">T_j</span> cannot acquire a lock after <span class="math inline">u_j</span>, so <span class="math inline">\text{lock}_j(q) \leq u_j</span>. Chaining along the cycle: <span class="math inline">u_1 &lt; u_2 &lt; \cdots &lt; u_k &lt; u_1</span> — contradiction. <span class="qed">∎</span></p>
</div>
</div>
<div class="prop">
<p><span class="tag">Proposition 6.6 — Deadlock and isolation levels</span> 2PL creates waiting cycles: <span class="math inline">T_1</span> holds X and wants Y, <span class="math inline">T_2</span> holds Y and wants X. DBMSs detect (wait-for graph, cycle = deadlock) and <em>abort a victim</em> (rollback then retry). The standard levels offered by SQL:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Level</th>
<th style="text-align: left;">Dirty read</th>
<th style="text-align: left;">Non-repeatable read</th>
<th style="text-align: left;">Phantoms</th>
<th style="text-align: left;">Mechanism</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">READ UNCOMMITTED</td>
<td style="text-align: left;">possible</td>
<td style="text-align: left;">possible</td>
<td style="text-align: left;">possible</td>
<td style="text-align: left;">no read locks</td>
</tr>
<tr class="even">
<td style="text-align: left;">READ COMMITTED</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">possible</td>
<td style="text-align: left;">possible</td>
<td style="text-align: left;">short read locks</td>
</tr>
<tr class="odd">
<td style="text-align: left;">REPEATABLE READ</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">possible</td>
<td style="text-align: left;">long row locks</td>
</tr>
<tr class="even">
<td style="text-align: left;">SERIALIZABLE</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">full 2PL / predicates</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SNAPSHOT (MVCC)</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no*</td>
<td style="text-align: left;">reads on a dated version, no read locks</td>
</tr>
</tbody>
</table>
<p>(*) at the price of write collisions detected a posteriori (PostgreSQL: error 40001, to be replayed). <strong>MVCC</strong> (multi-version concurrency control) keeps several dated versions of each row: each transaction reads a consistent snapshot of the past — readers never block writers. This is the default strategy of PostgreSQL and of MySQL’s InnoDB engine.</p>
</div>
<h2 id="ch7">7. The log and crash recovery</h2>
<p>Durability requires writing to persistent storage <em>before</em> answering “commit”, and atomicity requires being able to undo — even after a crash right in the middle. Both requirements are solved by one and the same structure: the <strong>log</strong> (<em>write-ahead log</em>, WAL), an ordered sequence of records describing every modification, written sequentially (hence fast, see ch.&nbsp;4).</p>
<div class="def">
<p><span class="tag">Definition 7.1 — WAL, LSN, STEAL/FORCE policy</span> Each log record receives a sequence number (<strong>LSN</strong>). For a page write by a transaction: &lt;LSN, T, page, row, before-image, after-image, previous-LSN-of-T&gt;. The <strong>WAL</strong> rule: the log fragment of a modification must reach the disk <em>before</em> the modified page. Possible policies: <strong>STEAL</strong> (one may evict an uncommitted modified page from the buffer → one must know how to undo) vs NO-STEAL; <strong>FORCE</strong> (all pages are written at commit → no need to redo) vs NO-FORCE. Every serious DBMS chooses STEAL/NO-FORCE — the most performant, the one that requires both <em>undo</em> and <em>redo</em>.</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 7.2 — Idempotence and ARIES recovery</span> The recovery passes must be <em>idempotent</em> (replayed twice, same effect): this holds if redo/undo are driven by the LSNs stored in the pages. The <strong>ARIES</strong> algorithm (Mohan et al., 1992), deployed in all major DBMSs, recovers in three phases:</p>
<ul>
<li><strong>Analysis</strong>: reread the log since the last <em>checkpoint</em> to rebuild the table of in-progress transactions and the dirty page table;</li>
<li><strong>Redo</strong>: replay, in LSN order, the after-image of every modification whose LSN exceeds the one recorded in the page (repeating history, including uncommitted transactions);</li>
<li><strong>Undo</strong>: cancel, in <em>reverse</em> LSN order, the modifications of uncommitted transactions, writing compensation records (CLR) — if the machine crashes again during recovery, one resumes where one had stopped.</li>
</ul>
</div>
<div class="ex">
<p><span class="tag">Example 7.3 — Rolling out a recovery by hand</span> Log (LSN: 1-7) then crash:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">LSN</th>
<th style="text-align: left;">Record</th>
<th style="text-align: left;">Effect</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">checkpoint</td>
<td style="text-align: left;">T1 active</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">T1: update X (before 10 → after 15)</td>
<td style="text-align: left;">page P1 dirty</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">T2: update Y (before 5 → after 8)</td>
<td style="text-align: left;">page P2 dirty</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">T1: commit</td>
<td style="text-align: left;">T1 completed</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">T2: update X (before 15 → after 20)</td>
<td style="text-align: left;">P1 dirty</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">T3: update Z (before 3 → after 7)</td>
<td style="text-align: left;">P3 dirty</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">T2: … (no commit)</td>
<td style="text-align: left;">crash here</td>
</tr>
</tbody>
</table>
<p>ARIES recovery: analysis → T2 and T3 in progress, T1 committed, pages P1-P3 potentially dirty. Redo: LSN 2, 3, 5, 6 replayed (X=20, Y=8, Z=7). Undo (reverse order): LSN 6 canceled (Z=3, CLR written), then LSN 5 (X=15) and LSN 3 (Y=5); T2 and T3 are rolled back, T1 survives. Note that redo reapplies LSN 5 (a write of T2, uncommitted) before undoing it: this is the mark of ARIES — “repeat history” — and the reason for the CLR, which makes undo itself restartable.</p>
</div>
<div class="note">
<p><span class="tag">Note — Checkpoints and the cost of durability</span> A fuzzy <em>checkpoint</em> forces the buffer to disk and bars a record in the log, bounding the length of the redo; without it, recovery would reread the whole log. In exchange, every commit waits for at least one sequential log write (<em>group commit</em>: concurrent commits share a single flush): typically ~1 ms — the measurable price of ACID.</p>
</div>
<h2 id="ch8">8. Query optimization</h2>
<p>SQL is declarative: the <strong>execution plan</strong> — the order of operations, the join algorithms, the indexes used — is chosen by the optimizer. The principle: rewrite the query as an algebraic tree, generate the equivalent plans via the laws of Proposition 1.4, estimate their cost with a model, keep the cheapest. It is a closed loop between theory (equivalences) and physics (the cost model of ch.&nbsp;4).</p>
<div class="def">
<p><span class="tag">Definition 8.1 — Cost model and selectivity</span> For each table, the catalog stores <span class="math inline">n</span> (number of tuples), <span class="math inline">b</span> (pages), and for each column <span class="math inline">ND(A)</span> (number of distinct values) or even a histogram. The <strong>selectivity</strong> of a predicate is the expected fraction of rows: <span class="math inline">sel(A = c) \approx 1/ND(A)</span>, <span class="math inline">sel(A &lt; c)</span> via histogram, <span class="math inline">sel(p_1 \wedge p_2) \approx sel(p_1)\cdot sel(p_2)</span> (independence — a false but convenient assumption, corrected by modern engines via dynamic sampling). Estimated cardinality of a node = selectivity × cardinality of the child.</p>
</div>
<div class="def">
<p><span class="tag">Definition 8.2 — Join algorithms</span> Let <span class="math inline">R</span> (<span class="math inline">B_R</span> pages) and <span class="math inline">S</span> (<span class="math inline">B_S</span> pages), with a buffer of <span class="math inline">M</span> pages:</p>
<ul>
<li><strong>nested loops</strong> (NLJ): for each page of <span class="math inline">R</span>, scan <span class="math inline">S</span> — cost <span class="math inline">B_R + B_R\!\cdot\!B_S</span>; by blocks of <span class="math inline">M-1</span> pages: <span class="math inline">B_R + \lceil B_R/(M-1)\rceil \cdot B_S</span>;</li>
<li><strong>sort-merge join</strong>: sort <span class="math inline">R</span> and <span class="math inline">S</span> (Thm 4.3) then merge — cost <span class="math inline">2B_R(1+\lceil\log_{M-1}\lceil B_R/M\rceil\rceil) + 2B_S(\dots) + B_R + B_S</span>, zero if already sorted (B+ index);</li>
<li><strong>hash join</strong>: partition both relations on the join key with the same hash (one pass if everything fits in <span class="math inline">M</span>), then build a hash table per partition and probe — cost <span class="math inline">\approx 3(B_R+B_S)</span>, in memory if <span class="math inline">B_R</span> or <span class="math inline">B_S</span> fits in RAM.</li>
</ul>
</div>
<div class="ex">
<p><span class="tag">Example 8.3 — Numbers: the winning plan cannot be guessed</span> <span class="math inline">B_R = 1000</span> pages, <span class="math inline">B_S = 500</span>, <span class="math inline">M = 50</span>. Simple nested loops: <span class="math inline">1000 + 1000\times500 = 501\,000</span> pages. By blocks: <span class="math inline">1000 + \lceil 1000/49\rceil \times 500 = 1000 + 21\times500 = 11\,500</span>. Sort-merge: sorting <span class="math inline">R</span> in 2 passes → 4000, sorting <span class="math inline">S</span> in 2 passes → 2000, merge 1500: total 7500. Hash: <span class="math inline">3\times(1000+500) = 4500</span> — and if <span class="math inline">S</span> fits in memory, <span class="math inline">1000 + 500 = 1500</span>.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Algorithm</th>
<th style="text-align: left;">Cost (I/O pages)</th>
<th style="text-align: left;">Success conditions</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">naive NLJ</td>
<td style="text-align: left;">501,000</td>
<td style="text-align: left;">none</td>
</tr>
<tr class="even">
<td style="text-align: left;">block NLJ</td>
<td style="text-align: left;">11,500</td>
<td style="text-align: left;"><span class="math inline">M \geq 3</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">sort-merge</td>
<td style="text-align: left;">7,500</td>
<td style="text-align: left;">all; optimal if inputs sorted</td>
</tr>
<tr class="even">
<td style="text-align: left;">hash</td>
<td style="text-align: left;">4,500</td>
<td style="text-align: left;">partitions ≤ <span class="math inline">M</span> pages</td>
</tr>
</tbody>
</table>
<p>The optimizer makes this table for <em>every</em> join and <em>every</em> nesting order: a query with 10 joins admits <span class="math inline">\sim 10!\times 2^{10}</span> equivalent trees. System&nbsp;R’s dynamic programming (sets of relations, Cartesian joins avoided) makes the exploration polynomial in <span class="math inline">2^n</span> tables; the general case is NP-hard, and beyond a dozen tables engines switch to randomized searches.</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 8.4 — Safe heuristic rewrites</span> Before any cost-based search, one applies the “always winning” rewrites: push down selections (Prop. 1.4), push down projections (reduce tuple width), reject Cartesian products outside useful joins, eliminate redundant subqueries, transform <code>IN</code> into semi-joins. Each selection pushed down divides the cardinality of the subtree involved: with <span class="math inline">sel = 1/100</span>, filtering <span class="math inline">10^6</span> rows before rather than after a join gains a factor ~100 on that stream. Engines add costly but profitable rewrites: elimination of unnecessary joins (a join by foreign key without reading the columns of <span class="math inline">S</span> and without multiplicity is superfluous), materialized CTEs, plan reuse (plan cache).</p>
</div>
<div class="def">
<p><span class="tag">Definition 8.5 — Evaluating selection: access paths</span> Even before the joins, each <strong>relational operator</strong> comes in several <em>implementations</em> that the optimizer compares:</p>
<ul>
<li><strong>selection</strong>: sequential scan (<span class="math inline">B_R</span> pages, Def. 4.2), or B+ tree descent when an index covers the predicate (<span class="math inline">\lceil \log_F B_R \rceil + 1</span> pages), or an <em>index-only scan</em> if the index contains all requested columns (zero table access);</li>
<li><strong>projection and aggregation</strong>: tuple stream, with sorting or hashing to eliminate duplicates and group (sort-agg vs hash-agg, depending on available memory);</li>
<li><strong>union, difference</strong>: merge of sorted streams or hash tables, in the same spirit as the joins of Def. 8.2.</li>
</ul>
<p>The cost of each variant combines the selectivity model (Def. 8.1), the buffer pool (Def. 4.5), and the available indexes (ch.&nbsp;5): reading an <code>EXPLAIN</code> is seeing this choice materialized node by node.</p>
</div>
<div class="note">
<p><span class="tag">Note — Reading an EXPLAIN</span> <code>EXPLAIN QUERY PLAN</code> (SQLite) or <code>EXPLAIN (ANALYZE, BUFFERS)</code> (PostgreSQL) shows the chosen tree and the real cardinalities. Typical diagnosis: an estimate off by a factor of 1000 (stale statistics, unmodeled correlation) → nested loops where hashing would be needed. Reflex: compare estimated vs actual <code>rows</code> node by node, and trace back to the first divergence.</p>
</div>
<h2 id="ch9">9. Beyond relational: NoSQL, graphs, vectors</h2>
<p>The relational model dominates transactional workloads, but three developments of the 2000-2020 period seeded new models: horizontal scale (NoSQL), data as graphs (knowledge graphs), and search by <strong>similarity</strong> over vectors — the fuel of learning systems and of RAG (see the <em>Large Language Models</em> module, chapter 7).</p>
<div class="thm">
<p><span class="tag">Theorem 9.1 — CAP (Brewer, 2000; Gilbert-Lynch, 2002)</span> In a distributed system subject to <em>network failures</em> (partitions), one cannot simultaneously guarantee strong consistency (C) and availability (A): one must choose, at least during the partition.</p>
<div class="proof" style="margin-top:.5rem;">
<p><span class="proof-title"><em>Proof</em>. </span>Sketch. Partition the network into two components <span class="math inline">\Gamma_1, \Gamma_2</span>. One client writes into <span class="math inline">\Gamma_1</span>, another reads from <span class="math inline">\Gamma_2</span>. If both operations succeed (A), the read cannot see the write: inconsistency (not C). To stay consistent, <span class="math inline">\Gamma_2</span> must refuse or block (not A). <span class="qed">∎</span></p>
</div>
<p>NoSQL systems therefore claim AP with <em>eventual</em> consistency (BASE); so-called CP systems sacrifice availability during partitions. The trade-off is managed per query (readable / writable consistency levels, quorum <span class="math inline">r + w &gt; n</span>).</p>
</div>
<div class="def">
<p><span class="tag">Definition 9.2 — NoSQL families</span></p>
<ul>
<li><p><strong>key-value</strong> (Redis, DynamoDB): a distributed hash table (ch.&nbsp;5 at cluster scale, consistent hashing);</p></li>
<li><p><strong>documents</strong> (MongoDB): identified JSON trees, queried by fields — 1NF is deliberately abandoned in order to group what is read together;</p>
<pre class="code"><code>{ "_id": "ord1043", "customer": { "name": "Anna", "city": "Palaiseau" },
  "lines": [ { "item": "DB", "qty": 2 }, { "item": "DL", "qty": 1 } ],
  "status": "shipped" }</code></pre></li>
<li><p><strong>columns</strong> (Cassandra, Bigtable): sparse rows physically grouped by column family and sorted by clustering key — SSTables and the <em>log-structured merge tree</em> (memtable → levels of sorted files, reads bounded by Bloom filters) replace the B+ tree;</p></li>
<li><p><strong>graphs</strong>: see below — the only model where the recursive join is a first-class citizen.</p></li>
</ul>
</div>
<div class="def">
<p><span class="tag">Definition 9.3 — Property graphs and RDF</span> A <strong>property graph</strong> (Neo4j; GQL standard) is a multi-relational graph whose nodes and edges carry key-value properties. The <strong>Cypher</strong> language queries by patterns:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>MATCH (a:Person {name: <span class="st">"Anna"</span>})<span class="op">-</span>[:ENROLLED_IN<span class="op">*</span><span class="fl">1..3</span>]<span class="op">-&gt;</span>(c:Course)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>WHERE c.credits <span class="op">&gt;=</span> <span class="dv">3</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>RETURN DISTINCT c.code<span class="op">;</span></span></code></pre></div>
<p>The <strong>RDF</strong> model (W3C) represents everything as <em>triples</em> (subject, predicate, object) forming a global labeled directed graph, with <em>IRIs</em> (universal identifiers) and ontologies (RDFS, OWL) for reasoning. SPARQL takes up SQL (SELECT/WHERE) on graph patterns:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>SELECT DISTINCT ?code WHERE {</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  :Anna :enrolledIn<span class="op">+</span> ?c .            <span class="co"># path of length ≥ 1 (SPARQL 1.1)</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  ?c :credits ?cr . FILTER(?cr <span class="op">&gt;=</span> <span class="dv">3</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  ?c :code ?code . }</span></code></pre></div>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Criterion</th>
<th style="text-align: left;">Property graph</th>
<th style="text-align: left;">RDF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Identifiers</td>
<td style="text-align: left;">local to the database</td>
<td style="text-align: left;">global IRIs → natural federation</td>
</tr>
<tr class="even">
<td style="text-align: left;">Edge properties</td>
<td style="text-align: left;">yes, first-class</td>
<td style="text-align: left;">by reification (statement-node)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Schema</td>
<td style="text-align: left;">flexible, local constraints</td>
<td style="text-align: left;">RDFS/OWL ontologies, inference</td>
</tr>
<tr class="even">
<td style="text-align: left;">Queries</td>
<td style="text-align: left;">Cypher/GQL, patterns + paths</td>
<td style="text-align: left;">SPARQL, federated, reasoning</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ecosystem</td>
<td style="text-align: left;">apps, recommendation, integration</td>
<td style="text-align: left;">web of data, science, libraries</td>
</tr>
</tbody>
</table>
<p>For learning on graphs (node embeddings, GNNs, message passing), both models project onto sparse matrices — see the <em>Graph ML</em> module, chapters 1 (why graphs?) and 5 (GNNs).</p>
</div>
<div class="def">
<p><span class="tag">Definition 9.4 — Vector databases and ANN search</span> A <strong>vector store</strong> indexes embeddings <span class="math inline">x_i \in \mathbb{R}^d</span> (produced by encoders — see the <em>NLP</em> module, ch.&nbsp;3, and <em>Multimodal GenAI</em>, ch.&nbsp;5) with a distance (cosine, <span class="math inline">L^2</span>) and answers “the <span class="math inline">k</span> nearest neighbors of <span class="math inline">q</span>”. <em>Exact</em> search costs <span class="math inline">O(nd)</span>: for <span class="math inline">n = 10^7</span>, <span class="math inline">d = 768</span>, that is <span class="math inline">7.7\times10^{10}</span> multiplications per query — prohibitive in service. <strong>Approximate</strong> (ANN) search trades a bit of recall for orders of magnitude of speed:</p>
<ul>
<li><strong>IVF</strong> (inverted file): partition the space into <span class="math inline">n_{list}</span> cells by k-means (see the <em>Machine Learning</em> module, ch.&nbsp;6); explore only the <span class="math inline">n_{probe}</span> closest cells. <span class="math inline">n_{list} = 4096</span>, <span class="math inline">n_{probe} = 16</span> over <span class="math inline">10^7</span> vectors: ~ <span class="math inline">39\,000</span> distances instead of <span class="math inline">10^7</span> — 250× less work, typical recall &gt; 95%;</li>
<li><strong>HNSW</strong> (Malkov-Yashunin): hierarchical “navigable small-world” graph. Layer 0 contains all the vectors, the upper layers increasingly sparse vertices (a node appears at layer <span class="math inline">\ell</span> with probability <span class="math inline">p^{-\ell}</span>). The search starts from the top layer’s vertex and performs <em>greedy routing</em> (move to the neighbor that gets closest to <span class="math inline">q</span>) while going down layer by layer; insertion links the new node to its <span class="math inline">M</span> nearest neighbors found this way. The long links of the upper layers (chosen by a diversity heuristic) provide the nearly logarithmic shortcut; practical cost ~<span class="math inline">O(\log n)</span>, tunable recall, at the price of costly construction and an in-memory graph;</li>
<li><strong>quantization</strong> (PQ): split <span class="math inline">x \in \mathbb{R}^d</span> into <span class="math inline">m</span> sub-vectors each quantized over <span class="math inline">2^8</span> centroids; the distance becomes a sum of terms read from tables — memory divided by ~<span class="math inline">d</span>, at the price of an approximate distance.</li>
</ul>
</div>
<div class="ex">
<p><span class="tag">Example 9.5 — Vector search in Python (full scan + IVF)</span></p>
<div class="sourceCode" id="cb7"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.cluster <span class="im">import</span> MiniBatchKMeans</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>rng  <span class="op">=</span> np.random.default_rng(<span class="dv">0</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>X    <span class="op">=</span> rng.normal(size<span class="op">=</span>(<span class="dv">100_000</span>, <span class="dv">64</span>)).astype(<span class="st">"float32"</span>)   <span class="co"># vector "database"</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>q    <span class="op">=</span> rng.normal(size<span class="op">=</span>(<span class="dv">64</span>,)).astype(<span class="st">"float32"</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> normalize(A): <span class="cf">return</span> A <span class="op">/</span> np.linalg.norm(A, axis<span class="op">=</span><span class="dv">1</span>, keepdims<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>Xn, qn <span class="op">=</span> normalize(X), q <span class="op">/</span> np.linalg.norm(q)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="co"># --- 1. exact search (brute force): O(n d)</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>d_all <span class="op">=</span> Xn <span class="op">@</span> qn</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>top10_exact <span class="op">=</span> <span class="bu">set</span>(np.argsort(d_all)[<span class="op">-</span><span class="dv">10</span>:])</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="co"># --- 2. IVF: nlist cells by k-means, we probe nprobe cells</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>nlist, nprobe <span class="op">=</span> <span class="dv">256</span>, <span class="dv">8</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>km <span class="op">=</span> MiniBatchKMeans(n_clusters<span class="op">=</span>nlist, n_init<span class="op">=</span><span class="dv">3</span>, random_state<span class="op">=</span><span class="dv">0</span>).fit(Xn)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>cell_of_X <span class="op">=</span> km.labels_</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>d_centro  <span class="op">=</span> np.linalg.norm(km.cluster_centers_ <span class="op">-</span> qn, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>probes    <span class="op">=</span> np.argsort(d_centro)[:nprobe]</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>cand      <span class="op">=</span> np.where(np.isin(cell_of_X, probes))[<span class="dv">0</span>]</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>top10_ivf <span class="op">=</span> <span class="bu">set</span>(cand[np.argsort(Xn[cand] <span class="op">@</span> qn)[<span class="op">-</span><span class="dv">10</span>:]])</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">len</span>(top10_exact <span class="op">&amp;</span> top10_ivf) <span class="op">/</span> <span class="dv">10</span>, <span class="st">"recall@10"</span>)     <span class="co"># typically 0.9-1.0</span></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"exact: </span><span class="sc">{</span><span class="bu">len</span>(Xn)<span class="sc">}</span><span class="ss"> distances; IVF: </span><span class="sc">{</span><span class="bu">len</span>(cand) <span class="op">+</span> nlist<span class="sc">}</span><span class="ss"> distances"</span>)</span></code></pre></div>
<p>Recall <code>@k</code> is traded against cost: it is the same trade-off as for B+ trees (exact, logarithmic, constrained by prefixes) — but with an assumed probabilistic tolerance. Relational DBMSs today integrate these indexes as extensions (pgvector; the <em>Large Language Models</em> module, ch.&nbsp;7, shows the complete RAG pipeline that consumes them).</p>
</div>
<h2 id="ch10">10. Web data and heterogeneous integration</h2>
<p>The web is the largest database in the world — without schema, without keys, without constraints. The data feeding learning (and data journalism) arrives as HTML pages, semi-structured files (JSON, XML), tables, documents. This chapter addresses the specific problems: extract, match, merge.</p>
<div class="def">
<p><span class="tag">Definition 10.1 — Semi-structured data and the web of data</span> Data is <strong>semi-structured</strong> when its schema is implicit, carried by the data itself (JSON/XML trees, RDF graphs). The <strong>web of data</strong> (linked data) publishes RDF with shared IRIs, and also nestles into ordinary pages via embedded annotations (schema.org in JSON-LD): search engines derive “rich snippets” from them. Interoperability rests on <strong>ontologies</strong> (shared vocabularies: FOAF, Dublin Core, schema.org) and <strong>alignments</strong> (<em>owl:sameAs</em> between IRIs denoting the same real-world entity).</p>
</div>
<div class="def">
<p><span class="tag">Definition 10.2 — Extraction, entity linking, entity resolution</span> <strong>Extraction</strong> turns unstructured data into structured data: DOM wrappers for pages, table extraction (header row detection, column typing), information extraction by models — the <em>NLP</em> module (ch.&nbsp;6: NER) is its engine. <strong>Entity linking</strong> attaches a text mention (“Macron”, “E. Macron”) to a reference entity (the president…); <strong>entity resolution</strong> (record linkage) decides whether two records describe the same thing. Typical signature: Jaccard similarity over sets of n-grams, <span class="math inline">J(A,B) = \|A \cap B\|\,/\,\|A \cup B\|</span>, e.g.: <span class="math inline">\{AL, LG, LGA\}</span> vs <span class="math inline">\{LG, GA, GAX\}</span>: intersection {LG, GA} (2), union 4 → <span class="math inline">J = 0.5</span>.</p>
</div>
<div class="prop">
<p><span class="tag">Proposition 10.3 — Blocking: making quadratic matching practical</span> Comparing <span class="math inline">n = 10^6</span> records pairwise costs <span class="math inline">n(n-1)/2 \approx 5\times10^{11}</span> comparisons. <strong>Blocking</strong> compares only the pairs sharing a blocking key (name prefix, soundex, locality). With 1000 balanced blocks of 1000 records: <span class="math inline">1000 \times \binom{1000}{2} \approx 5\times10^8</span> comparisons — 1000× fewer. The risk is the <em>false negative</em> (two duplicates in different blocks); one therefore multiplies the blocking keys and divides the comparisons by filtering (pairs whose name similarity is below a threshold are discarded before the costly comparisons).</p>
</div>
<div class="def">
<p><span class="tag">Definition 10.4 — Integration: matching, fusion, provenance</span> Integrating <span class="math inline">k</span> sources requires: (i) schema <strong>matching</strong> (“Prenom” ≈ “first_name”, by similarity of names, types, values), (ii) <strong>fusion</strong> of conflicting values (voting, freshness, trust in the source), (iii) <strong>provenance</strong> — which source produced which value, in order to audit and correct. Architectures: ETL toward a schematized warehouse, or ELT (load raw, transform at query time); the <em>data lake</em> stores raw data, the <em>lakehouse</em> adds transactions and a catalog. These topics (and data-assisted fact-checking) are the home ground of the CEDAR team — the subject of the next chapter.</p>
</div>
<div class="note">
<p><span class="tag">Note — Quality and trust</span> The GIGO rule (<em>garbage in, garbage out</em>) is constant: data preparation consumes the majority of ML project time. Knowing where data is born and how it is merged is not “data plumbing”: it is the condition for model reproducibility — and for the credibility of published figures.</p>
</div>
<h2 id="ch11">11. Course research notes — CEDAR (Mohanty)</h2>
<p>The module is led by Madhulika Mohanty, Inria researcher (chargée de recherche) in the <strong>CEDAR</strong> team (Inria Saclay — École Polytechnique), founded and led by Ioana Manolescu, Inria senior researcher (directrice de recherche), a specialist in complex and heterogeneous data management. The team’s work draws the arc of this module: from the foundations of data systems to the web of data, then to the use of data to verify information — Madhulika Mohanty contributes in particular on the querying and exploration of graph data. Verified selection:</p>
<ul>
<li><strong>Foundations and teaching of the field.</strong> S.&nbsp;Abiteboul, I.&nbsp;Manolescu, P.&nbsp;Rigaux, M.-C.&nbsp;Rousset, P.&nbsp;Senellart, <em>Web Data Management</em>, Cambridge University Press, 2011 — the reference treatise on web data management, <a href="http://webdam.inria.fr/Jorge/">freely available online</a>. With T.&nbsp;Kaoudi and M.&nbsp;Zampetakis, she also published <em>Cloud-Based RDF Data Management</em> (Morgan&nbsp;&amp;&nbsp;Claypool, 2020) — the RDF of ch.&nbsp;9 seen from the cloud and distribution side.</li>
<li><strong>RDF graph summaries.</strong> Real knowledge graphs are too large to be “seen” at a glance: G.&nbsp;Goasdoué, M.&nbsp;Guzewicz, I.&nbsp;Manolescu, <a href="https://dblp.org/pid/m/IoanaManolescu">“RDF Graph Summarization for First-Sight Structure Discovery”</a>, VLDB Journal 29(5), 2020 — building quotient summaries that approximate the graph in small fractions of its size, with a guarantee of exactness for “typical” query answers.</li>
<li><strong>Heterogeneous integration: ConnectionLens.</strong> The <em>ConnectionLens</em> platform (demo PVLDB 11(12), 2018, with C.&nbsp;Chanial, M.&nbsp;Dziri, M.&nbsp;Galhardas, J.&nbsp;Leblay, M.&nbsp;Le&nbsp;Nguyen) integrates relational databases, JSON, CSV, XML trees, and texts into a <em>single graph</em>; the long version (Anadiotis, Balalau, Bouganim, Chimienti, Galhardas, Haddad, Horel, Manolescu, Youssef, <em>Graph integration of structured, semistructured and unstructured data for data journalism</em>, Information Systems 104, 2022) formalizes the model: the direct follow-up of ch.&nbsp;10. A spectacular application: the automated detection of <a href="https://arxiv.org/abs/2102.04141">scientific conflicts of interest</a> (CIKM 2021) by crossing author statements, patents, clinical trials, and funding.</li>
<li><strong>Fact-checking and data journalism.</strong> Starting with “Computational fact-checking: a content management perspective” (S.&nbsp;Cazalens, J.&nbsp;Leblay, I.&nbsp;Manolescu, X.&nbsp;Lamarre, T.&nbsp;Tannier, PVLDB 11(12), 2018), the team treats claim verification as a <em>data management</em> problem: finding the sources, aligning them, evaluating the claims. The line continued with the verification of <em>numbers</em> (Balalau et al., TTO/TLS 2022, StatCheck demonstrator) then with the generation of factual counter-arguments; the ANR/DGA <a href="https://www.inria.fr/en/sourcessay">SourceSay</a> project (with the Décodeurs of <em>Le Monde</em>) equips journalists to find the <em>first source</em> of a digital rumor.</li>
<li><strong>AI × data.</strong> CEDAR’s current program connects information extraction (LLMs and graphs: FactSpotter, Findings of EMNLP 2023), heterogeneous data querying, and trust — the meeting of ch.&nbsp;10 with the <em>NLP</em> and <em>LLMs</em> modules of the master’s program. See the <a href="https://www.inria.fr/en/cedar">CEDAR page</a> and the <a href="https://dblp.org/pid/m/IoanaManolescu">dblp list</a>.</li>
</ul>
<div class="note">
<p><span class="tag">Note — What this changes for you</span> Project topics draw on this work: summarizing an RDF graph, integrating two heterogeneous sources with provenance, verifying a published statistic against open datasets — modeling (ch.&nbsp;3), querying efficiently (ch.&nbsp;5-8), assessing trust (ch.&nbsp;10).</p>
</div>
<h2 id="ex">Exercises</h2>
<ol type="1">
<li><p><strong>Algebra and SQL (solved).</strong> On the database of Example 1.2, express in algebra then in SQL: (a) the majors of the students enrolled in the DB course; (b) the students enrolled in <em>all</em> courses of at least 4 credits; (c) the courses with no enrollee. <em>Solution.</em> (a) <span class="math inline">\pi_{\texttt{major}}(\texttt{Student} \Join \sigma_{\texttt{code}=DB}(\texttt{Enrolled}))</span> — SQL: join + WHERE. (b) division: <span class="math inline">\pi_{\texttt{id}}(\texttt{Enrolled}) \div \pi_{\texttt{code}}(\sigma_{\texttt{credits}\geq4}(\texttt{Course}))</span> then join with Student; in SQL, <code>NOT EXISTS (SELECT … FROM Course c WHERE credits &gt;= 4 AND NOT EXISTS (SELECT … FROM Enrolled i WHERE i.id = e.id AND i.code = c.code))</code> — the double negation of Prop. 2.2, applied to the division of ch.&nbsp;1. (c) <span class="math inline">\pi_{\texttt{code}}(\texttt{Course}) - \pi_{\texttt{code}}(\texttt{Enrolled})</span>, SQL: <code>NOT EXISTS</code> or <code>LEFT JOIN … WHERE i.id IS NULL</code> — the anti-join.</p></li>
<li><p><strong>Closure and 3NF (solved).</strong> <span class="math inline">R(A,B,C,D,E)</span>, <span class="math inline">F = \{A \to B,\; BC \to D,\; D \to E\}</span>. (a) Compute the keys. (b) Is the relation in 3NF? (c) Decompose into 3NF without loss and verify each step with Theorem 3.5. <em>Solution.</em> (a) <span class="math inline">(AC)^{+}</span>: <span class="math inline">A</span> gives <span class="math inline">B</span>, <span class="math inline">ABC</span> gives <span class="math inline">D</span>, <span class="math inline">D</span> gives <span class="math inline">E</span> → everything: <span class="math inline">AC</span> is a key (<span class="math inline">A^{+} = AB</span>, <span class="math inline">C^{+} = C</span>: neither <span class="math inline">A</span> nor <span class="math inline">C</span> alone). Prime attributes: <span class="math inline">A, C</span>. (b) <span class="math inline">D \to E</span>: <span class="math inline">D</span> is not a superkey (<span class="math inline">D^{+} = DE</span>) and <span class="math inline">E</span> is not prime → not 3NF (2NF yes: no FD from a strict subset of the key). (c) By 3NF synthesis (minimal cover <span class="math inline">\{A\to B, BC\to D, D\to E\}</span>, one schema per determinant, plus a key): <span class="math inline">(AB, BCD, DE, AC)</span> — lossless and FD-preserving. The “by hand” decomposition <span class="math inline">(ABCD, DE)</span> then <span class="math inline">(AB, ACD)</span> preserves <span class="math inline">\{A\to B\}</span> but <em>loses</em> <span class="math inline">BC \to D</span> (check with Thm 3.5: the intersection <span class="math inline">B</span> determines nothing): synthesis avoids precisely this pitfall.</p></li>
<li><p><strong>B+ by hand (solved).</strong> Insert in order 2, 4, 6, 8, 10, 12, 14 into a B+ tree of order <span class="math inline">d=1</span>; give the final tree and its height (same conventions as Example 5.4: when a leaf <span class="math inline">[a,b,c]</span> splits, the copied separator is <span class="math inline">c</span>, the first key of the right leaf). <em>Solution.</em> 2 then 4: leaf [2,4]. The 6 overflows [2,4,6] → [2,4] / [6], copy of 6: root [6]. The 8: leaf [6,8]. The 10: [6,8,10] → [6,8] / [10], copy of 10: root [6,10], leaves [2,4] [6,8] [10]. The 12: leaf [10,12]. The 14: [10,12,14] → [10,12] / [14], copy of 14: the root [6,10,14] overflows (3 keys); <em>internal</em> split: the median key 10 is moved to the new root, internal children [6] and [14]. The 14 already placed: final tree</p>
<pre class="code"><code>              [10]
          ┌──────┴──────┐
        [ 6 ]         [ 14 ]
      ┌──┴──┐        ┌──┴──┐
    [2,4] [6,8]   [10,12] [14]</code></pre>
<p>Height: 3. Check: all leaves at the same level, 1 ≤ keys ≤ 2 everywhere — the invariants of Definition 5.1 hold at every step.</p></li>
<li><p><strong>Serializability (solved).</strong> Let <span class="math inline">H = r_1(X)\, r_2(X)\, w_1(X)\, w_2(X)\, r_1(Y)\, w_1(Y)\, c_1\, c_2</span>. Build <span class="math inline">SG(H)</span>; is <span class="math inline">H</span> serializable? recoverable? What would 2PL do? <em>Solution.</em> Conflicts on X: <span class="math inline">r_1&lt;w_2</span> (T1→T2), <span class="math inline">r_2&lt;w_1</span> (T2→T1), <span class="math inline">w_1&lt;w_2</span> (T1→T2). On Y: T2 does not write Y. Graph: T1↔︎T2 → cycle → not serializable (Thm 6.2). Recoverable? T2 reads X (original value) then writes X after <span class="math inline">w_1</span>: T2 reads nothing written by T1 → yes, recoverable — but with a lost update. Under 2PL, <span class="math inline">T_1</span> keeping its X lock until its lock point (after <span class="math inline">w_1(Y)</span>), <span class="math inline">w_2(X)</span> waits: the forbidden interleaving is simply impossible — Theorem 6.5 in action.</p></li>
<li><p><strong>External sort.</strong> <span class="math inline">N = 2\times10^5</span> pages, <span class="math inline">M = 500</span>. Compute the initial runs, passes, total I/O cost; how long on a disk at 20,000 pages/s? <em>Hint.</em> 400 runs, fan-in 499 → <span class="math inline">\lceil\log_{499} 400\rceil = 1</span>, <span class="math inline">p = 2</span>, cost <span class="math inline">2Np = 8\times10^5</span> pages → 40 s.</p></li>
<li><p><strong>Plan choice.</strong> Join <span class="math inline">R \Join S</span> with <span class="math inline">B_R = 200</span>, <span class="math inline">B_S = 10\,000</span>, <span class="math inline">M = 52</span>, a selection on <span class="math inline">R</span> of selectivity <span class="math inline">1/100</span> that can be pushed before the join. Compare: sort-merge on <span class="math inline">(R,S)</span>; hashing; and the order <span class="math inline">S \Join \sigma(R)</span> in block nested loops. <em>Hint.</em> <span class="math inline">\sigma(R)</span> fits in RAM (2 pages); NLJ with <span class="math inline">R</span> filtered on the outside: <span class="math inline">2 + 1\times10\,000</span> … the index changes everything: think “small relation in memory = outer loop”.</p></li>
<li><p><strong>SQLite recursion.</strong> Write in recursive SQL: (a) the degree (distance) of separation of each pair of users of a network (table <code>follow(a,b)</code>); (b) the connected components of an undirected graph. <em>Hint.</em> (a) propagate the length by accumulating and take the MIN per pair (window or GROUP BY); (b) propagate the MIN of reached identifiers up to the fixed point.</p></li>
<li><p><strong>Vectors: sizing.</strong> <span class="math inline">10^7</span> embeddings in <span class="math inline">d = 768</span> (float32): memory size? Number of multiplications for an exact k-NN? With IVF <span class="math inline">n_{list} = 4096</span>, <span class="math inline">n_{probe} = 32</span> (balanced cells): comparative work performed, and gain? <em>Hint.</em> 30.7 GB; <span class="math inline">7.68\times10^{10}</span> products; IVF: <span class="math inline">10^7/4096 \times 32 \approx 78\,000</span> vectors probed + distances to the centroids, i.e.&nbsp;~1% of the exact work, at the price of recall.</p></li>
<li><p><strong>Open design.</strong> A journalist receives 5 CSV files (elections, demographics, funding, companies, press). Propose an architecture to cross-check and trace the numerical claims of an article: target schema, indexes, provenance, typical queries (reread ch.&nbsp;10-11).</p></li>
</ol>
<h2 id="refs">References</h2>
<ul>
<li>E.&nbsp;F. Codd, “A Relational Model of Data for Large Shared Data Banks”, <em>Communications of the ACM</em> 13(6), 1970 — <a href="https://dl.acm.org/doi/10.1145/362384.362685">the founding paper</a> of the relational model.</li>
<li>S. Abiteboul, R. Hull, V. Vianu, <em>Foundations of Databases</em>, Addison-Wesley, 1995 — the theoretical reference: algebra/calculus (Thm 1.7), dependencies, chase, normal forms.</li>
<li>A. Silberschatz, H. Korth, S. Sudarshan, <em>Database System Concepts</em>, 7th ed., McGraw-Hill, 2019 — the course textbook: storage, B+ trees, transactions, ARIES, distributed.</li>
<li>H. Garcia-Molina, J. Ullman, J. Widom, <em>Database Systems: The Complete Book</em>, 2nd ed., Prentice Hall, 2008 — ch.&nbsp;13-14 (B+), 17-18 (concurrency), 15-16 (recovery).</li>
<li>D. Comer, “The Ubiquitous B-Tree”, <em>ACM Computing Surveys</em> 11(2), 1979 — <a href="https://dl.acm.org/doi/10.1145/356770.356776">the classic survey</a> on B-trees.</li>
<li>G. Graefe, “Query Evaluation Techniques for Large Databases”, <em>ACM Computing Surveys</em> 25(2), 1993 — <a href="https://dl.acm.org/doi/10.1145/152610.152611">joins, costs, optimization</a>, the source of ch.&nbsp;8.</li>
<li>P. Bernstein, V. Hadzilacos, N. Goodman, <em>Concurrency Control and Recovery in Database Systems</em>, Addison-Wesley, 1987 — the theorems of ch.&nbsp;6 (2PL, serializability), freely consultable online.</li>
<li>C. Mohan, D. Haderle, B. Lindsay, H. Pirahesh, P. Schwarz, “ARIES: A Transaction Recovery Method Supporting Fine-Granularity Locking and Roll-Backs Using Write-Ahead Logging”, <em>ACM TODS</em> 17(1), 1992 — <a href="https://dl.acm.org/doi/10.1145/128936.128942">the paper of ch.&nbsp;7</a>.</li>
<li>S. Gilbert, N. Lynch, “Brewer’s Conjecture and the Feasibility of Consistent, Available, Partition-Tolerant Web Services”, <em>SIGACT News</em> 33(2), 2002 — <a href="https://dl.acm.org/doi/10.1145/564585.564601">the formalization of CAP</a> (Thm 9.1).</li>
<li>N. Francis et al., “Cypher: An Evolving Query Language for Property Graphs”, <em>SIGMOD</em> 2018 — <a href="https://dl.acm.org/doi/10.1145/3183713.3183738">the language of property graphs</a>; on the RDF side: W3C, <a href="https://www.w3.org/TR/rdf11-concepts/">RDF 1.1 Concepts</a> and <a href="https://www.w3.org/TR/sparql11-query/">SPARQL 1.1</a>.</li>
<li>Y. Malkov, D. Yashunin, “Efficient and Robust Approximate Nearest Neighbor Search Using Hierarchical Navigable Small World Graphs”, <em>IEEE TPAMI</em> 2018 — <a href="https://arxiv.org/abs/1603.09320">arXiv 1603.09320</a>; H. Jégou, M. Douze, C. Schmid, “Product Quantization for Nearest Neighbor Search”, <em>IEEE TPAMI</em> 33(1), 2011 — the two pillars of ch.&nbsp;9.</li>
<li>J. Johnson, M. Douze, H. Jégou, “Billion-scale Similarity Search with GPUs”, <em>IEEE Trans. Big Data</em> 2017 — <a href="https://arxiv.org/abs/1702.08734">arXiv 1702.08734</a>: the FAISS library, the standard tool for vector labs.</li>
<li>S. Abiteboul, I. Manolescu, P. Rigaux, M.-C. Rousset, P. Senellart, <em>Web Data Management</em>, Cambridge University Press, 2011 — <a href="http://webdam.inria.fr/Jorge/">free online edition</a>; T. Kaoudi, I. Manolescu, M. Zampetakis, <em>Cloud-Based RDF Data Management</em>, Morgan &amp; Claypool, 2020.</li>
<li>T. Chanial et al., “ConnectionLens: Finding Connections across Heterogeneous Data Sources”, <em>PVLDB</em> 11(12), 2018; A. Anadiotis et al., “Graph integration of structured, semistructured and unstructured data for data journalism”, <em>Information Systems</em> 104, 2022 — the CEDAR team in action (ch.&nbsp;10-11); <a href="https://dblp.org/pid/m/IoanaManolescu">complete publication list on dblp</a>.</li>
<li>Documentation: <a href="https://www.sqlite.org/windowfunctions.html">SQLite window functions</a>, <a href="https://www.postgresql.org/docs/current/mvcc.html">MVCC in PostgreSQL</a>, <a href="https://www.mongodb.com/docs/manual/">MongoDB manual</a>, <a href="https://github.com/pgvector/pgvector">pgvector</a>.</li>
</ul>

</main>
<footer class="foot"><p><a href="../../index.html">← Master's program</a></p></footer>
<script defer="" src="../../assets/theme.js"></script>




</body></html>